package main

import (
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"strings"

	gatecontract "github.com/lihah111222333-cloud/super-dolphin-agent/internal/devtools/gate"
)

const requesterRunsLimitMax = 1_000

type requesterRunsResult struct {
	RequesterFingerprint gatecontract.RequesterFingerprint `json:"requester_fingerprint"`
	JobIDs               []string                          `json:"job_ids"`
}

type requesterRunsRequest struct {
	ledgerPath  string
	fingerprint gatecontract.RequesterFingerprint
	limit       int
}

// listRequesterRuns 从 SQLite 权威账本按 requester 索引返回最近的远程 job。
func listRequesterRuns(args []string, stdout io.Writer) error {
	request, err := parseRequesterRunsRequest(args)
	if err != nil {
		return err
	}
	store, err := gatecontract.NewDurationLedgerStore(request.ledgerPath)
	if err != nil {
		return protocolError("open requester ledger: %v", err)
	}
	jobIDs, err := store.ListRemoteCIRunIDsByRequester(request.fingerprint, request.limit)
	if err != nil {
		return infrastructureError("query requester runs: %v", err)
	}
	if err := json.NewEncoder(stdout).Encode(requesterRunsResult{RequesterFingerprint: request.fingerprint, JobIDs: jobIDs}); err != nil {
		return infrastructureError("write requester runs: %v", err)
	}
	return nil
}

// parseRequesterRunsRequest 解析查询参数并绑定显式或继承的 requester 身份。
func parseRequesterRunsRequest(args []string) (requesterRunsRequest, error) {
	flags := flag.NewFlagSet("requester runs", flag.ContinueOnError)
	flags.SetOutput(io.Discard)
	var (
		ledgerPath           string
		requesterFingerprint string
		limit                int
	)
	flags.StringVar(&ledgerPath, "ledger", "", "duration ledger path")
	flags.StringVar(
		&requesterFingerprint,
		"requester-fingerprint",
		"",
		"logical requester fingerprint generated by requester create",
	)
	flags.IntVar(&limit, "limit", 100, "maximum recent job IDs")
	if err := flags.Parse(args); err != nil {
		return requesterRunsRequest{}, protocolError("parse requester runs flags: %v", err)
	}
	if flags.NArg() != 0 || strings.TrimSpace(ledgerPath) == "" {
		return requesterRunsRequest{}, protocolError("requester runs requires --ledger and valid optional flags")
	}
	if limit <= 0 || limit > requesterRunsLimitMax {
		return requesterRunsRequest{}, protocolError("requester runs --limit must be between 1 and %d", requesterRunsLimitMax)
	}
	fingerprint, err := resolveRequesterFingerprint(
		requesterFingerprint,
		os.Getenv(gatecontract.RequesterFingerprintEnvironment),
	)
	if err != nil {
		return requesterRunsRequest{}, protocolError("resolve requester fingerprint: %v", err)
	}
	if fingerprint == "" {
		return requesterRunsRequest{}, protocolError(
			"requester runs requires --requester-fingerprint or %s",
			gatecontract.RequesterFingerprintEnvironment,
		)
	}
	return requesterRunsRequest{ledgerPath: ledgerPath, fingerprint: fingerprint, limit: limit}, nil
}

// resolveRequesterFingerprint 合并显式参数和继承环境；冲突时拒绝猜测。
func resolveRequesterFingerprint(
	explicit string,
	inherited string,
) (gatecontract.RequesterFingerprint, error) {
	if explicit != "" && inherited != "" && explicit != inherited {
		return "", errors.New("explicit and inherited requester fingerprints conflict")
	}
	value := explicit
	if value == "" {
		value = inherited
	}
	if value == "" {
		return "", nil
	}
	fingerprint, err := gatecontract.ParseRequesterFingerprint(value)
	if err != nil {
		return "", fmt.Errorf("invalid requester fingerprint: %w", err)
	}
	return fingerprint, nil
}
