// @ts-nocheck

export const RPC_METHODS = Object.freeze({
  CONFIG_READ: 'config/read',
  CONFIG_LSP_PROMPT_HINT_READ: 'config/lspPromptHint/read',
  CONFIG_LSP_PROMPT_HINT_WRITE: 'config/lspPromptHint/write',
  CONFIG_BUILTIN_TOOLS_READ: 'config/builtinTools/read',
  CONFIG_BUILTIN_TOOLS_WRITE: 'config/builtinTools/write',

  APP_UPDATE_CHECK: 'app/update/check',
  APP_UPDATE_DOWNLOAD: 'app/update/download',
  APP_UPDATE_INSTALL: 'app/update/install',
  APP_UPDATE_INSTALL_LATEST: 'app/update/installLatest',

  UI_WINDOW_BOOTSTRAP_GET: 'ui/windowBootstrap/get',
  UI_STATE_GET: 'ui/state/get',
  UI_SIDEBAR_GET: 'ui/sidebar/get',
  UI_LOG: 'ui/log',
  OBSERVABILITY_TRACE_GET: 'observability/trace/get',
  OBSERVABILITY_THREAD_RECENT: 'observability/thread/recent',
  OBSERVABILITY_RECENT_LIST: 'observability/recent/list',
  OBSERVABILITY_SLOW_LIST: 'observability/slow/list',
  OBSERVABILITY_ERROR_LIST: 'observability/error/list',
  OBSERVABILITY_STATUS: 'observability/status',
  OBSERVABILITY_FRONTEND_INGEST: 'observability/frontend/ingest',
  UI_OPEN_NEW_WINDOW: 'ui/openNewWindow',
  UI_CODE_LOCATE: 'ui/code/locate',
  UI_CODE_OPEN: 'ui/code/open',
  UI_CODE_SAVE: 'ui/code/save',
  UI_PATH_OPEN: 'ui/path/open',

  UI_PROJECTS_GET: 'ui/projects/get',
  UI_PROJECTS_SET_ACTIVE: 'ui/projects/setActive',
  UI_PROJECTS_ADD: 'ui/projects/add',
  UI_PROJECTS_REMOVE: 'ui/projects/remove',

  UI_PREFERENCES_GET: 'ui/preferences/get',
  UI_PREFERENCES_GET_ALL: 'ui/preferences/getAll',
  UI_PREFERENCES_SET: 'ui/preferences/set',
  MODEL_PROVIDERS_LIST: 'modelProviders/list',
  MODEL_PROVIDERS_SAVE: 'modelProviders/save',
  MODEL_PROVIDERS_APPLY: 'modelProviders/apply',

  UI_DASHBOARD_GET: 'ui/dashboard/get',
  UI_VIDEO_GET_API_KEY: 'ui/video/getApiKey',
  UI_VIDEO_SET_API_KEY: 'ui/video/setApiKey',
  DASHBOARD_LOGS: 'dashboard/logs',
  UI_MEMORY_GET: 'ui/memory/get',
  UI_MEMORY_ENTRY_GET: 'ui/memory/entry/get',
  UI_MEMORY_ENTRY_UPSERT: 'ui/memory/entry/upsert',
  UI_MEMORY_ENTRY_DELETE: 'ui/memory/entry/delete',
  UI_MEMORY_AUTO_DREAM_SET_INTENT: 'ui/memory/auto-dream/set-intent',
  UI_MEMORY_ENTRY_MERGE: 'ui/memory/entry/merge',
  UI_MEMORY_SIMILARITY_IGNORE: 'ui/memory/similarity/ignore',
  UI_MEMORY_SIMILARITY_CONSOLIDATE_ALL: 'ui/memory/similarity/consolidate-all',
  UI_MEMORY_SIMILARITY_CONSOLIDATE_ALL_START: 'ui/memory/similarity/consolidate-all/start',
  UI_MEMORY_SIMILARITY_CONSOLIDATE_ALL_STATUS: 'ui/memory/similarity/consolidate-all/status',
  UI_SHARED_FILE_GET: 'ui/memory/shared-file/get',
  UI_SHARED_FILE_DELETE: 'ui/memory/shared-file/delete',
  DASHBOARD_SHARED_FILES: 'dashboard/sharedFiles',
  DASHBOARD_WORKFLOW_MATERIAL_WRITE: 'dashboard/workflowMaterialWrite',

  PROMPT_ASSETS_LIST: 'prompt-assets/list',
  DASHBOARD_PROMPTS: 'dashboard/prompts',
  PROMPTS_GET: 'prompts/get',
  PROMPTS_WRITE: 'prompts/write',
  PROMPTS_DELETE: 'prompts/delete',
  PROMPT_INTENTS_DRAFT: 'prompt-intents/draft',
  PROMPT_INTENTS_COMMIT: 'prompt-intents/commit',
  PROMPT_INTENTS_DISCARD: 'prompt-intents/discard',
  PROMPT_INTENTS_DRY_RUN: 'prompt-intents/dry-run',
  PERSONALIZATION_PROFILE_GET: 'personalization/profile/get',
  PERSONALIZATION_PROFILE_SAVE: 'personalization/profile/save',
  PROMPT_SECTIONS_LIST: 'prompt-sections/list',
  PROMPT_SECTIONS_WRITE: 'prompt-sections/write',
  PROMPT_SECTIONS_DELETE: 'prompt-sections/delete',

  DASHBOARD_DAGS: 'dashboard/dags',
  DASHBOARD_DAG_DETAIL: 'dashboard/dagDetail',
  DASHBOARD_DAG_RUNS: 'dashboard/dagRuns',
  DASHBOARD_DAG_RUN: 'dashboard/dagRun',
  DASHBOARD_DAG_START: 'dashboard/dagStart',
  DASHBOARD_DAG_CREATE_AND_START: 'dashboard/dagCreateAndStart',
  DASHBOARD_DAG_DISPATCH_NODE: 'dashboard/dagDispatchNode',
  DASHBOARD_DAG_TERMINATE: 'dashboard/dagTerminate',
  DASHBOARD_DAG_DELETE: 'dashboard/dagDelete',
  DASHBOARD_DAG_APPLY_OPS: 'dashboard/dagApplyOps',

  WORKFLOW_TEMPLATES_LIST: 'workflowTemplates/list',
  WORKFLOW_TEMPLATES_GET: 'workflowTemplates/get',
  WORKFLOW_TEMPLATES_RENDER_DAG: 'workflowTemplates/renderDag',
  WORKFLOW_TEMPLATES_SAVE: 'workflowTemplates/save',
  WORKFLOW_TEMPLATES_ROLLBACK: 'workflowTemplates/rollback',

  CRONJOB_LIST: 'cronjob/list',
  CRONJOB_GET: 'cronjob/get',
  CRONJOB_CREATE: 'cronjob/create',
  CRONJOB_UPDATE: 'cronjob/update',
  CRONJOB_DELETE: 'cronjob/delete',
  CRONJOB_RUN_ONCE: 'cronjob/runOnce',
  CRONJOB_SET_ENABLED: 'cronjob/setEnabled',
  CRONJOB_LIST_RUNS: 'cronjob/listRuns',

  SKILLS_LOCAL_DELETE: 'skills/local/delete',
  SKILLS_LOCAL_READ: 'skills/local/read',
  SKILLS_LOCAL_LIST_FILES: 'skills/local/listFiles',
  SKILLS_LOCAL_WRITE: 'skills/local/write',
  SKILLS_LOCAL_IMPORT_DIR: 'skills/local/importDir',
  SKILLS_CREATE: 'skills/create',
  SKILLS_SUMMARY_SUGGEST: 'skills/summary/suggest',
  SKILLS_RESOLUTION_LIST: 'skills/resolution_list',
  SKILLS_RESOLUTION_PREVIEW: 'skills/resolution_preview',
  SKILLS_RESOLUTION_APPLY: 'skills/resolution_apply',
  SKILL_TOOLS_CREATE: 'skills/tools/create',
  SKILL_TOOLS_LIST: 'skills/tools/list',
  SKILL_TOOLS_GET: 'skills/tools/get',
  SKILL_TOOLS_UPDATE: 'skills/tools/update',
  SKILL_TOOLS_DELETE: 'skills/tools/delete',

  DATASOURCE_V2_CREATE: 'datasourceV2/create',
  DATASOURCE_V2_IMPORT_LOCAL_FILE: 'datasourceV2/importLocalFile',
  DATASOURCE_V2_LIST: 'datasourceV2/list',
  DATASOURCE_V2_GET: 'datasourceV2/get',
  DATASOURCE_V2_LIST_CHUNKS: 'datasourceV2/list_chunks',
  DATASOURCE_V2_UPDATE: 'datasourceV2/update',
  DATASOURCE_V2_DELETE: 'datasourceV2/delete',

  MCP_SERVER_LIST: 'mcpServer/list',
  MCP_SERVER_SQLITE_START: 'mcpServer/sqlite/start',
  MCP_SERVER_SQLITE_STOP: 'mcpServer/sqlite/stop',
  MCP_SERVER_PLAYWRIGHT_START: 'mcpServer/playwright/start',
  MCP_SERVER_PLAYWRIGHT_STOP: 'mcpServer/playwright/stop',
  MCP_TOOL_LIFECYCLE_SET: 'mcpServer/toolLifecycle/set',
  MCP_TOOL_LIFECYCLE_LIST: 'mcpServer/toolLifecycle/list',
  MCP_TOOL_LIFECYCLE_EXPORT: 'mcpServer/toolLifecycle/export',

  THREAD_START: 'thread/start',
  THREAD_LIST_PAGE: 'thread/listPage',
  THREAD_LOADED_LIST_PAGE: 'thread/loaded/listPage',
  THREAD_MESSAGES: 'thread/messages',
  THREAD_RESOLVE: 'thread/resolve',
  THREAD_ARCHIVE: 'thread/archive',
  THREAD_UNARCHIVE: 'thread/unarchive',
  THREAD_DELETE: 'thread/delete',
  THREAD_CONFIG_GET: 'thread/config/get',
  THREAD_CONFIG_SET: 'thread/config/set',
  THREAD_COMPACT_START: 'thread/compact/start',
  THREAD_RECOVER: 'thread/recover',
  THREAD_NAME_SET: 'thread/name/set',

  TURN_START: 'turn/start',
  TURN_INTERRUPT: 'turn/interrupt',
  TURN_FORCE_COMPLETE: 'turn/forceComplete',
  APPROVAL_RESPOND: 'approval/respond',
});
