package archtest

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
)

var wildcardRowSQLPattern = regexp.MustCompile(`(?is)\b(SELECT|RETURNING)\s+\*`)

func TestMCPOrchDAGStorageDoesNotBypassSQLC(t *testing.T) {
	t.Parallel()

	root := repoRootForGuardTests(t)
	checked := collectDAGSQLCGuardFiles(t, root)
	var violations []string
	for _, rel := range checked {
		path := filepath.Join(root, rel)
		violations = append(violations, rawSQLCallViolations(t, root, path, rel)...)
	}
	if len(violations) > 0 {
		t.Fatalf("mcp-orch DAG storage must use sqlc query methods, found bypasses:\n%s", strings.Join(violations, "\n"))
	}
}

func TestMCPOrchSQLCGeneratedPackageHasNoHandWrittenDBAccessors(t *testing.T) {
	t.Parallel()

	root := repoRootForGuardTests(t)
	sqlcDir := filepath.Join(root, "cmd", "mcp-orch", "store", "sqlc")
	assertForbiddenSQLCFilesAbsent(t, sqlcDir)
	assertMCPOrchSQLCProductionFilesGenerated(t, sqlcDir)
}

func assertForbiddenSQLCFilesAbsent(t *testing.T, sqlcDir string) {
	t.Helper()
	for _, name := range []string{
		"db_accessor.go",
		"db_ext.go",
		"task_dag_node_lookup.sql.go",
		"task_dag_node_write_batch.go",
	} {
		path := filepath.Join(sqlcDir, name)
		if _, err := os.Stat(path); err == nil {
			t.Fatalf("%s exists; mcp-orch/store/sqlc must remain generated-only except approved type helpers", path)
		} else if !os.IsNotExist(err) {
			t.Fatalf("stat %s: %v", path, err)
		}
	}
}

func assertMCPOrchSQLCProductionFilesGenerated(t *testing.T, sqlcDir string) {
	t.Helper()
	entries, err := os.ReadDir(sqlcDir)
	if err != nil {
		t.Fatalf("read %s: %v", sqlcDir, err)
	}
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") || name == "types_ext.go" {
			continue
		}
		path := filepath.Join(sqlcDir, name)
		data, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("read %s: %v", path, err)
		}
		if !strings.HasPrefix(string(data), "// Code generated by sqlc. DO NOT EDIT.") {
			t.Fatalf("%s is not sqlc-generated; put hand-written helpers outside cmd/mcp-orch/store/sqlc", path)
		}
	}
}

func TestMCPOrchSQLQueriesUseExplicitColumns(t *testing.T) {
	t.Parallel()

	root := repoRootForGuardTests(t)
	queryDir := filepath.Join(root, "cmd", "mcp-orch", "sql", "queries")
	var violations []string
	err := filepath.WalkDir(queryDir, func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() || !strings.HasSuffix(path, ".sql") {
			return nil
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if wildcardRowSQLPattern.Match(data) {
			rel, err := filepath.Rel(root, path)
			if err != nil {
				return err
			}
			violations = append(violations, rel)
		}
		return nil
	})
	if err != nil {
		t.Fatalf("walk %s: %v", queryDir, err)
	}
	if len(violations) > 0 {
		t.Fatalf("mcp-orch sqlc queries must enumerate columns instead of SELECT */RETURNING *:\n%s", strings.Join(violations, "\n"))
	}
}

func collectDAGSQLCGuardFiles(t *testing.T, root string) []string {
	t.Helper()
	var checked []string
	checked = appendGoFilesUnder(t, root, checked, filepath.Join("cmd", "mcp-orch", "store", "taskdag"))
	checked = appendGoFilesUnder(t, root, checked, filepath.Join("cmd", "mcp-orch", "orchestration", "cron"))
	checked = appendGoFilesUnder(t, root, checked, filepath.Join("cmd", "mcp-orch", "fxadapter"))
	checked = appendGoFilesUnder(t, root, checked, filepath.Join("cmd", "mcp-orch", "store", "sqlctx"))
	return append(checked, filepath.Join("cmd", "mcp-orch", "dag_cron_runner.go"))
}

func rawSQLCallViolations(t *testing.T, root, path, rel string) []string {
	t.Helper()

	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, path, nil, 0)
	if err != nil {
		t.Fatalf("parse %s: %v", rel, err)
	}
	var violations []string
	ast.Inspect(file, func(node ast.Node) bool {
		call, ok := node.(*ast.CallExpr)
		if !ok {
			return true
		}
		selector, ok := call.Fun.(*ast.SelectorExpr)
		if !ok || !isRawDBCall(selector.Sel.Name) {
			return true
		}
		position := fset.Position(selector.Sel.Pos())
		relPosition, err := filepath.Rel(root, position.Filename)
		if err != nil {
			relPosition = position.Filename
		}
		violations = append(violations, fmt.Sprintf("%s:%d calls .%s", relPosition, position.Line, selector.Sel.Name))
		return true
	})
	return violations
}

func isRawDBCall(name string) bool {
	switch name {
	case "Exec", "Query", "QueryRow":
		return true
	default:
		return false
	}
}

func appendGoFilesUnder(t *testing.T, root string, out []string, relDir string) []string {
	t.Helper()
	dir := filepath.Join(root, relDir)
	err := filepath.WalkDir(dir, func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() || !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		out = append(out, rel)
		return nil
	})
	if err != nil {
		t.Fatalf("walk %s: %v", relDir, err)
	}
	return out
}
