export const pageSurfaceManifest = {
  chat: {
    entry: 'pages/chat/ChatPage.jsx',
    servicePrefix: 'pages/chat/services/',
    adapterPrefix: 'pages/chat/adapters/',
    serviceEntry: 'pages/chat/services/chatCodeService.js',
    ownershipMode: 'service-boundary',
    ownedStateFiles: ['pages/chat/ChatPage.jsx'],
  },
  files: {
    entry: 'pages/files/FilesPage.jsx',
    servicePrefix: 'pages/files/services/',
    adapterPrefix: 'pages/files/adapters/',
    serviceEntry: 'pages/files/services/filesPageService.js',
    ownershipMode: 'dto-golden',
    dtoGoldenTest: 'pages/files/services/filesPageService.test.js',
    ownedStateFiles: ['pages/files/FilesPage.jsx'],
  },
  memory: {
    entry: 'pages/memory/MemoryPage.jsx',
    servicePrefix: 'pages/memory/services/',
    adapterPrefix: 'pages/memory/adapters/',
    serviceEntry: 'pages/memory/services/memoryPageService.js',
    ownershipMode: 'dto-golden',
    dtoGoldenTest: 'pages/memory/services/memoryPageService.test.js',
    ownedStateFiles: ['pages/memory/MemoryPage.jsx'],
  },
  observability: {
    entry: 'pages/observability/ObservabilityPage.jsx',
    servicePrefix: 'pages/observability/services/',
    adapterPrefix: 'pages/observability/adapters/',
    serviceEntry: 'pages/observability/services/observabilityPageService.js',
    ownershipMode: 'dto-golden',
    dtoGoldenTest: 'pages/observability/services/observabilityPageService.test.js',
    ownedStateFiles: ['pages/observability/ObservabilityPage.jsx'],
  },
  prompts: {
    entry: 'pages/prompts/PromptPage.jsx',
    servicePrefix: 'pages/prompts/services/',
    adapterPrefix: 'pages/prompts/adapters/',
    serviceEntry: 'pages/prompts/services/promptPageService.js',
    ownershipMode: 'dto-golden',
    dtoGoldenTest: 'pages/prompts/services/promptPageService.test.js',
    ownedStateFiles: [
      'pages/prompts/PromptPage.jsx',
      'features/prompts/PromptPageView.jsx',
    ],
  },
  settings: {
    entry: 'pages/settings/SettingsPage.jsx',
    servicePrefix: 'pages/settings/services/',
    adapterPrefix: 'pages/settings/adapters/',
    serviceEntry: 'pages/settings/services/settingsPageService.js',
    ownershipMode: 'service-boundary',
    ownedStateFiles: ['pages/settings/SettingsPage.jsx'],
  },
  skills: {
    entry: 'pages/skills/SkillsPage.jsx',
    servicePrefix: 'pages/skills/services/',
    adapterPrefix: 'pages/skills/adapters/',
    serviceEntry: 'pages/skills/services/skillsPageService.js',
    ownershipMode: 'service-boundary',
    ownedStateFiles: ['pages/skills/SkillsPage.jsx'],
  },
  workflows: {
    entry: 'pages/workflows/WorkflowPage.jsx',
    servicePrefix: 'pages/workflows/services/',
    adapterPrefix: 'pages/workflows/adapters/',
    serviceEntry: 'pages/workflows/services/workflowPageService.js',
    ownershipMode: 'service-boundary',
    ownedStateFiles: ['pages/workflows/WorkflowPage.jsx'],
  },
};
