package protocol

// LSP JSON-RPC 方法名常量集中维护，避免工具层和协议层拼写漂移。
const (
	MethodInitialize              = "initialize"
	MethodInitialized             = "initialized"
	MethodDidOpen                 = "textDocument/didOpen"
	MethodDidChange               = "textDocument/didChange"
	MethodDidClose                = "textDocument/didClose"
	MethodHover                   = "textDocument/hover"
	MethodDefinition              = "textDocument/definition"
	MethodImplementation          = "textDocument/implementation"
	MethodTypeDefinition          = "textDocument/typeDefinition"
	MethodReferences              = "textDocument/references"
	MethodDocumentSymbol          = "textDocument/documentSymbol"
	MethodCompletion              = "textDocument/completion"
	MethodRename                  = "textDocument/rename"
	MethodCodeAction              = "textDocument/codeAction"
	MethodSignatureHelp           = "textDocument/signatureHelp"
	MethodFormatting              = "textDocument/formatting"
	MethodFoldingRange            = "textDocument/foldingRange"
	MethodSemanticTokens          = "textDocument/semanticTokens"
	MethodSemanticTokensFull      = "textDocument/semanticTokens/full"
	MethodPrepareCallHierarchy    = "textDocument/prepareCallHierarchy"
	MethodCallHierarchyIncoming   = "callHierarchy/incomingCalls"
	MethodCallHierarchyOutgoing   = "callHierarchy/outgoingCalls"
	MethodPrepareTypeHierarchy    = "textDocument/prepareTypeHierarchy"
	MethodTypeHierarchySupertypes = "typeHierarchy/supertypes"
	MethodTypeHierarchySubtypes   = "typeHierarchy/subtypes"
	MethodWorkspaceSymbol         = "workspace/symbol"
	MethodTextDocumentDiagnostic  = "textDocument/diagnostic"
	MethodPublishDiagnostics      = "textDocument/publishDiagnostics"
	MethodLogMessage              = "window/logMessage"
	MethodShowMessage             = "window/showMessage"
)
