package gate

import "reflect"

func sqliteProjectionContractsForTest() []sqliteProjectionContract {
	return []sqliteProjectionContract{
		{table: "duration_calibrations", producer: reflect.TypeFor[DurationCalibration](), columns: map[string]string{
			"SchemaVersion": "schema_version", "Commit": "commit_sha", "Tree": "tree_sha", "Platform": "platform", "Runner": "runner", "Toolchain": "toolchain",
			"CommitEntrypoint": "commit_entrypoint", "PushEntrypoint": "push_entrypoint", "ReleaseEntrypoint": "release_entrypoint",
			"CommitCatalogDigest": "commit_catalog_digest", "PushCatalogDigest": "push_catalog_digest", "ReleaseCatalogDigest": "release_catalog_digest",
			"WorkloadCount": "workload_count", "RacePackageCount": "race_package_count", "CompletedAt": "completed_at_unix_ms",
		}, synthetic: map[string]string{"singleton": "single accepted calibration"}},
		{table: "duration_samples", producer: reflect.TypeFor[DurationSample](), expand: map[string]reflect.Type{"Bucket": reflect.TypeFor[DurationBucket]()}, columns: map[string]string{
			"Bucket.WorkloadID": "workload_id", "Bucket.CommandDigest": "command_digest", "Bucket.Platform": "platform", "Bucket.Runner": "runner",
			"Bucket.Toolchain": "toolchain", "Succeeded": "succeeded", "DurationMS": "duration_ms", "TargetKind": "target_kind",
			"ParentWorkloadID": "parent_workload_id", "ParentCommandDigest": "parent_command_digest", "TargetName": "target_name", "TargetStatus": "target_status",
		}, synthetic: map[string]string{"id": "monotonic retention order"}},
		{table: "ci_workload_catalogs", producer: reflect.TypeFor[WorkloadCatalog](), columns: map[string]string{"Version": "catalog_version", "Authoritative": "authoritative"}, exemptions: map[string]string{"Workloads": "normalized into ci_catalog_workloads"}, synthetic: map[string]string{"catalog_digest": "content address", "workload_count": "relation integrity guard", "created_at_unix_ms": "first observation time"}},
		{table: "ci_catalog_observations", producer: reflect.TypeFor[WorkloadCatalogObservation](), columns: map[string]string{"SourceTreeSHA": "source_tree_sha", "Entrypoint": "entrypoint", "Profile": "profile", "ObservedAt": "observed_at_unix_ms"}, synthetic: map[string]string{"catalog_digest": "catalog foreign key"}},
		{table: "ci_catalog_workloads", producer: reflect.TypeFor[Workload](), columns: map[string]string{"ID": "workload_id", "Kind": "kind", "CommandDigest": "command_digest", "BootstrapEstimateMS": "bootstrap_estimate_ms", "Shardable": "shardable"}, synthetic: map[string]string{"catalog_digest": "catalog foreign key", "ordinal": "canonical catalog order", "gate_id": "parsed workload owner", "target_kind": "parsed target category", "target_value": "decoded target identity"}},
		{table: "ci_workload_pass_proofs", producer: reflect.TypeFor[WorkloadPassProof](), columns: map[string]string{"IdentityDigest": "identity_digest", "WorkloadID": "workload_id", "ExecutionDigest": "execution_digest", "InputDigest": "input_digest", "EnvironmentDigest": "environment_digest", "ObjectKey": "object_key", "ObservedAt": "observed_at_unix_ms"}},
		{table: "ci_workload_fingerprints", producer: reflect.TypeFor[WorkloadFingerprintRecord](), columns: map[string]string{"IdentityDigest": "identity_digest", "WorkloadID": "workload_id", "ExecutionDigest": "execution_digest", "InputDigest": "input_digest", "EnvironmentDigest": "environment_digest"}, exemptions: map[string]string{"SourceTreeSHA": "normalized into ci_workload_fingerprint_observations", "ObservedAt": "normalized into ci_workload_fingerprint_observations"}, synthetic: map[string]string{"source_tree_sha": "legacy first-observation anchor", "observed_at_unix_ms": "legacy first-observation timestamp"}},
		{table: "ci_workload_fingerprint_observations", producer: reflect.TypeFor[WorkloadFingerprintRecord](), columns: map[string]string{"IdentityDigest": "identity_digest", "SourceTreeSHA": "source_tree_sha", "ObservedAt": "observed_at_unix_ms"}, exemptions: map[string]string{"WorkloadID": "owned by immutable fingerprint identity", "ExecutionDigest": "owned by immutable fingerprint identity", "InputDigest": "owned by immutable fingerprint identity", "EnvironmentDigest": "owned by immutable fingerprint identity"}},
		{table: "ci_runs", producer: reflect.TypeFor[RemoteCIRunRecord](), columns: map[string]string{"JobID": "job_id", "Entrypoint": "entrypoint", "Profile": "profile", "PlanDigest": "plan_digest", "CatalogDigest": "catalog_digest", "SourceTreeSHA": "source_tree_sha", "RunnerImage": "runner_image", "Status": "status", "Authoritative": "authoritative", "StartedAt": "started_at_unix_ms", "CompletedAt": "completed_at_unix_ms", "CleanupComplete": "cleanup_complete", "ErrorText": "error_text"}, exemptions: map[string]string{"RequesterFingerprint": "normalized into ci_run_requesters", "Shards": "normalized into ci_shards", "Executions": "normalized into ci_gate_executions", "ReusedWorkloads": "normalized into ci_run_workloads", "CacheMisses": "normalized into ci_run_workloads", "Warnings": "normalized into ci_run_warnings", "PhaseTimings": "normalized into ci_run_phase_timings"}},
		{table: "ci_shards", producer: reflect.TypeFor[RemoteCIShardRecord](), columns: map[string]string{"ShardIdentity": "shard_identity", "ContainerGroup": "container_group_id", "ContainerStatus": "container_status"}, exemptions: map[string]string{"Workloads": "normalized into ci_shard_workloads"}, synthetic: map[string]string{"job_id": "run foreign key"}},
		{table: "ci_gate_executions", producer: reflect.TypeFor[PlanGateExecution](), columns: map[string]string{"GateID": "workload_id", "Status": "status", "ExitCode": "exit_code", "StartedAt": "started_at_unix_ms", "CompletedAt": "completed_at_unix_ms", "ArgvDigest": "argv_digest", "LogDigest": "log_digest"}, exemptions: map[string]string{"Log": "immutable plaintext log remains in OSS evidence", "TestTimings": "projected into duration_samples"}, synthetic: map[string]string{"job_id": "run foreign key"}},
		{table: "ci_run_phase_timings", producer: reflect.TypeFor[RemoteCIPhaseTiming](), columns: map[string]string{"Phase": "phase", "StartedAt": "started_at_unix_ms", "DurationMillis": "duration_ms", "Outcome": "outcome", "WorkloadCount": "workload_count", "ShardCount": "shard_count", "CacheHitCount": "cache_hit_count", "CacheMissCount": "cache_miss_count"}, synthetic: map[string]string{"job_id": "run foreign key", "ordinal": "event order"}},
	}
}
