package gate

import (
	"reflect"

	"github.com/lihah111222333-cloud/super-dolphin-agent/internal/devtools/cicontract"
)

func sqliteProjectionContractsForTest() []sqliteProjectionContract {
	return []sqliteProjectionContract{
		{table: "duration_calibrations", producer: reflect.TypeFor[DurationCalibration](), columns: map[string]string{
			"SchemaVersion": "schema_version", "Commit": "commit_sha", "Tree": "tree_sha", "Platform": "platform", "Runner": "runner", "Toolchain": "toolchain",
			"CommitEntrypoint": "commit_entrypoint", "PushEntrypoint": "push_entrypoint", "ReleaseEntrypoint": "release_entrypoint",
			"CommitCatalogDigest": "commit_catalog_digest", "PushCatalogDigest": "push_catalog_digest", "ReleaseCatalogDigest": "release_catalog_digest",
			"CalibrationResourceClassID": "calibration_resource_class_id", "CalibrationResourceCPU": "calibration_resource_cpu", "CalibrationResourceMemoryGiB": "calibration_resource_memory_gib",
			"WorkloadCount": "workload_count", "RacePackageCount": "race_package_count", "AcceptedSnapshotID": "accepted_snapshot_id", "CompletedAt": "completed_at_unix_ms",
		}, synthetic: map[string]string{"singleton": "single accepted calibration"}},
		{table: "duration_samples", producer: reflect.TypeFor[DurationSample](), expand: map[string]reflect.Type{"Bucket": reflect.TypeFor[DurationBucket]()}, columns: map[string]string{
			"AcceptedGeneration": "accepted_generation", "Bucket.WorkloadID": "workload_id", "Bucket.CommandDigest": "command_digest", "Bucket.InputDigest": "input_digest", "Bucket.Platform": "platform", "Bucket.Runner": "runner",
			"Bucket.Toolchain": "toolchain", "Bucket.ExecutionMode": "execution_mode", "Bucket.ResourceClassID": "resource_class_id", "Bucket.ResourceCPU": "resource_cpu", "Bucket.ResourceMemoryGiB": "resource_memory_gib",
			"Succeeded": "succeeded", "DurationMS": "duration_ms", "TargetKind": "target_kind",
			"ParentWorkloadID": "parent_workload_id", "ParentCommandDigest": "parent_command_digest", "TargetName": "target_name", "TargetStatus": "target_status",
		}, synthetic: map[string]string{"id": "monotonic retention order"}},
		{table: "duration_shard_overheads", producer: reflect.TypeFor[ShardOrchestrationOverhead](), columns: map[string]string{
			"SchemaVersion": "schema_version", "PolicyVersion": "policy_version", "Platform": "platform", "Runner": "runner", "Toolchain": "toolchain",
			"CalibrationResourceClassID": "calibration_resource_class_id", "CalibrationResourceCPU": "calibration_resource_cpu", "CalibrationResourceMemoryGiB": "calibration_resource_memory_gib",
			"P95MS": "p95_ms", "SampleCount": "sample_count", "ProvenanceDigest": "provenance_digest", "AcceptedGeneration": "accepted_generation", "AcceptedSnapshotID": "accepted_snapshot_id",
		}, synthetic: map[string]string{"id": "monotonic accepted aggregate identity"}},
		{table: "duration_shard_overhead_samples", producer: reflect.TypeFor[ShardOrchestrationOverheadSample](), columns: map[string]string{
			"AcceptedGeneration": "accepted_generation", "ProvenanceDigest": "provenance_digest", "JobID": "job_id", "ShardIdentity": "shard_identity",
			"TotalStartedAt": "total_started_at_unix_ms", "TotalCompletedAt": "total_completed_at_unix_ms", "WorkloadEnvelopeStart": "workload_envelope_start_unix_ms", "WorkloadEnvelopeEnd": "workload_envelope_end_unix_ms",
			"AccountedDurationMS": "accounted_duration_ms", "AccountedIntervalCount": "accounted_interval_count", "OverheadMS": "overhead_ms",
		}, synthetic: map[string]string{"id": "monotonic retention order"}},
		{table: "ci_workload_catalogs", producer: reflect.TypeFor[WorkloadCatalog](), columns: map[string]string{"Version": "catalog_version", "Authoritative": "authoritative"}, exemptions: map[string]string{"Workloads": "normalized into ci_catalog_workloads"}, synthetic: map[string]string{"catalog_digest": "content address", "workload_count": "relation integrity guard", "created_at_unix_ms": "first observation time"}},
		{table: "ci_catalog_observations", producer: reflect.TypeFor[WorkloadCatalogObservation](), columns: map[string]string{"SourceTreeSHA": "source_tree_sha", "Entrypoint": "entrypoint", "Profile": "profile", "AcceptedGeneration": "accepted_generation", "ObservedAt": "observed_at_unix_ms"}, synthetic: map[string]string{"catalog_digest": "catalog foreign key"}},
		{table: "ci_catalog_workloads", producer: reflect.TypeFor[Workload](), columns: map[string]string{"ID": "workload_id", "Kind": "kind", "CommandDigest": "command_digest", "InputDigest": "input_digest", "BootstrapEstimateMS": "bootstrap_estimate_ms", "Shardable": "shardable"}, synthetic: map[string]string{"catalog_digest": "catalog foreign key", "ordinal": "canonical catalog order", "gate_id": "parsed workload owner", "target_kind": "parsed target category", "target_value": "decoded target identity"}},
		{table: "ci_runs", producer: reflect.TypeFor[RemoteCIRunRecord](), columns: map[string]string{"JobID": "job_id", "Force": "force", "Entrypoint": "entrypoint", "Profile": "profile", "PlanDigest": "plan_digest", "CatalogDigest": "catalog_digest", "AcceptedGeneration": "accepted_generation", "ImageCacheSnapshotID": "image_cache_snapshot_id", "SourceTreeSHA": "source_tree_sha", "CandidateGateSourceSHA256": "candidate_gate_source_sha256", "CandidateGateToolchainSHA256": "candidate_gate_toolchain_sha256", "RunnerImage": "runner_image", "Status": "status", "Authoritative": "authoritative", "StartedAt": "started_at_unix_ms", "CompletedAt": "completed_at_unix_ms", "CleanupComplete": "cleanup_complete", "ErrorText": "error_text"}, exemptions: map[string]string{"AgentTokenDigest": "normalized into ci_run_agent_identities", "Scope": "normalized into ci_remote_run_execution_scopes as canonical subset JSON/digest/count; nil/full remains legacy with no row", "Shards": "normalized into ci_shards", "Executions": "normalized into ci_gate_executions", "WorkloadExecutions": "normalized into ci_workload_executions", "WorkloadResults": "normalized into ci_run_workload_results", "Warnings": "normalized into ci_run_warnings", "TimingWarnings": "normalized into ci_run_timing_warnings", "TimingObservations": "normalized into ci_timing_observations", "CompileTimingObservations": "normalized into ci_compile_timing_observations", "DurationSamples": "appended to duration_samples in the same provisional-run transaction"}},
		{table: cicontract.LiveTimingWarningsTable, producer: reflect.TypeFor[RemoteCITimingWarning](), columns: map[string]string{"JobID": "job_id", "AgentTokenDigest": "agent_token_digest", "AcceptedGeneration": "accepted_generation", "Scope": "scope", "ShardIdentity": "shard_identity", "WorkloadID": "workload_id", "EvidenceKind": "evidence_kind", "Action": "action", "EvidenceStartedAt": "evidence_started_at_unix_ms", "ObservedAt": "observed_at_unix_ms", "EvidenceDurationMS": "evidence_duration_ms", "TargetMS": "target_ms", "WarningText": "warning_text"}},
		{table: cicontract.RunTimingWarningsTable, producer: reflect.TypeFor[RemoteCITimingWarning](), columns: map[string]string{"JobID": "job_id", "AgentTokenDigest": "agent_token_digest", "AcceptedGeneration": "accepted_generation", "Scope": "scope", "ShardIdentity": "shard_identity", "WorkloadID": "workload_id", "EvidenceKind": "evidence_kind", "Action": "action", "EvidenceStartedAt": "evidence_started_at_unix_ms", "ObservedAt": "observed_at_unix_ms", "EvidenceDurationMS": "evidence_duration_ms", "TargetMS": "target_ms", "WarningText": "warning_text"}},
		{table: "ci_run_workload_results", producer: reflect.TypeFor[RemoteCIWorkloadResult](), expand: map[string]reflect.Type{"Identity": reflect.TypeFor[WorkloadPassIdentity]()}, columns: map[string]string{"Identity.WorkloadID": "workload_id", "Identity.IdentityDigest": "identity_digest", "Identity.ExecutionDigest": "execution_digest", "Identity.InputDigest": "input_digest", "Identity.EnvironmentDigest": "environment_digest", "Disposition": "disposition", "OriginJobID": "origin_job_id", "OriginAcceptedGeneration": "origin_accepted_generation", "EvidenceSHA256": "evidence_sha256"}, synthetic: map[string]string{"job_id": "run foreign key"}},
		{table: "ci_workload_pass_evidence", producer: reflect.TypeFor[WorkloadPassEvidence](), expand: map[string]reflect.Type{"Identity": reflect.TypeFor[WorkloadPassIdentity]()}, columns: map[string]string{"Identity.IdentityDigest": "identity_digest", "Identity.WorkloadID": "workload_id", "Identity.ExecutionDigest": "execution_digest", "Identity.InputDigest": "input_digest", "Identity.EnvironmentDigest": "environment_digest", "OriginJobID": "origin_job_id", "OriginAcceptedGeneration": "accepted_generation", "OriginSourceTreeSHA": "origin_source_tree_sha", "OriginReceiptSetSHA256": "origin_receipt_set_sha256", "OriginExecution": "origin_execution_json", "EvidenceSHA256": "evidence_sha256"}},
		{table: "ci_shards", producer: reflect.TypeFor[RemoteCIShardRecord](), columns: map[string]string{"ShardIdentity": "shard_identity", "ContainerGroup": "container_group_id", "ContainerStatus": "container_status", "MaterializationTiming": "materialization_timing_json", "Resources": "resources_json"}, exemptions: map[string]string{"Workloads": "normalized into ci_shard_workloads", "TerminalEvidence": "normalized into ci_shard_terminal_containers and ci_shard_terminal_events"}, synthetic: map[string]string{"job_id": "run foreign key"}},
		{table: "ci_shard_terminal_containers", producer: reflect.TypeFor[RemoteCIContainerTerminalEvidence](), columns: map[string]string{"Name": "name", "State": "state", "ExitCode": "exit_code", "Reason": "reason", "Message": "message"}, synthetic: map[string]string{"job_id": "run foreign key", "shard_identity": "shard foreign key", "container_kind": "container or init discriminator", "ordinal": "stable provider list order"}},
		{table: "ci_shard_terminal_events", producer: reflect.TypeFor[RemoteCIEventEvidence](), columns: map[string]string{"Type": "type", "Reason": "reason", "Message": "message", "Count": "count", "LastTimestamp": "last_timestamp"}, synthetic: map[string]string{"job_id": "run foreign key", "shard_identity": "shard foreign key", "ordinal": "stable provider event order"}},
		{table: "ci_gate_executions", producer: reflect.TypeFor[PlanGateExecution](), columns: map[string]string{"GateID": "workload_id", "Status": "status", "ExitCode": "exit_code", "StartedAt": "started_at_unix_ms", "CompletedAt": "completed_at_unix_ms", "ArgvDigest": "argv_digest", "LogDigest": "log_digest", "TestTimings": "test_timings_json", "ExecutionProfile": "execution_profile_json"}, exemptions: map[string]string{"Log": "immutable plaintext log remains in OSS evidence", "ShardIdentity": "only workload executions are shard-bound"}, synthetic: map[string]string{"job_id": "run foreign key"}},
		{table: "ci_workload_executions", producer: reflect.TypeFor[PlanGateExecution](), columns: map[string]string{"ShardIdentity": "shard_identity", "GateID": "workload_id", "Status": "status", "ExitCode": "exit_code", "StartedAt": "started_at_unix_ms", "CompletedAt": "completed_at_unix_ms", "ArgvDigest": "argv_digest", "LogDigest": "log_digest", "TestTimings": "test_timings_json", "ExecutionProfile": "execution_profile_json"}, exemptions: map[string]string{"Log": "immutable plaintext log remains in OSS evidence"}, synthetic: map[string]string{"job_id": "run foreign key"}},
		{table: cicontract.TimingObservationsTable, producer: reflect.TypeFor[TimingObservation](), columns: map[string]string{"JobID": "job_id", "Scope": "scope", "ShardIdentity": "shard_identity", "WorkloadID": "workload_id", "Phase": "phase", "StartedAt": "started_at_unix_ms", "CompletedAt": "completed_at_unix_ms", "DurationMS": "duration_ms", "Measurement": "measurement", "Reason": "reason", "Aggregation": "aggregation", "CacheEvidence": "cache_evidence_json", "CompileGroupID": "compile_group_id", "CompileArtifactKey": "compile_artifact_key", "CompilePackageTarget": "compile_package_target", "CompileWorkloadIDs": "compile_workload_ids_json", "CompileArtifactSHA256": "compile_artifact_sha256", "CompileArtifactSize": "compile_artifact_size", "CompileCacheHits": "compile_cache_hits", "CompileCacheMisses": "compile_cache_misses", "CompileCachePuts": "compile_cache_puts", "CompileCacheStatus": "compile_cache_status", "CompileStatus": "compile_status", "CompileExitCode": "compile_exit_code", "CompileErrorText": "compile_error_text", "CompileCommandDigest": "compile_command_digest", "CompileProfileDigest": "compile_profile_digest", "CompileResourceClassID": "compile_resource_class_id", "CompileResourceCPU": "compile_resource_cpu", "CompileResourceMemoryGiB": "compile_resource_memory_gib", "CompileExecutionMode": "compile_execution_mode"}},
		{table: cicontract.CompileTimingObservationsTable, producer: reflect.TypeFor[CompileTimingObservation](), expand: map[string]reflect.Type{"Identity": reflect.TypeFor[CompileTimingIdentity]()}, columns: map[string]string{
			"Identity.PackageTarget": "package_target", "Identity.SemanticKey": "semantic_key", "Identity.Platform": "platform", "Identity.RunnerIdentityDigest": "runner_identity_digest", "Identity.ToolchainDigest": "toolchain_digest", "Identity.ExecutionMode": "execution_mode", "Identity.ResourceClassID": "resource_class_id", "Identity.ResourceCPU": "resource_cpu", "Identity.ResourceMemoryGiB": "resource_memory_gib", "DurationMS": "duration_ms", "StartedAt": "started_at_unix_ms", "CompletedAt": "completed_at_unix_ms", "Measurement": "measurement", "Aggregation": "aggregation",
		}, synthetic: map[string]string{"id": "monotonic row identity", "job_id": "run foreign key; run authority is the sole source for generation/status/authority/cleanup"}},
		{table: cicontract.CheckReceiptsTable, producer: reflect.TypeFor[CheckReceiptRecord](), columns: map[string]string{"RunID": "run_id", "JobID": "job_id", "CandidateTreeSHA": "candidate_tree_sha", "AgentTokenDigest": "agent_token_digest", "Force": "force", "AcceptedGeneration": "accepted_generation", "AcceptedSnapshotID": "accepted_snapshot_id", "RequiredCheck": "required_check", "Executed": "executed", "Reused": "reused", "ReuseProofSHA256": "reuse_proof_sha256", "Passed": "passed", "StartedAt": "started_at_unix_ms", "CompletedAt": "completed_at_unix_ms", "Duration": "duration_ms", "ReceiptSHA256": "receipt_sha256"}},
	}
}
