package codemapindex_test

import (
	"encoding/json"
	"os"
	"path/filepath"
	"runtime"
	"slices"
	"strings"
	"testing"

	"github.com/lihah111222333-cloud/super-dolphin-agent/internal/devtools/codemapindex"
)

// projectRoot walks up from this test file to the repo root (where go.mod lives).
func projectRoot(t *testing.T) string {
	t.Helper()
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller failed")
	}
	dir := filepath.Dir(thisFile)
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			t.Fatal("could not locate project root (go.mod not found)")
		}
		dir = parent
	}
}

// TestAIIndex_GeneratorAnchor verifies that the committed ai-index.json was
// produced by the canonical Go script (scripts/codemap_index.go) by checking
// for the generator anchor value. If someone regenerates the index with a
// Python/Node/etc. script the anchor will be absent or wrong, and this test
// will fail.
func TestAIIndex_GeneratorAnchor(t *testing.T) {
	root := projectRoot(t)
	indexPath := filepath.Join(root, "docs", "doc", "codemap", "ai-index.json")

	data, err := os.ReadFile(indexPath)
	if err != nil {
		t.Fatalf("failed to read ai-index.json: %v", err)
	}

	// ---- Sanity: no merge-conflict markers ----
	if strings.Contains(string(data), "<<<<<<<") || strings.Contains(string(data), ">>>>>>>") {
		t.Fatal("ai-index.json contains git merge-conflict markers; resolve conflicts and regenerate with `make codemap-refresh`")
	}

	// ---- Parse and validate generator anchor ----
	var idx struct {
		Generator string `json:"generator"`
	}
	if err := json.Unmarshal(data, &idx); err != nil {
		t.Fatalf("ai-index.json is not valid JSON: %v", err)
	}

	if idx.Generator != codemapindex.GeneratorAnchor {
		t.Fatalf(
			"ai-index.json generator mismatch:\n  got:  %q\n  want: %q\n\n"+
				"The index must be generated by the Go script.\n"+
				"Run: make codemap-refresh",
			idx.Generator, codemapindex.GeneratorAnchor,
		)
	}
}

// TestAIIndex_CompactFormat ensures the output is compact (single-line JSON),
// not pretty-printed. A pretty-printed 2.3MB file is unacceptable.
func TestAIIndex_CompactFormat(t *testing.T) {
	root := projectRoot(t)
	indexPath := filepath.Join(root, "docs", "doc", "codemap", "ai-index.json")

	data, err := os.ReadFile(indexPath)
	if err != nil {
		t.Fatalf("failed to read ai-index.json: %v", err)
	}

	lines := strings.Count(string(data), "\n")
	// Compact JSON from json.Marshal is a single line (0 or 1 newlines).
	// Allow up to 5 lines for minor formatting variance.
	if lines > 5 {
		t.Fatalf(
			"ai-index.json has %d lines; expected compact single-line JSON (≤5 lines).\n"+
				"Regenerate with: make codemap-refresh",
			lines,
		)
	}
}

// TestAIIndexRemoteCICoverage 锁定远程 CI 编号分卷与核心源码进入 canonical ai-index。
func TestAIIndexRemoteCICoverage(t *testing.T) {
	root := projectRoot(t)
	data, err := os.ReadFile(filepath.Join(root, "docs", "doc", "codemap", "ai-index.json"))
	if err != nil {
		t.Fatalf("read ai-index.json: %v", err)
	}
	var index codemapindex.Index
	if err := json.Unmarshal(data, &index); err != nil {
		t.Fatalf("decode ai-index.json: %v", err)
	}
	requireRemoteCICodemap(t, index.Codemaps)
	for _, source := range []string{
		"cmd/super-dolphin-gate/main.go",
		"internal/devtools/remoteci/coordinator.go",
		"internal/devtools/cicontract/contract.go",
		"internal/devtools/alicloud/eci/client.go",
		"internal/devtools/alicloud/oss/client.go",
	} {
		requireRemoteCISource(t, index.Files, source)
	}
}

func requireRemoteCICodemap(t *testing.T, codemaps []codemapindex.Codemap) {
	t.Helper()
	if !slices.ContainsFunc(codemaps, func(codemap codemapindex.Codemap) bool {
		return codemap.ID == "14" && codemap.File == "14-remote-ci.md"
	}) {
		t.Fatal("ai-index.json missing 14-remote-ci.md codemap")
	}
}

func requireRemoteCISource(t *testing.T, files map[string]*codemapindex.FileEntry, source string) {
	t.Helper()
	entry := files[source]
	if entry == nil || len(entry.Refs) == 0 {
		t.Fatalf("ai-index.json missing remote CI source reference for %s", source)
	}
	if !slices.ContainsFunc(entry.Refs, func(ref codemapindex.Ref) bool { return ref.CodemapID == "14" }) {
		t.Fatalf("ai-index.json source %s is not routed through codemap 14: %#v", source, entry.Refs)
	}
}

func TestScanSourceFilesSkipsWebDist(t *testing.T) {
	root := t.TempDir()
	writeTestFile(t, filepath.Join(root, "cmd", "agent-terminal", "main.go"), "package main\n")
	writeTestFile(t, filepath.Join(root, "cmd", "agent-terminal", "web-dist", "wails", "runtime.js"), "console.log('generated')\n")

	files, err := codemapindex.ScanSourceFiles(root)
	if err != nil {
		t.Fatalf("ScanSourceFiles() error = %v", err)
	}
	got := strings.Join(files, "\n")
	if strings.Contains(got, "cmd/agent-terminal/web-dist/") {
		t.Fatalf("ScanSourceFiles() indexed ignored web-dist output:\n%s", got)
	}
	if !strings.Contains(got, "cmd/agent-terminal/main.go") {
		t.Fatalf("ScanSourceFiles() = %v, want tracked source file", files)
	}
}

func writeTestFile(t *testing.T, path, body string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("mkdir fixture dir: %v", err)
	}
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatalf("write fixture file: %v", err)
	}
}
