// Package cron persists P21 P1b scheduled agent tasks.
//
// This store is the database surface only: it exposes CRUD on cron_jobs,
// claim/lease primitives driven by a single-statement atomic UPDATE with
// id-in-subquery (SQLite equivalent of FOR UPDATE SKIP LOCKED), and the
// per-trigger cron_job_runs rows that carry the three-phase state machine
// (pending -> submitting -> submitted -> running -> finished / failed /
// observe_lost).
//
// Claim atomicity relies on SQLite's statement-level atomicity: the UPDATE
// and its inner SELECT subquery execute as one indivisible step. There is no
// row-level locking; instead the WHERE id IN (SELECT ... LIMIT N) subquery
// picks candidate rows, and the outer UPDATE only touches rows that still
// match the unclaimed/expired lease predicate at write time. This gives the
// same "claim exactly N available rows, no duplicates across concurrent
// writers" guarantee as PG's FOR UPDATE SKIP LOCKED.
//
// The scheduler, lease renewer and crash-recovery policy that live on top
// of this store are delivered in Track C phase 2 — they live under
// internal/module/cron/*. claim_token is generated by the caller (UUID v4)
// so no Postgres extension is required.
package cron

import "github.com/anthropic-ai/super-agent-v3/internal/contract"

// Run status constants — mirror the CHECK constraint in migration 0045.
const (
	StatusPending     = contract.CronStatusPending
	StatusSubmitting  = contract.CronStatusSubmitting
	StatusSubmitted   = contract.CronStatusSubmitted
	StatusRunning     = contract.CronStatusRunning
	StatusFinished    = contract.CronStatusFinished
	StatusFailed      = contract.CronStatusFailed
	StatusObserveLost = contract.CronStatusObserveLost
)

// Provider whitelist mirrors the DB CHECK. The service layer still only
// accepts codex in v1 because the dedupe_key handshake is codex-only.
const (
	ProviderCodex  = contract.CronProviderCodex
	ProviderClaude = contract.CronProviderClaude
)

// Sentinel errors exposed so upper layers can errors.Is against them.
var (
	ErrJobNotFound             = contract.ErrCronJobNotFound
	ErrJobRunNotFound          = contract.ErrCronJobRunNotFound
	ErrClaimTokenMismatch      = contract.ErrCronClaimTokenMismatch
	ErrStatusTransitionRefused = contract.ErrCronStatusTransitionRefused
	ErrEmptyID                 = contract.ErrCronEmptyID
	ErrEmptyCWD                = contract.ErrCronEmptyCWD
	ErrEmptyProvider           = contract.ErrCronEmptyProvider
	ErrEmptyScheduleExpr       = contract.ErrCronEmptyScheduleExpr
	ErrEmptyClaimToken         = contract.ErrCronEmptyClaimToken
)

// Store is the persistence surface. Return values always clone sqlc rows
// into the Job / Run domain DTOs below; callers never see pgtype.
type Store = contract.CronStore

// Job is the domain DTO for a cron_jobs row. Time fields are zero when the
// underlying column is NULL; callers that need nullable semantics should
// check LastRunAt.IsZero() etc.
type Job = contract.CronJob

// Run is the domain DTO for a cron_job_runs row.
type Run = contract.CronRun

// CreateJobParams is the input for Store.CreateJob.
type CreateJobParams = contract.CronCreateJobParams

// UpdateJobScheduleParams is the input for Store.UpdateJobSchedule.
type UpdateJobScheduleParams = contract.CronUpdateJobScheduleParams

// ClaimDueJobsForUpdateParams drives ClaimDueJobsForUpdate. ClaimToken is generated by the
// caller (UUID v4). The scheduler uses MaxClaim=1 per call so each job
// gets an independent claim token; renew/finish/release then verify that
// token to prevent a preempted worker from overwriting state.
type ClaimDueJobsForUpdateParams = contract.CronClaimDueJobsForUpdateParams

// LeaseParams drives RenewLease / ExtendClaim.
type LeaseParams = contract.CronLeaseParams

// MarkFinishedParams drives MarkFinished.
type MarkFinishedParams = contract.CronMarkFinishedParams

// MarkFailedParams drives MarkFailed. LastStatus is a free-form label
// (typically "failed" or "observe_lost"); failure_count increments by 1.
type MarkFailedParams = contract.CronMarkFailedParams

// SetActiveTurnParams drives SetActiveTurn. Empty ThreadID / AgentID are
// treated as "don't overwrite" so resume paths can bind turn id without
// clobbering identity already recorded earlier in the run.
type SetActiveTurnParams = contract.CronSetActiveTurnParams

// InsertRunParams drives InsertRun. Status must be a value from the run
// status constants above and is validated by the DB CHECK constraint.
type InsertRunParams = contract.CronInsertRunParams

// CASRunStatusParams drives CASRunStatus. The transition is applied iff
// the current row.status equals ExpectedStatus; otherwise returns
// ErrStatusTransitionRefused.
type CASRunStatusParams = contract.CronCASRunStatusParams

// SetRunTurnParams drives SetRunTurn. Empty ThreadID / AgentID are
// preserved against existing values (CoalesceNullIf).
type SetRunTurnParams = contract.CronSetRunTurnParams
