package bus

import (
	"context"
	"reflect"
	"runtime"
	"strings"
	"sync"
	"time"

	agentdto "github.com/anthropic-ai/super-agent-v3/internal/dto/agent"
	taskdto "github.com/anthropic-ai/super-agent-v3/internal/dto/task"
	threaddto "github.com/anthropic-ai/super-agent-v3/internal/dto/thread"
	tooldto "github.com/anthropic-ai/super-agent-v3/internal/dto/tool"
	turndto "github.com/anthropic-ai/super-agent-v3/internal/dto/turn"
	uidto "github.com/anthropic-ai/super-agent-v3/internal/dto/ui"
	pkglogger "github.com/anthropic-ai/super-agent-v3/pkg/logger"
	"github.com/kelindar/event"
)

// LogSink subscribes to known bus events and mirrors them to structured logs.
type LogSink struct {
	subs        *Subscription
	trace       TraceRecorder
	traceMu     sync.Mutex
	traceCounts map[string]int64
}

// TraceStatus records whether a mirrored event produced a full or summarized trace.
type TraceStatus string

const (
	TraceStatusOK             TraceStatus = "ok"
	TraceStatusDroppedSummary TraceStatus = "dropped_summary"
)

// TraceCodeAnchor identifies the call site that emitted a bus trace record.
type TraceCodeAnchor struct {
	File     string
	Function string
	Line     int
}

// TraceRecord is the structured bus event mirror persisted by a TraceRecorder.
type TraceRecord struct {
	SchemaVersion int
	Timestamp     time.Time
	TraceID       string
	SpanID        string
	ParentSpanID  string
	Kind          string
	Method        string
	ThreadID      string
	AgentID       string
	TurnID        string
	CallID        string
	ToolName      string
	Status        TraceStatus
	Code          TraceCodeAnchor
	Metadata      map[string]any
}

// TraceRecorder persists structured trace records generated by the bus log sink.
type TraceRecorder interface {
	RecordTrace(context.Context, TraceRecord) error
}

// LogSinkDeps collects dependencies required to mirror bus events to logs and traces.
type LogSinkDeps struct {
	Dispatcher *event.Dispatcher
	Logger     *pkglogger.Logger
	Trace      TraceRecorder
}

// NewLogSink 创建日志sink。
func NewLogSink(p LogSinkDeps) *LogSink {
	sink := &LogSink{subs: NewSubscription(), trace: p.Trace, traceCounts: map[string]int64{}}
	if p.Dispatcher == nil || p.Logger == nil {
		pkglogger.Warn("bus: NewLogSink called with nil dispatcher or logger, event logging disabled")
		return sink
	}
	sink.bindAgent(p.Dispatcher, p.Logger)
	sink.bindThread(p.Dispatcher, p.Logger)
	sink.bindTurn(p.Dispatcher, p.Logger)
	sink.bindTool(p.Dispatcher, p.Logger)
	sink.bindTask(p.Dispatcher, p.Logger)
	sink.bindUI(p.Dispatcher, p.Logger)
	return sink
}

// Close 关闭平台bus资源。
func (s *LogSink) Close() {
	if s.subs == nil {
		return
	}
	s.subs.CancelAll()
	s.subs = nil
}

func (s *LogSink) bindAgent(dispatcher *event.Dispatcher, logger *pkglogger.Logger) {
	s.subs.Add(logEvent[agentdto.StateChanged](dispatcher, logger, s.traceLifecycleEvent))
	s.subs.Add(logEvent[agentdto.AgentLaunched](dispatcher, logger, s.traceLifecycleEvent))
	s.subs.Add(logEvent[agentdto.AgentStopped](dispatcher, logger, s.traceLifecycleEvent))
	s.subs.Add(logDebugEvent[agentdto.AgentRecovering](dispatcher, logger, s.traceHighFrequencyLifecycleEvent))
	s.subs.Add(logDebugEvent[agentdto.AgentFailed](dispatcher, logger, s.traceHighFrequencyLifecycleEvent))
	s.subs.Add(logDebugEvent[agentdto.AgentRuntimeReported](dispatcher, logger, s.traceHighFrequencyLifecycleEvent))
	s.subs.Add(logEvent[agentdto.AgentWarning](dispatcher, logger, s.traceLifecycleEvent))
	s.subs.Add(logEvent[agentdto.AgentError](dispatcher, logger, s.traceLifecycleEvent))
}

func (s *LogSink) bindThread(dispatcher *event.Dispatcher, logger *pkglogger.Logger) {
	s.subs.Add(logEvent[threaddto.Started](dispatcher, logger, s.traceLifecycleEvent))
	s.subs.Add(logEvent[threaddto.Stopped](dispatcher, logger, s.traceLifecycleEvent))
	s.subs.Add(logDebugEvent[threaddto.MessagesPage](dispatcher, logger, s.traceHighFrequencyLifecycleEvent))
}

func (s *LogSink) bindTurn(dispatcher *event.Dispatcher, logger *pkglogger.Logger) {
	s.subs.Add(logEvent[turndto.TurnStarted](dispatcher, logger, s.traceLifecycleEvent))
	s.subs.Add(logEvent[turndto.TurnCompleted](dispatcher, logger, s.traceLifecycleEvent))
	s.subs.Add(logEvent[turndto.TurnInterrupted](dispatcher, logger, s.traceLifecycleEvent))
	s.subs.Add(logEvent[turndto.TurnStalled](dispatcher, logger, s.traceLifecycleEvent))
	s.subs.Add(logEvent[turndto.TurnResumed](dispatcher, logger, s.traceLifecycleEvent))
	s.subs.Add(logDebugEvent[turndto.TurnInputReceived](dispatcher, logger, s.traceHighFrequencyLifecycleEvent))
	s.subs.Add(logDebugEvent[turndto.TurnOutputDelta](dispatcher, logger, s.traceHighFrequencyLifecycleEvent))
	s.subs.Add(logDebugEvent[turndto.PlanDelta](dispatcher, logger, s.traceHighFrequencyLifecycleEvent))
	s.subs.Add(logEvent[turndto.PlanUpdated](dispatcher, logger, s.traceLifecycleEvent))
	s.subs.Add(logDebugEvent[turndto.ItemStarted](dispatcher, logger, s.traceHighFrequencyLifecycleEvent))
	s.subs.Add(logDebugEvent[turndto.ItemCompleted](dispatcher, logger, s.traceHighFrequencyLifecycleEvent))
}

func (s *LogSink) bindTool(dispatcher *event.Dispatcher, logger *pkglogger.Logger) {
	s.subs.Add(logDebugEvent[tooldto.ToolCallBegin](dispatcher, logger, s.traceHighFrequencyLifecycleEvent))
	s.subs.Add(logDebugEvent[tooldto.ToolCallEnd](dispatcher, logger, s.traceHighFrequencyLifecycleEvent))
	s.subs.Add(logDebugEvent[tooldto.ToolApprovalRequested](dispatcher, logger, s.traceHighFrequencyLifecycleEvent))
	s.subs.Add(logDebugEvent[tooldto.ToolApprovalResolved](dispatcher, logger, s.traceHighFrequencyLifecycleEvent))
}

func (s *LogSink) bindTask(dispatcher *event.Dispatcher, logger *pkglogger.Logger) {
	s.subs.Add(logEvent[taskdto.TaskDagCreated](dispatcher, logger, s.traceLifecycleEvent))
	s.subs.Add(logEvent[taskdto.TaskNodeStatusChanged](dispatcher, logger, s.traceLifecycleEvent))
	s.subs.Add(logEvent[taskdto.TaskWakeupDispatched](dispatcher, logger, s.traceLifecycleEvent))
	s.subs.Add(logEvent[taskdto.TaskWakeupCompleted](dispatcher, logger, s.traceLifecycleEvent))
}

func (s *LogSink) bindUI(dispatcher *event.Dispatcher, logger *pkglogger.Logger) {
	s.subs.Add(logDebugEvent[uidto.UIProjectionUpdated](dispatcher, logger, s.traceHighFrequencyLifecycleEvent))
	s.subs.Add(logDebugEvent[uidto.UITimelineAppended](dispatcher, logger, s.traceHighFrequencyLifecycleEvent))
	s.subs.Add(logDebugEvent[uidto.UITokensUpdated](dispatcher, logger, s.traceHighFrequencyLifecycleEvent))
}

func logEvent[T event.Event](dispatcher *event.Dispatcher, logger *pkglogger.Logger, trace func(any)) func() {
	if dispatcher == nil || logger == nil {
		return func() {}
	}
	return event.Subscribe(dispatcher, func(ev T) {
		logger.Info("bus event",
			pkglogger.String("event_type", eventTypeName(ev)),
			pkglogger.Any("event", ev),
		)
		if trace != nil {
			trace(ev)
		}
	})
}

func logDebugEvent[T event.Event](dispatcher *event.Dispatcher, logger *pkglogger.Logger, trace func(any)) func() {
	if dispatcher == nil || logger == nil {
		return func() {}
	}
	return event.Subscribe(dispatcher, func(ev T) {
		logger.Debug("bus event",
			pkglogger.String("event_type", eventTypeName(ev)),
			pkglogger.Any("event", ev),
		)
		if trace != nil {
			trace(ev)
		}
	})
}

func eventTypeName(ev any) string {
	if ev == nil {
		return "<nil>"
	}
	return reflect.TypeOf(ev).String()
}

const busHighFrequencyTraceEvery = 100

func (s *LogSink) traceLifecycleEvent(ev any) {
	s.recordTraceEvent(ev, TraceStatusOK, nil)
}

func (s *LogSink) traceHighFrequencyLifecycleEvent(ev any) {
	if s == nil || s.trace == nil {
		return
	}
	eventType := eventTypeName(ev)
	s.traceMu.Lock()
	s.traceCounts[eventType]++
	count := s.traceCounts[eventType]
	if count < busHighFrequencyTraceEvery {
		s.traceMu.Unlock()
		return
	}
	s.traceCounts[eventType] = 0
	s.traceMu.Unlock()
	s.recordTraceEvent(ev, TraceStatusDroppedSummary, map[string]any{
		"event_type":    eventType,
		"dropped_count": count,
	})
}

func (s *LogSink) recordTraceEvent(ev any, status TraceStatus, metadata map[string]any) {
	if s == nil || s.trace == nil {
		return
	}
	ids := busTraceIdentifiers(ev)
	if metadata == nil {
		metadata = map[string]any{}
	}
	metadata["event_type"] = eventTypeName(ev)
	_ = s.trace.RecordTrace(context.Background(), TraceRecord{
		SchemaVersion: 1,
		Timestamp:     time.Now(),
		Kind:          "bus_event",
		Method:        "bus.event.lifecycle",
		TraceID:       ids.traceID,
		SpanID:        ids.spanID,
		ParentSpanID:  ids.parentSpanID,
		ThreadID:      ids.threadID,
		AgentID:       ids.agentID,
		TurnID:        ids.turnID,
		CallID:        ids.callID,
		ToolName:      ids.toolName,
		Status:        status,
		Code:          traceCodeAnchorFromCaller(0),
		Metadata:      metadata,
	})
}

func traceCodeAnchorFromCaller(skip int) TraceCodeAnchor {
	pc, file, line, ok := runtime.Caller(skip + 1)
	if !ok {
		return TraceCodeAnchor{}
	}
	function := ""
	if fn := runtime.FuncForPC(pc); fn != nil {
		function = fn.Name()
	}
	return TraceCodeAnchor{File: file, Function: function, Line: line}
}

type busTraceIDs struct{ traceID, spanID, parentSpanID, threadID, agentID, turnID, callID, toolName string }

func busTraceIdentifiers(ev any) busTraceIDs {
	value := reflect.Indirect(reflect.ValueOf(ev))
	if !value.IsValid() || value.Kind() != reflect.Struct {
		return busTraceIDs{}
	}
	return busTraceIDs{
		traceID:      stringField(value, "TraceID"),
		spanID:       stringField(value, "SpanID"),
		parentSpanID: stringField(value, "ParentSpanID"),
		threadID:     stringField(value, "ThreadID"),
		agentID:      stringField(value, "AgentID"),
		turnID:       stringField(value, "TurnID"),
		callID:       stringField(value, "CallID"),
		toolName:     stringField(value, "ToolName"),
	}
}

// stringField 处理string字段。
func stringField(value reflect.Value, name string) string {
	field := value.FieldByName(name)
	if !field.IsValid() && value.Kind() == reflect.Struct {
		for i := 0; i < value.NumField(); i++ {
			candidate := value.Field(i)
			if candidate.Kind() == reflect.Struct {
				if out := stringField(candidate, name); out != "" {
					return out
				}
			}
		}
		return ""
	}
	if !field.IsValid() || field.Kind() != reflect.String {
		return ""
	}
	return strings.TrimSpace(field.String())
}
