package prompt

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"strings"
	"sync"
)

// sectionInputCacheKey 处理sectioninput缓存键。
func sectionInputCacheKey(section PromptSection, input SectionContext) (string, bool) {
	switch section.CachePolicy {
	case Uncached:
		return strings.TrimSpace(section.Name), strings.TrimSpace(section.Name) != ""
	case InputScoped:
		encoded, err := json.Marshal(inputScopedCacheDependency(section, input))
		if err != nil {
			return "", false
		}
		digest := sha256.Sum256(encoded)
		return section.Name + ":" + hex.EncodeToString(digest[:]), true
	default:
		if dependency := cacheByNameSectionDependency(section, input); dependency != nil {
			encoded, err := json.Marshal(dependency)
			if err == nil {
				digest := sha256.Sum256(encoded)
				return section.Name + ":" + hex.EncodeToString(digest[:]), true
			}
		}
		return section.Name, true
	}
}

func inputScopedCacheDependency(section PromptSection, input SectionContext) any {
	return inputScopedSectionDependency(section, input)
}

// sectionCache 按名称缓存已解析的 prompt section 内容，generation 自增触发全量失效。
type sectionCache struct {
	mu         sync.RWMutex
	generation uint64
	values     map[string]*string
}

// sectionCache stores resolved prompt sections by the cache key generated by
// sectionInputCacheKey above. Claude often relies on section-name reuse, but V3
// intentionally keeps dependency-aware keys for sections whose output changes
// with render inputs such as enabled tools or output style. This is a deliberate
// freshness-over-parity choice: stable sections can still reuse bare names,
// while dependency-sensitive sections avoid stale prompt reuse.
func newSectionCache() *sectionCache {
	return &sectionCache{values: map[string]*string{}}
}

// Generation 处理代际。
func (c *sectionCache) Generation() uint64 {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return c.generation
}

// Lookup 按名称查找注册项。
func (c *sectionCache) Lookup(name string, generation uint64) (*string, bool) {
	key := strings.TrimSpace(name)
	if key == "" {
		return nil, false
	}

	c.mu.RLock()
	defer c.mu.RUnlock()
	if generation != c.generation {
		return nil, false
	}
	value, ok := c.values[key]
	if !ok {
		return nil, false
	}
	return cloneStringPtr(value), true
}

// Store 保存prompt。
func (c *sectionCache) Store(name string, generation uint64, value *string) bool {
	key := strings.TrimSpace(name)
	if key == "" {
		return false
	}

	c.mu.Lock()
	defer c.mu.Unlock()
	if generation != c.generation {
		return false
	}
	c.values[key] = cloneStringPtr(value)
	return true
}

// ObserveVolatile 处理observevolatile。
func (c *sectionCache) ObserveVolatile(name string, generation uint64, value *string) (*string, bool) {
	key := strings.TrimSpace(name)
	if key == "" {
		return cloneStringPtr(value), false
	}

	c.mu.Lock()
	defer c.mu.Unlock()
	if generation != c.generation {
		return cloneStringPtr(value), false
	}
	current, ok := c.values[key]
	changed := !ok || !stringPtrEqual(current, value)
	if changed {
		c.values[key] = cloneStringPtr(value)
		current = c.values[key]
	}
	return cloneStringPtr(current), changed
}

// InvalidateAll 处理invalidateall。
func (c *sectionCache) InvalidateAll(_ InvalidateReason) uint64 {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.generation++
	c.values = map[string]*string{}
	return c.generation
}

// InvalidateSections 处理invalidatesections。
func (c *sectionCache) InvalidateSections(names ...string) uint64 {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.generation++
	for _, name := range names {
		name = strings.TrimSpace(name)
		if name == "" {
			continue
		}
		for key := range c.values {
			if key == name || strings.HasPrefix(key, name+":") {
				delete(c.values, key)
			}
		}
	}
	return c.generation
}

// cloneStringPtr 深拷贝字符串指针，nil 安全。
func cloneStringPtr(value *string) *string {
	if value == nil {
		return nil
	}
	cloned := *value
	return &cloned
}

func stringPtrEqual(left, right *string) bool {
	switch {
	case left == nil && right == nil:
		return true
	case left == nil || right == nil:
		return false
	default:
		return *left == *right
	}
}
