// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_provider_binding.sql

package sqlc

import (
	"context"
)

const deleteAgentProviderBindingByAgentID = `-- name: DeleteAgentProviderBindingByAgentID :exec
DELETE FROM agent_provider_binding
WHERE agent_id = $1
`

func (q *Queries) DeleteAgentProviderBindingByAgentID(ctx context.Context, agentID string) error {
	_, err := q.db.Exec(ctx, deleteAgentProviderBindingByAgentID, agentID)
	return err
}

const getAgentProviderBindingByAgentID = `-- name: GetAgentProviderBindingByAgentID :one
SELECT agent_id, provider, provider_thread_id, codex_thread_id, rollout_path, cwd, archived, created_at, updated_at, session_uuid
FROM agent_provider_binding
WHERE agent_id = $1
`

func (q *Queries) GetAgentProviderBindingByAgentID(ctx context.Context, agentID string) (AgentProviderBinding, error) {
	row := q.db.QueryRow(ctx, getAgentProviderBindingByAgentID, agentID)
	var i AgentProviderBinding
	err := row.Scan(
		&i.AgentID,
		&i.Provider,
		&i.ProviderThreadID,
		&i.CodexThreadID,
		&i.RolloutPath,
		&i.Cwd,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SessionUUID,
	)
	return i, err
}

const getAgentProviderBindingByProviderThread = `-- name: GetAgentProviderBindingByProviderThread :one
SELECT agent_id, provider, provider_thread_id, codex_thread_id, rollout_path, cwd, archived, created_at, updated_at, session_uuid
FROM agent_provider_binding
WHERE provider = $1 AND provider_thread_id = $2
`

type GetAgentProviderBindingByProviderThreadParams struct {
	Provider         string `db:"provider" json:"provider"`
	ProviderThreadID string `db:"provider_thread_id" json:"provider_thread_id"`
}

func (q *Queries) GetAgentProviderBindingByProviderThread(ctx context.Context, arg GetAgentProviderBindingByProviderThreadParams) (AgentProviderBinding, error) {
	row := q.db.QueryRow(ctx, getAgentProviderBindingByProviderThread, arg.Provider, arg.ProviderThreadID)
	var i AgentProviderBinding
	err := row.Scan(
		&i.AgentID,
		&i.Provider,
		&i.ProviderThreadID,
		&i.CodexThreadID,
		&i.RolloutPath,
		&i.Cwd,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SessionUUID,
	)
	return i, err
}

const updateAgentProviderBindingArchived = `-- name: UpdateAgentProviderBindingArchived :exec
UPDATE agent_provider_binding
SET archived = $1,
    updated_at = $2
WHERE agent_id = $3
`

type UpdateAgentProviderBindingArchivedParams struct {
	Archived  bool   `db:"archived" json:"archived"`
	UpdatedAt int64  `db:"updated_at" json:"updated_at"`
	AgentID   string `db:"agent_id" json:"agent_id"`
}

func (q *Queries) UpdateAgentProviderBindingArchived(ctx context.Context, arg UpdateAgentProviderBindingArchivedParams) error {
	_, err := q.db.Exec(ctx, updateAgentProviderBindingArchived, arg.Archived, arg.UpdatedAt, arg.AgentID)
	return err
}

const updateAgentProviderBindingSessionUUID = `-- name: UpdateAgentProviderBindingSessionUUID :exec
UPDATE agent_provider_binding
SET session_uuid = $1,
    updated_at = $2
WHERE agent_id = $3
`

type UpdateAgentProviderBindingSessionUUIDParams struct {
	SessionUUID string `db:"session_uuid" json:"session_uuid"`
	UpdatedAt   int64  `db:"updated_at" json:"updated_at"`
	AgentID     string `db:"agent_id" json:"agent_id"`
}

func (q *Queries) UpdateAgentProviderBindingSessionUUID(ctx context.Context, arg UpdateAgentProviderBindingSessionUUIDParams) error {
	_, err := q.db.Exec(ctx, updateAgentProviderBindingSessionUUID, arg.SessionUUID, arg.UpdatedAt, arg.AgentID)
	return err
}

const upsertAgentProviderBinding = `-- name: UpsertAgentProviderBinding :exec
INSERT INTO agent_provider_binding (
    agent_id, provider, provider_thread_id, codex_thread_id, rollout_path, cwd, archived, created_at, updated_at, session_uuid
) VALUES ($1, $2, $3, $4, $5, $6, false, $7, $8, $9)
ON CONFLICT (agent_id) DO UPDATE
SET provider = EXCLUDED.provider,
    provider_thread_id = EXCLUDED.provider_thread_id,
    codex_thread_id = EXCLUDED.codex_thread_id,
    rollout_path = EXCLUDED.rollout_path,
    cwd = EXCLUDED.cwd,
    session_uuid = EXCLUDED.session_uuid,
    updated_at = EXCLUDED.updated_at
`

type UpsertAgentProviderBindingParams struct {
	AgentID          string `db:"agent_id" json:"agent_id"`
	Provider         string `db:"provider" json:"provider"`
	ProviderThreadID string `db:"provider_thread_id" json:"provider_thread_id"`
	CodexThreadID    string `db:"codex_thread_id" json:"codex_thread_id"`
	RolloutPath      string `db:"rollout_path" json:"rollout_path"`
	Cwd              string `db:"cwd" json:"cwd"`
	CreatedAt        int64  `db:"created_at" json:"created_at"`
	UpdatedAt        int64  `db:"updated_at" json:"updated_at"`
	SessionUUID      string `db:"session_uuid" json:"session_uuid"`
}

func (q *Queries) UpsertAgentProviderBinding(ctx context.Context, arg UpsertAgentProviderBindingParams) error {
	_, err := q.db.Exec(ctx, upsertAgentProviderBinding,
		arg.AgentID,
		arg.Provider,
		arg.ProviderThreadID,
		arg.CodexThreadID,
		arg.RolloutPath,
		arg.Cwd,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.SessionUUID,
	)
	return err
}
