// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_status.sql

package sqlc

import (
	"context"
)

const getAgentStatus = `-- name: GetAgentStatus :one
SELECT agent_id, agent_name, session_id, status, stagnant_sec, error, output_tail, created_at, updated_at
FROM agent_status
WHERE agent_id = $1
`

type GetAgentStatusParams struct {
	AgentID string `db:"agent_id" json:"agent_id"`
}

func (q *Queries) GetAgentStatus(ctx context.Context, arg GetAgentStatusParams) (AgentStatus, error) {
	row := q.db.QueryRow(ctx, getAgentStatus, arg.AgentID)
	var i AgentStatus
	err := row.Scan(
		&i.AgentID,
		&i.AgentName,
		&i.SessionID,
		&i.Status,
		&i.StagnantSec,
		&i.Error,
		&i.OutputTail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentStatuses = `-- name: ListAgentStatuses :many
SELECT agent_id, agent_name, session_id, status, stagnant_sec, error, output_tail, created_at, updated_at
FROM agent_status
WHERE ($1::text = '' OR status = $1)
ORDER BY updated_at DESC
LIMIT 500
`

type ListAgentStatusesParams struct {
	Column1 string `db:"column_1" json:"column_1"`
}

func (q *Queries) ListAgentStatuses(ctx context.Context, arg ListAgentStatusesParams) ([]AgentStatus, error) {
	rows, err := q.db.Query(ctx, listAgentStatuses, arg.Column1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentStatus{}
	for rows.Next() {
		var i AgentStatus
		if err := rows.Scan(
			&i.AgentID,
			&i.AgentName,
			&i.SessionID,
			&i.Status,
			&i.StagnantSec,
			&i.Error,
			&i.OutputTail,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAgentStatus = `-- name: UpsertAgentStatus :one
INSERT INTO agent_status (agent_id, agent_name, session_id, status, stagnant_sec, error, output_tail, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7::jsonb, NOW(), NOW())
ON CONFLICT (agent_id) DO UPDATE
SET agent_name = EXCLUDED.agent_name,
    session_id = EXCLUDED.session_id,
    status = EXCLUDED.status,
    stagnant_sec = EXCLUDED.stagnant_sec,
    error = EXCLUDED.error,
    output_tail = EXCLUDED.output_tail,
    updated_at = NOW()
RETURNING agent_id, agent_name, session_id, status, stagnant_sec, error, output_tail, created_at, updated_at
`

type UpsertAgentStatusParams struct {
	AgentID     string `db:"agent_id" json:"agent_id"`
	AgentName   string `db:"agent_name" json:"agent_name"`
	SessionID   string `db:"session_id" json:"session_id"`
	Status      string `db:"status" json:"status"`
	StagnantSec int32  `db:"stagnant_sec" json:"stagnant_sec"`
	Error       string `db:"error" json:"error"`
	Column7     []byte `db:"column_7" json:"column_7"`
}

func (q *Queries) UpsertAgentStatus(ctx context.Context, arg UpsertAgentStatusParams) (AgentStatus, error) {
	row := q.db.QueryRow(ctx, upsertAgentStatus,
		arg.AgentID,
		arg.AgentName,
		arg.SessionID,
		arg.Status,
		arg.StagnantSec,
		arg.Error,
		arg.Column7,
	)
	var i AgentStatus
	err := row.Scan(
		&i.AgentID,
		&i.AgentName,
		&i.SessionID,
		&i.Status,
		&i.StagnantSec,
		&i.Error,
		&i.OutputTail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
