// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_status.sql

package sqlc

import (
	"context"
	"encoding/json"
)

const getAgentStatus = `-- name: GetAgentStatus :one
SELECT agent_id, agent_name, session_id, status, stagnant_sec, error, output_tail, created_at, updated_at
FROM agent_status
WHERE agent_id = ?
`

type GetAgentStatusParams struct {
	AgentID string `db:"agent_id" json:"agent_id"`
}

func (q *Queries) GetAgentStatus(ctx context.Context, arg GetAgentStatusParams) (AgentStatus, error) {
	row := q.db.QueryRowContext(ctx, getAgentStatus, arg.AgentID)
	var i AgentStatus
	err := row.Scan(
		&i.AgentID,
		&i.AgentName,
		&i.SessionID,
		&i.Status,
		&i.StagnantSec,
		&i.Error,
		&i.OutputTail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentStatuses = `-- name: ListAgentStatuses :many
SELECT agent_id, agent_name, session_id, status, stagnant_sec, error, output_tail, created_at, updated_at
FROM agent_status
WHERE (?1 = '' OR status = ?1)
ORDER BY updated_at DESC
LIMIT 500
`

type ListAgentStatusesParams struct {
	StatusFilter any `db:"status_filter" json:"status_filter"`
}

func (q *Queries) ListAgentStatuses(ctx context.Context, arg ListAgentStatusesParams) ([]AgentStatus, error) {
	rows, err := q.db.QueryContext(ctx, listAgentStatuses, arg.StatusFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentStatus{}
	for rows.Next() {
		var i AgentStatus
		if err := rows.Scan(
			&i.AgentID,
			&i.AgentName,
			&i.SessionID,
			&i.Status,
			&i.StagnantSec,
			&i.Error,
			&i.OutputTail,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAgentStatus = `-- name: UpsertAgentStatus :one
INSERT INTO agent_status (agent_id, agent_name, session_id, status, stagnant_sec, error, output_tail, created_at, updated_at)
VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?8
)
ON CONFLICT (agent_id) DO UPDATE
SET agent_name = EXCLUDED.agent_name,
    session_id = EXCLUDED.session_id,
    status = EXCLUDED.status,
    stagnant_sec = EXCLUDED.stagnant_sec,
    error = EXCLUDED.error,
    output_tail = EXCLUDED.output_tail,
    updated_at = EXCLUDED.updated_at
RETURNING agent_id, agent_name, session_id, status, stagnant_sec, error, output_tail, created_at, updated_at
`

type UpsertAgentStatusParams struct {
	AgentID     string          `db:"agent_id" json:"agent_id"`
	AgentName   string          `db:"agent_name" json:"agent_name"`
	SessionID   string          `db:"session_id" json:"session_id"`
	Status      string          `db:"status" json:"status"`
	StagnantSec int64           `db:"stagnant_sec" json:"stagnant_sec"`
	Error       string          `db:"error" json:"error"`
	OutputTail  json.RawMessage `db:"output_tail" json:"output_tail"`
	Now         int64           `db:"now" json:"now"`
}

func (q *Queries) UpsertAgentStatus(ctx context.Context, arg UpsertAgentStatusParams) (AgentStatus, error) {
	row := q.db.QueryRowContext(ctx, upsertAgentStatus,
		arg.AgentID,
		arg.AgentName,
		arg.SessionID,
		arg.Status,
		arg.StagnantSec,
		arg.Error,
		arg.OutputTail,
		arg.Now,
	)
	var i AgentStatus
	err := row.Scan(
		&i.AgentID,
		&i.AgentName,
		&i.SessionID,
		&i.Status,
		&i.StagnantSec,
		&i.Error,
		&i.OutputTail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
