// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ai_log.sql

package sqlc

import (
	"context"
	"encoding/json"
)

const countAILogsByStatus = `-- name: CountAILogsByStatus :many
LIMIT ?;

SELECT level AS http_status, COUNT(*) AS count
FROM system_logs
GROUP BY level
ORDER BY l
`

type CountAILogsByStatusRow struct {
	HttpStatus string `db:"http_status" json:"http_status"`
	Count      int64  `db:"count" json:"count"`
}

func (q *Queries) CountAILogsByStatus(ctx context.Context) ([]CountAILogsByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, countAILogsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountAILogsByStatusRow{}
	for rows.Next() {
		var i CountAILogsByStatusRow
		if err := rows.Scan(&i.HttpStatus, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAILogSystemLogs = `-- name: ListAILogSystemLogs :many
SELECT id, ts, level, logger, message, raw, source, component, agent_id, thread_id, trace_id, event_type, tool_name, duration_ms, extra
FROM system_logs
WHERE (? = '' OR message LIKE '%' || ? || '%')
ORDER BY ts DESC, id DESC
LIMIT ?
`

type ListAILogSystemLogsParams struct {
	Column1 interface{} `db:"column_1" json:"column_1"`
	Column2 *string     `db:"column_2" json:"column_2"`
	Limit   int64       `db:"limit" json:"limit"`
}

func (q *Queries) ListAILogSystemLogs(ctx context.Context, arg ListAILogSystemLogsParams) ([]SystemLog, error) {
	rows, err := q.db.QueryContext(ctx, listAILogSystemLogs, arg.Column1, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemLog{}
	for rows.Next() {
		var i SystemLog
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.Level,
			&i.Logger,
			&i.Message,
			&i.Raw,
			&i.Source,
			&i.Component,
			&i.AgentID,
			&i.ThreadID,
			&i.TraceID,
			&i.EventType,
			&i.ToolName,
			&i.DurationMs,
			&i.Extra,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAILogsByCategory = `-- name: ListAILogsByCategory :many
SELECT
    id,
    ts,
    level,
    logger,
    message,
    raw,
    source,
    component,
    agent_id,
    thread_id,
    trace_id,
    event_type,
    tool_name,
    duration_ms,
    extra,
    CASE
        WHEN message LIKE '%api request%'
            OR message LIKE '%request to%'
            OR message LIKE '%http request%' THEN 'api_request'
        WHEN message LIKE '%api error%'
            OR message LIKE '%api_error%' THEN 'api_error'
        WHEN message LIKE '%compat%'
            OR message LIKE '%fallback%'
            OR message LIKE '%兼容%' THEN 'compat_fallback'
        WHEN message LIKE '%runtime%'
            AND message LIKE '%config%' THEN 'runtime_config'
        WHEN message LIKE '%error%'
            OR message LIKE '%exception%' THEN 'error'
        ELSE 'ai_event'
    END AS category,
    '' AS method,
    '' AS url,
    '' AS endpoint,
    '' AS http_status,
    '' AS status_text,
    '' AS model
FROM system_logs
WHERE (? = '' OR (
    CASE
        WHEN message LIKE '%api request%' OR message LIKE '%request to%' OR message LIKE '%http request%' THEN 'api_request'
        WHEN message LIKE '%api error%' OR message LIKE '%api_error%' THEN 'api_error'
        WHEN message LIKE '%compat%' OR message LIKE '%fallback%' OR message LIKE '%兼容%' THEN 'compat_fallback'
        WHEN message LIKE '%runtime%' AND message LIKE '%config%' THEN 'runtime_config'
        WHEN message LIKE '%error%' OR message LIKE '%exception%' THEN 'error'
        ELSE 'ai_event'
    END = ?))
  AND (? = '' OR message LIKE '%' || ? || '%')
ORDER BY ts DESC, id DESC
`

type ListAILogsByCategoryParams struct {
	Column1 interface{} `db:"column_1" json:"column_1"`
	Message string      `db:"message" json:"message"`
	Column3 interface{} `db:"column_3" json:"column_3"`
	Column4 *string     `db:"column_4" json:"column_4"`
	Limit   int64       `db:"limit" json:"limit"`
}

type ListAILogsByCategoryRow struct {
	ID         int64           `db:"id" json:"id"`
	Ts         int64           `db:"ts" json:"ts"`
	Level      string          `db:"level" json:"level"`
	Logger     string          `db:"logger" json:"logger"`
	Message    string          `db:"message" json:"message"`
	Raw        string          `db:"raw" json:"raw"`
	Source     string          `db:"source" json:"source"`
	Component  string          `db:"component" json:"component"`
	AgentID    string          `db:"agent_id" json:"agent_id"`
	ThreadID   string          `db:"thread_id" json:"thread_id"`
	TraceID    string          `db:"trace_id" json:"trace_id"`
	EventType  string          `db:"event_type" json:"event_type"`
	ToolName   string          `db:"tool_name" json:"tool_name"`
	DurationMs *int64          `db:"duration_ms" json:"duration_ms"`
	Extra      json.RawMessage `db:"extra" json:"extra"`
	Category   string          `db:"category" json:"category"`
	Method     string          `db:"method" json:"method"`
	Url        string          `db:"url" json:"url"`
	Endpoint   string          `db:"endpoint" json:"endpoint"`
	HttpStatus string          `db:"http_status" json:"http_status"`
	StatusText string          `db:"status_text" json:"status_text"`
	Model      string          `db:"model" json:"model"`
}

func (q *Queries) ListAILogsByCategory(ctx context.Context, arg ListAILogsByCategoryParams) ([]ListAILogsByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listAILogsByCategory,
		arg.Column1,
		arg.Message,
		arg.Column3,
		arg.Column4,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAILogsByCategoryRow{}
	for rows.Next() {
		var i ListAILogsByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.Level,
			&i.Logger,
			&i.Message,
			&i.Raw,
			&i.Source,
			&i.Component,
			&i.AgentID,
			&i.ThreadID,
			&i.TraceID,
			&i.EventType,
			&i.ToolName,
			&i.DurationMs,
			&i.Extra,
			&i.Category,
			&i.Method,
			&i.Url,
			&i.Endpoint,
			&i.HttpStatus,
			&i.StatusText,
			&i.Model,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentAILogs = `-- name: ListRecentAILogs :many
vel ASC;

WITH derived_logs AS (
    SELECT
        id,
        ts,
        level,
        logger,
        message,
        raw,
        source,
        component,
        agent_id,
        thread_id,
        trace_id,
        event_type,
        tool_name,
        duration_ms,
        extra,
        CASE
            WHEN message LIKE '%api request%'
                OR message LIKE '%request to%'
                OR message LIKE '%http request%' THEN 'api_request'
            WHEN message LIKE '%api error%'
                OR message LIKE '%api_error%' THEN 'api_error'
            WHEN message LIKE '%compat%'
                OR message LIKE '%fallback%'
                OR message LIKE '%兼容%' THEN 'compat_fallback'
            WHEN message LIKE '%runtime%'
                AND message LIKE '%config%' THEN 'runtime_config'
            WHEN message LIKE '%error%'
                OR message LIKE '%exception%' THEN 'error'
            ELSE 'ai_event'
        END AS category,
        '' AS method,
        '' AS url,
        '' AS endpoint,
        '' AS http_status,
        '' AS status_text,
        '' AS model
    FROM system_logs
)
SELECT
    id,
    ts,
    level,
    logger,
    message,
    raw,
    source,
    component,
    agent_id,
    thread_id,
    trace_id,
    event_type,
    tool_name,
    duration_ms,
    extra,
    category,
    method,
    url,
    endpoint,
    http_status,
    status_text,
    model
FROM derived_logs
ORDER BY ts DESC, id D
`

type ListRecentAILogsParams struct {
	Limit int64 `db:"limit" json:"limit"`
}

type ListRecentAILogsRow struct {
	ID         int64  `db:"id" json:"id"`
	Ts         int64  `db:"ts" json:"ts"`
	Level      string `db:"level" json:"level"`
	Logger     string `db:"logger" json:"logger"`
	Message    string `db:"message" json:"message"`
	Raw        string `db:"raw" json:"raw"`
	Source     string `db:"source" json:"source"`
	Component  string `db:"component" json:"component"`
	AgentID    string `db:"agent_id" json:"agent_id"`
	ThreadID   string `db:"thread_id" json:"thread_id"`
	TraceID    string `db:"trace_id" json:"trace_id"`
	EventType  string `db:"event_type" json:"event_type"`
	ToolName   string `db:"tool_name" json:"tool_name"`
	DurationMs *int64 `db:"duration_ms" json:"duration_ms"`
	Extra      string `db:"extra" json:"extra"`
	Category   string `db:"category" json:"category"`
	Method     string `db:"method" json:"method"`
	Url        string `db:"url" json:"url"`
	Endpoint   string `db:"endpoint" json:"endpoint"`
	HttpStatus string `db:"http_status" json:"http_status"`
	StatusText string `db:"status_text" json:"status_text"`
	Model      string `db:"model" json:"model"`
}

func (q *Queries) ListRecentAILogs(ctx context.Context, arg ListRecentAILogsParams) ([]ListRecentAILogsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentAILogs, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentAILogsRow{}
	for rows.Next() {
		var i ListRecentAILogsRow
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.Level,
			&i.Logger,
			&i.Message,
			&i.Raw,
			&i.Source,
			&i.Component,
			&i.AgentID,
			&i.ThreadID,
			&i.TraceID,
			&i.EventType,
			&i.ToolName,
			&i.DurationMs,
			&i.Extra,
			&i.Category,
			&i.Method,
			&i.Url,
			&i.Endpoint,
			&i.HttpStatus,
			&i.StatusText,
			&i.Model,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
