// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_log.sql

package sqlc

import (
	"context"
)

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit_events (ts, event_type, action, result, actor, target, detail, level, extra)
VALUES ((CAST(strftime('%s','now') AS INTEGER) * 1000), ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertAuditEventParams struct {
	EventType string `db:"event_type" json:"event_type"`
	Action    string `db:"action" json:"action"`
	Result    string `db:"result" json:"result"`
	Actor     string `db:"actor" json:"actor"`
	Target    string `db:"target" json:"target"`
	Detail    string `db:"detail" json:"detail"`
	Level     string `db:"level" json:"level"`
	Extra     string `db:"extra" json:"extra"`
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditEvent,
		arg.EventType,
		arg.Action,
		arg.Result,
		arg.Actor,
		arg.Target,
		arg.Detail,
		arg.Level,
		arg.Extra,
	)
	return err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT ts, event_type, action, result, actor, target, detail, level, extra
FROM audit_events
WHERE (? = '' OR event_type = ?)
  AND (? = '' OR action = ?)
  AND (? = '' OR actor = ?)
  AND (? = ''
    OR event_type LIKE '%' || ? || '%'
    OR action LIKE '%' || ? || '%'
    OR result LIKE '%' || ? || '%'
    OR actor LIKE '%' || ? || '%'
    OR target LIKE '%' || ? || '%'
    OR detail LIKE '%' || ? || '%')
ORDER BY ts DESC, id DESC
LIMIT ?
`

type ListAuditEventsParams struct {
	Column1   interface{} `db:"column_1" json:"column_1"`
	EventType string      `db:"event_type" json:"event_type"`
	Column3   interface{} `db:"column_3" json:"column_3"`
	Action    string      `db:"action" json:"action"`
	Column5   interface{} `db:"column_5" json:"column_5"`
	Actor     string      `db:"actor" json:"actor"`
	Column7   interface{} `db:"column_7" json:"column_7"`
	Column8   *string     `db:"column_8" json:"column_8"`
	Column9   *string     `db:"column_9" json:"column_9"`
	Column10  *string     `db:"column_10" json:"column_10"`
	Column11  *string     `db:"column_11" json:"column_11"`
	Column12  *string     `db:"column_12" json:"column_12"`
	Column13  *string     `db:"column_13" json:"column_13"`
	Limit     int64       `db:"limit" json:"limit"`
}

type ListAuditEventsRow struct {
	Ts        int64  `db:"ts" json:"ts"`
	EventType string `db:"event_type" json:"event_type"`
	Action    string `db:"action" json:"action"`
	Result    string `db:"result" json:"result"`
	Actor     string `db:"actor" json:"actor"`
	Target    string `db:"target" json:"target"`
	Detail    string `db:"detail" json:"detail"`
	Level     string `db:"level" json:"level"`
	Extra     string `db:"extra" json:"extra"`
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]ListAuditEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuditEvents,
		arg.Column1,
		arg.EventType,
		arg.Column3,
		arg.Action,
		arg.Column5,
		arg.Actor,
		arg.Column7,
		arg.Column8,
		arg.Column9,
		arg.Column10,
		arg.Column11,
		arg.Column12,
		arg.Column13,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditEventsRow{}
	for rows.Next() {
		var i ListAuditEventsRow
		if err := rows.Scan(
			&i.Ts,
			&i.EventType,
			&i.Action,
			&i.Result,
			&i.Actor,
			&i.Target,
			&i.Detail,
			&i.Level,
			&i.Extra,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
