// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: audit_log.sql

package sqlc

import (
	"context"
	"time"
)

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit_events (ts, event_type, action, result, actor, target, detail, level, extra)
VALUES (NOW(), $1, $2, $3, $4, $5, $6, $7, $8::jsonb)
`

type InsertAuditEventParams struct {
	EventType string `db:"event_type" json:"event_type"`
	Action    string `db:"action" json:"action"`
	Result    string `db:"result" json:"result"`
	Actor     string `db:"actor" json:"actor"`
	Target    string `db:"target" json:"target"`
	Detail    string `db:"detail" json:"detail"`
	Level     string `db:"level" json:"level"`
	Column8   []byte `db:"column_8" json:"column_8"`
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAuditEvent,
		arg.EventType,
		arg.Action,
		arg.Result,
		arg.Actor,
		arg.Target,
		arg.Detail,
		arg.Level,
		arg.Column8,
	)
	return err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT ts, event_type, action, result, actor, target, detail, level, extra
FROM audit_events
WHERE ($1::text = '' OR event_type = $1)
  AND ($2::text = '' OR action = $2)
  AND ($3::text = '' OR actor = $3)
  AND ($4::text = ''
    OR event_type ILIKE '%' || $4 || '%'
    OR action ILIKE '%' || $4 || '%'
    OR result ILIKE '%' || $4 || '%'
    OR actor ILIKE '%' || $4 || '%'
    OR target ILIKE '%' || $4 || '%'
    OR detail ILIKE '%' || $4 || '%')
ORDER BY ts DESC, id DESC
LIMIT $5
`

type ListAuditEventsParams struct {
	Column1 string `db:"column_1" json:"column_1"`
	Column2 string `db:"column_2" json:"column_2"`
	Column3 string `db:"column_3" json:"column_3"`
	Column4 string `db:"column_4" json:"column_4"`
	Limit   int32  `db:"limit" json:"limit"`
}

type ListAuditEventsRow struct {
	Ts        time.Time `db:"ts" json:"ts"`
	EventType string    `db:"event_type" json:"event_type"`
	Action    string    `db:"action" json:"action"`
	Result    string    `db:"result" json:"result"`
	Actor     string    `db:"actor" json:"actor"`
	Target    string    `db:"target" json:"target"`
	Detail    string    `db:"detail" json:"detail"`
	Level     string    `db:"level" json:"level"`
	Extra     []byte    `db:"extra" json:"extra"`
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]ListAuditEventsRow, error) {
	rows, err := q.db.Query(ctx, listAuditEvents,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditEventsRow{}
	for rows.Next() {
		var i ListAuditEventsRow
		if err := rows.Scan(
			&i.Ts,
			&i.EventType,
			&i.Action,
			&i.Result,
			&i.Actor,
			&i.Target,
			&i.Detail,
			&i.Level,
			&i.Extra,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
