// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bus_log.sql

package sqlc

import (
	"context"
)

const listBusExceptionLogs = `-- name: ListBusExceptionLogs :many
SELECT id, ts, category, severity, source, tool_name, message, '' AS traceback, '{}' AS extra
FROM bus_exception_logs
WHERE (?1 = '' OR category = ?1)
  AND (?2 = '' OR severity = ?2)
  AND (?3 = ''
    OR lower(source) LIKE lower(?4)
    OR lower(tool_name) LIKE lower(?4)
    OR lower(message) LIKE lower(?4)
    OR lower(traceback) LIKE lower(?4))
ORDER BY ts DESC, id DESC
LIMIT ?5
`

type ListBusExceptionLogsParams struct {
	CategoryFilter interface{} `db:"category_filter" json:"category_filter"`
	SeverityFilter interface{} `db:"severity_filter" json:"severity_filter"`
	Keyword        interface{} `db:"keyword" json:"keyword"`
	KeywordPattern string      `db:"keyword_pattern" json:"keyword_pattern"`
	LimitCount     int64       `db:"limit_count" json:"limit_count"`
}

type ListBusExceptionLogsRow struct {
	ID        int64  `db:"id" json:"id"`
	Ts        int64  `db:"ts" json:"ts"`
	Category  string `db:"category" json:"category"`
	Severity  string `db:"severity" json:"severity"`
	Source    string `db:"source" json:"source"`
	ToolName  string `db:"tool_name" json:"tool_name"`
	Message   string `db:"message" json:"message"`
	Traceback string `db:"traceback" json:"traceback"`
	Extra     string `db:"extra" json:"extra"`
}

func (q *Queries) ListBusExceptionLogs(ctx context.Context, arg ListBusExceptionLogsParams) ([]ListBusExceptionLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, listBusExceptionLogs,
		arg.CategoryFilter,
		arg.SeverityFilter,
		arg.Keyword,
		arg.KeywordPattern,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBusExceptionLogsRow{}
	for rows.Next() {
		var i ListBusExceptionLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.Category,
			&i.Severity,
			&i.Source,
			&i.ToolName,
			&i.Message,
			&i.Traceback,
			&i.Extra,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
