// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cron_job.sql

package sqlc

import (
	"context"
	"encoding/json"
)

const cASCronJobRunStatus = `-- name: CASCronJobRunStatus :execrows
UPDATE cron_job_runs
SET status     = ?1,
    error      = ?2,
    updated_at = ?3
WHERE id = ?4 AND status = ?5
`

type CASCronJobRunStatusParams struct {
	NextStatus     string `db:"next_status" json:"next_status"`
	Error          string `db:"error" json:"error"`
	UpdatedAt      int64  `db:"updated_at" json:"updated_at"`
	ID             string `db:"id" json:"id"`
	ExpectedStatus string `db:"expected_status" json:"expected_status"`
}

// CASCronJobRunStatus only advances the status when the current status
// equals expected_status; protects three-phase transitions (pending ->
// submitting -> submitted -> running -> finished/failed/observe_lost)
// from stale worker overwrites.
func (q *Queries) CASCronJobRunStatus(ctx context.Context, arg CASCronJobRunStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, cASCronJobRunStatus,
		arg.NextStatus,
		arg.Error,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedStatus,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const claimDueJobsForUpdate = `-- name: ClaimDueJobsForUpdate :many

UPDATE cron_jobs
SET claimed_by       = ?1,
    claimed_at       = ?2,
    lease_expires_at = ?3,
    claim_token      = ?4,
    updated_at       = ?2
WHERE id IN (
    SELECT id
    FROM cron_jobs
    WHERE enabled = 1
      AND (claim_token = '' OR COALESCE(lease_expires_at, 0) <= ?2)
      AND COALESCE(next_retry_at, next_run_at) <= ?2
    ORDER BY COALESCE(next_retry_at, next_run_at) ASC, id ASC
    LIMIT ?5
)
  AND enabled = 1
  AND (claim_token = '' OR COALESCE(lease_expires_at, 0) <= ?2)
  AND COALESCE(next_retry_at, next_run_at) <= ?2
RETURNING id, name, prompt, schedule_type, schedule_expr,
          timezone, provider, model, cwd, config, skills,
          notify_channel, enabled, next_run_at, last_scheduled_at,
          last_run_at, claimed_at, claimed_by, lease_expires_at,
          claim_token, thread_id, agent_id, active_turn_id,
          last_turn_id, failure_count, max_attempts, next_retry_at,
          last_status, last_error_at, last_error, created_at,
          updated_at
`

type ClaimDueJobsForUpdateParams struct {
	ClaimedBy      string `db:"claimed_by" json:"claimed_by"`
	Now            *int64 `db:"now" json:"now"`
	LeaseExpiresAt *int64 `db:"lease_expires_at" json:"lease_expires_at"`
	ClaimToken     string `db:"claim_token" json:"claim_token"`
	MaxClaim       int64  `db:"max_claim" json:"max_claim"`
}

// Claim / lease -----------------------------------------------------
// ClaimDueJobsForUpdate marks up to `limit` due rows as claimed by `claimed_by`.
// FOR UPDATE SKIP LOCKED removed: SQLite does not support it.
// Task07 implements atomic claim with one UPDATE ... RETURNING statement.
// The outer UPDATE repeats the availability predicate so claim ownership is
// rechecked at write time, preserving fencing if another writer wins first.
func (q *Queries) ClaimDueJobsForUpdate(ctx context.Context, arg ClaimDueJobsForUpdateParams) ([]CronJob, error) {
	rows, err := q.db.QueryContext(ctx, claimDueJobsForUpdate,
		arg.ClaimedBy,
		arg.Now,
		arg.LeaseExpiresAt,
		arg.ClaimToken,
		arg.MaxClaim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CronJob{}
	for rows.Next() {
		var i CronJob
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Prompt,
			&i.ScheduleType,
			&i.ScheduleExpr,
			&i.Timezone,
			&i.Provider,
			&i.Model,
			&i.CWD,
			&i.Config,
			&i.Skills,
			&i.NotifyChannel,
			&i.Enabled,
			&i.NextRunAt,
			&i.LastScheduledAt,
			&i.LastRunAt,
			&i.ClaimedAt,
			&i.ClaimedBy,
			&i.LeaseExpiresAt,
			&i.ClaimToken,
			&i.ThreadID,
			&i.AgentID,
			&i.ActiveTurnID,
			&i.LastTurnID,
			&i.FailureCount,
			&i.MaxAttempts,
			&i.NextRetryAt,
			&i.LastStatus,
			&i.LastErrorAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createCronJob = `-- name: CreateCronJob :one

INSERT INTO cron_jobs (
    id, name, prompt, schedule_type, schedule_expr, timezone, provider,
    model, cwd, config, skills, notify_channel, enabled, next_run_at,
    max_attempts, created_at, updated_at
) VALUES (
    ?1, ?2, ?3, ?4,
    ?5, ?6, ?7,
    ?8, ?9,
    ?10,
    ?11,
    ?12, ?13, ?14,
    ?15, ?16, ?17
)
RETURNING id, name, prompt, schedule_type, schedule_expr, timezone, provider,
          model, cwd, config, skills, notify_channel, enabled, next_run_at,
          last_scheduled_at, last_run_at, claimed_at, claimed_by,
          lease_expires_at, claim_token, thread_id, agent_id, active_turn_id,
          last_turn_id, failure_count, max_attempts, next_retry_at,
          last_status, last_error_at, last_error, created_at, updated_at
`

type CreateCronJobParams struct {
	ID            string          `db:"id" json:"id"`
	Name          string          `db:"name" json:"name"`
	Prompt        string          `db:"prompt" json:"prompt"`
	ScheduleType  string          `db:"schedule_type" json:"schedule_type"`
	ScheduleExpr  string          `db:"schedule_expr" json:"schedule_expr"`
	Timezone      string          `db:"timezone" json:"timezone"`
	Provider      string          `db:"provider" json:"provider"`
	Model         string          `db:"model" json:"model"`
	CWD           string          `db:"cwd" json:"cwd"`
	Config        json.RawMessage `db:"config" json:"config"`
	Skills        json.RawMessage `db:"skills" json:"skills"`
	NotifyChannel string          `db:"notify_channel" json:"notify_channel"`
	Enabled       int64           `db:"enabled" json:"enabled"`
	NextRunAt     int64           `db:"next_run_at" json:"next_run_at"`
	MaxAttempts   int64           `db:"max_attempts" json:"max_attempts"`
	CreatedAt     int64           `db:"created_at" json:"created_at"`
	UpdatedAt     int64           `db:"updated_at" json:"updated_at"`
}

// CRUD --------------------------------------------------------------
func (q *Queries) CreateCronJob(ctx context.Context, arg CreateCronJobParams) (CronJob, error) {
	row := q.db.QueryRowContext(ctx, createCronJob,
		arg.ID,
		arg.Name,
		arg.Prompt,
		arg.ScheduleType,
		arg.ScheduleExpr,
		arg.Timezone,
		arg.Provider,
		arg.Model,
		arg.CWD,
		arg.Config,
		arg.Skills,
		arg.NotifyChannel,
		arg.Enabled,
		arg.NextRunAt,
		arg.MaxAttempts,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CronJob
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Prompt,
		&i.ScheduleType,
		&i.ScheduleExpr,
		&i.Timezone,
		&i.Provider,
		&i.Model,
		&i.CWD,
		&i.Config,
		&i.Skills,
		&i.NotifyChannel,
		&i.Enabled,
		&i.NextRunAt,
		&i.LastScheduledAt,
		&i.LastRunAt,
		&i.ClaimedAt,
		&i.ClaimedBy,
		&i.LeaseExpiresAt,
		&i.ClaimToken,
		&i.ThreadID,
		&i.AgentID,
		&i.ActiveTurnID,
		&i.LastTurnID,
		&i.FailureCount,
		&i.MaxAttempts,
		&i.NextRetryAt,
		&i.LastStatus,
		&i.LastErrorAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCronJob = `-- name: DeleteCronJob :exec
DELETE FROM cron_jobs WHERE id = ?
`

type DeleteCronJobParams struct {
	ID string `db:"id" json:"id"`
}

func (q *Queries) DeleteCronJob(ctx context.Context, arg DeleteCronJobParams) error {
	_, err := q.db.ExecContext(ctx, deleteCronJob, arg.ID)
	return err
}

const extendClaim = `-- name: ExtendClaim :execrows
UPDATE cron_jobs
SET lease_expires_at = ?1,
    updated_at       = ?2
WHERE id = ?3 AND claim_token = ?4
  AND lease_expires_at IS NOT NULL
  AND lease_expires_at < ?1
`

type ExtendClaimParams struct {
	LeaseExpiresAt *int64 `db:"lease_expires_at" json:"lease_expires_at"`
	Now            int64  `db:"now" json:"now"`
	ID             string `db:"id" json:"id"`
	ClaimToken     string `db:"claim_token" json:"claim_token"`
}

func (q *Queries) ExtendClaim(ctx context.Context, arg ExtendClaimParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, extendClaim,
		arg.LeaseExpiresAt,
		arg.Now,
		arg.ID,
		arg.ClaimToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCronJobByID = `-- name: GetCronJobByID :one
SELECT id, name, prompt, schedule_type, schedule_expr, timezone, provider,
       model, cwd, config, skills, notify_channel, enabled, next_run_at,
       last_scheduled_at, last_run_at, claimed_at, claimed_by,
       lease_expires_at, claim_token, thread_id, agent_id, active_turn_id,
       last_turn_id, failure_count, max_attempts, next_retry_at,
       last_status, last_error_at, last_error, created_at, updated_at
FROM cron_jobs
WHERE id = ?
`

type GetCronJobByIDParams struct {
	ID string `db:"id" json:"id"`
}

func (q *Queries) GetCronJobByID(ctx context.Context, arg GetCronJobByIDParams) (CronJob, error) {
	row := q.db.QueryRowContext(ctx, getCronJobByID, arg.ID)
	var i CronJob
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Prompt,
		&i.ScheduleType,
		&i.ScheduleExpr,
		&i.Timezone,
		&i.Provider,
		&i.Model,
		&i.CWD,
		&i.Config,
		&i.Skills,
		&i.NotifyChannel,
		&i.Enabled,
		&i.NextRunAt,
		&i.LastScheduledAt,
		&i.LastRunAt,
		&i.ClaimedAt,
		&i.ClaimedBy,
		&i.LeaseExpiresAt,
		&i.ClaimToken,
		&i.ThreadID,
		&i.AgentID,
		&i.ActiveTurnID,
		&i.LastTurnID,
		&i.FailureCount,
		&i.MaxAttempts,
		&i.NextRetryAt,
		&i.LastStatus,
		&i.LastErrorAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCronJobRunByDedupeKey = `-- name: GetCronJobRunByDedupeKey :one
SELECT id, job_id, scheduled_at, idempotency_key, dedupe_key, thread_id,
       agent_id, turn_id, submitted_at, status, error, created_at,
       updated_at
FROM cron_job_runs
WHERE dedupe_key = ? AND dedupe_key <> ''
`

type GetCronJobRunByDedupeKeyParams struct {
	DedupeKey string `db:"dedupe_key" json:"dedupe_key"`
}

func (q *Queries) GetCronJobRunByDedupeKey(ctx context.Context, arg GetCronJobRunByDedupeKeyParams) (CronJobRun, error) {
	row := q.db.QueryRowContext(ctx, getCronJobRunByDedupeKey, arg.DedupeKey)
	var i CronJobRun
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.ScheduledAt,
		&i.IdempotencyKey,
		&i.DedupeKey,
		&i.ThreadID,
		&i.AgentID,
		&i.TurnID,
		&i.SubmittedAt,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCronJobRunByID = `-- name: GetCronJobRunByID :one
SELECT id, job_id, scheduled_at, idempotency_key, dedupe_key, thread_id,
       agent_id, turn_id, submitted_at, status, error, created_at,
       updated_at
FROM cron_job_runs
WHERE id = ?
`

type GetCronJobRunByIDParams struct {
	ID string `db:"id" json:"id"`
}

func (q *Queries) GetCronJobRunByID(ctx context.Context, arg GetCronJobRunByIDParams) (CronJobRun, error) {
	row := q.db.QueryRowContext(ctx, getCronJobRunByID, arg.ID)
	var i CronJobRun
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.ScheduledAt,
		&i.IdempotencyKey,
		&i.DedupeKey,
		&i.ThreadID,
		&i.AgentID,
		&i.TurnID,
		&i.SubmittedAt,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRunningCronJobRunByTurnID = `-- name: GetRunningCronJobRunByTurnID :one
SELECT id, job_id, scheduled_at, idempotency_key, dedupe_key, thread_id,
       agent_id, turn_id, submitted_at, status, error, created_at,
       updated_at
FROM cron_job_runs
WHERE turn_id = ? AND status = 'running'
LIMIT 1
`

type GetRunningCronJobRunByTurnIDParams struct {
	TurnID string `db:"turn_id" json:"turn_id"`
}

// Used by CompleteTurn to locate the active run for a completed turn without
// scanning all unresolved rows. turn_id is indexed by the dedupe_key B-tree
// and the status guard ensures only one row can match (at most one run per
// turn can be in 'running').
func (q *Queries) GetRunningCronJobRunByTurnID(ctx context.Context, arg GetRunningCronJobRunByTurnIDParams) (CronJobRun, error) {
	row := q.db.QueryRowContext(ctx, getRunningCronJobRunByTurnID, arg.TurnID)
	var i CronJobRun
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.ScheduledAt,
		&i.IdempotencyKey,
		&i.DedupeKey,
		&i.ThreadID,
		&i.AgentID,
		&i.TurnID,
		&i.SubmittedAt,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubmittedOrRunningCronJobRunByTurnID = `-- name: GetSubmittedOrRunningCronJobRunByTurnID :one
SELECT id, job_id, scheduled_at, idempotency_key, dedupe_key, thread_id,
       agent_id, turn_id, submitted_at, status, error, created_at,
       updated_at
FROM cron_job_runs
WHERE turn_id = ?1
  AND turn_id <> ''
  AND status IN ('submitted', 'running')
LIMIT 1
`

type GetSubmittedOrRunningCronJobRunByTurnIDParams struct {
	TurnID string `db:"turn_id" json:"turn_id"`
}

// Used by CompleteTurn to locate early terminal events that arrive while a run
// is still submitted, without falling back to the unresolved recovery scan.
func (q *Queries) GetSubmittedOrRunningCronJobRunByTurnID(ctx context.Context, arg GetSubmittedOrRunningCronJobRunByTurnIDParams) (CronJobRun, error) {
	row := q.db.QueryRowContext(ctx, getSubmittedOrRunningCronJobRunByTurnID, arg.TurnID)
	var i CronJobRun
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.ScheduledAt,
		&i.IdempotencyKey,
		&i.DedupeKey,
		&i.ThreadID,
		&i.AgentID,
		&i.TurnID,
		&i.SubmittedAt,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCronJobRun = `-- name: InsertCronJobRun :one

INSERT INTO cron_job_runs (
    id, job_id, scheduled_at, idempotency_key, dedupe_key,
    status, created_at, updated_at
) VALUES (
    ?1, ?2, ?3,
    ?4, ?5,
    ?6, ?7, ?8
)
RETURNING id, job_id, scheduled_at, idempotency_key, dedupe_key, thread_id,
          agent_id, turn_id, submitted_at, status, error, created_at,
          updated_at
`

type InsertCronJobRunParams struct {
	ID             string `db:"id" json:"id"`
	JobID          string `db:"job_id" json:"job_id"`
	ScheduledAt    int64  `db:"scheduled_at" json:"scheduled_at"`
	IdempotencyKey string `db:"idempotency_key" json:"idempotency_key"`
	DedupeKey      string `db:"dedupe_key" json:"dedupe_key"`
	Status         string `db:"status" json:"status"`
	CreatedAt      int64  `db:"created_at" json:"created_at"`
	UpdatedAt      int64  `db:"updated_at" json:"updated_at"`
}

// cron_job_runs -----------------------------------------------------
func (q *Queries) InsertCronJobRun(ctx context.Context, arg InsertCronJobRunParams) (CronJobRun, error) {
	row := q.db.QueryRowContext(ctx, insertCronJobRun,
		arg.ID,
		arg.JobID,
		arg.ScheduledAt,
		arg.IdempotencyKey,
		arg.DedupeKey,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CronJobRun
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.ScheduledAt,
		&i.IdempotencyKey,
		&i.DedupeKey,
		&i.ThreadID,
		&i.AgentID,
		&i.TurnID,
		&i.SubmittedAt,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCronJobRunsByJob = `-- name: ListCronJobRunsByJob :many
SELECT id, job_id, scheduled_at, idempotency_key, dedupe_key, thread_id,
       agent_id, turn_id, submitted_at, status, error, created_at,
       updated_at
FROM cron_job_runs
WHERE job_id = ?
ORDER BY created_at DESC, id DESC
LIMIT ?
`

type ListCronJobRunsByJobParams struct {
	JobID string `db:"job_id" json:"job_id"`
	Limit int64  `db:"limit" json:"limit"`
}

func (q *Queries) ListCronJobRunsByJob(ctx context.Context, arg ListCronJobRunsByJobParams) ([]CronJobRun, error) {
	rows, err := q.db.QueryContext(ctx, listCronJobRunsByJob, arg.JobID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CronJobRun{}
	for rows.Next() {
		var i CronJobRun
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.ScheduledAt,
			&i.IdempotencyKey,
			&i.DedupeKey,
			&i.ThreadID,
			&i.AgentID,
			&i.TurnID,
			&i.SubmittedAt,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCronJobs = `-- name: ListCronJobs :many
SELECT id, name, prompt, schedule_type, schedule_expr, timezone, provider,
       model, cwd, config, skills, notify_channel, enabled, next_run_at,
       last_scheduled_at, last_run_at, claimed_at, claimed_by,
       lease_expires_at, claim_token, thread_id, agent_id, active_turn_id,
       last_turn_id, failure_count, max_attempts, next_retry_at,
       last_status, last_error_at, last_error, created_at, updated_at
FROM cron_jobs
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListCronJobs(ctx context.Context) ([]CronJob, error) {
	rows, err := q.db.QueryContext(ctx, listCronJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CronJob{}
	for rows.Next() {
		var i CronJob
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Prompt,
			&i.ScheduleType,
			&i.ScheduleExpr,
			&i.Timezone,
			&i.Provider,
			&i.Model,
			&i.CWD,
			&i.Config,
			&i.Skills,
			&i.NotifyChannel,
			&i.Enabled,
			&i.NextRunAt,
			&i.LastScheduledAt,
			&i.LastRunAt,
			&i.ClaimedAt,
			&i.ClaimedBy,
			&i.LeaseExpiresAt,
			&i.ClaimToken,
			&i.ThreadID,
			&i.AgentID,
			&i.ActiveTurnID,
			&i.LastTurnID,
			&i.FailureCount,
			&i.MaxAttempts,
			&i.NextRetryAt,
			&i.LastStatus,
			&i.LastErrorAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCronJobsClaimedBy = `-- name: ListCronJobsClaimedBy :many
SELECT id, name, prompt, schedule_type, schedule_expr, timezone, provider,
       model, cwd, config, skills, notify_channel, enabled, next_run_at,
       last_scheduled_at, last_run_at, claimed_at, claimed_by,
       lease_expires_at, claim_token, thread_id, agent_id, active_turn_id,
       last_turn_id, failure_count, max_attempts, next_retry_at,
       last_status, last_error_at, last_error, created_at, updated_at
FROM cron_jobs
WHERE claimed_by = ? AND claim_token <> ''
ORDER BY id ASC
`

type ListCronJobsClaimedByParams struct {
	ClaimedBy string `db:"claimed_by" json:"claimed_by"`
}

// Used by RenewLeases / ExtendClaimForTurnProgress to fetch only the jobs
// owned by this scheduler instance, avoiding a full-table scan of cron_jobs.
func (q *Queries) ListCronJobsClaimedBy(ctx context.Context, arg ListCronJobsClaimedByParams) ([]CronJob, error) {
	rows, err := q.db.QueryContext(ctx, listCronJobsClaimedBy, arg.ClaimedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CronJob{}
	for rows.Next() {
		var i CronJob
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Prompt,
			&i.ScheduleType,
			&i.ScheduleExpr,
			&i.Timezone,
			&i.Provider,
			&i.Model,
			&i.CWD,
			&i.Config,
			&i.Skills,
			&i.NotifyChannel,
			&i.Enabled,
			&i.NextRunAt,
			&i.LastScheduledAt,
			&i.LastRunAt,
			&i.ClaimedAt,
			&i.ClaimedBy,
			&i.LeaseExpiresAt,
			&i.ClaimToken,
			&i.ThreadID,
			&i.AgentID,
			&i.ActiveTurnID,
			&i.LastTurnID,
			&i.FailureCount,
			&i.MaxAttempts,
			&i.NextRetryAt,
			&i.LastStatus,
			&i.LastErrorAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnresolvedCronJobRuns = `-- name: ListUnresolvedCronJobRuns :many
SELECT id, job_id, scheduled_at, idempotency_key, dedupe_key, thread_id,
       agent_id, turn_id, submitted_at, status, error, created_at,
       updated_at
FROM cron_job_runs
WHERE status IN ('submitting', 'submitted', 'running')
ORDER BY created_at ASC, id ASC
`

// Used on scheduler boot for crash recovery: any run stuck in submitting /
// submitted / running must be re-entered through Observe / LookupByDedupeKey
// instead of StartTurn, per the three-phase protocol.
func (q *Queries) ListUnresolvedCronJobRuns(ctx context.Context) ([]CronJobRun, error) {
	rows, err := q.db.QueryContext(ctx, listUnresolvedCronJobRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CronJobRun{}
	for rows.Next() {
		var i CronJobRun
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.ScheduledAt,
			&i.IdempotencyKey,
			&i.DedupeKey,
			&i.ThreadID,
			&i.AgentID,
			&i.TurnID,
			&i.SubmittedAt,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnresolvedCronJobRunsPage = `-- name: ListUnresolvedCronJobRunsPage :many
SELECT id, job_id, scheduled_at, idempotency_key, dedupe_key, thread_id,
       agent_id, turn_id, submitted_at, status, error, created_at,
       updated_at
FROM cron_job_runs
WHERE status IN ('submitting', 'submitted', 'running')
  AND (?1 = '' OR id > ?1)
ORDER BY id ASC
LIMIT ?2
`

type ListUnresolvedCronJobRunsPageParams struct {
	Cursor interface{} `db:"cursor" json:"cursor"`
	Limit  int64       `db:"limit" json:"limit"`
}

// Bounded scheduler boot recovery page. The caller advances cursor with the
// last returned id so startup recovery never materializes every unresolved row.
func (q *Queries) ListUnresolvedCronJobRunsPage(ctx context.Context, arg ListUnresolvedCronJobRunsPageParams) ([]CronJobRun, error) {
	rows, err := q.db.QueryContext(ctx, listUnresolvedCronJobRunsPage, arg.Cursor, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CronJobRun{}
	for rows.Next() {
		var i CronJobRun
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.ScheduledAt,
			&i.IdempotencyKey,
			&i.DedupeKey,
			&i.ThreadID,
			&i.AgentID,
			&i.TurnID,
			&i.SubmittedAt,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCronJobFailed = `-- name: MarkCronJobFailed :execrows
UPDATE cron_jobs
SET claimed_by        = '',
    claimed_at        = NULL,
    lease_expires_at  = NULL,
    claim_token       = '',
    last_run_at       = ?1,
    last_turn_id      = ?2,
    active_turn_id    = '',
    last_status       = ?3,
    last_error_at     = ?4,
    last_error        = ?5,
    failure_count     = failure_count + 1,
    next_run_at       = ?6,
    next_retry_at     = ?7,
    updated_at        = ?8
WHERE cron_jobs.id = ?9
  AND cron_jobs.claim_token = ?10
  AND cron_jobs.active_turn_id = ?11
  AND EXISTS (
      SELECT 1
      FROM cron_job_runs
      WHERE cron_job_runs.id = ?12
        AND cron_job_runs.job_id = cron_jobs.id
        AND cron_job_runs.turn_id = ?11
        AND cron_job_runs.status = ?3
  )
`

type MarkCronJobFailedParams struct {
	LastRunAt            *int64 `db:"last_run_at" json:"last_run_at"`
	LastTurnID           string `db:"last_turn_id" json:"last_turn_id"`
	LastStatus           string `db:"last_status" json:"last_status"`
	LastErrorAt          *int64 `db:"last_error_at" json:"last_error_at"`
	LastError            string `db:"last_error" json:"last_error"`
	NextRunAt            int64  `db:"next_run_at" json:"next_run_at"`
	NextRetryAt          *int64 `db:"next_retry_at" json:"next_retry_at"`
	UpdatedAt            int64  `db:"updated_at" json:"updated_at"`
	ID                   string `db:"id" json:"id"`
	ClaimToken           string `db:"claim_token" json:"claim_token"`
	ExpectedActiveTurnID string `db:"expected_active_turn_id" json:"expected_active_turn_id"`
	RunID                string `db:"run_id" json:"run_id"`
}

func (q *Queries) MarkCronJobFailed(ctx context.Context, arg MarkCronJobFailedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markCronJobFailed,
		arg.LastRunAt,
		arg.LastTurnID,
		arg.LastStatus,
		arg.LastErrorAt,
		arg.LastError,
		arg.NextRunAt,
		arg.NextRetryAt,
		arg.UpdatedAt,
		arg.ID,
		arg.ClaimToken,
		arg.ExpectedActiveTurnID,
		arg.RunID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markCronJobFinished = `-- name: MarkCronJobFinished :execrows
UPDATE cron_jobs
SET claimed_by        = '',
    claimed_at        = NULL,
    lease_expires_at  = NULL,
    claim_token       = '',
    last_run_at       = ?1,
    last_turn_id      = ?2,
    active_turn_id    = '',
    last_status       = 'finished',
    last_error_at     = NULL,
    last_error        = '',
    failure_count     = 0,
    next_run_at       = ?3,
    next_retry_at     = NULL,
    updated_at        = ?4
WHERE cron_jobs.id = ?5
  AND cron_jobs.claim_token = ?6
  AND cron_jobs.active_turn_id = ?7
  AND EXISTS (
      SELECT 1
      FROM cron_job_runs
      WHERE cron_job_runs.id = ?8
        AND cron_job_runs.job_id = cron_jobs.id
        AND cron_job_runs.turn_id = ?7
        AND cron_job_runs.status = 'finished'
  )
`

type MarkCronJobFinishedParams struct {
	LastRunAt            *int64 `db:"last_run_at" json:"last_run_at"`
	LastTurnID           string `db:"last_turn_id" json:"last_turn_id"`
	NextRunAt            int64  `db:"next_run_at" json:"next_run_at"`
	UpdatedAt            int64  `db:"updated_at" json:"updated_at"`
	ID                   string `db:"id" json:"id"`
	ClaimToken           string `db:"claim_token" json:"claim_token"`
	ExpectedActiveTurnID string `db:"expected_active_turn_id" json:"expected_active_turn_id"`
	RunID                string `db:"run_id" json:"run_id"`
}

// MarkCronJobFinished releases the claim only when the current job claim,
// active turn, and already-finished run row all describe the same terminal
// event. This prevents a late terminal event from an old run from releasing a
// newer claim.
func (q *Queries) MarkCronJobFinished(ctx context.Context, arg MarkCronJobFinishedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markCronJobFinished,
		arg.LastRunAt,
		arg.LastTurnID,
		arg.NextRunAt,
		arg.UpdatedAt,
		arg.ID,
		arg.ClaimToken,
		arg.ExpectedActiveTurnID,
		arg.RunID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const patchCronJobNextRunAt = `-- name: PatchCronJobNextRunAt :exec
UPDATE cron_jobs
SET next_run_at = ?1,
    updated_at  = ?2
WHERE id = ?3
`

type PatchCronJobNextRunAtParams struct {
	NextRunAt int64  `db:"next_run_at" json:"next_run_at"`
	UpdatedAt int64  `db:"updated_at" json:"updated_at"`
	ID        string `db:"id" json:"id"`
}

// Narrow update used by RunOnce: only touches next_run_at + updated_at
// without overwriting any other field, avoiding a read-modify-write race.
func (q *Queries) PatchCronJobNextRunAt(ctx context.Context, arg PatchCronJobNextRunAtParams) error {
	_, err := q.db.ExecContext(ctx, patchCronJobNextRunAt, arg.NextRunAt, arg.UpdatedAt, arg.ID)
	return err
}

const releaseClaim = `-- name: ReleaseClaim :execrows
UPDATE cron_jobs
SET claimed_by       = '',
    claimed_at       = NULL,
    lease_expires_at = NULL,
    claim_token      = '',
    updated_at       = ?1
WHERE id = ?2 AND claim_token = ?3
`

type ReleaseClaimParams struct {
	Now        int64  `db:"now" json:"now"`
	ID         string `db:"id" json:"id"`
	ClaimToken string `db:"claim_token" json:"claim_token"`
}

func (q *Queries) ReleaseClaim(ctx context.Context, arg ReleaseClaimParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, releaseClaim, arg.Now, arg.ID, arg.ClaimToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const renewLease = `-- name: RenewLease :execrows
UPDATE cron_jobs
SET lease_expires_at = ?1,
    updated_at       = ?2
WHERE id = ?3 AND claim_token = ?4
`

type RenewLeaseParams struct {
	LeaseExpiresAt *int64 `db:"lease_expires_at" json:"lease_expires_at"`
	Now            int64  `db:"now" json:"now"`
	ID             string `db:"id" json:"id"`
	ClaimToken     string `db:"claim_token" json:"claim_token"`
}

func (q *Queries) RenewLease(ctx context.Context, arg RenewLeaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, renewLease,
		arg.LeaseExpiresAt,
		arg.Now,
		arg.ID,
		arg.ClaimToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setCronJobActiveTurn = `-- name: SetCronJobActiveTurn :execrows
UPDATE cron_jobs
SET active_turn_id = ?1,
    thread_id      = COALESCE(NULLIF(?2, ''), thread_id),
    agent_id       = COALESCE(NULLIF(?3, ''), agent_id),
    updated_at     = ?4
WHERE id = ?5 AND claim_token = ?6
`

type SetCronJobActiveTurnParams struct {
	ActiveTurnID string      `db:"active_turn_id" json:"active_turn_id"`
	ThreadID     interface{} `db:"thread_id" json:"thread_id"`
	AgentID      interface{} `db:"agent_id" json:"agent_id"`
	Now          int64       `db:"now" json:"now"`
	ID           string      `db:"id" json:"id"`
	ClaimToken   string      `db:"claim_token" json:"claim_token"`
}

func (q *Queries) SetCronJobActiveTurn(ctx context.Context, arg SetCronJobActiveTurnParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setCronJobActiveTurn,
		arg.ActiveTurnID,
		arg.ThreadID,
		arg.AgentID,
		arg.Now,
		arg.ID,
		arg.ClaimToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setCronJobEnabled = `-- name: SetCronJobEnabled :exec
UPDATE cron_jobs
SET enabled    = ?1,
    updated_at = ?2
WHERE id = ?3
`

type SetCronJobEnabledParams struct {
	Enabled   int64  `db:"enabled" json:"enabled"`
	UpdatedAt int64  `db:"updated_at" json:"updated_at"`
	ID        string `db:"id" json:"id"`
}

func (q *Queries) SetCronJobEnabled(ctx context.Context, arg SetCronJobEnabledParams) error {
	_, err := q.db.ExecContext(ctx, setCronJobEnabled, arg.Enabled, arg.UpdatedAt, arg.ID)
	return err
}

const setCronJobRunTurn = `-- name: SetCronJobRunTurn :execrows
UPDATE cron_job_runs
SET turn_id       = ?1,
    thread_id     = COALESCE(NULLIF(?2, ''), thread_id),
    agent_id      = COALESCE(NULLIF(?3, ''), agent_id),
    submitted_at  = ?4,
    updated_at    = ?5
WHERE id = ?6
`

type SetCronJobRunTurnParams struct {
	TurnID      string      `db:"turn_id" json:"turn_id"`
	ThreadID    interface{} `db:"thread_id" json:"thread_id"`
	AgentID     interface{} `db:"agent_id" json:"agent_id"`
	SubmittedAt *int64      `db:"submitted_at" json:"submitted_at"`
	UpdatedAt   int64       `db:"updated_at" json:"updated_at"`
	ID          string      `db:"id" json:"id"`
}

func (q *Queries) SetCronJobRunTurn(ctx context.Context, arg SetCronJobRunTurnParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setCronJobRunTurn,
		arg.TurnID,
		arg.ThreadID,
		arg.AgentID,
		arg.SubmittedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateCronJobSchedule = `-- name: UpdateCronJobSchedule :exec
UPDATE cron_jobs
SET name            = ?1,
    prompt          = ?2,
    schedule_type   = ?3,
    schedule_expr   = ?4,
    timezone        = ?5,
    provider        = ?6,
    model           = ?7,
    cwd             = ?8,
    config          = ?9,
    skills          = ?10,
    notify_channel  = ?11,
    enabled         = ?12,
    next_run_at     = ?13,
    max_attempts    = ?14,
    updated_at      = ?15
WHERE id = ?16
`

type UpdateCronJobScheduleParams struct {
	Name          string          `db:"name" json:"name"`
	Prompt        string          `db:"prompt" json:"prompt"`
	ScheduleType  string          `db:"schedule_type" json:"schedule_type"`
	ScheduleExpr  string          `db:"schedule_expr" json:"schedule_expr"`
	Timezone      string          `db:"timezone" json:"timezone"`
	Provider      string          `db:"provider" json:"provider"`
	Model         string          `db:"model" json:"model"`
	CWD           string          `db:"cwd" json:"cwd"`
	Config        json.RawMessage `db:"config" json:"config"`
	Skills        json.RawMessage `db:"skills" json:"skills"`
	NotifyChannel string          `db:"notify_channel" json:"notify_channel"`
	Enabled       int64           `db:"enabled" json:"enabled"`
	NextRunAt     int64           `db:"next_run_at" json:"next_run_at"`
	MaxAttempts   int64           `db:"max_attempts" json:"max_attempts"`
	UpdatedAt     int64           `db:"updated_at" json:"updated_at"`
	ID            string          `db:"id" json:"id"`
}

func (q *Queries) UpdateCronJobSchedule(ctx context.Context, arg UpdateCronJobScheduleParams) error {
	_, err := q.db.ExecContext(ctx, updateCronJobSchedule,
		arg.Name,
		arg.Prompt,
		arg.ScheduleType,
		arg.ScheduleExpr,
		arg.Timezone,
		arg.Provider,
		arg.Model,
		arg.CWD,
		arg.Config,
		arg.Skills,
		arg.NotifyChannel,
		arg.Enabled,
		arg.NextRunAt,
		arg.MaxAttempts,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
