// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: cwd_lock.sql

package sqlc

import (
	"context"
	"time"
)

const acquireCwdLock = `-- name: AcquireCwdLock :execrows
INSERT INTO cwd_instance_locks (cwd, instance_id, pid, acquired_at, heartbeat_at)
VALUES ($1, $2, $3, NOW(), NOW())
ON CONFLICT (cwd) DO UPDATE
SET instance_id = EXCLUDED.instance_id,
    pid = EXCLUDED.pid,
    acquired_at = NOW(),
    heartbeat_at = NOW()
WHERE cwd_instance_locks.instance_id = EXCLUDED.instance_id
   OR cwd_instance_locks.heartbeat_at < NOW() - INTERVAL '45 seconds'
`

type AcquireCwdLockParams struct {
	Cwd        string `db:"cwd" json:"cwd"`
	InstanceID string `db:"instance_id" json:"instance_id"`
	Pid        int32  `db:"pid" json:"pid"`
}

func (q *Queries) AcquireCwdLock(ctx context.Context, arg AcquireCwdLockParams) (int64, error) {
	result, err := q.db.Exec(ctx, acquireCwdLock, arg.Cwd, arg.InstanceID, arg.Pid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStaleCwdLocks = `-- name: DeleteStaleCwdLocks :execrows
DELETE FROM cwd_instance_locks
WHERE heartbeat_at < NOW() - INTERVAL '45 seconds'
`

func (q *Queries) DeleteStaleCwdLocks(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleCwdLocks)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const forceAcquireCwdLock = `-- name: ForceAcquireCwdLock :execrows
INSERT INTO cwd_instance_locks (cwd, instance_id, pid, acquired_at, heartbeat_at)
VALUES ($1, $2, $3, NOW(), NOW())
ON CONFLICT (cwd) DO UPDATE
SET instance_id = EXCLUDED.instance_id,
    pid = EXCLUDED.pid,
    acquired_at = NOW(),
    heartbeat_at = NOW()
WHERE cwd_instance_locks.pid = $4
`

type ForceAcquireCwdLockParams struct {
	Cwd        string `db:"cwd" json:"cwd"`
	InstanceID string `db:"instance_id" json:"instance_id"`
	Pid        int32  `db:"pid" json:"pid"`
	Pid_2      int32  `db:"pid_2" json:"pid_2"`
}

func (q *Queries) ForceAcquireCwdLock(ctx context.Context, arg ForceAcquireCwdLockParams) (int64, error) {
	result, err := q.db.Exec(ctx, forceAcquireCwdLock,
		arg.Cwd,
		arg.InstanceID,
		arg.Pid,
		arg.Pid_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCwdLockHolder = `-- name: GetCwdLockHolder :one
SELECT instance_id, pid, heartbeat_at
FROM cwd_instance_locks
WHERE cwd = $1
`

type GetCwdLockHolderRow struct {
	InstanceID  string    `db:"instance_id" json:"instance_id"`
	Pid         int32     `db:"pid" json:"pid"`
	HeartbeatAt time.Time `db:"heartbeat_at" json:"heartbeat_at"`
}

func (q *Queries) GetCwdLockHolder(ctx context.Context, cwd string) (GetCwdLockHolderRow, error) {
	row := q.db.QueryRow(ctx, getCwdLockHolder, cwd)
	var i GetCwdLockHolderRow
	err := row.Scan(&i.InstanceID, &i.Pid, &i.HeartbeatAt)
	return i, err
}

const heartbeatCwdLock = `-- name: HeartbeatCwdLock :exec
UPDATE cwd_instance_locks
SET heartbeat_at = NOW(),
    pid = $3
WHERE cwd = $1 AND instance_id = $2
`

type HeartbeatCwdLockParams struct {
	Cwd        string `db:"cwd" json:"cwd"`
	InstanceID string `db:"instance_id" json:"instance_id"`
	Pid        int32  `db:"pid" json:"pid"`
}

func (q *Queries) HeartbeatCwdLock(ctx context.Context, arg HeartbeatCwdLockParams) error {
	_, err := q.db.Exec(ctx, heartbeatCwdLock, arg.Cwd, arg.InstanceID, arg.Pid)
	return err
}

const releaseCwdLock = `-- name: ReleaseCwdLock :execrows
DELETE FROM cwd_instance_locks
WHERE cwd = $1 AND instance_id = $2
`

type ReleaseCwdLockParams struct {
	Cwd        string `db:"cwd" json:"cwd"`
	InstanceID string `db:"instance_id" json:"instance_id"`
}

func (q *Queries) ReleaseCwdLock(ctx context.Context, arg ReleaseCwdLockParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseCwdLock, arg.Cwd, arg.InstanceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
