// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: datasource.sql

package sqlc

import (
	"context"
)

const deleteDatasourceDocument = `-- name: DeleteDatasourceDocument :execrows
DELETE FROM datasource_documents
WHERE workspace_root = ? AND name = ?
`

type DeleteDatasourceDocumentParams struct {
	WorkspaceRoot string `db:"workspace_root" json:"workspace_root"`
	Name          string `db:"name" json:"name"`
}

func (q *Queries) DeleteDatasourceDocument(ctx context.Context, arg DeleteDatasourceDocumentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDatasourceDocument, arg.WorkspaceRoot, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listDatasourceDocumentPromptMetadata = `-- name: ListDatasourceDocumentPromptMetadata :many
SELECT workspace_root, name, extension, size_bytes, stored_path,
       length(CAST(content AS BLOB)) AS content_bytes
FROM datasource_documents
WHERE workspace_root = ?1
ORDER BY name ASC
LIMIT ?2
`

type ListDatasourceDocumentPromptMetadataParams struct {
	WorkspaceRoot string `db:"workspace_root" json:"workspace_root"`
	LimitCount    int64  `db:"limit_count" json:"limit_count"`
}

type ListDatasourceDocumentPromptMetadataRow struct {
	WorkspaceRoot string `db:"workspace_root" json:"workspace_root"`
	Name          string `db:"name" json:"name"`
	Extension     string `db:"extension" json:"extension"`
	SizeBytes     int64  `db:"size_bytes" json:"size_bytes"`
	StoredPath    string `db:"stored_path" json:"stored_path"`
	ContentBytes  *int64 `db:"content_bytes" json:"content_bytes"`
}

func (q *Queries) ListDatasourceDocumentPromptMetadata(ctx context.Context, arg ListDatasourceDocumentPromptMetadataParams) ([]ListDatasourceDocumentPromptMetadataRow, error) {
	rows, err := q.db.QueryContext(ctx, listDatasourceDocumentPromptMetadata, arg.WorkspaceRoot, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDatasourceDocumentPromptMetadataRow{}
	for rows.Next() {
		var i ListDatasourceDocumentPromptMetadataRow
		if err := rows.Scan(
			&i.WorkspaceRoot,
			&i.Name,
			&i.Extension,
			&i.SizeBytes,
			&i.StoredPath,
			&i.ContentBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDatasourceDocuments = `-- name: ListDatasourceDocuments :many
SELECT workspace_root, name, extension, size_bytes, stored_path, content
FROM datasource_documents
WHERE workspace_root = ?
ORDER BY name ASC
`

type ListDatasourceDocumentsParams struct {
	WorkspaceRoot string `db:"workspace_root" json:"workspace_root"`
}

type ListDatasourceDocumentsRow struct {
	WorkspaceRoot string `db:"workspace_root" json:"workspace_root"`
	Name          string `db:"name" json:"name"`
	Extension     string `db:"extension" json:"extension"`
	SizeBytes     int64  `db:"size_bytes" json:"size_bytes"`
	StoredPath    string `db:"stored_path" json:"stored_path"`
	Content       string `db:"content" json:"content"`
}

func (q *Queries) ListDatasourceDocuments(ctx context.Context, arg ListDatasourceDocumentsParams) ([]ListDatasourceDocumentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDatasourceDocuments, arg.WorkspaceRoot)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDatasourceDocumentsRow{}
	for rows.Next() {
		var i ListDatasourceDocumentsRow
		if err := rows.Scan(
			&i.WorkspaceRoot,
			&i.Name,
			&i.Extension,
			&i.SizeBytes,
			&i.StoredPath,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDatasourcePromptDocuments = `-- name: ListDatasourcePromptDocuments :many
SELECT workspace_root, name, extension, size_bytes, stored_path, content
FROM datasource_documents
WHERE workspace_root = ?1
ORDER BY name ASC
LIMIT ?2
`

type ListDatasourcePromptDocumentsParams struct {
	WorkspaceRoot string `db:"workspace_root" json:"workspace_root"`
	LimitCount    int64  `db:"limit_count" json:"limit_count"`
}

type ListDatasourcePromptDocumentsRow struct {
	WorkspaceRoot string `db:"workspace_root" json:"workspace_root"`
	Name          string `db:"name" json:"name"`
	Extension     string `db:"extension" json:"extension"`
	SizeBytes     int64  `db:"size_bytes" json:"size_bytes"`
	StoredPath    string `db:"stored_path" json:"stored_path"`
	Content       string `db:"content" json:"content"`
}

func (q *Queries) ListDatasourcePromptDocuments(ctx context.Context, arg ListDatasourcePromptDocumentsParams) ([]ListDatasourcePromptDocumentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDatasourcePromptDocuments, arg.WorkspaceRoot, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDatasourcePromptDocumentsRow{}
	for rows.Next() {
		var i ListDatasourcePromptDocumentsRow
		if err := rows.Scan(
			&i.WorkspaceRoot,
			&i.Name,
			&i.Extension,
			&i.SizeBytes,
			&i.StoredPath,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDatasourceDocument = `-- name: UpsertDatasourceDocument :execrows

INSERT INTO datasource_documents (
    workspace_root, name, extension, size_bytes, stored_path, content, updated_at
) VALUES (
    ?1, ?2, ?3, ?4,
    ?5, ?6, CAST(strftime('%s','now') AS INTEGER) * 1000
)
ON CONFLICT (workspace_root, name) DO UPDATE SET
    extension = excluded.extension,
    size_bytes = excluded.size_bytes,
    stored_path = excluded.stored_path,
    content = excluded.content,
    updated_at = CAST(strftime('%s','now') AS INTEGER) * 1000
`

type UpsertDatasourceDocumentParams struct {
	WorkspaceRoot string `db:"workspace_root" json:"workspace_root"`
	Name          string `db:"name" json:"name"`
	Extension     string `db:"extension" json:"extension"`
	SizeBytes     int64  `db:"size_bytes" json:"size_bytes"`
	StoredPath    string `db:"stored_path" json:"stored_path"`
	Content       string `db:"content" json:"content"`
}

// datasource.sql - sqlc queries for datasource_documents.
func (q *Queries) UpsertDatasourceDocument(ctx context.Context, arg UpsertDatasourceDocumentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertDatasourceDocument,
		arg.WorkspaceRoot,
		arg.Name,
		arg.Extension,
		arg.SizeBytes,
		arg.StoredPath,
		arg.Content,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
