// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: datasource_v2.sql

package sqlc

import (
	"context"
)

const deleteDatasourceV2ChunksByDocumentID = `-- name: DeleteDatasourceV2ChunksByDocumentID :execrows
DELETE FROM datasource_v2_text_chunks
WHERE document_id = ?1
`

type DeleteDatasourceV2ChunksByDocumentIDParams struct {
	DocumentID int64 `db:"document_id" json:"document_id"`
}

func (q *Queries) DeleteDatasourceV2ChunksByDocumentID(ctx context.Context, arg DeleteDatasourceV2ChunksByDocumentIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDatasourceV2ChunksByDocumentID, arg.DocumentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteDatasourceV2Document = `-- name: DeleteDatasourceV2Document :execrows
DELETE FROM datasource_v2_documents
WHERE id = ?1
`

type DeleteDatasourceV2DocumentParams struct {
	ID int64 `db:"id" json:"id"`
}

func (q *Queries) DeleteDatasourceV2Document(ctx context.Context, arg DeleteDatasourceV2DocumentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDatasourceV2Document, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getDatasourceV2Document = `-- name: GetDatasourceV2Document :one
SELECT id, source_path, file_name, extension, size_bytes, content_hash, chunk_count, total_chars, status, error_message, created_at, updated_at
FROM datasource_v2_documents
WHERE id = ?1
`

type GetDatasourceV2DocumentParams struct {
	ID int64 `db:"id" json:"id"`
}

func (q *Queries) GetDatasourceV2Document(ctx context.Context, arg GetDatasourceV2DocumentParams) (DatasourceV2Document, error) {
	row := q.db.QueryRowContext(ctx, getDatasourceV2Document, arg.ID)
	var i DatasourceV2Document
	err := row.Scan(
		&i.ID,
		&i.SourcePath,
		&i.FileName,
		&i.Extension,
		&i.SizeBytes,
		&i.ContentHash,
		&i.ChunkCount,
		&i.TotalChars,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDatasourceV2Chunk = `-- name: InsertDatasourceV2Chunk :exec
INSERT INTO datasource_v2_text_chunks (
    document_id,
    chunk_index,
    content,
    char_count,
    byte_count,
    embedding,
    embedding_model,
    embedding_dim,
    token_count
)
VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9
)
`

type InsertDatasourceV2ChunkParams struct {
	DocumentID     int64  `db:"document_id" json:"document_id"`
	ChunkIndex     int32  `db:"chunk_index" json:"chunk_index"`
	Content        string `db:"content" json:"content"`
	CharCount      int32  `db:"char_count" json:"char_count"`
	ByteCount      int32  `db:"byte_count" json:"byte_count"`
	Embedding      []byte `db:"embedding" json:"embedding"`
	EmbeddingModel string `db:"embedding_model" json:"embedding_model"`
	EmbeddingDim   int32  `db:"embedding_dim" json:"embedding_dim"`
	TokenCount     int32  `db:"token_count" json:"token_count"`
}

func (q *Queries) InsertDatasourceV2Chunk(ctx context.Context, arg InsertDatasourceV2ChunkParams) error {
	_, err := q.db.ExecContext(ctx, insertDatasourceV2Chunk,
		arg.DocumentID,
		arg.ChunkIndex,
		arg.Content,
		arg.CharCount,
		arg.ByteCount,
		arg.Embedding,
		arg.EmbeddingModel,
		arg.EmbeddingDim,
		arg.TokenCount,
	)
	return err
}

const listDatasourceV2Chunks = `-- name: ListDatasourceV2Chunks :many
SELECT id, document_id, chunk_index, content, char_count, byte_count, embedding, embedding_model, embedding_dim, token_count, created_at
FROM datasource_v2_text_chunks
WHERE document_id = ?1
ORDER BY chunk_index ASC
`

type ListDatasourceV2ChunksParams struct {
	DocumentID int64 `db:"document_id" json:"document_id"`
}

type ListDatasourceV2ChunksRow struct {
	ID             int64  `db:"id" json:"id"`
	DocumentID     int64  `db:"document_id" json:"document_id"`
	ChunkIndex     int32  `db:"chunk_index" json:"chunk_index"`
	Content        string `db:"content" json:"content"`
	CharCount      int32  `db:"char_count" json:"char_count"`
	ByteCount      int32  `db:"byte_count" json:"byte_count"`
	Embedding      []byte `db:"embedding" json:"embedding"`
	EmbeddingModel string `db:"embedding_model" json:"embedding_model"`
	EmbeddingDim   int32  `db:"embedding_dim" json:"embedding_dim"`
	TokenCount     int32  `db:"token_count" json:"token_count"`
	CreatedAt      int64  `db:"created_at" json:"created_at"`
}

func (q *Queries) ListDatasourceV2Chunks(ctx context.Context, arg ListDatasourceV2ChunksParams) ([]ListDatasourceV2ChunksRow, error) {
	rows, err := q.db.QueryContext(ctx, listDatasourceV2Chunks, arg.DocumentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDatasourceV2ChunksRow{}
	for rows.Next() {
		var i ListDatasourceV2ChunksRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.ChunkIndex,
			&i.Content,
			&i.CharCount,
			&i.ByteCount,
			&i.Embedding,
			&i.EmbeddingModel,
			&i.EmbeddingDim,
			&i.TokenCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDatasourceV2Documents = `-- name: ListDatasourceV2Documents :many
SELECT id, source_path, file_name, extension, size_bytes, content_hash, chunk_count, total_chars, status, error_message, created_at, updated_at
FROM datasource_v2_documents
WHERE (
    ?1 = ''
    OR source_path LIKE '%' || ?1 || '%'
    OR file_name LIKE '%' || ?1 || '%'
    OR status LIKE '%' || ?1 || '%'
)
ORDER BY updated_at DESC, id DESC
LIMIT ?2
`

type ListDatasourceV2DocumentsParams struct {
	Keyword interface{} `db:"keyword" json:"keyword"`
	Limit   int64       `db:"limit" json:"limit"`
}

func (q *Queries) ListDatasourceV2Documents(ctx context.Context, arg ListDatasourceV2DocumentsParams) ([]DatasourceV2Document, error) {
	rows, err := q.db.QueryContext(ctx, listDatasourceV2Documents, arg.Keyword, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DatasourceV2Document{}
	for rows.Next() {
		var i DatasourceV2Document
		if err := rows.Scan(
			&i.ID,
			&i.SourcePath,
			&i.FileName,
			&i.Extension,
			&i.SizeBytes,
			&i.ContentHash,
			&i.ChunkCount,
			&i.TotalChars,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDatasourceV2DocumentReady = `-- name: MarkDatasourceV2DocumentReady :one
UPDATE datasource_v2_documents
SET content_hash = ?1,
    chunk_count = ?2,
    total_chars = ?3,
    status = 'ready',
    error_message = NULL,
    updated_at = (CAST(strftime('%s','now') AS INTEGER) * 1000)
WHERE id = ?4
RETURNING id, source_path, file_name, extension, size_bytes, content_hash, chunk_count, total_chars, status, error_message, created_at, updated_at
`

type MarkDatasourceV2DocumentReadyParams struct {
	ContentHash *string `db:"content_hash" json:"content_hash"`
	ChunkCount  int32   `db:"chunk_count" json:"chunk_count"`
	TotalChars  int32   `db:"total_chars" json:"total_chars"`
	ID          int64   `db:"id" json:"id"`
}

func (q *Queries) MarkDatasourceV2DocumentReady(ctx context.Context, arg MarkDatasourceV2DocumentReadyParams) (DatasourceV2Document, error) {
	row := q.db.QueryRowContext(ctx, markDatasourceV2DocumentReady,
		arg.ContentHash,
		arg.ChunkCount,
		arg.TotalChars,
		arg.ID,
	)
	var i DatasourceV2Document
	err := row.Scan(
		&i.ID,
		&i.SourcePath,
		&i.FileName,
		&i.Extension,
		&i.SizeBytes,
		&i.ContentHash,
		&i.ChunkCount,
		&i.TotalChars,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchDatasourceV2ChunksByEmbedding = `-- name: SearchDatasourceV2ChunksByEmbedding :many
SELECT
    c.id,
    c.document_id,
    c.chunk_index,
    c.content,
    c.char_count,
    c.byte_count,
    c.embedding,
    c.embedding_model,
    c.embedding_dim,
    c.token_count,
    c.created_at,
    d.source_path,
    d.file_name,
    CAST(vec_distance_cosine(c.embedding, ?1) AS REAL) AS distance
FROM datasource_v2_text_chunks AS c
JOIN datasource_v2_documents AS d ON d.id = c.document_id
WHERE d.status = 'ready'
  AND c.embedding IS NOT NULL
  AND c.embedding_model = ?2
  AND c.embedding_dim = ?3
  AND c.token_count > 0
ORDER BY distance ASC, c.document_id ASC, c.chunk_index ASC
LIMIT ?4
`

type SearchDatasourceV2ChunksByEmbeddingParams struct {
	Embedding      interface{} `db:"embedding" json:"embedding"`
	EmbeddingModel string      `db:"embedding_model" json:"embedding_model"`
	EmbeddingDim   int32       `db:"embedding_dim" json:"embedding_dim"`
	Limit          int64       `db:"limit" json:"limit"`
}

type SearchDatasourceV2ChunksByEmbeddingRow struct {
	ID             int64   `db:"id" json:"id"`
	DocumentID     int64   `db:"document_id" json:"document_id"`
	ChunkIndex     int32   `db:"chunk_index" json:"chunk_index"`
	Content        string  `db:"content" json:"content"`
	CharCount      int32   `db:"char_count" json:"char_count"`
	ByteCount      int32   `db:"byte_count" json:"byte_count"`
	Embedding      []byte  `db:"embedding" json:"embedding"`
	EmbeddingModel string  `db:"embedding_model" json:"embedding_model"`
	EmbeddingDim   int32   `db:"embedding_dim" json:"embedding_dim"`
	TokenCount     int32   `db:"token_count" json:"token_count"`
	CreatedAt      int64   `db:"created_at" json:"created_at"`
	SourcePath     string  `db:"source_path" json:"source_path"`
	FileName       string  `db:"file_name" json:"file_name"`
	Distance       float64 `db:"distance" json:"distance"`
}

func (q *Queries) SearchDatasourceV2ChunksByEmbedding(ctx context.Context, arg SearchDatasourceV2ChunksByEmbeddingParams) ([]SearchDatasourceV2ChunksByEmbeddingRow, error) {
	rows, err := q.db.QueryContext(ctx, searchDatasourceV2ChunksByEmbedding,
		arg.Embedding,
		arg.EmbeddingModel,
		arg.EmbeddingDim,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchDatasourceV2ChunksByEmbeddingRow{}
	for rows.Next() {
		var i SearchDatasourceV2ChunksByEmbeddingRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.ChunkIndex,
			&i.Content,
			&i.CharCount,
			&i.ByteCount,
			&i.Embedding,
			&i.EmbeddingModel,
			&i.EmbeddingDim,
			&i.TokenCount,
			&i.CreatedAt,
			&i.SourcePath,
			&i.FileName,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDatasourceV2DocumentMetadata = `-- name: UpdateDatasourceV2DocumentMetadata :one
UPDATE datasource_v2_documents
SET source_path = ?1,
    file_name = ?2,
    extension = ?3,
    size_bytes = ?4,
    updated_at = (CAST(strftime('%s','now') AS INTEGER) * 1000)
WHERE id = ?5
RETURNING id, source_path, file_name, extension, size_bytes, content_hash, chunk_count, total_chars, status, error_message, created_at, updated_at
`

type UpdateDatasourceV2DocumentMetadataParams struct {
	SourcePath string `db:"source_path" json:"source_path"`
	FileName   string `db:"file_name" json:"file_name"`
	Extension  string `db:"extension" json:"extension"`
	SizeBytes  int64  `db:"size_bytes" json:"size_bytes"`
	ID         int64  `db:"id" json:"id"`
}

func (q *Queries) UpdateDatasourceV2DocumentMetadata(ctx context.Context, arg UpdateDatasourceV2DocumentMetadataParams) (DatasourceV2Document, error) {
	row := q.db.QueryRowContext(ctx, updateDatasourceV2DocumentMetadata,
		arg.SourcePath,
		arg.FileName,
		arg.Extension,
		arg.SizeBytes,
		arg.ID,
	)
	var i DatasourceV2Document
	err := row.Scan(
		&i.ID,
		&i.SourcePath,
		&i.FileName,
		&i.Extension,
		&i.SizeBytes,
		&i.ContentHash,
		&i.ChunkCount,
		&i.TotalChars,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertDatasourceV2DocumentImporting = `-- name: UpsertDatasourceV2DocumentImporting :one
INSERT INTO datasource_v2_documents (
    source_path,
    file_name,
    extension,
    size_bytes,
    status,
    error_message,
    content_hash,
    chunk_count,
    total_chars,
    updated_at
)
VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    'importing',
    NULL,
    NULL,
    0,
    0,
    (CAST(strftime('%s','now') AS INTEGER) * 1000)
)
ON CONFLICT (source_path) DO UPDATE
SET file_name = EXCLUDED.file_name,
    extension = EXCLUDED.extension,
    size_bytes = EXCLUDED.size_bytes,
    status = 'importing',
    error_message = NULL,
    content_hash = NULL,
    chunk_count = 0,
    total_chars = 0,
    updated_at = (CAST(strftime('%s','now') AS INTEGER) * 1000)
RETURNING id, source_path, file_name, extension, size_bytes, content_hash, chunk_count, total_chars, status, error_message, created_at, updated_at
`

type UpsertDatasourceV2DocumentImportingParams struct {
	SourcePath string `db:"source_path" json:"source_path"`
	FileName   string `db:"file_name" json:"file_name"`
	Extension  string `db:"extension" json:"extension"`
	SizeBytes  int64  `db:"size_bytes" json:"size_bytes"`
}

func (q *Queries) UpsertDatasourceV2DocumentImporting(ctx context.Context, arg UpsertDatasourceV2DocumentImportingParams) (DatasourceV2Document, error) {
	row := q.db.QueryRowContext(ctx, upsertDatasourceV2DocumentImporting,
		arg.SourcePath,
		arg.FileName,
		arg.Extension,
		arg.SizeBytes,
	)
	var i DatasourceV2Document
	err := row.Scan(
		&i.ID,
		&i.SourcePath,
		&i.FileName,
		&i.Extension,
		&i.SizeBytes,
		&i.ContentHash,
		&i.ChunkCount,
		&i.TotalChars,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
