// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hook_pending_review.sql

package sqlc

import (
	"context"
	"encoding/json"
)

const cancelExpiredHookReviews = `-- name: CancelExpiredHookReviews :execrows
UPDATE hook_pending_reviews
SET status = 'expired', decision = default_action, resolved_at = ?
WHERE status = 'pending' AND deadline_at <= ?
`

type CancelExpiredHookReviewsParams struct {
	ResolvedAt *int64 `db:"resolved_at" json:"resolved_at"`
	DeadlineAt int64  `db:"deadline_at" json:"deadline_at"`
}

func (q *Queries) CancelExpiredHookReviews(ctx context.Context, arg CancelExpiredHookReviewsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelExpiredHookReviews, arg.ResolvedAt, arg.DeadlineAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const cancelHookPendingReviewsByAgent = `-- name: CancelHookPendingReviewsByAgent :execrows
UPDATE hook_pending_reviews
SET status = 'cancelled', resolved_at = ?
WHERE agent_id = ? AND status = 'pending'
`

type CancelHookPendingReviewsByAgentParams struct {
	ResolvedAt *int64 `db:"resolved_at" json:"resolved_at"`
	AgentID    string `db:"agent_id" json:"agent_id"`
}

func (q *Queries) CancelHookPendingReviewsByAgent(ctx context.Context, arg CancelHookPendingReviewsByAgentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelHookPendingReviewsByAgent, arg.ResolvedAt, arg.AgentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const cancelHookPendingReviewsByLease = `-- name: CancelHookPendingReviewsByLease :execrows
UPDATE hook_pending_reviews
SET status = 'cancelled', resolved_at = ?
WHERE subscriber_lease = ? AND status = 'pending'
`

type CancelHookPendingReviewsByLeaseParams struct {
	ResolvedAt      *int64 `db:"resolved_at" json:"resolved_at"`
	SubscriberLease string `db:"subscriber_lease" json:"subscriber_lease"`
}

func (q *Queries) CancelHookPendingReviewsByLease(ctx context.Context, arg CancelHookPendingReviewsByLeaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelHookPendingReviewsByLease, arg.ResolvedAt, arg.SubscriberLease)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countHookPendingReviews = `-- name: CountHookPendingReviews :one
SELECT COUNT(*)
FROM hook_pending_reviews
WHERE status = 'pending'
`

func (q *Queries) CountHookPendingReviews(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countHookPendingReviews)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getHookPendingReview = `-- name: GetHookPendingReview :one
SELECT hook_call_id, topic, agent_id, thread_id, turn_id, subscriber_lease, payload, default_action,
       status, created_at, deadline_at
FROM hook_pending_reviews
WHERE hook_call_id = ? AND status = 'pending'
`

type GetHookPendingReviewParams struct {
	HookCallID string `db:"hook_call_id" json:"hook_call_id"`
}

type GetHookPendingReviewRow struct {
	HookCallID      string          `db:"hook_call_id" json:"hook_call_id"`
	Topic           string          `db:"topic" json:"topic"`
	AgentID         string          `db:"agent_id" json:"agent_id"`
	ThreadID        string          `db:"thread_id" json:"thread_id"`
	TurnID          string          `db:"turn_id" json:"turn_id"`
	SubscriberLease string          `db:"subscriber_lease" json:"subscriber_lease"`
	Payload         json.RawMessage `db:"payload" json:"payload"`
	DefaultAction   string          `db:"default_action" json:"default_action"`
	Status          string          `db:"status" json:"status"`
	CreatedAt       int64           `db:"created_at" json:"created_at"`
	DeadlineAt      int64           `db:"deadline_at" json:"deadline_at"`
}

func (q *Queries) GetHookPendingReview(ctx context.Context, arg GetHookPendingReviewParams) (GetHookPendingReviewRow, error) {
	row := q.db.QueryRowContext(ctx, getHookPendingReview, arg.HookCallID)
	var i GetHookPendingReviewRow
	err := row.Scan(
		&i.HookCallID,
		&i.Topic,
		&i.AgentID,
		&i.ThreadID,
		&i.TurnID,
		&i.SubscriberLease,
		&i.Payload,
		&i.DefaultAction,
		&i.Status,
		&i.CreatedAt,
		&i.DeadlineAt,
	)
	return i, err
}

const getHookPendingReviewForSave = `-- name: GetHookPendingReviewForSave :one
SELECT hook_call_id, topic, agent_id, thread_id, turn_id, subscriber_lease, payload, default_action,
       status, created_at, deadline_at
FROM hook_pending_reviews
WHERE hook_call_id = ?
`

type GetHookPendingReviewForSaveParams struct {
	HookCallID string `db:"hook_call_id" json:"hook_call_id"`
}

type GetHookPendingReviewForSaveRow struct {
	HookCallID      string          `db:"hook_call_id" json:"hook_call_id"`
	Topic           string          `db:"topic" json:"topic"`
	AgentID         string          `db:"agent_id" json:"agent_id"`
	ThreadID        string          `db:"thread_id" json:"thread_id"`
	TurnID          string          `db:"turn_id" json:"turn_id"`
	SubscriberLease string          `db:"subscriber_lease" json:"subscriber_lease"`
	Payload         json.RawMessage `db:"payload" json:"payload"`
	DefaultAction   string          `db:"default_action" json:"default_action"`
	Status          string          `db:"status" json:"status"`
	CreatedAt       int64           `db:"created_at" json:"created_at"`
	DeadlineAt      int64           `db:"deadline_at" json:"deadline_at"`
}

func (q *Queries) GetHookPendingReviewForSave(ctx context.Context, arg GetHookPendingReviewForSaveParams) (GetHookPendingReviewForSaveRow, error) {
	row := q.db.QueryRowContext(ctx, getHookPendingReviewForSave, arg.HookCallID)
	var i GetHookPendingReviewForSaveRow
	err := row.Scan(
		&i.HookCallID,
		&i.Topic,
		&i.AgentID,
		&i.ThreadID,
		&i.TurnID,
		&i.SubscriberLease,
		&i.Payload,
		&i.DefaultAction,
		&i.Status,
		&i.CreatedAt,
		&i.DeadlineAt,
	)
	return i, err
}

const getHookResolvedReview = `-- name: GetHookResolvedReview :one
SELECT decision, resolved_at, subscriber_lease
FROM hook_pending_reviews
WHERE hook_call_id = ? AND status = 'resolved'
`

type GetHookResolvedReviewParams struct {
	HookCallID string `db:"hook_call_id" json:"hook_call_id"`
}

type GetHookResolvedReviewRow struct {
	Decision        string `db:"decision" json:"decision"`
	ResolvedAt      *int64 `db:"resolved_at" json:"resolved_at"`
	SubscriberLease string `db:"subscriber_lease" json:"subscriber_lease"`
}

func (q *Queries) GetHookResolvedReview(ctx context.Context, arg GetHookResolvedReviewParams) (GetHookResolvedReviewRow, error) {
	row := q.db.QueryRowContext(ctx, getHookResolvedReview, arg.HookCallID)
	var i GetHookResolvedReviewRow
	err := row.Scan(&i.Decision, &i.ResolvedAt, &i.SubscriberLease)
	return i, err
}

const listHookPendingReviewsByAgent = `-- name: ListHookPendingReviewsByAgent :many
SELECT hook_call_id, topic, agent_id, thread_id, turn_id, subscriber_lease, payload, default_action,
       status, created_at, deadline_at
FROM hook_pending_reviews
WHERE agent_id = ? AND status = 'pending'
ORDER BY created_at ASC, hook_call_id ASC
LIMIT 500
`

type ListHookPendingReviewsByAgentParams struct {
	AgentID string `db:"agent_id" json:"agent_id"`
}

type ListHookPendingReviewsByAgentRow struct {
	HookCallID      string          `db:"hook_call_id" json:"hook_call_id"`
	Topic           string          `db:"topic" json:"topic"`
	AgentID         string          `db:"agent_id" json:"agent_id"`
	ThreadID        string          `db:"thread_id" json:"thread_id"`
	TurnID          string          `db:"turn_id" json:"turn_id"`
	SubscriberLease string          `db:"subscriber_lease" json:"subscriber_lease"`
	Payload         json.RawMessage `db:"payload" json:"payload"`
	DefaultAction   string          `db:"default_action" json:"default_action"`
	Status          string          `db:"status" json:"status"`
	CreatedAt       int64           `db:"created_at" json:"created_at"`
	DeadlineAt      int64           `db:"deadline_at" json:"deadline_at"`
}

func (q *Queries) ListHookPendingReviewsByAgent(ctx context.Context, arg ListHookPendingReviewsByAgentParams) ([]ListHookPendingReviewsByAgentRow, error) {
	rows, err := q.db.QueryContext(ctx, listHookPendingReviewsByAgent, arg.AgentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHookPendingReviewsByAgentRow{}
	for rows.Next() {
		var i ListHookPendingReviewsByAgentRow
		if err := rows.Scan(
			&i.HookCallID,
			&i.Topic,
			&i.AgentID,
			&i.ThreadID,
			&i.TurnID,
			&i.SubscriberLease,
			&i.Payload,
			&i.DefaultAction,
			&i.Status,
			&i.CreatedAt,
			&i.DeadlineAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHookPendingReviewsByAgentPage = `-- name: ListHookPendingReviewsByAgentPage :many
SELECT hook_call_id, topic, agent_id, thread_id, turn_id, subscriber_lease, payload, default_action,
       status, created_at, deadline_at
FROM hook_pending_reviews
WHERE agent_id = ?1
  AND status = 'pending'
  AND (
      CAST(?2 AS TEXT) = ''
      OR created_at > ?3
      OR (created_at = ?3 AND hook_call_id > CAST(?2 AS TEXT))
  )
ORDER BY created_at ASC, hook_call_id ASC
LIMIT ?4 + 1
`

type ListHookPendingReviewsByAgentPageParams struct {
	AgentID          string `db:"agent_id" json:"agent_id"`
	CursorHookCallID string `db:"cursor_hook_call_id" json:"cursor_hook_call_id"`
	CursorCreatedAt  int64  `db:"cursor_created_at" json:"cursor_created_at"`
	Limit            any    `db:"limit" json:"limit"`
}

type ListHookPendingReviewsByAgentPageRow struct {
	HookCallID      string          `db:"hook_call_id" json:"hook_call_id"`
	Topic           string          `db:"topic" json:"topic"`
	AgentID         string          `db:"agent_id" json:"agent_id"`
	ThreadID        string          `db:"thread_id" json:"thread_id"`
	TurnID          string          `db:"turn_id" json:"turn_id"`
	SubscriberLease string          `db:"subscriber_lease" json:"subscriber_lease"`
	Payload         json.RawMessage `db:"payload" json:"payload"`
	DefaultAction   string          `db:"default_action" json:"default_action"`
	Status          string          `db:"status" json:"status"`
	CreatedAt       int64           `db:"created_at" json:"created_at"`
	DeadlineAt      int64           `db:"deadline_at" json:"deadline_at"`
}

func (q *Queries) ListHookPendingReviewsByAgentPage(ctx context.Context, arg ListHookPendingReviewsByAgentPageParams) ([]ListHookPendingReviewsByAgentPageRow, error) {
	rows, err := q.db.QueryContext(ctx, listHookPendingReviewsByAgentPage,
		arg.AgentID,
		arg.CursorHookCallID,
		arg.CursorCreatedAt,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHookPendingReviewsByAgentPageRow{}
	for rows.Next() {
		var i ListHookPendingReviewsByAgentPageRow
		if err := rows.Scan(
			&i.HookCallID,
			&i.Topic,
			&i.AgentID,
			&i.ThreadID,
			&i.TurnID,
			&i.SubscriberLease,
			&i.Payload,
			&i.DefaultAction,
			&i.Status,
			&i.CreatedAt,
			&i.DeadlineAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recoverHookPendingReviews = `-- name: RecoverHookPendingReviews :many
SELECT hook_call_id, topic, agent_id, thread_id, turn_id, subscriber_lease, payload, default_action,
       status, created_at, deadline_at
FROM hook_pending_reviews
WHERE status = 'pending'
ORDER BY deadline_at ASC
`

type RecoverHookPendingReviewsRow struct {
	HookCallID      string          `db:"hook_call_id" json:"hook_call_id"`
	Topic           string          `db:"topic" json:"topic"`
	AgentID         string          `db:"agent_id" json:"agent_id"`
	ThreadID        string          `db:"thread_id" json:"thread_id"`
	TurnID          string          `db:"turn_id" json:"turn_id"`
	SubscriberLease string          `db:"subscriber_lease" json:"subscriber_lease"`
	Payload         json.RawMessage `db:"payload" json:"payload"`
	DefaultAction   string          `db:"default_action" json:"default_action"`
	Status          string          `db:"status" json:"status"`
	CreatedAt       int64           `db:"created_at" json:"created_at"`
	DeadlineAt      int64           `db:"deadline_at" json:"deadline_at"`
}

func (q *Queries) RecoverHookPendingReviews(ctx context.Context) ([]RecoverHookPendingReviewsRow, error) {
	rows, err := q.db.QueryContext(ctx, recoverHookPendingReviews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecoverHookPendingReviewsRow{}
	for rows.Next() {
		var i RecoverHookPendingReviewsRow
		if err := rows.Scan(
			&i.HookCallID,
			&i.Topic,
			&i.AgentID,
			&i.ThreadID,
			&i.TurnID,
			&i.SubscriberLease,
			&i.Payload,
			&i.DefaultAction,
			&i.Status,
			&i.CreatedAt,
			&i.DeadlineAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveHookPendingReview = `-- name: ResolveHookPendingReview :execrows
UPDATE hook_pending_reviews
SET status = CASE WHEN status = 'pending' THEN 'resolved' ELSE status END,
    decision = CASE WHEN status = 'pending' THEN ?1 ELSE decision END,
    reason = CASE WHEN status = 'pending' THEN ?2 ELSE reason END,
    idempotency_key = CASE WHEN status = 'pending' THEN ?3 ELSE idempotency_key END,
    resolved_by = CASE WHEN status = 'pending' THEN ?4 ELSE resolved_by END,
    resolved_at = CASE WHEN status = 'pending' THEN ?5 ELSE resolved_at END
WHERE hook_call_id = ?6
  AND (
      status = 'pending'
      OR (status = 'resolved' AND idempotency_key = ?3)
  )
`

type ResolveHookPendingReviewParams struct {
	Decision       string `db:"decision" json:"decision"`
	Reason         string `db:"reason" json:"reason"`
	IdempotencyKey string `db:"idempotency_key" json:"idempotency_key"`
	ResolvedBy     string `db:"resolved_by" json:"resolved_by"`
	ResolvedAt     *int64 `db:"resolved_at" json:"resolved_at"`
	HookCallID     string `db:"hook_call_id" json:"hook_call_id"`
}

func (q *Queries) ResolveHookPendingReview(ctx context.Context, arg ResolveHookPendingReviewParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, resolveHookPendingReview,
		arg.Decision,
		arg.Reason,
		arg.IdempotencyKey,
		arg.ResolvedBy,
		arg.ResolvedAt,
		arg.HookCallID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const saveHookPendingReview = `-- name: SaveHookPendingReview :execrows

INSERT INTO hook_pending_reviews (
    hook_call_id, topic, agent_id, thread_id, turn_id, subscriber_lease, payload, default_action,
    status, created_at, deadline_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'pending', ?, ?)
ON CONFLICT (hook_call_id) DO NOTHING
`

type SaveHookPendingReviewParams struct {
	HookCallID      string          `db:"hook_call_id" json:"hook_call_id"`
	Topic           string          `db:"topic" json:"topic"`
	AgentID         string          `db:"agent_id" json:"agent_id"`
	ThreadID        string          `db:"thread_id" json:"thread_id"`
	TurnID          string          `db:"turn_id" json:"turn_id"`
	SubscriberLease string          `db:"subscriber_lease" json:"subscriber_lease"`
	Payload         json.RawMessage `db:"payload" json:"payload"`
	DefaultAction   string          `db:"default_action" json:"default_action"`
	CreatedAt       int64           `db:"created_at" json:"created_at"`
	DeadlineAt      int64           `db:"deadline_at" json:"deadline_at"`
}

// hook_pending_review.sql - sqlc queries for hook_pending_reviews table.
// Migrated from internal/store/hookstore/hookstore.go raw SQL.
func (q *Queries) SaveHookPendingReview(ctx context.Context, arg SaveHookPendingReviewParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, saveHookPendingReview,
		arg.HookCallID,
		arg.Topic,
		arg.AgentID,
		arg.ThreadID,
		arg.TurnID,
		arg.SubscriberLease,
		arg.Payload,
		arg.DefaultAction,
		arg.CreatedAt,
		arg.DeadlineAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
