// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mcp_tool_lifecycle.sql

package sqlc

import (
	"context"
)

const backfillMCPToolLifecycle = `-- name: BackfillMCPToolLifecycle :one
INSERT INTO mcp_tool_lifecycle (
    workspace_root, server_name, manifest_name, tool_name, state, reason, replacement_tool, last_seen_at, created_at, updated_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    'enabled',
    '',
    '',
    ?5,
    ?5,
    ?5
)
ON CONFLICT (workspace_root, server_name, tool_name) DO UPDATE
SET manifest_name = CASE
        WHEN EXCLUDED.manifest_name <> '' THEN EXCLUDED.manifest_name
        ELSE mcp_tool_lifecycle.manifest_name
    END,
    last_seen_at = EXCLUDED.last_seen_at,
    updated_at = EXCLUDED.updated_at
RETURNING workspace_root, server_name, manifest_name, tool_name, state, reason, replacement_tool, last_seen_at, created_at, updated_at
`

type BackfillMCPToolLifecycleParams struct {
	WorkspaceRoot string `db:"workspace_root" json:"workspace_root"`
	ServerName    string `db:"server_name" json:"server_name"`
	ManifestName  string `db:"manifest_name" json:"manifest_name"`
	ToolName      string `db:"tool_name" json:"tool_name"`
	Now           int64  `db:"now" json:"now"`
}

func (q *Queries) BackfillMCPToolLifecycle(ctx context.Context, arg BackfillMCPToolLifecycleParams) (McpToolLifecycle, error) {
	row := q.db.QueryRowContext(ctx, backfillMCPToolLifecycle,
		arg.WorkspaceRoot,
		arg.ServerName,
		arg.ManifestName,
		arg.ToolName,
		arg.Now,
	)
	var i McpToolLifecycle
	err := row.Scan(
		&i.WorkspaceRoot,
		&i.ServerName,
		&i.ManifestName,
		&i.ToolName,
		&i.State,
		&i.Reason,
		&i.ReplacementTool,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMCPToolLifecycle = `-- name: GetMCPToolLifecycle :one
SELECT workspace_root, server_name, manifest_name, tool_name, state, reason, replacement_tool, last_seen_at, created_at, updated_at
FROM mcp_tool_lifecycle
WHERE workspace_root = ? AND server_name = ? AND tool_name = ?
`

type GetMCPToolLifecycleParams struct {
	WorkspaceRoot string `db:"workspace_root" json:"workspace_root"`
	ServerName    string `db:"server_name" json:"server_name"`
	ToolName      string `db:"tool_name" json:"tool_name"`
}

func (q *Queries) GetMCPToolLifecycle(ctx context.Context, arg GetMCPToolLifecycleParams) (McpToolLifecycle, error) {
	row := q.db.QueryRowContext(ctx, getMCPToolLifecycle, arg.WorkspaceRoot, arg.ServerName, arg.ToolName)
	var i McpToolLifecycle
	err := row.Scan(
		&i.WorkspaceRoot,
		&i.ServerName,
		&i.ManifestName,
		&i.ToolName,
		&i.State,
		&i.Reason,
		&i.ReplacementTool,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMCPToolLifecycle = `-- name: ListMCPToolLifecycle :many
SELECT workspace_root, server_name, manifest_name, tool_name, state, reason, replacement_tool, last_seen_at, created_at, updated_at
FROM mcp_tool_lifecycle
WHERE workspace_root = ? AND server_name = ?
ORDER BY tool_name ASC
`

type ListMCPToolLifecycleParams struct {
	WorkspaceRoot string `db:"workspace_root" json:"workspace_root"`
	ServerName    string `db:"server_name" json:"server_name"`
}

func (q *Queries) ListMCPToolLifecycle(ctx context.Context, arg ListMCPToolLifecycleParams) ([]McpToolLifecycle, error) {
	rows, err := q.db.QueryContext(ctx, listMCPToolLifecycle, arg.WorkspaceRoot, arg.ServerName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []McpToolLifecycle{}
	for rows.Next() {
		var i McpToolLifecycle
		if err := rows.Scan(
			&i.WorkspaceRoot,
			&i.ServerName,
			&i.ManifestName,
			&i.ToolName,
			&i.State,
			&i.Reason,
			&i.ReplacementTool,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMCPToolLifecycle = `-- name: UpsertMCPToolLifecycle :one
INSERT INTO mcp_tool_lifecycle (
    workspace_root, server_name, manifest_name, tool_name, state, reason, replacement_tool, last_seen_at, created_at, updated_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?8,
    ?8
)
ON CONFLICT (workspace_root, server_name, tool_name) DO UPDATE
SET manifest_name = EXCLUDED.manifest_name,
    state = EXCLUDED.state,
    reason = EXCLUDED.reason,
    replacement_tool = EXCLUDED.replacement_tool,
    last_seen_at = EXCLUDED.last_seen_at,
    updated_at = EXCLUDED.updated_at
RETURNING workspace_root, server_name, manifest_name, tool_name, state, reason, replacement_tool, last_seen_at, created_at, updated_at
`

type UpsertMCPToolLifecycleParams struct {
	WorkspaceRoot   string `db:"workspace_root" json:"workspace_root"`
	ServerName      string `db:"server_name" json:"server_name"`
	ManifestName    string `db:"manifest_name" json:"manifest_name"`
	ToolName        string `db:"tool_name" json:"tool_name"`
	State           string `db:"state" json:"state"`
	Reason          string `db:"reason" json:"reason"`
	ReplacementTool string `db:"replacement_tool" json:"replacement_tool"`
	Now             int64  `db:"now" json:"now"`
}

func (q *Queries) UpsertMCPToolLifecycle(ctx context.Context, arg UpsertMCPToolLifecycleParams) (McpToolLifecycle, error) {
	row := q.db.QueryRowContext(ctx, upsertMCPToolLifecycle,
		arg.WorkspaceRoot,
		arg.ServerName,
		arg.ManifestName,
		arg.ToolName,
		arg.State,
		arg.Reason,
		arg.ReplacementTool,
		arg.Now,
	)
	var i McpToolLifecycle
	err := row.Scan(
		&i.WorkspaceRoot,
		&i.ServerName,
		&i.ManifestName,
		&i.ToolName,
		&i.State,
		&i.Reason,
		&i.ReplacementTool,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
