// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"encoding/json"
)

type AgentInteraction struct {
	ID             int64           `db:"id" json:"id"`
	ThreadID       string          `db:"thread_id" json:"thread_id"`
	ParentID       *int64          `db:"parent_id" json:"parent_id"`
	Sender         string          `db:"sender" json:"sender"`
	Receiver       string          `db:"receiver" json:"receiver"`
	MsgType        string          `db:"msg_type" json:"msg_type"`
	Status         string          `db:"status" json:"status"`
	RequiresReview int64           `db:"requires_review" json:"requires_review"`
	ReviewedBy     string          `db:"reviewed_by" json:"reviewed_by"`
	ReviewNote     string          `db:"review_note" json:"review_note"`
	ReviewedAt     *int64          `db:"reviewed_at" json:"reviewed_at"`
	Payload        json.RawMessage `db:"payload" json:"payload"`
	CreatedAt      int64           `db:"created_at" json:"created_at"`
	UpdatedAt      int64           `db:"updated_at" json:"updated_at"`
}

type AgentProviderBinding struct {
	AgentID            string `db:"agent_id" json:"agent_id"`
	Provider           string `db:"provider" json:"provider"`
	ProviderThreadID   string `db:"provider_thread_id" json:"provider_thread_id"`
	CodexThreadID      string `db:"codex_thread_id" json:"codex_thread_id"`
	RolloutPath        string `db:"rollout_path" json:"rollout_path"`
	CWD                string `db:"cwd" json:"cwd"`
	ParentAgentID      string `db:"parent_agent_id" json:"parent_agent_id"`
	AgentType          string `db:"agent_type" json:"agent_type"`
	AgentMemoryScope   string `db:"agent_memory_scope" json:"agent_memory_scope"`
	Archived           int64  `db:"archived" json:"archived"`
	CreatedAt          int64  `db:"created_at" json:"created_at"`
	UpdatedAt          int64  `db:"updated_at" json:"updated_at"`
	SessionUUID        string `db:"session_uuid" json:"session_uuid"`
	CodexHome          string `db:"codex_home" json:"codex_home"`
	CodexInstanceKey   string `db:"codex_instance_key" json:"codex_instance_key"`
	CodexModelProvider string `db:"codex_model_provider" json:"codex_model_provider"`
}

type AgentStatus struct {
	AgentID     string          `db:"agent_id" json:"agent_id"`
	AgentName   string          `db:"agent_name" json:"agent_name"`
	SessionID   string          `db:"session_id" json:"session_id"`
	Status      string          `db:"status" json:"status"`
	StagnantSec int64           `db:"stagnant_sec" json:"stagnant_sec"`
	Error       string          `db:"error" json:"error"`
	OutputTail  json.RawMessage `db:"output_tail" json:"output_tail"`
	CreatedAt   int64           `db:"created_at" json:"created_at"`
	UpdatedAt   int64           `db:"updated_at" json:"updated_at"`
}

type CronJob struct {
	ID              string          `db:"id" json:"id"`
	Name            string          `db:"name" json:"name"`
	Prompt          string          `db:"prompt" json:"prompt"`
	ScheduleType    string          `db:"schedule_type" json:"schedule_type"`
	ScheduleExpr    string          `db:"schedule_expr" json:"schedule_expr"`
	Timezone        string          `db:"timezone" json:"timezone"`
	Provider        string          `db:"provider" json:"provider"`
	Model           string          `db:"model" json:"model"`
	CWD             string          `db:"cwd" json:"cwd"`
	Config          json.RawMessage `db:"config" json:"config"`
	Skills          json.RawMessage `db:"skills" json:"skills"`
	NotifyChannel   string          `db:"notify_channel" json:"notify_channel"`
	Enabled         int64           `db:"enabled" json:"enabled"`
	NextRunAt       int64           `db:"next_run_at" json:"next_run_at"`
	LastScheduledAt *int64          `db:"last_scheduled_at" json:"last_scheduled_at"`
	LastRunAt       *int64          `db:"last_run_at" json:"last_run_at"`
	ClaimedAt       *int64          `db:"claimed_at" json:"claimed_at"`
	ClaimedBy       string          `db:"claimed_by" json:"claimed_by"`
	LeaseExpiresAt  *int64          `db:"lease_expires_at" json:"lease_expires_at"`
	ClaimToken      string          `db:"claim_token" json:"claim_token"`
	ThreadID        string          `db:"thread_id" json:"thread_id"`
	AgentID         string          `db:"agent_id" json:"agent_id"`
	ActiveTurnID    string          `db:"active_turn_id" json:"active_turn_id"`
	LastTurnID      string          `db:"last_turn_id" json:"last_turn_id"`
	FailureCount    int64           `db:"failure_count" json:"failure_count"`
	MaxAttempts     int64           `db:"max_attempts" json:"max_attempts"`
	NextRetryAt     *int64          `db:"next_retry_at" json:"next_retry_at"`
	LastStatus      string          `db:"last_status" json:"last_status"`
	LastErrorAt     *int64          `db:"last_error_at" json:"last_error_at"`
	LastError       string          `db:"last_error" json:"last_error"`
	CreatedAt       int64           `db:"created_at" json:"created_at"`
	UpdatedAt       int64           `db:"updated_at" json:"updated_at"`
}

type CronJobRun struct {
	ID             string `db:"id" json:"id"`
	JobID          string `db:"job_id" json:"job_id"`
	ScheduledAt    int64  `db:"scheduled_at" json:"scheduled_at"`
	IdempotencyKey string `db:"idempotency_key" json:"idempotency_key"`
	DedupeKey      string `db:"dedupe_key" json:"dedupe_key"`
	ThreadID       string `db:"thread_id" json:"thread_id"`
	AgentID        string `db:"agent_id" json:"agent_id"`
	TurnID         string `db:"turn_id" json:"turn_id"`
	SubmittedAt    *int64 `db:"submitted_at" json:"submitted_at"`
	Status         string `db:"status" json:"status"`
	Error          string `db:"error" json:"error"`
	CreatedAt      int64  `db:"created_at" json:"created_at"`
	UpdatedAt      int64  `db:"updated_at" json:"updated_at"`
}

type PromptRoutingTest struct {
	ID                int64  `db:"id" json:"id"`
	Input             string `db:"input" json:"input"`
	ExpectedPromptKey string `db:"expected_prompt_key" json:"expected_prompt_key"`
	Note              string `db:"note" json:"note"`
	Enabled           int64  `db:"enabled" json:"enabled"`
	CreatedAt         int64  `db:"created_at" json:"created_at"`
	UpdatedAt         int64  `db:"updated_at" json:"updated_at"`
}

type PromptTemplateSection struct {
	ID          int64  `db:"id" json:"id"`
	TemplateID  int64  `db:"template_id" json:"template_id"`
	SectionKey  string `db:"section_key" json:"section_key"`
	Region      string `db:"region" json:"region"`
	Ordinal     int64  `db:"ordinal" json:"ordinal"`
	Body        string `db:"body" json:"body"`
	EnableWhen  string `db:"enable_when" json:"enable_when"`
	Enabled     int64  `db:"enabled" json:"enabled"`
	CreatedAt   int64  `db:"created_at" json:"created_at"`
	UpdatedAt   int64  `db:"updated_at" json:"updated_at"`
	TriggerType string `db:"trigger_type" json:"trigger_type"`
	RecallTopic string `db:"recall_topic" json:"recall_topic"`
}

type SharedFile struct {
	Path      string `db:"path" json:"path"`
	Content   string `db:"content" json:"content"`
	UpdatedBy string `db:"updated_by" json:"updated_by"`
	CreatedAt int64  `db:"created_at" json:"created_at"`
	UpdatedAt int64  `db:"updated_at" json:"updated_at"`
}

type SystemLog struct {
	ID         int64           `db:"id" json:"id"`
	Ts         int64           `db:"ts" json:"ts"`
	Level      string          `db:"level" json:"level"`
	Logger     string          `db:"logger" json:"logger"`
	Message    string          `db:"message" json:"message"`
	Raw        string          `db:"raw" json:"raw"`
	Source     string          `db:"source" json:"source"`
	Component  string          `db:"component" json:"component"`
	AgentID    string          `db:"agent_id" json:"agent_id"`
	ThreadID   string          `db:"thread_id" json:"thread_id"`
	TraceID    string          `db:"trace_id" json:"trace_id"`
	EventType  string          `db:"event_type" json:"event_type"`
	ToolName   string          `db:"tool_name" json:"tool_name"`
	DurationMs *int64          `db:"duration_ms" json:"duration_ms"`
	Extra      json.RawMessage `db:"extra" json:"extra"`
}

type TopologyApproval struct {
	ID                   string `db:"id" json:"id"`
	Status               string `db:"status" json:"status"`
	RequestedBy          string `db:"requested_by" json:"requested_by"`
	Reason               string `db:"reason" json:"reason"`
	CreatedAt            int64  `db:"created_at" json:"created_at"`
	ExpireAt             int64  `db:"expire_at" json:"expire_at"`
	ReviewedAt           *int64 `db:"reviewed_at" json:"reviewed_at"`
	Reviewer             string `db:"reviewer" json:"reviewer"`
	ReviewNote           string `db:"review_note" json:"review_note"`
	ArchHash             string `db:"arch_hash" json:"arch_hash"`
	ProposedArchitecture string `db:"proposed_architecture" json:"proposed_architecture"`
}

type TurnDedupeRegistry struct {
	DedupeKey      string `db:"dedupe_key" json:"dedupe_key"`
	LocalTurnID    string `db:"local_turn_id" json:"local_turn_id"`
	ProviderTurnID string `db:"provider_turn_id" json:"provider_turn_id"`
	ThreadID       string `db:"thread_id" json:"thread_id"`
	CreatedAt      int64  `db:"created_at" json:"created_at"`
	UpdatedAt      int64  `db:"updated_at" json:"updated_at"`
	TerminalAt     *int64 `db:"terminal_at" json:"terminal_at"`
}

type WorkspaceRun struct {
	ID            int64  `db:"id" json:"id"`
	RunKey        string `db:"run_key" json:"run_key"`
	DAGKey        string `db:"dag_key" json:"dag_key"`
	SourceRoot    string `db:"source_root" json:"source_root"`
	WorkspacePath string `db:"workspace_path" json:"workspace_path"`
	Status        string `db:"status" json:"status"`
	CreatedBy     string `db:"created_by" json:"created_by"`
	UpdatedBy     string `db:"updated_by" json:"updated_by"`
	Metadata      string `db:"metadata" json:"metadata"`
	CreatedAt     int64  `db:"created_at" json:"created_at"`
	UpdatedAt     int64  `db:"updated_at" json:"updated_at"`
	FinishedAt    *int64 `db:"finished_at" json:"finished_at"`
}

type WorkspaceRunFile struct {
	ID                 int64  `db:"id" json:"id"`
	RunKey             string `db:"run_key" json:"run_key"`
	RelativePath       string `db:"relative_path" json:"relative_path"`
	BaselineSha256     string `db:"baseline_sha256" json:"baseline_sha256"`
	WorkspaceSha256    string `db:"workspace_sha256" json:"workspace_sha256"`
	SourceSha256Before string `db:"source_sha256_before" json:"source_sha256_before"`
	SourceSha256After  string `db:"source_sha256_after" json:"source_sha256_after"`
	State              string `db:"state" json:"state"`
	LastError          string `db:"last_error" json:"last_error"`
	CreatedAt          int64  `db:"created_at" json:"created_at"`
	UpdatedAt          int64  `db:"updated_at" json:"updated_at"`
}
