// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prompt_template.sql

package sqlc

import (
	"context"
	"time"
)

const createPromptTemplate = `-- name: CreatePromptTemplate :one
INSERT INTO prompt_templates (
    prompt_key, title, agent_key, tool_name, prompt_text,
    variables, tags, description, when_to_use, enabled, manually_edited, match_when, priority,
    created_by, updated_by, updated_at
) VALUES ($1, $2, $3, $4, $5, $6::jsonb, $7::jsonb, $8, $9, $10, $11, $12::jsonb, $13, $14, $15, NOW())
ON CONFLICT (prompt_key) DO NOTHING
RETURNING id, prompt_key, title, agent_key, tool_name, prompt_text, variables, tags, description, when_to_use, enabled, manually_edited, match_when, priority, created_by, updated_by, created_at, updated_at
`

type CreatePromptTemplateParams struct {
	PromptKey      string `db:"prompt_key" json:"prompt_key"`
	Title          string `db:"title" json:"title"`
	AgentKey       string `db:"agent_key" json:"agent_key"`
	ToolName       string `db:"tool_name" json:"tool_name"`
	PromptText     string `db:"prompt_text" json:"prompt_text"`
	Column6        []byte `db:"column_6" json:"column_6"`
	Column7        []byte `db:"column_7" json:"column_7"`
	Description    string `db:"description" json:"description"`
	WhenToUse      string `db:"when_to_use" json:"when_to_use"`
	Enabled        bool   `db:"enabled" json:"enabled"`
	ManuallyEdited bool   `db:"manually_edited" json:"manually_edited"`
	Column12       []byte `db:"column_12" json:"column_12"`
	Priority       int32  `db:"priority" json:"priority"`
	CreatedBy      string `db:"created_by" json:"created_by"`
	UpdatedBy      string `db:"updated_by" json:"updated_by"`
}

type CreatePromptTemplateRow struct {
	ID             int64     `db:"id" json:"id"`
	PromptKey      string    `db:"prompt_key" json:"prompt_key"`
	Title          string    `db:"title" json:"title"`
	AgentKey       string    `db:"agent_key" json:"agent_key"`
	ToolName       string    `db:"tool_name" json:"tool_name"`
	PromptText     string    `db:"prompt_text" json:"prompt_text"`
	Variables      []byte    `db:"variables" json:"variables"`
	Tags           []byte    `db:"tags" json:"tags"`
	Description    string    `db:"description" json:"description"`
	WhenToUse      string    `db:"when_to_use" json:"when_to_use"`
	Enabled        bool      `db:"enabled" json:"enabled"`
	ManuallyEdited bool      `db:"manually_edited" json:"manually_edited"`
	MatchWhen      []byte    `db:"match_when" json:"match_when"`
	Priority       int32     `db:"priority" json:"priority"`
	CreatedBy      string    `db:"created_by" json:"created_by"`
	UpdatedBy      string    `db:"updated_by" json:"updated_by"`
	CreatedAt      time.Time `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreatePromptTemplate(ctx context.Context, arg CreatePromptTemplateParams) (CreatePromptTemplateRow, error) {
	row := q.db.QueryRow(ctx, createPromptTemplate,
		arg.PromptKey,
		arg.Title,
		arg.AgentKey,
		arg.ToolName,
		arg.PromptText,
		arg.Column6,
		arg.Column7,
		arg.Description,
		arg.WhenToUse,
		arg.Enabled,
		arg.ManuallyEdited,
		arg.Column12,
		arg.Priority,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i CreatePromptTemplateRow
	err := row.Scan(
		&i.ID,
		&i.PromptKey,
		&i.Title,
		&i.AgentKey,
		&i.ToolName,
		&i.PromptText,
		&i.Variables,
		&i.Tags,
		&i.Description,
		&i.WhenToUse,
		&i.Enabled,
		&i.ManuallyEdited,
		&i.MatchWhen,
		&i.Priority,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePromptTemplate = `-- name: DeletePromptTemplate :execrows
DELETE FROM prompt_templates
WHERE prompt_key = $1
`

type DeletePromptTemplateParams struct {
	PromptKey string `db:"prompt_key" json:"prompt_key"`
}

func (q *Queries) DeletePromptTemplate(ctx context.Context, arg DeletePromptTemplateParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePromptTemplate, arg.PromptKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPromptTemplate = `-- name: GetPromptTemplate :one
SELECT id, prompt_key, title, agent_key, tool_name, prompt_text, variables, tags, description, when_to_use, enabled, manually_edited, match_when, priority, created_by, updated_by, created_at, updated_at
FROM prompt_templates
WHERE prompt_key = $1
`

type GetPromptTemplateParams struct {
	PromptKey string `db:"prompt_key" json:"prompt_key"`
}

type GetPromptTemplateRow struct {
	ID             int64     `db:"id" json:"id"`
	PromptKey      string    `db:"prompt_key" json:"prompt_key"`
	Title          string    `db:"title" json:"title"`
	AgentKey       string    `db:"agent_key" json:"agent_key"`
	ToolName       string    `db:"tool_name" json:"tool_name"`
	PromptText     string    `db:"prompt_text" json:"prompt_text"`
	Variables      []byte    `db:"variables" json:"variables"`
	Tags           []byte    `db:"tags" json:"tags"`
	Description    string    `db:"description" json:"description"`
	WhenToUse      string    `db:"when_to_use" json:"when_to_use"`
	Enabled        bool      `db:"enabled" json:"enabled"`
	ManuallyEdited bool      `db:"manually_edited" json:"manually_edited"`
	MatchWhen      []byte    `db:"match_when" json:"match_when"`
	Priority       int32     `db:"priority" json:"priority"`
	CreatedBy      string    `db:"created_by" json:"created_by"`
	UpdatedBy      string    `db:"updated_by" json:"updated_by"`
	CreatedAt      time.Time `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetPromptTemplate(ctx context.Context, arg GetPromptTemplateParams) (GetPromptTemplateRow, error) {
	row := q.db.QueryRow(ctx, getPromptTemplate, arg.PromptKey)
	var i GetPromptTemplateRow
	err := row.Scan(
		&i.ID,
		&i.PromptKey,
		&i.Title,
		&i.AgentKey,
		&i.ToolName,
		&i.PromptText,
		&i.Variables,
		&i.Tags,
		&i.Description,
		&i.WhenToUse,
		&i.Enabled,
		&i.ManuallyEdited,
		&i.MatchWhen,
		&i.Priority,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPromptVersion = `-- name: InsertPromptVersion :one
INSERT INTO prompt_versions (
    prompt_key, title, agent_key, tool_name, prompt_text,
    variables, tags, description, enabled, created_by, updated_by, source_updated_at
) VALUES ($1, $2, $3, $4, $5, $6::jsonb, $7::jsonb, $8, $9, $10, $11, $12)
RETURNING id
`

type InsertPromptVersionParams struct {
	PromptKey       string     `db:"prompt_key" json:"prompt_key"`
	Title           string     `db:"title" json:"title"`
	AgentKey        string     `db:"agent_key" json:"agent_key"`
	ToolName        string     `db:"tool_name" json:"tool_name"`
	PromptText      string     `db:"prompt_text" json:"prompt_text"`
	Column6         []byte     `db:"column_6" json:"column_6"`
	Column7         []byte     `db:"column_7" json:"column_7"`
	Description     string     `db:"description" json:"description"`
	Enabled         bool       `db:"enabled" json:"enabled"`
	CreatedBy       string     `db:"created_by" json:"created_by"`
	UpdatedBy       string     `db:"updated_by" json:"updated_by"`
	SourceUpdatedAt *time.Time `db:"source_updated_at" json:"source_updated_at"`
}

func (q *Queries) InsertPromptVersion(ctx context.Context, arg InsertPromptVersionParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertPromptVersion,
		arg.PromptKey,
		arg.Title,
		arg.AgentKey,
		arg.ToolName,
		arg.PromptText,
		arg.Column6,
		arg.Column7,
		arg.Description,
		arg.Enabled,
		arg.CreatedBy,
		arg.UpdatedBy,
		arg.SourceUpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listPromptTemplates = `-- name: ListPromptTemplates :many
SELECT id, prompt_key, title, agent_key, tool_name, prompt_text, variables, tags, description, when_to_use, enabled, manually_edited, match_when, priority, created_by, updated_by, created_at, updated_at
FROM prompt_templates
WHERE ($1::text = '' OR agent_key = $1)
  AND ($2::text = ''
    OR prompt_key ILIKE '%' || $2 || '%'
    OR title ILIKE '%' || $2 || '%'
    OR prompt_text ILIKE '%' || $2 || '%')
  AND (NOT EXISTS (
      SELECT 1
      FROM jsonb_array_elements_text(tags) AS tag(value)
      WHERE tag.value LIKE 'scope.cwd:%'
    )
    OR tags ? 'scope.global'
    OR tags ? ('scope.cwd:' || $3::text))
ORDER BY updated_at DESC
LIMIT $4
`

type ListPromptTemplatesParams struct {
	AgentKey   string `db:"agent_key" json:"agent_key"`
	Keyword    string `db:"keyword" json:"keyword"`
	CWD        string `db:"cwd" json:"cwd"`
	LimitCount int32  `db:"limit_count" json:"limit_count"`
}

type ListPromptTemplatesRow struct {
	ID             int64     `db:"id" json:"id"`
	PromptKey      string    `db:"prompt_key" json:"prompt_key"`
	Title          string    `db:"title" json:"title"`
	AgentKey       string    `db:"agent_key" json:"agent_key"`
	ToolName       string    `db:"tool_name" json:"tool_name"`
	PromptText     string    `db:"prompt_text" json:"prompt_text"`
	Variables      []byte    `db:"variables" json:"variables"`
	Tags           []byte    `db:"tags" json:"tags"`
	Description    string    `db:"description" json:"description"`
	WhenToUse      string    `db:"when_to_use" json:"when_to_use"`
	Enabled        bool      `db:"enabled" json:"enabled"`
	ManuallyEdited bool      `db:"manually_edited" json:"manually_edited"`
	MatchWhen      []byte    `db:"match_when" json:"match_when"`
	Priority       int32     `db:"priority" json:"priority"`
	CreatedBy      string    `db:"created_by" json:"created_by"`
	UpdatedBy      string    `db:"updated_by" json:"updated_by"`
	CreatedAt      time.Time `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListPromptTemplates(ctx context.Context, arg ListPromptTemplatesParams) ([]ListPromptTemplatesRow, error) {
	rows, err := q.db.Query(ctx, listPromptTemplates,
		arg.AgentKey,
		arg.Keyword,
		arg.CWD,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPromptTemplatesRow{}
	for rows.Next() {
		var i ListPromptTemplatesRow
		if err := rows.Scan(
			&i.ID,
			&i.PromptKey,
			&i.Title,
			&i.AgentKey,
			&i.ToolName,
			&i.PromptText,
			&i.Variables,
			&i.Tags,
			&i.Description,
			&i.WhenToUse,
			&i.Enabled,
			&i.ManuallyEdited,
			&i.MatchWhen,
			&i.Priority,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPromptTemplate = `-- name: UpsertPromptTemplate :one
INSERT INTO prompt_templates (
    prompt_key, title, agent_key, tool_name, prompt_text,
    variables, tags, description, when_to_use, enabled, manually_edited, match_when, priority,
    created_by, updated_by, updated_at
) VALUES ($1, $2, $3, $4, $5, $6::jsonb, $7::jsonb, $8, $9, $10, $11, $12::jsonb, $13, $14, $15, NOW())
ON CONFLICT (prompt_key) DO UPDATE
SET title = EXCLUDED.title,
    agent_key = EXCLUDED.agent_key,
    tool_name = EXCLUDED.tool_name,
    prompt_text = EXCLUDED.prompt_text,
    variables = EXCLUDED.variables,
    tags = EXCLUDED.tags,
    description = EXCLUDED.description,
    when_to_use = EXCLUDED.when_to_use,
    enabled = EXCLUDED.enabled,
    manually_edited = EXCLUDED.manually_edited,
    match_when = EXCLUDED.match_when,
    priority = EXCLUDED.priority,
    updated_by = EXCLUDED.updated_by,
    updated_at = NOW()
RETURNING id, prompt_key, title, agent_key, tool_name, prompt_text, variables, tags, description, when_to_use, enabled, manually_edited, match_when, priority, created_by, updated_by, created_at, updated_at
`

type UpsertPromptTemplateParams struct {
	PromptKey      string `db:"prompt_key" json:"prompt_key"`
	Title          string `db:"title" json:"title"`
	AgentKey       string `db:"agent_key" json:"agent_key"`
	ToolName       string `db:"tool_name" json:"tool_name"`
	PromptText     string `db:"prompt_text" json:"prompt_text"`
	Column6        []byte `db:"column_6" json:"column_6"`
	Column7        []byte `db:"column_7" json:"column_7"`
	Description    string `db:"description" json:"description"`
	WhenToUse      string `db:"when_to_use" json:"when_to_use"`
	Enabled        bool   `db:"enabled" json:"enabled"`
	ManuallyEdited bool   `db:"manually_edited" json:"manually_edited"`
	Column12       []byte `db:"column_12" json:"column_12"`
	Priority       int32  `db:"priority" json:"priority"`
	CreatedBy      string `db:"created_by" json:"created_by"`
	UpdatedBy      string `db:"updated_by" json:"updated_by"`
}

type UpsertPromptTemplateRow struct {
	ID             int64     `db:"id" json:"id"`
	PromptKey      string    `db:"prompt_key" json:"prompt_key"`
	Title          string    `db:"title" json:"title"`
	AgentKey       string    `db:"agent_key" json:"agent_key"`
	ToolName       string    `db:"tool_name" json:"tool_name"`
	PromptText     string    `db:"prompt_text" json:"prompt_text"`
	Variables      []byte    `db:"variables" json:"variables"`
	Tags           []byte    `db:"tags" json:"tags"`
	Description    string    `db:"description" json:"description"`
	WhenToUse      string    `db:"when_to_use" json:"when_to_use"`
	Enabled        bool      `db:"enabled" json:"enabled"`
	ManuallyEdited bool      `db:"manually_edited" json:"manually_edited"`
	MatchWhen      []byte    `db:"match_when" json:"match_when"`
	Priority       int32     `db:"priority" json:"priority"`
	CreatedBy      string    `db:"created_by" json:"created_by"`
	UpdatedBy      string    `db:"updated_by" json:"updated_by"`
	CreatedAt      time.Time `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpsertPromptTemplate(ctx context.Context, arg UpsertPromptTemplateParams) (UpsertPromptTemplateRow, error) {
	row := q.db.QueryRow(ctx, upsertPromptTemplate,
		arg.PromptKey,
		arg.Title,
		arg.AgentKey,
		arg.ToolName,
		arg.PromptText,
		arg.Column6,
		arg.Column7,
		arg.Description,
		arg.WhenToUse,
		arg.Enabled,
		arg.ManuallyEdited,
		arg.Column12,
		arg.Priority,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i UpsertPromptTemplateRow
	err := row.Scan(
		&i.ID,
		&i.PromptKey,
		&i.Title,
		&i.AgentKey,
		&i.ToolName,
		&i.PromptText,
		&i.Variables,
		&i.Tags,
		&i.Description,
		&i.WhenToUse,
		&i.Enabled,
		&i.ManuallyEdited,
		&i.MatchWhen,
		&i.Priority,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
