// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prompt_routing_test.sql

package sqlc

import (
	"context"
)

const listEnabledPromptRoutingTests = `-- name: ListEnabledPromptRoutingTests :many
SELECT id, input, expected_prompt_key, note, enabled, created_at, updated_at
FROM prompt_routing_tests
WHERE enabled = 1
ORDER BY id
`

func (q *Queries) ListEnabledPromptRoutingTests(ctx context.Context) ([]PromptRoutingTest, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledPromptRoutingTests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PromptRoutingTest{}
	for rows.Next() {
		var i PromptRoutingTest
		if err := rows.Scan(
			&i.ID,
			&i.Input,
			&i.ExpectedPromptKey,
			&i.Note,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
