// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcquireCwdLock(ctx context.Context, arg AcquireCwdLockParams) (int64, error)
	AgentThreadExists(ctx context.Context, threadID string) (bool, error)
	AgentThreadRunningExists(ctx context.Context, threadID string) (bool, error)
	ApproveSkillCandidate(ctx context.Context, arg ApproveSkillCandidateParams) (SkillCandidate, error)
	ApproveTopologyApproval(ctx context.Context, arg ApproveTopologyApprovalParams) (int64, error)
	BindAgentThread(ctx context.Context, arg BindAgentThreadParams) error
	BindTurnDedupeProviderID(ctx context.Context, arg BindTurnDedupeProviderIDParams) error
	// CASCronJobRunStatus only advances the status when the current status
	// equals expected_status; protects three-phase transitions (pending ->
	// submitting -> submitted -> running -> finished/failed/observe_lost)
	// from stale worker overwrites.
	//
	CASCronJobRunStatus(ctx context.Context, arg CASCronJobRunStatusParams) (int64, error)
	// Claim / lease -----------------------------------------------------
	// ClaimDueJobsForUpdate marks up to `limit` due rows as claimed by `claimed_by`.
	// The embedded SELECT ... FOR UPDATE SKIP LOCKED makes sure two
	// schedulers hitting the same tick never grab the same row. claim_token
	// is generated in the application layer (Go UUID) and passed in so no
	// Postgres extension (pgcrypto / uuid-ossp) is required.
	//
	ClaimDueJobsForUpdate(ctx context.Context, arg ClaimDueJobsForUpdateParams) ([]CronJob, error)
	CountAILogsByStatus(ctx context.Context) ([]CountAILogsByStatusRow, error)
	CountAllThreads(ctx context.Context) (int64, error)
	// Returns the number of child agents belonging to the given parent.
	// Used to determine the next sequential suffix for child agent IDs.
	CountChildAgentThreads(ctx context.Context, parentAgentID string) (int64, error)
	// CRUD --------------------------------------------------------------
	CreateCronJob(ctx context.Context, arg CreateCronJobParams) (CronJob, error)
	CreateInteraction(ctx context.Context, arg CreateInteractionParams) (AgentInteraction, error)
	// Legacy V2 store SQL used proposal_hash/proposal_json columns.
	// These queries are aligned to the V2 exported public schema used for the baseline.
	CreateTopologyApproval(ctx context.Context, arg CreateTopologyApprovalParams) (TopologyApproval, error)
	DeleteAgentProviderBindingByAgentID(ctx context.Context, agentID string) error
	DeleteAgentThreadByID(ctx context.Context, threadID string) error
	DeleteCommandCard(ctx context.Context, cardKey string) (int64, error)
	DeleteCronJob(ctx context.Context, id string) error
	DeletePromptTemplate(ctx context.Context, promptKey string) (int64, error)
	DeletePromptTemplateSection(ctx context.Context, arg DeletePromptTemplateSectionParams) (int64, error)
	DeleteSharedFile(ctx context.Context, path string) (int64, error)
	DeleteStaleCwdLocks(ctx context.Context) (int64, error)
	ExpireStaleAgentThreads(ctx context.Context, arg ExpireStaleAgentThreadsParams) (int64, error)
	ExtendClaim(ctx context.Context, arg ExtendClaimParams) (int64, error)
	ForceAcquireCwdLock(ctx context.Context, arg ForceAcquireCwdLockParams) (int64, error)
	GetAgentProviderBindingByAgentID(ctx context.Context, agentID string) (GetAgentProviderBindingByAgentIDRow, error)
	GetAgentProviderBindingByProviderThread(ctx context.Context, arg GetAgentProviderBindingByProviderThreadParams) (GetAgentProviderBindingByProviderThreadRow, error)
	GetAgentStatus(ctx context.Context, agentID string) (AgentStatus, error)
	GetAgentThreadByID(ctx context.Context, threadID string) (GetAgentThreadByIDRow, error)
	GetAgentThreadByPort(ctx context.Context, port int32) (GetAgentThreadByPortRow, error)
	GetCommandCard(ctx context.Context, cardKey string) (CommandCard, error)
	GetCronJobByID(ctx context.Context, id string) (CronJob, error)
	GetCronJobRunByDedupeKey(ctx context.Context, dedupeKey string) (CronJobRun, error)
	GetCronJobRunByID(ctx context.Context, id string) (CronJobRun, error)
	GetCwdLockHolder(ctx context.Context, cwd string) (GetCwdLockHolderRow, error)
	GetInteraction(ctx context.Context, id int64) (AgentInteraction, error)
	// Returns the still-live registry row for dedupe_key, or an empty row
	// when none exists / all matching rows are already terminal. The
	// scheduler's caller checks local_turn_id == "" to distinguish miss
	// from hit.
	GetLiveTurnDedupe(ctx context.Context, dedupeKey string) (TurnDedupeRegistry, error)
	GetPromptTemplate(ctx context.Context, promptKey string) (GetPromptTemplateRow, error)
	// Used by CompleteTurn to locate the active run for a completed turn without
	// scanning all unresolved rows. turn_id is indexed by the dedupe_key B-tree
	// and the status guard ensures only one row can match (at most one run per
	// turn can be in 'running').
	GetRunningCronJobRunByTurnID(ctx context.Context, turnID string) (CronJobRun, error)
	GetSessionInsightByLocalTurn(ctx context.Context, arg GetSessionInsightByLocalTurnParams) (SessionInsight, error)
	GetSharedFile(ctx context.Context, path string) (SharedFile, error)
	GetSkillCandidateByID(ctx context.Context, id int64) (SkillCandidate, error)
	GetThreadByAgent(ctx context.Context, agentID string) (string, error)
	GetUIPreferenceValue(ctx context.Context, arg GetUIPreferenceValueParams) ([]byte, error)
	GetWorkspaceRun(ctx context.Context, runKey string) (WorkspaceRun, error)
	GetWorkspaceRunFile(ctx context.Context, arg GetWorkspaceRunFileParams) (WorkspaceRunFile, error)
	HeartbeatCwdLock(ctx context.Context, arg HeartbeatCwdLockParams) error
	InsertAgentFeedbackEvent(ctx context.Context, arg InsertAgentFeedbackEventParams) (AgentFeedbackEvent, error)
	InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error
	InsertCommandCardVersion(ctx context.Context, arg InsertCommandCardVersionParams) error
	// cron_job_runs -----------------------------------------------------
	InsertCronJobRun(ctx context.Context, arg InsertCronJobRunParams) (CronJobRun, error)
	InsertPromptVersion(ctx context.Context, arg InsertPromptVersionParams) (int64, error)
	// Queries for skill_candidates. See migration 0064 for the table layout
	// and status-machine contract. State-changing UPDATEs use RETURNING *
	// with a status-guard in the WHERE clause: a non-matching state yields
	// pgx.ErrNoRows, which the store layer maps to platformdb.ErrConflict.
	InsertSkillCandidate(ctx context.Context, arg InsertSkillCandidateParams) (SkillCandidate, error)
	InsertSystemLog(ctx context.Context, arg InsertSystemLogParams) error
	InsertTaskTrace(ctx context.Context, arg InsertTaskTraceParams) (TaskTrace, error)
	ListAILogSystemLogs(ctx context.Context, arg ListAILogSystemLogsParams) ([]SystemLog, error)
	ListAILogsByCategory(ctx context.Context, arg ListAILogsByCategoryParams) ([]ListAILogsByCategoryRow, error)
	ListAgentFeedbackEventsByAgent(ctx context.Context, arg ListAgentFeedbackEventsByAgentParams) ([]AgentFeedbackEvent, error)
	ListAgentFeedbackEventsByThread(ctx context.Context, arg ListAgentFeedbackEventsByThreadParams) ([]AgentFeedbackEvent, error)
	ListAgentStatuses(ctx context.Context, dollar_1 string) ([]AgentStatus, error)
	ListAgentThreadBindings(ctx context.Context) ([]ListAgentThreadBindingsRow, error)
	ListAgentThreadCwds(ctx context.Context) ([]ListAgentThreadCwdsRow, error)
	ListAgentThreadCwdsByPrefix(ctx context.Context, dollar_1 *string) ([]ListAgentThreadCwdsByPrefixRow, error)
	ListAgentThreads(ctx context.Context) ([]ListAgentThreadsRow, error)
	ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]ListAuditEventsRow, error)
	ListBusExceptionLogs(ctx context.Context, arg ListBusExceptionLogsParams) ([]ListBusExceptionLogsRow, error)
	ListCommandCardVersions(ctx context.Context, cardKey string) ([]CommandCardVersion, error)
	ListCommandCards(ctx context.Context, arg ListCommandCardsParams) ([]ListCommandCardsRow, error)
	ListCronJobRunsByJob(ctx context.Context, arg ListCronJobRunsByJobParams) ([]CronJobRun, error)
	ListCronJobs(ctx context.Context) ([]CronJob, error)
	// Used by RenewLeases / ExtendClaimForTurnProgress to fetch only the jobs
	// owned by this scheduler instance, avoiding a full-table scan of cron_jobs.
	ListCronJobsClaimedBy(ctx context.Context, claimedBy string) ([]CronJob, error)
	ListEnabledPromptRoutingTests(ctx context.Context) ([]PromptRoutingTest, error)
	ListInteractions(ctx context.Context, arg ListInteractionsParams) ([]AgentInteraction, error)
	// ListObservedApprovalRequests returns the per-thread approval_requests
	// window but only for turns where approval_requests_observed = TRUE.
	// Claude path rows (observed=FALSE, value=0) are excluded so callers
	// don't conflate "provider didn't emit the event" with "the turn had
	// zero approvals". See P3 plan *_observed discussion.
	//
	ListObservedApprovalRequests(ctx context.Context, arg ListObservedApprovalRequestsParams) ([]ListObservedApprovalRequestsRow, error)
	// ListObservedTokenTurns returns turns where token_snapshot_observed =
	// TRUE. Used by dashboards that want to average token costs without
	// pulling in thread-projection zero-fallback rows.
	//
	ListObservedTokenTurns(ctx context.Context, arg ListObservedTokenTurnsParams) ([]ListObservedTokenTurnsRow, error)
	ListPendingSkillCandidates(ctx context.Context, arg ListPendingSkillCandidatesParams) ([]SkillCandidate, error)
	ListPendingTopologyApprovals(ctx context.Context) ([]TopologyApproval, error)
	ListPromptTemplateSectionsByTemplate(ctx context.Context, templateID int64) ([]PromptTemplateSection, error)
	ListPromptTemplates(ctx context.Context, arg ListPromptTemplatesParams) ([]ListPromptTemplatesRow, error)
	ListRecentAILogs(ctx context.Context, limit int32) ([]ListRecentAILogsRow, error)
	// ListRecentSessionInsights is used by the dashboard API to return the
	// N most recent turns across all threads.
	//
	ListRecentSessionInsights(ctx context.Context, limit int32) ([]SessionInsight, error)
	ListRecoverableAgentThreads(ctx context.Context) ([]ListRecoverableAgentThreadsRow, error)
	ListRunningAgentThreads(ctx context.Context) ([]ListRunningAgentThreadsRow, error)
	ListRunningAgents(ctx context.Context) ([]ListRunningAgentsRow, error)
	ListSessionInsightsByThread(ctx context.Context, arg ListSessionInsightsByThreadParams) ([]SessionInsight, error)
	ListSharedFiles(ctx context.Context, arg ListSharedFilesParams) ([]SharedFile, error)
	ListSystemLogs(ctx context.Context, arg ListSystemLogsParams) ([]SystemLog, error)
	ListTaskTraces(ctx context.Context, arg ListTaskTracesParams) ([]TaskTrace, error)
	ListUIPreferences(ctx context.Context, dollar_1 string) ([]ListUIPreferencesRow, error)
	// Used on scheduler boot for crash recovery: any run stuck in submitting /
	// submitted / running must be re-entered through Observe / LookupByDedupeKey
	// instead of StartTurn, per the three-phase protocol.
	ListUnresolvedCronJobRuns(ctx context.Context) ([]CronJobRun, error)
	ListWorkspaceRunFiles(ctx context.Context, arg ListWorkspaceRunFilesParams) ([]WorkspaceRunFile, error)
	ListWorkspaceRuns(ctx context.Context, arg ListWorkspaceRunsParams) ([]WorkspaceRun, error)
	LoadAgentThreadPromptSnapshot(ctx context.Context, threadID string) ([]byte, error)
	LookupSkillCandidateApproval(ctx context.Context, arg LookupSkillCandidateApprovalParams) (SkillCandidate, error)
	MarkCronJobFailed(ctx context.Context, arg MarkCronJobFailedParams) (int64, error)
	// MarkCronJobFinished releases the claim, records the successful run's
	// turn id and advances scheduling fields. Conditional on claim_token so
	// a late worker cannot overwrite terminal state after being preempted.
	//
	MarkCronJobFinished(ctx context.Context, arg MarkCronJobFinishedParams) (int64, error)
	MarkSkillCandidatePromoted(ctx context.Context, id int64) (SkillCandidate, error)
	MarkSkillCandidatesSuperseded(ctx context.Context, arg MarkSkillCandidatesSupersededParams) (int64, error)
	MarkTurnDedupeTerminal(ctx context.Context, arg MarkTurnDedupeTerminalParams) error
	// Narrow update used by RunOnce: only touches next_run_at + updated_at
	// without overwriting any other field, avoiding a read-modify-write race.
	PatchCronJobNextRunAt(ctx context.Context, arg PatchCronJobNextRunAtParams) error
	// Runtime SQL template from V2 DBQueryStore.Query:
	// WITH q AS (<runtime read-only SQL>) SELECT * FROM q LIMIT $1;
	// A true sqlc query cannot represent a runtime-supplied SELECT shape, so this
	// file keeps a typed placeholder until sqlc generation is introduced.
	PlaceholderDBQuery(ctx context.Context) ([]*string, error)
	RebindAgentThreadTx(ctx context.Context, arg RebindAgentThreadTxParams) error
	RejectSkillCandidate(ctx context.Context, arg RejectSkillCandidateParams) (SkillCandidate, error)
	RejectTopologyApproval(ctx context.Context, arg RejectTopologyApprovalParams) (int64, error)
	ReleaseClaim(ctx context.Context, arg ReleaseClaimParams) (int64, error)
	ReleaseCwdLock(ctx context.Context, arg ReleaseCwdLockParams) (int64, error)
	RenewLease(ctx context.Context, arg RenewLeaseParams) (int64, error)
	ResetRunningAgentThreads(ctx context.Context) error
	ReviewInteraction(ctx context.Context, arg ReviewInteractionParams) (AgentInteraction, error)
	UpdateAgentThreadPromptSnapshot(ctx context.Context, arg UpdateAgentThreadPromptSnapshotParams) (int64, error)
	SetCronJobActiveTurn(ctx context.Context, arg SetCronJobActiveTurnParams) (int64, error)
	SetCronJobEnabled(ctx context.Context, arg SetCronJobEnabledParams) error
	SetCronJobRunTurn(ctx context.Context, arg SetCronJobRunTurnParams) (int64, error)
	// Deletes every row whose updated_at is older than cutoff. Run on a
	// coarse interval by the scheduler so the table can never outgrow
	// the tracker TTL window.
	SweepTurnDedupeRegistry(ctx context.Context, cutoff pgtype.Timestamptz) error
	TransitionWorkspaceRunStatus(ctx context.Context, arg TransitionWorkspaceRunStatusParams) (WorkspaceRun, error)
	UnbindAgentThread(ctx context.Context, agentID string) error
	UpdateAgentCwd(ctx context.Context, arg UpdateAgentCwdParams) error
	UpdateAgentProviderBindingArchived(ctx context.Context, arg UpdateAgentProviderBindingArchivedParams) error
	UpdateAgentProviderBindingSessionUUID(ctx context.Context, arg UpdateAgentProviderBindingSessionUUIDParams) error
	// Atomically clears pending_launch and stamps the router decision after the
	// Claude CLI has been spawned for this thread.
	UpdateAgentThreadLaunchResult(ctx context.Context, arg UpdateAgentThreadLaunchResultParams) error
	UpdateAgentThreadStatus(ctx context.Context, arg UpdateAgentThreadStatusParams) error
	UpdateCronJobSchedule(ctx context.Context, arg UpdateCronJobScheduleParams) error
	UpdateWorkspaceRunStatus(ctx context.Context, arg UpdateWorkspaceRunStatusParams) (WorkspaceRun, error)
	// Codex identity columns use "'' preserves existing value" semantics so
	// non-P1a callers that pass '' do not overwrite an already-persisted
	// identity. The immutable trigger still rejects any attempt to rewrite a
	// non-empty identity column with a different non-empty value.
	UpsertAgentProviderBinding(ctx context.Context, arg UpsertAgentProviderBindingParams) error
	UpsertAgentStatus(ctx context.Context, arg UpsertAgentStatusParams) (AgentStatus, error)
	UpsertAgentThread(ctx context.Context, arg UpsertAgentThreadParams) error
	UpsertCommandCard(ctx context.Context, arg UpsertCommandCardParams) (CommandCard, error)
	UpsertPromptTemplate(ctx context.Context, arg UpsertPromptTemplateParams) (UpsertPromptTemplateRow, error)
	// Upsert by (template_id, section_key). Touches updated_at on conflict so
	// operators see when they last edited a row. Empty enable_when stays as-is
	// (NULL or '{}' both mean "always inject" per EvaluateEnableWhen).
	UpsertPromptTemplateSection(ctx context.Context, arg UpsertPromptTemplateSectionParams) (PromptTemplateSection, error)
	// UpsertSessionInsight merges an incoming snapshot with any existing row
	// keyed by (thread_id, local_turn_id). The update clause encodes two
	// invariants the P3 plan requires at the SQL layer:
	//
	//  * terminal precedence: once status is 'interrupted' or 'aborted', a
	//    later 'completed'/'failed' must not displace it. success is
	//    likewise frozen once the locked terminal is set.
	//  * token no-regression: counters only advance. A context-window-only
	//    event with zero counts cannot regress token_input / token_output /
	//    token_total. Scalar GREATEST is per-field so a legitimate zero
	//    event for one dimension does not zero out a sibling.
	//
	// The *_observed flags go sticky: once TRUE, no later event can flip
	// them back to FALSE. This keeps "we already saw real data" from being
	// clobbered by a projection that doesn't re-emit the signal.
	//
	UpsertSessionInsight(ctx context.Context, arg UpsertSessionInsightParams) (SessionInsight, error)
	UpsertSharedFile(ctx context.Context, arg UpsertSharedFileParams) (SharedFile, error)
	// Queries for turn_dedupe_registry. See migration 0060 for the table
	// layout + lifetime contract.
	UpsertTurnDedupeRegistry(ctx context.Context, arg UpsertTurnDedupeRegistryParams) error
	UpsertUIPreference(ctx context.Context, arg UpsertUIPreferenceParams) error
	UpsertWorkspaceRun(ctx context.Context, arg UpsertWorkspaceRunParams) (WorkspaceRun, error)
	UpsertWorkspaceRunFile(ctx context.Context, arg UpsertWorkspaceRunFileParams) (WorkspaceRunFile, error)
}

var _ Querier = (*Queries)(nil)
