// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: task_trace.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertTaskTrace = `-- name: InsertTaskTrace :one
INSERT INTO task_traces (
    trace_id, span_id, parent_span_id, span_name, component,
    input_payload, output_payload, status, error_text, duration_ms, metadata, started_at, finished_at
) VALUES ($1, $2, $3, $4, $5, $6::jsonb, $7::jsonb, $8, $9, $10, $11::jsonb, NOW(), NULL)
RETURNING id, trace_id, span_id, parent_span_id, span_name, component, status, input_payload, output_payload, error_text, metadata, started_at, finished_at, duration_ms
`

type InsertTaskTraceParams struct {
	TraceID      string `db:"trace_id" json:"trace_id"`
	SpanID       string `db:"span_id" json:"span_id"`
	ParentSpanID string `db:"parent_span_id" json:"parent_span_id"`
	SpanName     string `db:"span_name" json:"span_name"`
	Component    string `db:"component" json:"component"`
	Column6      []byte `db:"column_6" json:"column_6"`
	Column7      []byte `db:"column_7" json:"column_7"`
	Status       string `db:"status" json:"status"`
	ErrorText    string `db:"error_text" json:"error_text"`
	DurationMs   int32  `db:"duration_ms" json:"duration_ms"`
	Column11     []byte `db:"column_11" json:"column_11"`
}

func (q *Queries) InsertTaskTrace(ctx context.Context, arg InsertTaskTraceParams) (TaskTrace, error) {
	row := q.db.QueryRow(ctx, insertTaskTrace,
		arg.TraceID,
		arg.SpanID,
		arg.ParentSpanID,
		arg.SpanName,
		arg.Component,
		arg.Column6,
		arg.Column7,
		arg.Status,
		arg.ErrorText,
		arg.DurationMs,
		arg.Column11,
	)
	var i TaskTrace
	err := row.Scan(
		&i.ID,
		&i.TraceID,
		&i.SpanID,
		&i.ParentSpanID,
		&i.SpanName,
		&i.Component,
		&i.Status,
		&i.InputPayload,
		&i.OutputPayload,
		&i.ErrorText,
		&i.Metadata,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
	)
	return i, err
}

const listTaskTraces = `-- name: ListTaskTraces :many
SELECT id, trace_id, span_id, parent_span_id, span_name, component, status, input_payload, output_payload, error_text, metadata, started_at, finished_at, duration_ms
FROM task_traces
WHERE ($1::text = '' OR component = $1)
  AND ($2::timestamptz IS NULL OR started_at >= $2)
  AND ($3::text = ''
    OR span_name ILIKE '%' || $3 || '%'
    OR status ILIKE '%' || $3 || '%')
ORDER BY started_at DESC
LIMIT $4
`

type ListTaskTracesParams struct {
	Column1 string             `db:"column_1" json:"column_1"`
	Column2 pgtype.Timestamptz `db:"column_2" json:"column_2"`
	Column3 string             `db:"column_3" json:"column_3"`
	Limit   int32              `db:"limit" json:"limit"`
}

func (q *Queries) ListTaskTraces(ctx context.Context, arg ListTaskTracesParams) ([]TaskTrace, error) {
	rows, err := q.db.Query(ctx, listTaskTraces,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskTrace{}
	for rows.Next() {
		var i TaskTrace
		if err := rows.Scan(
			&i.ID,
			&i.TraceID,
			&i.SpanID,
			&i.ParentSpanID,
			&i.SpanName,
			&i.Component,
			&i.Status,
			&i.InputPayload,
			&i.OutputPayload,
			&i.ErrorText,
			&i.Metadata,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
