// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_dag.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireTaskDagWorkerLease = `-- name: AcquireTaskDagWorkerLease :execrows
INSERT INTO task_dag_worker_leases (target_agent_id, owner_id, lease_expires_at, updated_at)
VALUES ($1, $2, NOW() + $3::interval, NOW())
ON CONFLICT (target_agent_id) DO UPDATE
SET owner_id = EXCLUDED.owner_id,
    lease_expires_at = EXCLUDED.lease_expires_at,
    updated_at = NOW()
WHERE task_dag_worker_leases.lease_expires_at < NOW()
   OR task_dag_worker_leases.owner_id = EXCLUDED.owner_id
`

type AcquireTaskDagWorkerLeaseParams struct {
	TargetAgentID string          `db:"target_agent_id" json:"target_agent_id"`
	OwnerID       string          `db:"owner_id" json:"owner_id"`
	Column3       pgtype.Interval `db:"column_3" json:"column_3"`
}

func (q *Queries) AcquireTaskDagWorkerLease(ctx context.Context, arg AcquireTaskDagWorkerLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, acquireTaskDagWorkerLease, arg.TargetAgentID, arg.OwnerID, arg.Column3)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const bindRunningTaskDagNodeTurn = `-- name: BindRunningTaskDagNodeTurn :one
UPDATE task_dag_nodes
SET active_turn_id = $1,
    last_event_at = NOW(),
    updated_at = NOW()
WHERE dag_key = $2
  AND node_key = $3
  AND status = 'running'
  AND active_turn_id IS NULL
  AND active_wakeup_id = $4
RETURNING id, dag_key, node_key, title, node_type, assigned_to, depends_on, status, command_ref, config, result, started_at, finished_at, created_at, updated_at, active_turn_id, active_wakeup_id, last_event_at
`

type BindRunningTaskDagNodeTurnParams struct {
	ActiveTurnID   *string `db:"active_turn_id" json:"active_turn_id"`
	DagKey         string  `db:"dag_key" json:"dag_key"`
	NodeKey        string  `db:"node_key" json:"node_key"`
	ActiveWakeupID *int64  `db:"active_wakeup_id" json:"active_wakeup_id"`
}

func (q *Queries) BindRunningTaskDagNodeTurn(ctx context.Context, arg BindRunningTaskDagNodeTurnParams) (TaskDagNode, error) {
	row := q.db.QueryRow(ctx, bindRunningTaskDagNodeTurn,
		arg.ActiveTurnID,
		arg.DagKey,
		arg.NodeKey,
		arg.ActiveWakeupID,
	)
	var i TaskDagNode
	err := row.Scan(
		&i.ID,
		&i.DagKey,
		&i.NodeKey,
		&i.Title,
		&i.NodeType,
		&i.AssignedTo,
		&i.DependsOn,
		&i.Status,
		&i.CommandRef,
		&i.Config,
		&i.Result,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveTurnID,
		&i.ActiveWakeupID,
		&i.LastEventAt,
	)
	return i, err
}

const bindTaskDagWakeupTurn = `-- name: BindTaskDagWakeupTurn :execrows
UPDATE task_dag_wakeups
SET bound_turn_id = $1, turn_bound_at = NOW(), updated_at = NOW()
WHERE id = $2 AND status = 'sent' AND sent_at IS NOT NULL AND bound_turn_id IS NULL
`

type BindTaskDagWakeupTurnParams struct {
	BoundTurnID *string `db:"bound_turn_id" json:"bound_turn_id"`
	ID          int64   `db:"id" json:"id"`
}

func (q *Queries) BindTaskDagWakeupTurn(ctx context.Context, arg BindTaskDagWakeupTurnParams) (int64, error) {
	result, err := q.db.Exec(ctx, bindTaskDagWakeupTurn, arg.BoundTurnID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimDueTaskDagWakeups = `-- name: ClaimDueTaskDagWakeups :many
UPDATE task_dag_wakeups
SET status = 'dispatching', claimed_at = NOW(), claimed_by = $1,
    lease_expires_at = NOW() + $2::interval, attempt_count = attempt_count + 1, updated_at = NOW()
WHERE id IN (
    SELECT id
    FROM task_dag_wakeups
    WHERE status = 'pending' AND next_retry_at <= NOW()
    ORDER BY next_retry_at, id
    LIMIT $3
    FOR UPDATE SKIP LOCKED
)
RETURNING id, dag_key, node_key, wakeup_kind, target_agent_id, prompt_payload, idempotency_key, status, attempt_count, next_retry_at, claimed_at, claimed_by, lease_expires_at, sent_at, bound_turn_id, turn_bound_at, last_error, created_at, updated_at
`

type ClaimDueTaskDagWakeupsParams struct {
	ClaimedBy string          `db:"claimed_by" json:"claimed_by"`
	Column2   pgtype.Interval `db:"column_2" json:"column_2"`
	Limit     int32           `db:"limit" json:"limit"`
}

func (q *Queries) ClaimDueTaskDagWakeups(ctx context.Context, arg ClaimDueTaskDagWakeupsParams) ([]TaskDagWakeup, error) {
	rows, err := q.db.Query(ctx, claimDueTaskDagWakeups, arg.ClaimedBy, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskDagWakeup{}
	for rows.Next() {
		var i TaskDagWakeup
		if err := rows.Scan(
			&i.ID,
			&i.DagKey,
			&i.NodeKey,
			&i.WakeupKind,
			&i.TargetAgentID,
			&i.PromptPayload,
			&i.IdempotencyKey,
			&i.Status,
			&i.AttemptCount,
			&i.NextRetryAt,
			&i.ClaimedAt,
			&i.ClaimedBy,
			&i.LeaseExpiresAt,
			&i.SentAt,
			&i.BoundTurnID,
			&i.TurnBoundAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeTaskDagNode = `-- name: CompleteTaskDagNode :one
UPDATE task_dag_nodes
SET status = $1, result = $2::jsonb, active_turn_id = NULL, active_wakeup_id = NULL,
    finished_at = COALESCE(finished_at, NOW()), updated_at = NOW()
WHERE dag_key = $3 AND node_key = $4 AND status IN ('running', 'awaiting_verify')
RETURNING id, dag_key, node_key, title, node_type, assigned_to, depends_on, status, command_ref, config, result, started_at, finished_at, created_at, updated_at, active_turn_id, active_wakeup_id, last_event_at
`

type CompleteTaskDagNodeParams struct {
	Status  string `db:"status" json:"status"`
	Column2 []byte `db:"column_2" json:"column_2"`
	DagKey  string `db:"dag_key" json:"dag_key"`
	NodeKey string `db:"node_key" json:"node_key"`
}

func (q *Queries) CompleteTaskDagNode(ctx context.Context, arg CompleteTaskDagNodeParams) (TaskDagNode, error) {
	row := q.db.QueryRow(ctx, completeTaskDagNode,
		arg.Status,
		arg.Column2,
		arg.DagKey,
		arg.NodeKey,
	)
	var i TaskDagNode
	err := row.Scan(
		&i.ID,
		&i.DagKey,
		&i.NodeKey,
		&i.Title,
		&i.NodeType,
		&i.AssignedTo,
		&i.DependsOn,
		&i.Status,
		&i.CommandRef,
		&i.Config,
		&i.Result,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveTurnID,
		&i.ActiveWakeupID,
		&i.LastEventAt,
	)
	return i, err
}

const enqueueTaskDagWakeup = `-- name: EnqueueTaskDagWakeup :execrows
INSERT INTO task_dag_wakeups (dag_key, node_key, wakeup_kind, target_agent_id, prompt_payload, idempotency_key)
VALUES ($1, $2, $3, $4, $5::jsonb, $6)
ON CONFLICT (idempotency_key) DO NOTHING
`

type EnqueueTaskDagWakeupParams struct {
	DagKey         string `db:"dag_key" json:"dag_key"`
	NodeKey        string `db:"node_key" json:"node_key"`
	WakeupKind     string `db:"wakeup_kind" json:"wakeup_kind"`
	TargetAgentID  string `db:"target_agent_id" json:"target_agent_id"`
	Column5        []byte `db:"column_5" json:"column_5"`
	IdempotencyKey string `db:"idempotency_key" json:"idempotency_key"`
}

func (q *Queries) EnqueueTaskDagWakeup(ctx context.Context, arg EnqueueTaskDagWakeupParams) (int64, error) {
	result, err := q.db.Exec(ctx, enqueueTaskDagWakeup,
		arg.DagKey,
		arg.NodeKey,
		arg.WakeupKind,
		arg.TargetAgentID,
		arg.Column5,
		arg.IdempotencyKey,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failTaskDagWakeup = `-- name: FailTaskDagWakeup :execrows
UPDATE task_dag_wakeups
SET status = 'failed', last_error = $1, claimed_at = NULL, claimed_by = '', lease_expires_at = NULL, updated_at = NOW()
WHERE id = $2 AND status = 'dispatching' AND claimed_at = $3
`

type FailTaskDagWakeupParams struct {
	LastError string             `db:"last_error" json:"last_error"`
	ID        int64              `db:"id" json:"id"`
	ClaimedAt pgtype.Timestamptz `db:"claimed_at" json:"claimed_at"`
}

func (q *Queries) FailTaskDagWakeup(ctx context.Context, arg FailTaskDagWakeupParams) (int64, error) {
	result, err := q.db.Exec(ctx, failTaskDagWakeup, arg.LastError, arg.ID, arg.ClaimedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTaskDag = `-- name: GetTaskDag :one
SELECT id, dag_key, title, description, status, created_by, metadata, started_at, finished_at, created_at, updated_at
FROM task_dags
WHERE dag_key = $1
`

func (q *Queries) GetTaskDag(ctx context.Context, dagKey string) (TaskDag, error) {
	row := q.db.QueryRow(ctx, getTaskDag, dagKey)
	var i TaskDag
	err := row.Scan(
		&i.ID,
		&i.DagKey,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedBy,
		&i.Metadata,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskDagForUpdate = `-- name: GetTaskDagForUpdate :one
SELECT id, dag_key, title, description, status, created_by, metadata, started_at, finished_at, created_at, updated_at
FROM task_dags
WHERE dag_key = $1
FOR UPDATE
`

func (q *Queries) GetTaskDagForUpdate(ctx context.Context, dagKey string) (TaskDag, error) {
	row := q.db.QueryRow(ctx, getTaskDagForUpdate, dagKey)
	var i TaskDag
	err := row.Scan(
		&i.ID,
		&i.DagKey,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedBy,
		&i.Metadata,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskDagNodesForUpdate = `-- name: GetTaskDagNodesForUpdate :many
SELECT id, dag_key, node_key, title, node_type, assigned_to, depends_on, status, command_ref, config, result, started_at, finished_at, created_at, updated_at, active_turn_id, active_wakeup_id, last_event_at
FROM task_dag_nodes
WHERE dag_key = $1
ORDER BY created_at, id
FOR UPDATE
`

func (q *Queries) GetTaskDagNodesForUpdate(ctx context.Context, dagKey string) ([]TaskDagNode, error) {
	rows, err := q.db.Query(ctx, getTaskDagNodesForUpdate, dagKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskDagNode{}
	for rows.Next() {
		var i TaskDagNode
		if err := rows.Scan(
			&i.ID,
			&i.DagKey,
			&i.NodeKey,
			&i.Title,
			&i.NodeType,
			&i.AssignedTo,
			&i.DependsOn,
			&i.Status,
			&i.CommandRef,
			&i.Config,
			&i.Result,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ActiveTurnID,
			&i.ActiveWakeupID,
			&i.LastEventAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskDagWakeup = `-- name: GetTaskDagWakeup :one
SELECT id, dag_key, node_key, wakeup_kind, target_agent_id, prompt_payload, idempotency_key, status, attempt_count, next_retry_at, claimed_at, claimed_by, lease_expires_at, sent_at, bound_turn_id, turn_bound_at, last_error, created_at, updated_at
FROM task_dag_wakeups
WHERE id = $1
`

func (q *Queries) GetTaskDagWakeup(ctx context.Context, id int64) (TaskDagWakeup, error) {
	row := q.db.QueryRow(ctx, getTaskDagWakeup, id)
	var i TaskDagWakeup
	err := row.Scan(
		&i.ID,
		&i.DagKey,
		&i.NodeKey,
		&i.WakeupKind,
		&i.TargetAgentID,
		&i.PromptPayload,
		&i.IdempotencyKey,
		&i.Status,
		&i.AttemptCount,
		&i.NextRetryAt,
		&i.ClaimedAt,
		&i.ClaimedBy,
		&i.LeaseExpiresAt,
		&i.SentAt,
		&i.BoundTurnID,
		&i.TurnBoundAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingOrDispatchingTaskDagWakeups = `-- name: ListPendingOrDispatchingTaskDagWakeups :many
SELECT id, dag_key, node_key, wakeup_kind, target_agent_id, prompt_payload, idempotency_key, status, attempt_count, next_retry_at, claimed_at, claimed_by, lease_expires_at, sent_at, bound_turn_id, turn_bound_at, last_error, created_at, updated_at
FROM task_dag_wakeups
WHERE status IN ('pending', 'dispatching')
ORDER BY next_retry_at, id
`

func (q *Queries) ListPendingOrDispatchingTaskDagWakeups(ctx context.Context) ([]TaskDagWakeup, error) {
	rows, err := q.db.Query(ctx, listPendingOrDispatchingTaskDagWakeups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskDagWakeup{}
	for rows.Next() {
		var i TaskDagWakeup
		if err := rows.Scan(
			&i.ID,
			&i.DagKey,
			&i.NodeKey,
			&i.WakeupKind,
			&i.TargetAgentID,
			&i.PromptPayload,
			&i.IdempotencyKey,
			&i.Status,
			&i.AttemptCount,
			&i.NextRetryAt,
			&i.ClaimedAt,
			&i.ClaimedBy,
			&i.LeaseExpiresAt,
			&i.SentAt,
			&i.BoundTurnID,
			&i.TurnBoundAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunningTaskDagNodesByAssignee = `-- name: ListRunningTaskDagNodesByAssignee :many
SELECT id, dag_key, node_key, title, node_type, assigned_to, depends_on, status, command_ref, config, result, started_at, finished_at, created_at, updated_at, active_turn_id, active_wakeup_id, last_event_at
FROM task_dag_nodes
WHERE assigned_to = $1 AND status = 'running'
ORDER BY created_at
`

func (q *Queries) ListRunningTaskDagNodesByAssignee(ctx context.Context, assignedTo string) ([]TaskDagNode, error) {
	rows, err := q.db.Query(ctx, listRunningTaskDagNodesByAssignee, assignedTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskDagNode{}
	for rows.Next() {
		var i TaskDagNode
		if err := rows.Scan(
			&i.ID,
			&i.DagKey,
			&i.NodeKey,
			&i.Title,
			&i.NodeType,
			&i.AssignedTo,
			&i.DependsOn,
			&i.Status,
			&i.CommandRef,
			&i.Config,
			&i.Result,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ActiveTurnID,
			&i.ActiveWakeupID,
			&i.LastEventAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSentUnboundTaskDagWakeups = `-- name: ListSentUnboundTaskDagWakeups :many
SELECT id, dag_key, node_key, wakeup_kind, target_agent_id, prompt_payload, idempotency_key, status, attempt_count, next_retry_at, claimed_at, claimed_by, lease_expires_at, sent_at, bound_turn_id, turn_bound_at, last_error, created_at, updated_at
FROM task_dag_wakeups
WHERE target_agent_id = $1 AND status = 'sent' AND sent_at IS NOT NULL AND bound_turn_id IS NULL
ORDER BY sent_at DESC, id DESC
`

func (q *Queries) ListSentUnboundTaskDagWakeups(ctx context.Context, targetAgentID string) ([]TaskDagWakeup, error) {
	rows, err := q.db.Query(ctx, listSentUnboundTaskDagWakeups, targetAgentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskDagWakeup{}
	for rows.Next() {
		var i TaskDagWakeup
		if err := rows.Scan(
			&i.ID,
			&i.DagKey,
			&i.NodeKey,
			&i.WakeupKind,
			&i.TargetAgentID,
			&i.PromptPayload,
			&i.IdempotencyKey,
			&i.Status,
			&i.AttemptCount,
			&i.NextRetryAt,
			&i.ClaimedAt,
			&i.ClaimedBy,
			&i.LeaseExpiresAt,
			&i.SentAt,
			&i.BoundTurnID,
			&i.TurnBoundAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskDagNodes = `-- name: ListTaskDagNodes :many
SELECT id, dag_key, node_key, title, node_type, assigned_to, depends_on, status, command_ref, config, result, started_at, finished_at, created_at, updated_at, active_turn_id, active_wakeup_id, last_event_at
FROM task_dag_nodes
WHERE dag_key = $1
ORDER BY created_at
`

func (q *Queries) ListTaskDagNodes(ctx context.Context, dagKey string) ([]TaskDagNode, error) {
	rows, err := q.db.Query(ctx, listTaskDagNodes, dagKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskDagNode{}
	for rows.Next() {
		var i TaskDagNode
		if err := rows.Scan(
			&i.ID,
			&i.DagKey,
			&i.NodeKey,
			&i.Title,
			&i.NodeType,
			&i.AssignedTo,
			&i.DependsOn,
			&i.Status,
			&i.CommandRef,
			&i.Config,
			&i.Result,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ActiveTurnID,
			&i.ActiveWakeupID,
			&i.LastEventAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskDags = `-- name: ListTaskDags :many
SELECT id, dag_key, title, description, status, created_by, metadata, started_at, finished_at, created_at, updated_at
FROM task_dags
WHERE ($1::text = '' OR status = $1)
  AND ($2::text = ''
    OR dag_key ILIKE '%' || $2 || '%'
    OR title ILIKE '%' || $2 || '%'
    OR description ILIKE '%' || $2 || '%')
ORDER BY updated_at DESC, id DESC
LIMIT $3
`

type ListTaskDagsParams struct {
	Column1 string `db:"column_1" json:"column_1"`
	Column2 string `db:"column_2" json:"column_2"`
	Limit   int32  `db:"limit" json:"limit"`
}

func (q *Queries) ListTaskDags(ctx context.Context, arg ListTaskDagsParams) ([]TaskDag, error) {
	rows, err := q.db.Query(ctx, listTaskDags, arg.Column1, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskDag{}
	for rows.Next() {
		var i TaskDag
		if err := rows.Scan(
			&i.ID,
			&i.DagKey,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedBy,
			&i.Metadata,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTaskDagWakeupSent = `-- name: MarkTaskDagWakeupSent :execrows
UPDATE task_dag_wakeups
SET status = 'sent', sent_at = NOW(), updated_at = NOW()
WHERE id = $1 AND status = 'dispatching' AND claimed_at = $2
`

type MarkTaskDagWakeupSentParams struct {
	ID        int64              `db:"id" json:"id"`
	ClaimedAt pgtype.Timestamptz `db:"claimed_at" json:"claimed_at"`
}

func (q *Queries) MarkTaskDagWakeupSent(ctx context.Context, arg MarkTaskDagWakeupSentParams) (int64, error) {
	result, err := q.db.Exec(ctx, markTaskDagWakeupSent, arg.ID, arg.ClaimedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reclaimStaleDispatchingTaskDagWakeups = `-- name: ReclaimStaleDispatchingTaskDagWakeups :execrows
UPDATE task_dag_wakeups
SET status = 'pending', claimed_at = NULL, claimed_by = '', lease_expires_at = NULL, updated_at = NOW()
WHERE status = 'dispatching' AND lease_expires_at < NOW()
`

func (q *Queries) ReclaimStaleDispatchingTaskDagWakeups(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, reclaimStaleDispatchingTaskDagWakeups)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseTaskDagWorkerLease = `-- name: ReleaseTaskDagWorkerLease :exec
DELETE FROM task_dag_worker_leases
WHERE target_agent_id = $1 AND owner_id = $2
`

type ReleaseTaskDagWorkerLeaseParams struct {
	TargetAgentID string `db:"target_agent_id" json:"target_agent_id"`
	OwnerID       string `db:"owner_id" json:"owner_id"`
}

func (q *Queries) ReleaseTaskDagWorkerLease(ctx context.Context, arg ReleaseTaskDagWorkerLeaseParams) error {
	_, err := q.db.Exec(ctx, releaseTaskDagWorkerLease, arg.TargetAgentID, arg.OwnerID)
	return err
}

const renewTaskDagWorkerLease = `-- name: RenewTaskDagWorkerLease :execrows
UPDATE task_dag_worker_leases
SET lease_expires_at = NOW() + $1::interval,
    updated_at = NOW()
WHERE target_agent_id = $2 AND owner_id = $3 AND lease_expires_at >= NOW()
`

type RenewTaskDagWorkerLeaseParams struct {
	Column1       pgtype.Interval `db:"column_1" json:"column_1"`
	TargetAgentID string          `db:"target_agent_id" json:"target_agent_id"`
	OwnerID       string          `db:"owner_id" json:"owner_id"`
}

func (q *Queries) RenewTaskDagWorkerLease(ctx context.Context, arg RenewTaskDagWorkerLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, renewTaskDagWorkerLease, arg.Column1, arg.TargetAgentID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retryTaskDagWakeup = `-- name: RetryTaskDagWakeup :execrows
UPDATE task_dag_wakeups
SET status = 'pending', next_retry_at = NOW() + $1::interval, last_error = $2,
    claimed_at = NULL, claimed_by = '', lease_expires_at = NULL, updated_at = NOW()
WHERE id = $3 AND status = 'dispatching' AND claimed_at = $4 AND attempt_count < 8
`

type RetryTaskDagWakeupParams struct {
	Column1   pgtype.Interval    `db:"column_1" json:"column_1"`
	LastError string             `db:"last_error" json:"last_error"`
	ID        int64              `db:"id" json:"id"`
	ClaimedAt pgtype.Timestamptz `db:"claimed_at" json:"claimed_at"`
}

func (q *Queries) RetryTaskDagWakeup(ctx context.Context, arg RetryTaskDagWakeupParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryTaskDagWakeup,
		arg.Column1,
		arg.LastError,
		arg.ID,
		arg.ClaimedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchRunningTaskDagNodeEvent = `-- name: TouchRunningTaskDagNodeEvent :one
UPDATE task_dag_nodes
SET last_event_at = $1,
    updated_at = NOW()
WHERE dag_key = $2
  AND node_key = $3
  AND status = 'running'
  AND active_turn_id = $4
  AND (last_event_at IS NULL OR last_event_at < $1)
RETURNING id, dag_key, node_key, title, node_type, assigned_to, depends_on, status, command_ref, config, result, started_at, finished_at, created_at, updated_at, active_turn_id, active_wakeup_id, last_event_at
`

type TouchRunningTaskDagNodeEventParams struct {
	LastEventAt  pgtype.Timestamptz `db:"last_event_at" json:"last_event_at"`
	DagKey       string             `db:"dag_key" json:"dag_key"`
	NodeKey      string             `db:"node_key" json:"node_key"`
	ActiveTurnID *string            `db:"active_turn_id" json:"active_turn_id"`
}

func (q *Queries) TouchRunningTaskDagNodeEvent(ctx context.Context, arg TouchRunningTaskDagNodeEventParams) (TaskDagNode, error) {
	row := q.db.QueryRow(ctx, touchRunningTaskDagNodeEvent,
		arg.LastEventAt,
		arg.DagKey,
		arg.NodeKey,
		arg.ActiveTurnID,
	)
	var i TaskDagNode
	err := row.Scan(
		&i.ID,
		&i.DagKey,
		&i.NodeKey,
		&i.Title,
		&i.NodeType,
		&i.AssignedTo,
		&i.DependsOn,
		&i.Status,
		&i.CommandRef,
		&i.Config,
		&i.Result,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveTurnID,
		&i.ActiveWakeupID,
		&i.LastEventAt,
	)
	return i, err
}

const updateAwaitingVerifyTaskDagNodeStatus = `-- name: UpdateAwaitingVerifyTaskDagNodeStatus :one
UPDATE task_dag_nodes
SET status = $1, result = $2::jsonb, active_turn_id = NULL, active_wakeup_id = NULL, updated_at = NOW()
WHERE dag_key = $3 AND node_key = $4 AND status IN ('running')
RETURNING id, dag_key, node_key, title, node_type, assigned_to, depends_on, status, command_ref, config, result, started_at, finished_at, created_at, updated_at, active_turn_id, active_wakeup_id, last_event_at
`

type UpdateAwaitingVerifyTaskDagNodeStatusParams struct {
	Status  string `db:"status" json:"status"`
	Column2 []byte `db:"column_2" json:"column_2"`
	DagKey  string `db:"dag_key" json:"dag_key"`
	NodeKey string `db:"node_key" json:"node_key"`
}

func (q *Queries) UpdateAwaitingVerifyTaskDagNodeStatus(ctx context.Context, arg UpdateAwaitingVerifyTaskDagNodeStatusParams) (TaskDagNode, error) {
	row := q.db.QueryRow(ctx, updateAwaitingVerifyTaskDagNodeStatus,
		arg.Status,
		arg.Column2,
		arg.DagKey,
		arg.NodeKey,
	)
	var i TaskDagNode
	err := row.Scan(
		&i.ID,
		&i.DagKey,
		&i.NodeKey,
		&i.Title,
		&i.NodeType,
		&i.AssignedTo,
		&i.DependsOn,
		&i.Status,
		&i.CommandRef,
		&i.Config,
		&i.Result,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveTurnID,
		&i.ActiveWakeupID,
		&i.LastEventAt,
	)
	return i, err
}

const updateRunningTaskDagNodeStatus = `-- name: UpdateRunningTaskDagNodeStatus :one
UPDATE task_dag_nodes
SET status = $1, result = $2::jsonb, active_turn_id = NULL, active_wakeup_id = $3,
    last_event_at = NULL, started_at = COALESCE(started_at, NOW()), updated_at = NOW()
WHERE dag_key = $4 AND node_key = $5 AND status IN ('pending')
RETURNING id, dag_key, node_key, title, node_type, assigned_to, depends_on, status, command_ref, config, result, started_at, finished_at, created_at, updated_at, active_turn_id, active_wakeup_id, last_event_at
`

type UpdateRunningTaskDagNodeStatusParams struct {
	Status         string `db:"status" json:"status"`
	Column2        []byte `db:"column_2" json:"column_2"`
	ActiveWakeupID *int64 `db:"active_wakeup_id" json:"active_wakeup_id"`
	DagKey         string `db:"dag_key" json:"dag_key"`
	NodeKey        string `db:"node_key" json:"node_key"`
}

func (q *Queries) UpdateRunningTaskDagNodeStatus(ctx context.Context, arg UpdateRunningTaskDagNodeStatusParams) (TaskDagNode, error) {
	row := q.db.QueryRow(ctx, updateRunningTaskDagNodeStatus,
		arg.Status,
		arg.Column2,
		arg.ActiveWakeupID,
		arg.DagKey,
		arg.NodeKey,
	)
	var i TaskDagNode
	err := row.Scan(
		&i.ID,
		&i.DagKey,
		&i.NodeKey,
		&i.Title,
		&i.NodeType,
		&i.AssignedTo,
		&i.DependsOn,
		&i.Status,
		&i.CommandRef,
		&i.Config,
		&i.Result,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveTurnID,
		&i.ActiveWakeupID,
		&i.LastEventAt,
	)
	return i, err
}

const updateTaskDagNodeStatus = `-- name: UpdateTaskDagNodeStatus :one
UPDATE task_dag_nodes
SET status = $1,
    result = $2::jsonb,
    updated_at = NOW()
WHERE dag_key = $3 AND node_key = $4
RETURNING id, dag_key, node_key, title, node_type, assigned_to, depends_on, status, command_ref, config, result, started_at, finished_at, created_at, updated_at, active_turn_id, active_wakeup_id, last_event_at
`

type UpdateTaskDagNodeStatusParams struct {
	Status  string `db:"status" json:"status"`
	Column2 []byte `db:"column_2" json:"column_2"`
	DagKey  string `db:"dag_key" json:"dag_key"`
	NodeKey string `db:"node_key" json:"node_key"`
}

func (q *Queries) UpdateTaskDagNodeStatus(ctx context.Context, arg UpdateTaskDagNodeStatusParams) (TaskDagNode, error) {
	row := q.db.QueryRow(ctx, updateTaskDagNodeStatus,
		arg.Status,
		arg.Column2,
		arg.DagKey,
		arg.NodeKey,
	)
	var i TaskDagNode
	err := row.Scan(
		&i.ID,
		&i.DagKey,
		&i.NodeKey,
		&i.Title,
		&i.NodeType,
		&i.AssignedTo,
		&i.DependsOn,
		&i.Status,
		&i.CommandRef,
		&i.Config,
		&i.Result,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveTurnID,
		&i.ActiveWakeupID,
		&i.LastEventAt,
	)
	return i, err
}

const updateTaskDagNodeStatusFlexible = `-- name: UpdateTaskDagNodeStatusFlexible :one
UPDATE task_dag_nodes
SET status = $1, result = $2::jsonb, updated_at = NOW()
WHERE dag_key = $3 AND node_key = $4
RETURNING id, dag_key, node_key, title, node_type, assigned_to, depends_on, status, command_ref, config, result, started_at, finished_at, created_at, updated_at, active_turn_id, active_wakeup_id, last_event_at
`

type UpdateTaskDagNodeStatusFlexibleParams struct {
	Status  string `db:"status" json:"status"`
	Column2 []byte `db:"column_2" json:"column_2"`
	DagKey  string `db:"dag_key" json:"dag_key"`
	NodeKey string `db:"node_key" json:"node_key"`
}

func (q *Queries) UpdateTaskDagNodeStatusFlexible(ctx context.Context, arg UpdateTaskDagNodeStatusFlexibleParams) (TaskDagNode, error) {
	row := q.db.QueryRow(ctx, updateTaskDagNodeStatusFlexible,
		arg.Status,
		arg.Column2,
		arg.DagKey,
		arg.NodeKey,
	)
	var i TaskDagNode
	err := row.Scan(
		&i.ID,
		&i.DagKey,
		&i.NodeKey,
		&i.Title,
		&i.NodeType,
		&i.AssignedTo,
		&i.DependsOn,
		&i.Status,
		&i.CommandRef,
		&i.Config,
		&i.Result,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveTurnID,
		&i.ActiveWakeupID,
		&i.LastEventAt,
	)
	return i, err
}

const upsertTaskDag = `-- name: UpsertTaskDag :one
INSERT INTO task_dags (dag_key, title, description, status, created_by, metadata)
VALUES ($1, $2, $3, $4, $5, $6::jsonb)
ON CONFLICT (dag_key) DO UPDATE
SET title = EXCLUDED.title,
    description = EXCLUDED.description,
    status = EXCLUDED.status,
    created_by = EXCLUDED.created_by,
    metadata = EXCLUDED.metadata,
    updated_at = NOW()
RETURNING id, dag_key, title, description, status, created_by, metadata, started_at, finished_at, created_at, updated_at
`

type UpsertTaskDagParams struct {
	DagKey      string `db:"dag_key" json:"dag_key"`
	Title       string `db:"title" json:"title"`
	Description string `db:"description" json:"description"`
	Status      string `db:"status" json:"status"`
	CreatedBy   string `db:"created_by" json:"created_by"`
	Column6     []byte `db:"column_6" json:"column_6"`
}

func (q *Queries) UpsertTaskDag(ctx context.Context, arg UpsertTaskDagParams) (TaskDag, error) {
	row := q.db.QueryRow(ctx, upsertTaskDag,
		arg.DagKey,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.CreatedBy,
		arg.Column6,
	)
	var i TaskDag
	err := row.Scan(
		&i.ID,
		&i.DagKey,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedBy,
		&i.Metadata,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTaskDagNode = `-- name: UpsertTaskDagNode :one
INSERT INTO task_dag_nodes (dag_key, node_key, title, node_type, assigned_to, depends_on, command_ref, config)
VALUES ($1, $2, $3, $4, $5, $6::jsonb, $7, $8::jsonb)
ON CONFLICT (dag_key, node_key) DO UPDATE
SET title = EXCLUDED.title,
    node_type = EXCLUDED.node_type,
    assigned_to = EXCLUDED.assigned_to,
    depends_on = EXCLUDED.depends_on,
    command_ref = EXCLUDED.command_ref,
    config = EXCLUDED.config,
    updated_at = NOW()
RETURNING id, dag_key, node_key, title, node_type, assigned_to, depends_on, status, command_ref, config, result, started_at, finished_at, created_at, updated_at, active_turn_id, active_wakeup_id, last_event_at
`

type UpsertTaskDagNodeParams struct {
	DagKey     string `db:"dag_key" json:"dag_key"`
	NodeKey    string `db:"node_key" json:"node_key"`
	Title      string `db:"title" json:"title"`
	NodeType   string `db:"node_type" json:"node_type"`
	AssignedTo string `db:"assigned_to" json:"assigned_to"`
	Column6    []byte `db:"column_6" json:"column_6"`
	CommandRef string `db:"command_ref" json:"command_ref"`
	Column8    []byte `db:"column_8" json:"column_8"`
}

func (q *Queries) UpsertTaskDagNode(ctx context.Context, arg UpsertTaskDagNodeParams) (TaskDagNode, error) {
	row := q.db.QueryRow(ctx, upsertTaskDagNode,
		arg.DagKey,
		arg.NodeKey,
		arg.Title,
		arg.NodeType,
		arg.AssignedTo,
		arg.Column6,
		arg.CommandRef,
		arg.Column8,
	)
	var i TaskDagNode
	err := row.Scan(
		&i.ID,
		&i.DagKey,
		&i.NodeKey,
		&i.Title,
		&i.NodeType,
		&i.AssignedTo,
		&i.DependsOn,
		&i.Status,
		&i.CommandRef,
		&i.Config,
		&i.Result,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveTurnID,
		&i.ActiveWakeupID,
		&i.LastEventAt,
	)
	return i, err
}
