// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: thread_binding.sql

package sqlc

import (
	"context"
)

const bindAgentThread = `-- name: BindAgentThread :exec
INSERT INTO agent_provider_binding (
    agent_id,
    provider,
    provider_thread_id,
    codex_thread_id,
    rollout_path,
    cwd,
    parent_agent_id,
    agent_type,
    agent_memory_scope,
    archived,
    created_at,
    updated_at,
    session_uuid
) VALUES (
    ?1,
    'codex',
    ?2,
    ?2,
    '',
    ?3,
    '',
    '',
    '',
    false,
    ?4,
    ?5,
    ''
)
ON CONFLICT (agent_id) DO UPDATE
SET codex_thread_id = EXCLUDED.codex_thread_id,
    cwd = EXCLUDED.cwd,
    updated_at = EXCLUDED.updated_at
`

type BindAgentThreadParams struct {
	AgentID   string `db:"agent_id" json:"agent_id"`
	ThreadID  string `db:"thread_id" json:"thread_id"`
	CWD       string `db:"cwd" json:"cwd"`
	CreatedAt int64  `db:"created_at" json:"created_at"`
	UpdatedAt int64  `db:"updated_at" json:"updated_at"`
}

func (q *Queries) BindAgentThread(ctx context.Context, arg BindAgentThreadParams) error {
	_, err := q.db.ExecContext(ctx, bindAgentThread,
		arg.AgentID,
		arg.ThreadID,
		arg.CWD,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getThreadByAgent = `-- name: GetThreadByAgent :one
SELECT COALESCE(NULLIF(codex_thread_id, ''), provider_thread_id) AS thread_id
FROM agent_provider_binding
WHERE agent_id = ?
`

type GetThreadByAgentParams struct {
	AgentID string `db:"agent_id" json:"agent_id"`
}

func (q *Queries) GetThreadByAgent(ctx context.Context, arg GetThreadByAgentParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getThreadByAgent, arg.AgentID)
	var thread_id string
	err := row.Scan(&thread_id)
	return thread_id, err
}

const listAgentThreadBindings = `-- name: ListAgentThreadBindings :many
SELECT agent_id, provider, provider_thread_id, codex_thread_id, rollout_path, cwd, parent_agent_id, agent_type, agent_memory_scope, archived, created_at, updated_at, session_uuid, codex_home, codex_instance_key, codex_model_provider, provider_recovery_home
FROM agent_provider_binding
ORDER BY created_at DESC, agent_id DESC
`

func (q *Queries) ListAgentThreadBindings(ctx context.Context) ([]AgentProviderBinding, error) {
	rows, err := q.db.QueryContext(ctx, listAgentThreadBindings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentProviderBinding{}
	for rows.Next() {
		var i AgentProviderBinding
		if err := rows.Scan(
			&i.AgentID,
			&i.Provider,
			&i.ProviderThreadID,
			&i.CodexThreadID,
			&i.RolloutPath,
			&i.CWD,
			&i.ParentAgentID,
			&i.AgentType,
			&i.AgentMemoryScope,
			&i.Archived,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SessionUUID,
			&i.CodexHome,
			&i.CodexInstanceKey,
			&i.CodexModelProvider,
			&i.ProviderRecoveryHome,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rebindAgentThreadTx = `-- name: RebindAgentThreadTx :exec
INSERT INTO agent_provider_binding (
    agent_id, provider, provider_thread_id, codex_thread_id, rollout_path, cwd,
    parent_agent_id, agent_type, agent_memory_scope, archived, created_at, updated_at, session_uuid
)
VALUES (
    ?1, 'codex', ?2, ?2, '', ?3,
    '', '', '', false, ?4, ?5, ''
)
ON CONFLICT (agent_id) DO UPDATE
SET provider_thread_id = EXCLUDED.provider_thread_id,
    codex_thread_id    = EXCLUDED.codex_thread_id,
    cwd                = EXCLUDED.cwd,
    updated_at         = EXCLUDED.updated_at
`

type RebindAgentThreadTxParams struct {
	AgentID   string `db:"agent_id" json:"agent_id"`
	ThreadID  string `db:"thread_id" json:"thread_id"`
	CWD       string `db:"cwd" json:"cwd"`
	CreatedAt int64  `db:"created_at" json:"created_at"`
	UpdatedAt int64  `db:"updated_at" json:"updated_at"`
}

// SQLite does not support DML inside CTEs; Task rewrite: DELETE then INSERT.
// The Go layer wraps these in a transaction. This placeholder keeps the
// same query name so generated code compiles; real atomicity is in the Go tx.
func (q *Queries) RebindAgentThreadTx(ctx context.Context, arg RebindAgentThreadTxParams) error {
	_, err := q.db.ExecContext(ctx, rebindAgentThreadTx,
		arg.AgentID,
		arg.ThreadID,
		arg.CWD,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const unbindAgentThread = `-- name: UnbindAgentThread :exec
DELETE FROM agent_provider_binding
WHERE agent_id = ?
`

type UnbindAgentThreadParams struct {
	AgentID string `db:"agent_id" json:"agent_id"`
}

func (q *Queries) UnbindAgentThread(ctx context.Context, arg UnbindAgentThreadParams) error {
	_, err := q.db.ExecContext(ctx, unbindAgentThread, arg.AgentID)
	return err
}

const updateAgentCwd = `-- name: UpdateAgentCwd :exec
UPDATE agent_provider_binding
SET cwd = ?,
    updated_at = ?
WHERE agent_id = ?
`

type UpdateAgentCwdParams struct {
	CWD       string `db:"cwd" json:"cwd"`
	UpdatedAt int64  `db:"updated_at" json:"updated_at"`
	AgentID   string `db:"agent_id" json:"agent_id"`
}

func (q *Queries) UpdateAgentCwd(ctx context.Context, arg UpdateAgentCwdParams) error {
	_, err := q.db.ExecContext(ctx, updateAgentCwd, arg.CWD, arg.UpdatedAt, arg.AgentID)
	return err
}
