// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: thread_binding.sql

package sqlc

import (
	"context"
)

const bindAgentThread = `-- name: BindAgentThread :exec
INSERT INTO agent_provider_binding (
    agent_id,
    provider,
    provider_thread_id,
    codex_thread_id,
    rollout_path,
    cwd,
    archived,
    created_at,
    updated_at,
    session_uuid
) VALUES (
    $1,
    'codex',
    $2,
    $2,
    '',
    $3,
    false,
    $4,
    $5,
    ''
)
ON CONFLICT (agent_id) DO UPDATE
SET codex_thread_id = EXCLUDED.codex_thread_id,
    cwd = EXCLUDED.cwd,
    updated_at = EXCLUDED.updated_at
`

type BindAgentThreadParams struct {
	AgentID   string `db:"agent_id" json:"agent_id"`
	ThreadID  string `db:"thread_id" json:"thread_id"`
	Cwd       string `db:"cwd" json:"cwd"`
	CreatedAt int64  `db:"created_at" json:"created_at"`
	UpdatedAt int64  `db:"updated_at" json:"updated_at"`
}

func (q *Queries) BindAgentThread(ctx context.Context, arg BindAgentThreadParams) error {
	_, err := q.db.Exec(ctx, bindAgentThread,
		arg.AgentID,
		arg.ThreadID,
		arg.Cwd,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getThreadByAgent = `-- name: GetThreadByAgent :one
SELECT COALESCE(NULLIF(codex_thread_id, ''), provider_thread_id) AS thread_id
FROM agent_provider_binding
WHERE agent_id = $1
`

func (q *Queries) GetThreadByAgent(ctx context.Context, agentID string) (string, error) {
	row := q.db.QueryRow(ctx, getThreadByAgent, agentID)
	var thread_id string
	err := row.Scan(&thread_id)
	return thread_id, err
}

const listAgentThreadBindings = `-- name: ListAgentThreadBindings :many
SELECT agent_id, provider, provider_thread_id, codex_thread_id, rollout_path, cwd, archived, created_at, updated_at, session_uuid
FROM agent_provider_binding
ORDER BY created_at DESC, agent_id DESC
`

func (q *Queries) ListAgentThreadBindings(ctx context.Context) ([]AgentProviderBinding, error) {
	rows, err := q.db.Query(ctx, listAgentThreadBindings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentProviderBinding{}
	for rows.Next() {
		var i AgentProviderBinding
		if err := rows.Scan(
			&i.AgentID,
			&i.Provider,
			&i.ProviderThreadID,
			&i.CodexThreadID,
			&i.RolloutPath,
			&i.Cwd,
			&i.Archived,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SessionUUID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unbindAgentThread = `-- name: UnbindAgentThread :exec
DELETE FROM agent_provider_binding
WHERE agent_id = $1
`

func (q *Queries) UnbindAgentThread(ctx context.Context, agentID string) error {
	_, err := q.db.Exec(ctx, unbindAgentThread, agentID)
	return err
}

const updateAgentCwd = `-- name: UpdateAgentCwd :exec
UPDATE agent_provider_binding
SET cwd = $1,
    updated_at = $2
WHERE agent_id = $3
`

type UpdateAgentCwdParams struct {
	Cwd       string `db:"cwd" json:"cwd"`
	UpdatedAt int64  `db:"updated_at" json:"updated_at"`
	AgentID   string `db:"agent_id" json:"agent_id"`
}

func (q *Queries) UpdateAgentCwd(ctx context.Context, arg UpdateAgentCwdParams) error {
	_, err := q.db.Exec(ctx, updateAgentCwd, arg.Cwd, arg.UpdatedAt, arg.AgentID)
	return err
}
