// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: turn_dedupe_registry.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bindTurnDedupeProviderID = `-- name: BindTurnDedupeProviderID :exec
UPDATE turn_dedupe_registry
   SET provider_turn_id = $1,
       updated_at       = $2
 WHERE dedupe_key = $3
`

type BindTurnDedupeProviderIDParams struct {
	ProviderTurnID string             `db:"provider_turn_id" json:"provider_turn_id"`
	Now            pgtype.Timestamptz `db:"now" json:"now"`
	DedupeKey      string             `db:"dedupe_key" json:"dedupe_key"`
}

func (q *Queries) BindTurnDedupeProviderID(ctx context.Context, arg BindTurnDedupeProviderIDParams) error {
	_, err := q.db.Exec(ctx, bindTurnDedupeProviderID, arg.ProviderTurnID, arg.Now, arg.DedupeKey)
	return err
}

const getLiveTurnDedupe = `-- name: GetLiveTurnDedupe :one
SELECT dedupe_key, local_turn_id, provider_turn_id, thread_id, created_at,
       updated_at, terminal_at
  FROM turn_dedupe_registry
 WHERE dedupe_key = $1
   AND terminal_at IS NULL
 LIMIT 1
`

// Returns the still-live registry row for dedupe_key, or an empty row
// when none exists / all matching rows are already terminal. The
// scheduler's caller checks local_turn_id == "" to distinguish miss
// from hit.
func (q *Queries) GetLiveTurnDedupe(ctx context.Context, dedupeKey string) (TurnDedupeRegistry, error) {
	row := q.db.QueryRow(ctx, getLiveTurnDedupe, dedupeKey)
	var i TurnDedupeRegistry
	err := row.Scan(
		&i.DedupeKey,
		&i.LocalTurnID,
		&i.ProviderTurnID,
		&i.ThreadID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TerminalAt,
	)
	return i, err
}

const markTurnDedupeTerminal = `-- name: MarkTurnDedupeTerminal :exec
UPDATE turn_dedupe_registry
   SET terminal_at = $1,
       updated_at  = $1
 WHERE dedupe_key = $2
   AND terminal_at IS NULL
`

type MarkTurnDedupeTerminalParams struct {
	Now       pgtype.Timestamptz `db:"now" json:"now"`
	DedupeKey string             `db:"dedupe_key" json:"dedupe_key"`
}

func (q *Queries) MarkTurnDedupeTerminal(ctx context.Context, arg MarkTurnDedupeTerminalParams) error {
	_, err := q.db.Exec(ctx, markTurnDedupeTerminal, arg.Now, arg.DedupeKey)
	return err
}

const sweepTurnDedupeRegistry = `-- name: SweepTurnDedupeRegistry :exec
DELETE FROM turn_dedupe_registry
 WHERE updated_at < $1
`

// Deletes every row whose updated_at is older than cutoff. Run on a
// coarse interval by the scheduler so the table can never outgrow
// the tracker TTL window.
func (q *Queries) SweepTurnDedupeRegistry(ctx context.Context, cutoff pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, sweepTurnDedupeRegistry, cutoff)
	return err
}

const upsertTurnDedupeRegistry = `-- name: UpsertTurnDedupeRegistry :exec

INSERT INTO turn_dedupe_registry (
    dedupe_key, local_turn_id, thread_id, created_at, updated_at, terminal_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $4,
    NULL
)
ON CONFLICT (dedupe_key) DO UPDATE SET
    local_turn_id    = EXCLUDED.local_turn_id,
    thread_id        = CASE
                          WHEN EXCLUDED.thread_id = '' THEN turn_dedupe_registry.thread_id
                          ELSE EXCLUDED.thread_id
                       END,
    provider_turn_id = turn_dedupe_registry.provider_turn_id,
    updated_at       = EXCLUDED.updated_at,
    terminal_at      = NULL
`

type UpsertTurnDedupeRegistryParams struct {
	DedupeKey   string             `db:"dedupe_key" json:"dedupe_key"`
	LocalTurnID string             `db:"local_turn_id" json:"local_turn_id"`
	ThreadID    string             `db:"thread_id" json:"thread_id"`
	Now         pgtype.Timestamptz `db:"now" json:"now"`
}

// Queries for turn_dedupe_registry. See migration 0060 for the table
// layout + lifetime contract.
func (q *Queries) UpsertTurnDedupeRegistry(ctx context.Context, arg UpsertTurnDedupeRegistryParams) error {
	_, err := q.db.Exec(ctx, upsertTurnDedupeRegistry,
		arg.DedupeKey,
		arg.LocalTurnID,
		arg.ThreadID,
		arg.Now,
	)
	return err
}
