// @ts-check

import { createBackendApi } from './backend/backendApiFactoryThread.js';
import { registerBridgeLogStore, sendFrontendLogBatch, emitFrontendTraceEvent } from './wailsBridge.js';

export { RPC_METHODS } from './backend/backendRpcMethods.js';
export { createBackendApi };

const backendApi = createBackendApi();

const {
  callBackend, readConfig, readLspPromptHint, writeLspPromptHint,
  readBuiltinTools, writeBuiltinTool, checkAppUpdate, downloadAppUpdate,
  installAppUpdate, installLatestAppUpdate, getWindowBootstrap, getSidebarState,
  openNewWindow, getThreadState, getProjects, setActiveProject,
  addProject, removeProject, getPreference, getAllPreferences,
  setPreference, listModelProviders, saveModelProviders, applyModelProvider,
  getDashboardPage, getVideoApiKey, setVideoApiKey, listDashboardLogs,
  getObservabilityTrace, getObservabilityThreadRecent, listObservabilityRecent, listObservabilitySlow,
  listObservabilityErrors, getObservabilityStatus, getMemorySnapshot, getMemoryEntry,
  upsertMemoryEntry, deleteMemoryEntry, setMemoryAutoDreamIntent, mergeMemoryEntries,
  ignoreMemorySimilarity, consolidateMemorySimilarities, startConsolidateMemorySimilarities, getMemoryConsolidationStatus,
  listSharedFiles, readSharedFile, deleteSharedFile, writeWorkflowMaterial,
  listPromptAssets, getDashboardPrompts, getPrompt, writePrompt,
  deletePrompt, draftPromptIntent, commitPromptIntent, discardPromptIntent,
  dryRunPromptIntent, getPersonalizationProfile, savePersonalizationProfile, listPromptSections,
  writePromptSection, deletePromptSection, listDags, getDagDetail,
  getDagRuns, getDagRun, startDag, createAndStartDag,
  dispatchDagNode, terminateDagRun, terminateDag, deleteDag,
  applyDagOps, listWorkflowTemplates, getWorkflowTemplate, renderWorkflowTemplateDraft,
  saveWorkflowTemplate, rollbackWorkflowTemplate, listCronJobs, getCronJob,
  createCronJob, updateCronJob, deleteCronJob, runCronJobOnce,
  setCronJobEnabled, listCronJobRuns, locateCodeFile, openCodeFile,
  openPath, saveCodeFile, readSkill, listSkillFiles,
  writeSkill, createSkill, importSkillDirectories, suggestSkillSummary,
  listSkillResolutions, previewSkillResolution, applySkillResolution, deleteSkill,
  createSkillTool, listSkillTools, getSkillTool, updateSkillTool,
  deleteSkillTool, createDatasourceDocument, importDatasourceLocalFile, listDatasourceDocuments,
  getDatasourceDocument, listDatasourceChunks, updateDatasourceDocument, deleteDatasourceDocument,
  listMCPServers, listToolbridgeTools, startSQLiteMCPServer, stopSQLiteMCPServer, startPlaywrightMCPServer,
  stopPlaywrightMCPServer, setMCPToolLifecycle, listMCPToolLifecycle, exportMCPToolLifecycle,
  listThreadsPage, listLoadedThreadsPage, getThreadMessages, getPromptHistory, resolveThreadIdentity,
  archiveThread, unarchiveThread, deleteThread, getThreadConfig,
  setThreadConfig, forkThread, startThread, startTurn, interruptTurn,
  forceCompleteTurn, respondApproval, compactThread, recoverThread,
  renameThread, getBuildInfo, onAgentEvent, onBridgeEvent,
  onFilesDropped, onRuntimeReconnect, readDroppedTextFiles, saveClipboardImage,
  saveTextFile, openSharedFile, previewSharedFile, beginTextClipboardWrite,
  copyTextToClipboard, selectFiles, selectDatasourceImportFile, selectProjectDir,
  selectProjectDirs,
} = backendApi;

export {
  callBackend, readConfig, readLspPromptHint, writeLspPromptHint,
  readBuiltinTools, writeBuiltinTool, checkAppUpdate, downloadAppUpdate,
  installAppUpdate, installLatestAppUpdate, getWindowBootstrap, getSidebarState,
  openNewWindow, getThreadState, getProjects, setActiveProject,
  addProject, removeProject, getPreference, getAllPreferences,
  setPreference, listModelProviders, saveModelProviders, applyModelProvider,
  getDashboardPage, getVideoApiKey, setVideoApiKey, listDashboardLogs,
  getObservabilityTrace, getObservabilityThreadRecent, listObservabilityRecent, listObservabilitySlow,
  listObservabilityErrors, getObservabilityStatus, getMemorySnapshot, getMemoryEntry,
  upsertMemoryEntry, deleteMemoryEntry, setMemoryAutoDreamIntent, mergeMemoryEntries,
  ignoreMemorySimilarity, consolidateMemorySimilarities, startConsolidateMemorySimilarities, getMemoryConsolidationStatus,
  listSharedFiles, readSharedFile, deleteSharedFile, writeWorkflowMaterial,
  listPromptAssets, getDashboardPrompts, getPrompt, writePrompt,
  deletePrompt, draftPromptIntent, commitPromptIntent, discardPromptIntent,
  dryRunPromptIntent, getPersonalizationProfile, savePersonalizationProfile, listPromptSections,
  writePromptSection, deletePromptSection, listDags, getDagDetail,
  getDagRuns, getDagRun, startDag, createAndStartDag,
  dispatchDagNode, terminateDagRun, terminateDag, deleteDag,
  applyDagOps, listWorkflowTemplates, getWorkflowTemplate, renderWorkflowTemplateDraft,
  saveWorkflowTemplate, rollbackWorkflowTemplate, listCronJobs, getCronJob,
  createCronJob, updateCronJob, deleteCronJob, runCronJobOnce,
  setCronJobEnabled, listCronJobRuns, locateCodeFile, openCodeFile,
  openPath, saveCodeFile, readSkill, listSkillFiles,
  writeSkill, createSkill, importSkillDirectories, suggestSkillSummary,
  listSkillResolutions, previewSkillResolution, applySkillResolution, deleteSkill,
  createSkillTool, listSkillTools, getSkillTool, updateSkillTool,
  deleteSkillTool, createDatasourceDocument, importDatasourceLocalFile, listDatasourceDocuments,
  getDatasourceDocument, listDatasourceChunks, updateDatasourceDocument, deleteDatasourceDocument,
  listMCPServers, listToolbridgeTools, startSQLiteMCPServer, stopSQLiteMCPServer, startPlaywrightMCPServer,
  stopPlaywrightMCPServer, setMCPToolLifecycle, listMCPToolLifecycle, exportMCPToolLifecycle,
  listThreadsPage, listLoadedThreadsPage, getThreadMessages, getPromptHistory, resolveThreadIdentity,
  archiveThread, unarchiveThread, deleteThread, getThreadConfig,
  setThreadConfig, forkThread, startThread, startTurn, interruptTurn,
  forceCompleteTurn, respondApproval, compactThread, recoverThread,
  renameThread, getBuildInfo, onAgentEvent, onBridgeEvent,
  onFilesDropped, onRuntimeReconnect, readDroppedTextFiles, saveClipboardImage,
  saveTextFile, openSharedFile, previewSharedFile, beginTextClipboardWrite,
  copyTextToClipboard, selectFiles, selectDatasourceImportFile, selectProjectDir,
  selectProjectDirs, registerBridgeLogStore, sendFrontendLogBatch, emitFrontendTraceEvent,
};
