// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CommandCard struct {
	ID              int64              `json:"id"`
	CardKey         string             `json:"card_key"`
	Title           string             `json:"title"`
	Description     string             `json:"description"`
	CommandTemplate string             `json:"command_template"`
	ArgsSchema      []byte             `json:"args_schema"`
	RiskLevel       string             `json:"risk_level"`
	Enabled         bool               `json:"enabled"`
	CreatedBy       string             `json:"created_by"`
	UpdatedBy       string             `json:"updated_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type CommandCardVersion struct {
	ID              int64              `json:"id"`
	CardKey         string             `json:"card_key"`
	Title           string             `json:"title"`
	Description     string             `json:"description"`
	CommandTemplate string             `json:"command_template"`
	ArgsSchema      []byte             `json:"args_schema"`
	RiskLevel       string             `json:"risk_level"`
	Enabled         bool               `json:"enabled"`
	CreatedBy       string             `json:"created_by"`
	UpdatedBy       string             `json:"updated_by"`
	SourceUpdatedAt pgtype.Timestamptz `json:"source_updated_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ArchivedAt      pgtype.Timestamptz `json:"archived_at"`
}

type SharedFile struct {
	Path      string             `json:"path"`
	Content   string             `json:"content"`
	UpdatedBy string             `json:"updated_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type TaskAck struct {
	ID            int64              `json:"id"`
	AckKey        string             `json:"ack_key"`
	Title         string             `json:"title"`
	Description   string             `json:"description"`
	AssignedTo    string             `json:"assigned_to"`
	RequestedBy   string             `json:"requested_by"`
	Priority      string             `json:"priority"`
	Status        string             `json:"status"`
	Progress      int32              `json:"progress"`
	AckMessage    string             `json:"ack_message"`
	ResultSummary string             `json:"result_summary"`
	Metadata      []byte             `json:"metadata"`
	DueAt         pgtype.Timestamptz `json:"due_at"`
	AckedAt       pgtype.Timestamptz `json:"acked_at"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type TaskDag struct {
	ID          int64              `json:"id"`
	DagKey      string             `json:"dag_key"`
	Version     int64              `json:"version"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Status      string             `json:"status"`
	CreatedBy   string             `json:"created_by"`
	Metadata    []byte             `json:"metadata"`
	Trigger     string             `json:"trigger"`
	CronExpr    string             `json:"cron_expr"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	FinishedAt  pgtype.Timestamptz `json:"finished_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type TaskDagNode struct {
	ID             int64              `json:"id"`
	DagKey         string             `json:"dag_key"`
	NodeKey        string             `json:"node_key"`
	RunID          pgtype.Int8        `json:"run_id"`
	Title          string             `json:"title"`
	NodeType       string             `json:"node_type"`
	AssignedTo     string             `json:"assigned_to"`
	DependsOn      []byte             `json:"depends_on"`
	Status         string             `json:"status"`
	CommandRef     string             `json:"command_ref"`
	Config         []byte             `json:"config"`
	Result         []byte             `json:"result"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ActiveTurnID   pgtype.Text        `json:"active_turn_id"`
	ActiveWakeupID pgtype.Int8        `json:"active_wakeup_id"`
	LastEventAt    pgtype.Timestamptz `json:"last_event_at"`
	// SpawningThreadID — DAG v2 F1.5 / ADR-009：AgentExecutor spawn 出的最近一次
	// child agent thread id（软关联，无外键，重试时覆盖）。NULL 表示从未 spawn
	// 或本节点 node_type != agent。详 migration 0083_dag_v2_spawning_thread_id.sql。
	SpawningThreadID pgtype.Text `json:"spawning_thread_id"`
}

type TaskDagWakeup struct {
	ID             int64              `json:"id"`
	DagKey         string             `json:"dag_key"`
	NodeKey        string             `json:"node_key"`
	RunID          pgtype.Int8        `json:"run_id"`
	WakeupKind     string             `json:"wakeup_kind"`
	TargetAgentID  string             `json:"target_agent_id"`
	PromptPayload  []byte             `json:"prompt_payload"`
	IdempotencyKey string             `json:"idempotency_key"`
	Status         string             `json:"status"`
	AttemptCount   int32              `json:"attempt_count"`
	NextRetryAt    pgtype.Timestamptz `json:"next_retry_at"`
	ClaimedAt      pgtype.Timestamptz `json:"claimed_at"`
	ClaimedBy      string             `json:"claimed_by"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	SentAt         pgtype.Timestamptz `json:"sent_at"`
	BoundTurnID    pgtype.Text        `json:"bound_turn_id"`
	TurnBoundAt    pgtype.Timestamptz `json:"turn_bound_at"`
	LastError      string             `json:"last_error"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type WorkspaceRun struct {
	ID            int64              `json:"id"`
	RunKey        string             `json:"run_key"`
	DagKey        string             `json:"dag_key"`
	SourceRoot    string             `json:"source_root"`
	WorkspacePath string             `json:"workspace_path"`
	Status        string             `json:"status"`
	CreatedBy     string             `json:"created_by"`
	UpdatedBy     string             `json:"updated_by"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
}

type WorkspaceRunFile struct {
	ID                 int64              `json:"id"`
	RunKey             string             `json:"run_key"`
	RelativePath       string             `json:"relative_path"`
	BaselineSha256     string             `json:"baseline_sha256"`
	WorkspaceSha256    string             `json:"workspace_sha256"`
	SourceSha256Before string             `json:"source_sha256_before"`
	SourceSha256After  string             `json:"source_sha256_after"`
	State              string             `json:"state"`
	LastError          string             `json:"last_error"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

// TaskDagRun mirrors the row type that `sqlc generate` would emit for the
// migrations 0072-0075 schema. Manually copied from a sqlc-1.30 dry run
// because the existing baseline models.go diverges from sqlc-1.30 output
// (omit_unused_structs:true drops TaskDag / TaskDagNode top-level types
// when the queries SELECT explicit columns); regenerating in-place would
// break store.go's TaskDag/TaskDagNode references. Keeping this manually
// is a localised fix until the project does a full sqlc realignment
// (separate refactor, out of scope for T1.2).
type TaskDagRun struct {
	ID                 int64              `json:"id"`
	RunKey             string             `json:"run_key"`
	DagKey             string             `json:"dag_key"`
	DagVersionSnapshot int64              `json:"dag_version_snapshot"`
	TriggerSource      string             `json:"trigger_source"`
	Status             string             `json:"status"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	FinishedAt         pgtype.Timestamptz `json:"finished_at"`
	Events             []byte             `json:"events"`
	BudgetUsed         int64              `json:"budget_used"`
	BudgetLimit        pgtype.Int8        `json:"budget_limit"`
	Metadata           []byte             `json:"metadata"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}
