// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CommandCard struct {
	ID              int64              `json:"id"`
	CardKey         string             `json:"card_key"`
	Title           string             `json:"title"`
	Description     string             `json:"description"`
	CommandTemplate string             `json:"command_template"`
	ArgsSchema      []byte             `json:"args_schema"`
	RiskLevel       string             `json:"risk_level"`
	Enabled         bool               `json:"enabled"`
	CreatedBy       string             `json:"created_by"`
	UpdatedBy       string             `json:"updated_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type CommandCardVersion struct {
	ID              int64              `json:"id"`
	CardKey         string             `json:"card_key"`
	Title           string             `json:"title"`
	Description     string             `json:"description"`
	CommandTemplate string             `json:"command_template"`
	ArgsSchema      []byte             `json:"args_schema"`
	RiskLevel       string             `json:"risk_level"`
	Enabled         bool               `json:"enabled"`
	CreatedBy       string             `json:"created_by"`
	UpdatedBy       string             `json:"updated_by"`
	SourceUpdatedAt pgtype.Timestamptz `json:"source_updated_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ArchivedAt      pgtype.Timestamptz `json:"archived_at"`
}

type SharedFile struct {
	Path      string             `json:"path"`
	Content   string             `json:"content"`
	UpdatedBy string             `json:"updated_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type TaskAck struct {
	ID            int64              `json:"id"`
	AckKey        string             `json:"ack_key"`
	Title         string             `json:"title"`
	Description   string             `json:"description"`
	AssignedTo    string             `json:"assigned_to"`
	RequestedBy   string             `json:"requested_by"`
	Priority      string             `json:"priority"`
	Status        string             `json:"status"`
	Progress      int32              `json:"progress"`
	AckMessage    string             `json:"ack_message"`
	ResultSummary string             `json:"result_summary"`
	Metadata      []byte             `json:"metadata"`
	DueAt         pgtype.Timestamptz `json:"due_at"`
	AckedAt       pgtype.Timestamptz `json:"acked_at"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type TaskDag struct {
	ID          int64              `json:"id"`
	DagKey      string             `json:"dag_key"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Status      string             `json:"status"`
	CreatedBy   string             `json:"created_by"`
	Metadata    []byte             `json:"metadata"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	FinishedAt  pgtype.Timestamptz `json:"finished_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type TaskDagNode struct {
	ID             int64              `json:"id"`
	DagKey         string             `json:"dag_key"`
	NodeKey        string             `json:"node_key"`
	Title          string             `json:"title"`
	NodeType       string             `json:"node_type"`
	AssignedTo     string             `json:"assigned_to"`
	DependsOn      []byte             `json:"depends_on"`
	Status         string             `json:"status"`
	CommandRef     string             `json:"command_ref"`
	Config         []byte             `json:"config"`
	Result         []byte             `json:"result"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ActiveTurnID   pgtype.Text        `json:"active_turn_id"`
	ActiveWakeupID pgtype.Int8        `json:"active_wakeup_id"`
	LastEventAt    pgtype.Timestamptz `json:"last_event_at"`
}

type TaskDagWakeup struct {
	ID             int64              `json:"id"`
	DagKey         string             `json:"dag_key"`
	NodeKey        string             `json:"node_key"`
	WakeupKind     string             `json:"wakeup_kind"`
	TargetAgentID  string             `json:"target_agent_id"`
	PromptPayload  []byte             `json:"prompt_payload"`
	IdempotencyKey string             `json:"idempotency_key"`
	Status         string             `json:"status"`
	AttemptCount   int32              `json:"attempt_count"`
	NextRetryAt    pgtype.Timestamptz `json:"next_retry_at"`
	ClaimedAt      pgtype.Timestamptz `json:"claimed_at"`
	ClaimedBy      string             `json:"claimed_by"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	SentAt         pgtype.Timestamptz `json:"sent_at"`
	BoundTurnID    pgtype.Text        `json:"bound_turn_id"`
	TurnBoundAt    pgtype.Timestamptz `json:"turn_bound_at"`
	LastError      string             `json:"last_error"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type WorkspaceRun struct {
	ID            int64              `json:"id"`
	RunKey        string             `json:"run_key"`
	DagKey        string             `json:"dag_key"`
	SourceRoot    string             `json:"source_root"`
	WorkspacePath string             `json:"workspace_path"`
	Status        string             `json:"status"`
	CreatedBy     string             `json:"created_by"`
	UpdatedBy     string             `json:"updated_by"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
}

type WorkspaceRunFile struct {
	ID                 int64              `json:"id"`
	RunKey             string             `json:"run_key"`
	RelativePath       string             `json:"relative_path"`
	BaselineSha256     string             `json:"baseline_sha256"`
	WorkspaceSha256    string             `json:"workspace_sha256"`
	SourceSha256Before string             `json:"source_sha256_before"`
	SourceSha256After  string             `json:"source_sha256_after"`
	State              string             `json:"state"`
	LastError          string             `json:"last_error"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}
