// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prompt_template.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePromptTemplate = `-- name: DeletePromptTemplate :execrows
DELETE FROM prompt_templates
WHERE prompt_key = $1
`

func (q *Queries) DeletePromptTemplate(ctx context.Context, promptKey string) (int64, error) {
	result, err := q.db.Exec(ctx, deletePromptTemplate, promptKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPromptTemplate = `-- name: GetPromptTemplate :one
SELECT id, prompt_key, title, agent_key, tool_name, prompt_text, variables, tags, description, enabled, created_by, updated_by, created_at, updated_at
FROM prompt_templates
WHERE prompt_key = $1
`

type GetPromptTemplateRow struct {
	ID          int64              `json:"id"`
	PromptKey   string             `json:"prompt_key"`
	Title       string             `json:"title"`
	AgentKey    string             `json:"agent_key"`
	ToolName    string             `json:"tool_name"`
	PromptText  string             `json:"prompt_text"`
	Variables   []byte             `json:"variables"`
	Tags        []byte             `json:"tags"`
	Description string             `json:"description"`
	Enabled     bool               `json:"enabled"`
	CreatedBy   string             `json:"created_by"`
	UpdatedBy   string             `json:"updated_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetPromptTemplate(ctx context.Context, promptKey string) (GetPromptTemplateRow, error) {
	row := q.db.QueryRow(ctx, getPromptTemplate, promptKey)
	var i GetPromptTemplateRow
	err := row.Scan(
		&i.ID,
		&i.PromptKey,
		&i.Title,
		&i.AgentKey,
		&i.ToolName,
		&i.PromptText,
		&i.Variables,
		&i.Tags,
		&i.Description,
		&i.Enabled,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPromptVersion = `-- name: InsertPromptVersion :one
INSERT INTO prompt_versions (
    prompt_key, title, agent_key, tool_name, prompt_text,
    variables, tags, description, enabled, created_by, updated_by, source_updated_at
) VALUES ($1, $2, $3, $4, $5, $6::jsonb, $7::jsonb, $8, $9, $10, $11, $12)
RETURNING id
`

type InsertPromptVersionParams struct {
	PromptKey       string             `json:"prompt_key"`
	Title           string             `json:"title"`
	AgentKey        string             `json:"agent_key"`
	ToolName        string             `json:"tool_name"`
	PromptText      string             `json:"prompt_text"`
	Column6         []byte             `json:"column_6"`
	Column7         []byte             `json:"column_7"`
	Description     string             `json:"description"`
	Enabled         bool               `json:"enabled"`
	CreatedBy       string             `json:"created_by"`
	UpdatedBy       string             `json:"updated_by"`
	SourceUpdatedAt pgtype.Timestamptz `json:"source_updated_at"`
}

func (q *Queries) InsertPromptVersion(ctx context.Context, arg InsertPromptVersionParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertPromptVersion,
		arg.PromptKey,
		arg.Title,
		arg.AgentKey,
		arg.ToolName,
		arg.PromptText,
		arg.Column6,
		arg.Column7,
		arg.Description,
		arg.Enabled,
		arg.CreatedBy,
		arg.UpdatedBy,
		arg.SourceUpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listPromptTemplates = `-- name: ListPromptTemplates :many
SELECT id, prompt_key, title, agent_key, tool_name, prompt_text, variables, tags, description, enabled, created_by, updated_by, created_at, updated_at
FROM prompt_templates
WHERE ($1::text = '' OR agent_key = $1)
  AND ($2::text = ''
    OR prompt_key ILIKE '%' || $2 || '%'
    OR title ILIKE '%' || $2 || '%'
    OR prompt_text ILIKE '%' || $2 || '%')
ORDER BY updated_at DESC
LIMIT $3
`

type ListPromptTemplatesParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Limit   int32  `json:"limit"`
}

type ListPromptTemplatesRow struct {
	ID          int64              `json:"id"`
	PromptKey   string             `json:"prompt_key"`
	Title       string             `json:"title"`
	AgentKey    string             `json:"agent_key"`
	ToolName    string             `json:"tool_name"`
	PromptText  string             `json:"prompt_text"`
	Variables   []byte             `json:"variables"`
	Tags        []byte             `json:"tags"`
	Description string             `json:"description"`
	Enabled     bool               `json:"enabled"`
	CreatedBy   string             `json:"created_by"`
	UpdatedBy   string             `json:"updated_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListPromptTemplates(ctx context.Context, arg ListPromptTemplatesParams) ([]ListPromptTemplatesRow, error) {
	rows, err := q.db.Query(ctx, listPromptTemplates, arg.Column1, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPromptTemplatesRow{}
	for rows.Next() {
		var i ListPromptTemplatesRow
		if err := rows.Scan(
			&i.ID,
			&i.PromptKey,
			&i.Title,
			&i.AgentKey,
			&i.ToolName,
			&i.PromptText,
			&i.Variables,
			&i.Tags,
			&i.Description,
			&i.Enabled,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPromptTemplate = `-- name: UpsertPromptTemplate :one
INSERT INTO prompt_templates (
    prompt_key, title, agent_key, tool_name, prompt_text,
    variables, tags, description, enabled, created_by, updated_by, updated_at
) VALUES ($1, $2, $3, $4, $5, $6::jsonb, $7::jsonb, $8, $9, $10, $11, NOW())
ON CONFLICT (prompt_key) DO UPDATE
SET title = EXCLUDED.title,
    agent_key = EXCLUDED.agent_key,
    tool_name = EXCLUDED.tool_name,
    prompt_text = EXCLUDED.prompt_text,
    variables = EXCLUDED.variables,
    tags = EXCLUDED.tags,
    description = EXCLUDED.description,
    enabled = EXCLUDED.enabled,
    updated_by = EXCLUDED.updated_by,
    updated_at = NOW()
RETURNING id, prompt_key, title, agent_key, tool_name, prompt_text, variables, tags, description, enabled, created_by, updated_by, created_at, updated_at
`

type UpsertPromptTemplateParams struct {
	PromptKey   string `json:"prompt_key"`
	Title       string `json:"title"`
	AgentKey    string `json:"agent_key"`
	ToolName    string `json:"tool_name"`
	PromptText  string `json:"prompt_text"`
	Column6     []byte `json:"column_6"`
	Column7     []byte `json:"column_7"`
	Description string `json:"description"`
	Enabled     bool   `json:"enabled"`
	CreatedBy   string `json:"created_by"`
	UpdatedBy   string `json:"updated_by"`
}

type UpsertPromptTemplateRow struct {
	ID          int64              `json:"id"`
	PromptKey   string             `json:"prompt_key"`
	Title       string             `json:"title"`
	AgentKey    string             `json:"agent_key"`
	ToolName    string             `json:"tool_name"`
	PromptText  string             `json:"prompt_text"`
	Variables   []byte             `json:"variables"`
	Tags        []byte             `json:"tags"`
	Description string             `json:"description"`
	Enabled     bool               `json:"enabled"`
	CreatedBy   string             `json:"created_by"`
	UpdatedBy   string             `json:"updated_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertPromptTemplate(ctx context.Context, arg UpsertPromptTemplateParams) (UpsertPromptTemplateRow, error) {
	row := q.db.QueryRow(ctx, upsertPromptTemplate,
		arg.PromptKey,
		arg.Title,
		arg.AgentKey,
		arg.ToolName,
		arg.PromptText,
		arg.Column6,
		arg.Column7,
		arg.Description,
		arg.Enabled,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i UpsertPromptTemplateRow
	err := row.Scan(
		&i.ID,
		&i.PromptKey,
		&i.Title,
		&i.AgentKey,
		&i.ToolName,
		&i.PromptText,
		&i.Variables,
		&i.Tags,
		&i.Description,
		&i.Enabled,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
