// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	AcquireTaskDagWorkerLease(ctx context.Context, arg AcquireTaskDagWorkerLeaseParams) (int64, error)
	BindRunningTaskDagNodeTurn(ctx context.Context, arg BindRunningTaskDagNodeTurnParams) (TaskDagNode, error)
	BindTaskDagWakeupTurn(ctx context.Context, arg BindTaskDagWakeupTurnParams) (int64, error)
	ClaimDueTaskDagWakeups(ctx context.Context, arg ClaimDueTaskDagWakeupsParams) ([]TaskDagWakeup, error)
	CompleteTaskDagNode(ctx context.Context, arg CompleteTaskDagNodeParams) (TaskDagNode, error)
	EnqueueTaskDagWakeup(ctx context.Context, arg EnqueueTaskDagWakeupParams) (int64, error)
	FailTaskDagWakeup(ctx context.Context, arg FailTaskDagWakeupParams) (int64, error)
	GetTaskDag(ctx context.Context, dagKey string) (TaskDag, error)
	GetTaskDagForUpdate(ctx context.Context, dagKey string) (TaskDag, error)
	GetTaskDagNodesForUpdate(ctx context.Context, dagKey string) ([]TaskDagNode, error)
	GetTaskDagWakeup(ctx context.Context, id int64) (TaskDagWakeup, error)
	ListPendingOrDispatchingTaskDagWakeups(ctx context.Context) ([]TaskDagWakeup, error)
	ListRunningTaskDagNodesByAssignee(ctx context.Context, assignedTo string) ([]TaskDagNode, error)
	ListSentUnboundTaskDagWakeups(ctx context.Context, targetAgentID string) ([]TaskDagWakeup, error)
	ListTaskDagNodes(ctx context.Context, dagKey string) ([]TaskDagNode, error)
	ListTaskDags(ctx context.Context, arg ListTaskDagsParams) ([]TaskDag, error)
	MarkTaskDagWakeupSent(ctx context.Context, arg MarkTaskDagWakeupSentParams) (int64, error)
	ReclaimStaleDispatchingTaskDagWakeups(ctx context.Context) (int64, error)
	ReleaseTaskDagWorkerLease(ctx context.Context, arg ReleaseTaskDagWorkerLeaseParams) error
	RenewTaskDagWorkerLease(ctx context.Context, arg RenewTaskDagWorkerLeaseParams) (int64, error)
	RetryTaskDagWakeup(ctx context.Context, arg RetryTaskDagWakeupParams) (int64, error)
	TouchRunningTaskDagNodeEvent(ctx context.Context, arg TouchRunningTaskDagNodeEventParams) (TaskDagNode, error)
	UpdateAwaitingVerifyTaskDagNodeStatus(ctx context.Context, arg UpdateAwaitingVerifyTaskDagNodeStatusParams) (TaskDagNode, error)
	UpdateRunningTaskDagNodeStatus(ctx context.Context, arg UpdateRunningTaskDagNodeStatusParams) (TaskDagNode, error)
	UpdateTaskDagNodeStatus(ctx context.Context, arg UpdateTaskDagNodeStatusParams) (TaskDagNode, error)
	UpdateTaskDagNodeStatusFlexible(ctx context.Context, arg UpdateTaskDagNodeStatusFlexibleParams) (TaskDagNode, error)
	UpsertTaskDag(ctx context.Context, arg UpsertTaskDagParams) (TaskDag, error)
	UpsertTaskDagNode(ctx context.Context, arg UpsertTaskDagNodeParams) (TaskDagNode, error)
}

var _ Querier = (*Queries)(nil)
