// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_dag_run.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveTaskDagRunsByKey = `-- name: CountActiveTaskDagRunsByKey :one
SELECT COUNT(*)::bigint AS active
FROM task_dag_runs
WHERE dag_key = $1 AND status = 'running'
`

// StartDAG 用于多 run 并发 reject：当且仅当 0 时才允许新 run。
// T1.2-mid 限制；F6.5 升级 multi-run 后此 query 不再被 StartDAG 调用。
func (q *Queries) CountActiveTaskDagRunsByKey(ctx context.Context, dagKey string) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveTaskDagRunsByKey, dagKey)
	var active int64
	err := row.Scan(&active)
	return active, err
}

const createTaskDagRun = `-- name: CreateTaskDagRun :one

INSERT INTO task_dag_runs (run_key, dag_key, dag_version_snapshot, trigger_source, status, metadata, budget_limit)
VALUES ($1, $2, $3, $4, 'running', $5::jsonb, $6)
RETURNING id, run_key, dag_key, dag_version_snapshot, trigger_source, status, started_at, finished_at, events, budget_used, budget_limit, metadata, created_at, updated_at
`

type CreateTaskDagRunParams struct {
	RunKey             string      `json:"run_key"`
	DagKey             string      `json:"dag_key"`
	DagVersionSnapshot int64       `json:"dag_version_snapshot"`
	TriggerSource      string      `json:"trigger_source"`
	Column5            []byte      `json:"column_5"`
	BudgetLimit        pgtype.Int8 `json:"budget_limit"`
}

// DAG v2 T1.2-mid: task_dag_runs CRUD + 根节点 promote 入口。
// 蓝图 v2 §5 决策 C 混合：每次 StartDAG 创建一条 run；T1.2-mid 阶段单 DAG
// 单 run，多并发 reject。F6.5 升级为 multi-run + 节点复制带 run_id。
// StartDAG 调用：插入新 run；run_key 由 service 层生成（保证 UNIQUE）。
// dag_version_snapshot 由调用方从 task_dags.version 当前值传入，保证
// run 创建后 DAG 模板被改不影响这次 run（Temporal 风格）。
func (q *Queries) CreateTaskDagRun(ctx context.Context, arg CreateTaskDagRunParams) (TaskDagRun, error) {
	row := q.db.QueryRow(ctx, createTaskDagRun,
		arg.RunKey,
		arg.DagKey,
		arg.DagVersionSnapshot,
		arg.TriggerSource,
		arg.Column5,
		arg.BudgetLimit,
	)
	var i TaskDagRun
	err := row.Scan(
		&i.ID,
		&i.RunKey,
		&i.DagKey,
		&i.DagVersionSnapshot,
		&i.TriggerSource,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Events,
		&i.BudgetUsed,
		&i.BudgetLimit,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskDagRun = `-- name: GetTaskDagRun :one
SELECT id, run_key, dag_key, dag_version_snapshot, trigger_source, status, started_at, finished_at, events, budget_used, budget_limit, metadata, created_at, updated_at
FROM task_dag_runs
WHERE run_key = $1
`

func (q *Queries) GetTaskDagRun(ctx context.Context, runKey string) (TaskDagRun, error) {
	row := q.db.QueryRow(ctx, getTaskDagRun, runKey)
	var i TaskDagRun
	err := row.Scan(
		&i.ID,
		&i.RunKey,
		&i.DagKey,
		&i.DagVersionSnapshot,
		&i.TriggerSource,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Events,
		&i.BudgetUsed,
		&i.BudgetLimit,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTaskDagRunsByKey = `-- name: ListTaskDagRunsByKey :many
SELECT id, run_key, dag_key, dag_version_snapshot, trigger_source, status, started_at, finished_at, events, budget_used, budget_limit, metadata, created_at, updated_at
FROM task_dag_runs
WHERE dag_key = $1
  AND ($2::text = '' OR status = $2)
ORDER BY started_at DESC, id DESC
LIMIT $3
`

type ListTaskDagRunsByKeyParams struct {
	DagKey  string `json:"dag_key"`
	Column2 string `json:"column_2"`
	Limit   int32  `json:"limit"`
}

// 按 dag_key + 可选 status 过滤；空 status 表示全部状态。
// 与 ListTaskDags 风格一致：$2=” 当作未过滤。
func (q *Queries) ListTaskDagRunsByKey(ctx context.Context, arg ListTaskDagRunsByKeyParams) ([]TaskDagRun, error) {
	rows, err := q.db.Query(ctx, listTaskDagRunsByKey, arg.DagKey, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskDagRun{}
	for rows.Next() {
		var i TaskDagRun
		if err := rows.Scan(
			&i.ID,
			&i.RunKey,
			&i.DagKey,
			&i.DagVersionSnapshot,
			&i.TriggerSource,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Events,
			&i.BudgetUsed,
			&i.BudgetLimit,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteRootNodesToReady = `-- name: PromoteRootNodesToReady :execrows
UPDATE task_dag_nodes
SET status = 'ready',
    updated_at = NOW()
WHERE dag_key = $1
  AND status = 'pending'
  AND jsonb_array_length(depends_on) = 0
`

// StartDAG 在新 run 创建后调用：把 dag_key 下所有 depends_on=[] 且 status='pending'
// 的根节点提升为 'ready'。返回受影响行数（service 层用于断言至少一个根节点被
// 提升，否则视为 DAG 无可执行起点）。
// 状态机：pending → ready 是合法转移（见 nodeexec/types.go ValidTransitions）。
func (q *Queries) PromoteRootNodesToReady(ctx context.Context, dagKey string) (int64, error) {
	result, err := q.db.Exec(ctx, promoteRootNodesToReady, dagKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
