// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_dag_node_spawning_thread.sql

package sqlc

import (
	"context"
)

const updateTaskDagNodeSpawningThread = `-- name: UpdateTaskDagNodeSpawningThread :one
UPDATE task_dag_nodes
SET spawning_thread_id = ?1,
    updated_at = (CAST(strftime('%s','now') AS INTEGER) * 1000)
WHERE dag_key = ?2
  AND node_key = ?3
  AND run_id = ?4
  AND ?4 > 0
  AND status NOT IN ('done', 'failed', 'cancelled', 'skipped')
  AND (
      spawning_thread_id IS NULL
      OR TRIM(spawning_thread_id) = ''
      OR TRIM(spawning_thread_id) = TRIM(COALESCE(?1, ''))
  )
RETURNING id, dag_key, node_key, run_id, title,
          node_type, assigned_to, CAST(depends_on AS BLOB) AS depends_on,
          status, command_ref, CAST(config AS BLOB) AS config, CAST(result AS BLOB) AS result,
          started_at, finished_at, created_at,
          updated_at, active_turn_id, active_wakeup_id,
          last_event_at, spawning_thread_id,
          '' AS previous_spawning_thread_id
`

type UpdateTaskDagNodeSpawningThreadParams struct {
	SpawningThreadID *string `db:"spawning_thread_id" json:"spawning_thread_id"`
	DagKey           string  `db:"dag_key" json:"dag_key"`
	NodeKey          string  `db:"node_key" json:"node_key"`
	RunID            *int64  `db:"run_id" json:"run_id"`
}

type UpdateTaskDagNodeSpawningThreadRow struct {
	ID               int64   `db:"id" json:"id"`
	DagKey           string  `db:"dag_key" json:"dag_key"`
	NodeKey          string  `db:"node_key" json:"node_key"`
	RunID            *int64  `db:"run_id" json:"run_id"`
	Title            string  `db:"title" json:"title"`
	NodeType         string  `db:"node_type" json:"node_type"`
	AssignedTo       string  `db:"assigned_to" json:"assigned_to"`
	DependsOn        []byte  `db:"depends_on" json:"depends_on"`
	Status           string  `db:"status" json:"status"`
	CommandRef       string  `db:"command_ref" json:"command_ref"`
	Config           []byte  `db:"config" json:"config"`
	Result           []byte  `db:"result" json:"result"`
	StartedAt        *int64  `db:"started_at" json:"started_at"`
	FinishedAt       *int64  `db:"finished_at" json:"finished_at"`
	CreatedAt        int64   `db:"created_at" json:"created_at"`
	UpdatedAt        int64   `db:"updated_at" json:"updated_at"`
	ActiveTurnID     *string `db:"active_turn_id" json:"active_turn_id"`
	ActiveWakeupID   *int64  `db:"active_wakeup_id" json:"active_wakeup_id"`
	LastEventAt      *int64  `db:"last_event_at" json:"last_event_at"`
	SpawningThreadID *string `db:"spawning_thread_id" json:"spawning_thread_id"`
	Column21         string  `db:"column_21" json:"column_21"`
}

func (q *Queries) UpdateTaskDagNodeSpawningThread(ctx context.Context, arg UpdateTaskDagNodeSpawningThreadParams) (UpdateTaskDagNodeSpawningThreadRow, error) {
	row := q.db.QueryRowContext(ctx, updateTaskDagNodeSpawningThread,
		arg.SpawningThreadID,
		arg.DagKey,
		arg.NodeKey,
		arg.RunID,
	)
	var i UpdateTaskDagNodeSpawningThreadRow
	err := row.Scan(
		&i.ID,
		&i.DagKey,
		&i.NodeKey,
		&i.RunID,
		&i.Title,
		&i.NodeType,
		&i.AssignedTo,
		&i.DependsOn,
		&i.Status,
		&i.CommandRef,
		&i.Config,
		&i.Result,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveTurnID,
		&i.ActiveWakeupID,
		&i.LastEventAt,
		&i.SpawningThreadID,
		&i.Column21,
	)
	return i, err
}
