// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_dag_node_write.sql

package sqlc

import (
	"context"
)

const updateTaskDagNodeStatus = `-- name: UpdateTaskDagNodeStatus :one
UPDATE task_dag_nodes
SET status = $1,
    result = $2::jsonb,
    updated_at = NOW()
WHERE dag_key = $3 AND node_key = $4
RETURNING id, dag_key, node_key, title, node_type, assigned_to, depends_on, status, command_ref, config, result, started_at, finished_at, created_at, updated_at, active_turn_id, active_wakeup_id, last_event_at
`

type UpdateTaskDagNodeStatusParams struct {
	Status  string `db:"status" json:"status"`
	Column2 []byte `db:"column_2" json:"column_2"`
	DagKey  string `db:"dag_key" json:"dag_key"`
	NodeKey string `db:"node_key" json:"node_key"`
}

func (q *Queries) UpdateTaskDagNodeStatus(ctx context.Context, arg UpdateTaskDagNodeStatusParams) (TaskDagNode, error) {
	row := q.db.QueryRow(ctx, updateTaskDagNodeStatus,
		arg.Status,
		arg.Column2,
		arg.DagKey,
		arg.NodeKey,
	)
	var i TaskDagNode
	err := row.Scan(
		&i.ID,
		&i.DagKey,
		&i.NodeKey,
		&i.Title,
		&i.NodeType,
		&i.AssignedTo,
		&i.DependsOn,
		&i.Status,
		&i.CommandRef,
		&i.Config,
		&i.Result,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveTurnID,
		&i.ActiveWakeupID,
		&i.LastEventAt,
	)
	return i, err
}

const updateTaskDagNodeStatusFlexible = `-- name: UpdateTaskDagNodeStatusFlexible :one
UPDATE task_dag_nodes
SET status = $1, result = $2::jsonb, updated_at = NOW()
WHERE dag_key = $3 AND node_key = $4
RETURNING id, dag_key, node_key, title, node_type, assigned_to, depends_on, status, command_ref, config, result, started_at, finished_at, created_at, updated_at, active_turn_id, active_wakeup_id, last_event_at
`

type UpdateTaskDagNodeStatusFlexibleParams struct {
	Status  string `db:"status" json:"status"`
	Column2 []byte `db:"column_2" json:"column_2"`
	DagKey  string `db:"dag_key" json:"dag_key"`
	NodeKey string `db:"node_key" json:"node_key"`
}

func (q *Queries) UpdateTaskDagNodeStatusFlexible(ctx context.Context, arg UpdateTaskDagNodeStatusFlexibleParams) (TaskDagNode, error) {
	row := q.db.QueryRow(ctx, updateTaskDagNodeStatusFlexible,
		arg.Status,
		arg.Column2,
		arg.DagKey,
		arg.NodeKey,
	)
	var i TaskDagNode
	err := row.Scan(
		&i.ID,
		&i.DagKey,
		&i.NodeKey,
		&i.Title,
		&i.NodeType,
		&i.AssignedTo,
		&i.DependsOn,
		&i.Status,
		&i.CommandRef,
		&i.Config,
		&i.Result,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveTurnID,
		&i.ActiveWakeupID,
		&i.LastEventAt,
	)
	return i, err
}

const upsertTaskDagNode = `-- name: UpsertTaskDagNode :one
INSERT INTO task_dag_nodes (dag_key, node_key, title, node_type, assigned_to, depends_on, command_ref, config)
VALUES ($1, $2, $3, $4, $5, $6::jsonb, $7, $8::jsonb)
ON CONFLICT (dag_key, node_key) DO UPDATE
SET title = EXCLUDED.title,
    node_type = EXCLUDED.node_type,
    assigned_to = EXCLUDED.assigned_to,
    depends_on = EXCLUDED.depends_on,
    command_ref = EXCLUDED.command_ref,
    config = EXCLUDED.config,
    updated_at = NOW()
RETURNING id, dag_key, node_key, title, node_type, assigned_to, depends_on, status, command_ref, config, result, started_at, finished_at, created_at, updated_at, active_turn_id, active_wakeup_id, last_event_at
`

type UpsertTaskDagNodeParams struct {
	DagKey     string `db:"dag_key" json:"dag_key"`
	NodeKey    string `db:"node_key" json:"node_key"`
	Title      string `db:"title" json:"title"`
	NodeType   string `db:"node_type" json:"node_type"`
	AssignedTo string `db:"assigned_to" json:"assigned_to"`
	Column6    []byte `db:"column_6" json:"column_6"`
	CommandRef string `db:"command_ref" json:"command_ref"`
	Column8    []byte `db:"column_8" json:"column_8"`
}

func (q *Queries) UpsertTaskDagNode(ctx context.Context, arg UpsertTaskDagNodeParams) (TaskDagNode, error) {
	row := q.db.QueryRow(ctx, upsertTaskDagNode,
		arg.DagKey,
		arg.NodeKey,
		arg.Title,
		arg.NodeType,
		arg.AssignedTo,
		arg.Column6,
		arg.CommandRef,
		arg.Column8,
	)
	var i TaskDagNode
	err := row.Scan(
		&i.ID,
		&i.DagKey,
		&i.NodeKey,
		&i.Title,
		&i.NodeType,
		&i.AssignedTo,
		&i.DependsOn,
		&i.Status,
		&i.CommandRef,
		&i.Config,
		&i.Result,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveTurnID,
		&i.ActiveWakeupID,
		&i.LastEventAt,
	)
	return i, err
}
