// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_dag_worker_lease.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireTaskDagWorkerLease = `-- name: AcquireTaskDagWorkerLease :execrows
INSERT INTO task_dag_worker_leases (target_agent_id, owner_id, lease_expires_at, updated_at)
VALUES ($1, $2, NOW() + $3::interval, NOW())
ON CONFLICT (target_agent_id) DO UPDATE
SET owner_id = EXCLUDED.owner_id,
    lease_expires_at = EXCLUDED.lease_expires_at,
    updated_at = NOW()
WHERE task_dag_worker_leases.lease_expires_at < NOW()
   OR task_dag_worker_leases.owner_id = EXCLUDED.owner_id
`

type AcquireTaskDagWorkerLeaseParams struct {
	TargetAgentID string          `db:"target_agent_id" json:"target_agent_id"`
	OwnerID       string          `db:"owner_id" json:"owner_id"`
	Column3       pgtype.Interval `db:"column_3" json:"column_3"`
}

func (q *Queries) AcquireTaskDagWorkerLease(ctx context.Context, arg AcquireTaskDagWorkerLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, acquireTaskDagWorkerLease, arg.TargetAgentID, arg.OwnerID, arg.Column3)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseTaskDagWorkerLease = `-- name: ReleaseTaskDagWorkerLease :exec
DELETE FROM task_dag_worker_leases
WHERE target_agent_id = $1 AND owner_id = $2
`

type ReleaseTaskDagWorkerLeaseParams struct {
	TargetAgentID string `db:"target_agent_id" json:"target_agent_id"`
	OwnerID       string `db:"owner_id" json:"owner_id"`
}

func (q *Queries) ReleaseTaskDagWorkerLease(ctx context.Context, arg ReleaseTaskDagWorkerLeaseParams) error {
	_, err := q.db.Exec(ctx, releaseTaskDagWorkerLease, arg.TargetAgentID, arg.OwnerID)
	return err
}

const renewTaskDagWorkerLease = `-- name: RenewTaskDagWorkerLease :execrows
UPDATE task_dag_worker_leases
SET lease_expires_at = NOW() + $1::interval,
    updated_at = NOW()
WHERE target_agent_id = $2 AND owner_id = $3 AND lease_expires_at >= NOW()
`

type RenewTaskDagWorkerLeaseParams struct {
	Column1       pgtype.Interval `db:"column_1" json:"column_1"`
	TargetAgentID string          `db:"target_agent_id" json:"target_agent_id"`
	OwnerID       string          `db:"owner_id" json:"owner_id"`
}

func (q *Queries) RenewTaskDagWorkerLease(ctx context.Context, arg RenewTaskDagWorkerLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, renewTaskDagWorkerLease, arg.Column1, arg.TargetAgentID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
