// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_dag_wakeup_query.sql

package sqlc

import (
	"context"
)

const getTaskDagWakeup = `-- name: GetTaskDagWakeup :one
SELECT id, dag_key, node_key, wakeup_kind, target_agent_id, prompt_payload,
       idempotency_key, status, attempt_count, next_retry_at, claimed_at,
       claimed_by, lease_expires_at, sent_at, bound_turn_id, turn_bound_at,
       last_error, created_at, updated_at, run_id
FROM task_dag_wakeups
WHERE id = $1
`

func (q *Queries) GetTaskDagWakeup(ctx context.Context, id int64) (TaskDagWakeup, error) {
	row := q.db.QueryRow(ctx, getTaskDagWakeup, id)
	var i TaskDagWakeup
	err := row.Scan(
		&i.ID,
		&i.DagKey,
		&i.NodeKey,
		&i.WakeupKind,
		&i.TargetAgentID,
		&i.PromptPayload,
		&i.IdempotencyKey,
		&i.Status,
		&i.AttemptCount,
		&i.NextRetryAt,
		&i.ClaimedAt,
		&i.ClaimedBy,
		&i.LeaseExpiresAt,
		&i.SentAt,
		&i.BoundTurnID,
		&i.TurnBoundAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RunID,
	)
	return i, err
}

const listPendingOrDispatchingTaskDagWakeups = `-- name: ListPendingOrDispatchingTaskDagWakeups :many
SELECT id, dag_key, node_key, wakeup_kind, target_agent_id, prompt_payload,
       idempotency_key, status, attempt_count, next_retry_at, claimed_at,
       claimed_by, lease_expires_at, sent_at, bound_turn_id, turn_bound_at,
       last_error, created_at, updated_at, run_id
FROM task_dag_wakeups
WHERE status IN ('pending', 'dispatching')
ORDER BY next_retry_at, id
`

func (q *Queries) ListPendingOrDispatchingTaskDagWakeups(ctx context.Context) ([]TaskDagWakeup, error) {
	rows, err := q.db.Query(ctx, listPendingOrDispatchingTaskDagWakeups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskDagWakeup{}
	for rows.Next() {
		var i TaskDagWakeup
		if err := rows.Scan(
			&i.ID,
			&i.DagKey,
			&i.NodeKey,
			&i.WakeupKind,
			&i.TargetAgentID,
			&i.PromptPayload,
			&i.IdempotencyKey,
			&i.Status,
			&i.AttemptCount,
			&i.NextRetryAt,
			&i.ClaimedAt,
			&i.ClaimedBy,
			&i.LeaseExpiresAt,
			&i.SentAt,
			&i.BoundTurnID,
			&i.TurnBoundAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RunID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSentUnboundTaskDagWakeups = `-- name: ListSentUnboundTaskDagWakeups :many
SELECT id, dag_key, node_key, wakeup_kind, target_agent_id, prompt_payload,
       idempotency_key, status, attempt_count, next_retry_at, claimed_at,
       claimed_by, lease_expires_at, sent_at, bound_turn_id, turn_bound_at,
       last_error, created_at, updated_at, run_id
FROM task_dag_wakeups
WHERE target_agent_id = $1 AND status = 'sent' AND sent_at IS NOT NULL AND bound_turn_id IS NULL
ORDER BY sent_at DESC, id DESC
`

func (q *Queries) ListSentUnboundTaskDagWakeups(ctx context.Context, targetAgentID string) ([]TaskDagWakeup, error) {
	rows, err := q.db.Query(ctx, listSentUnboundTaskDagWakeups, targetAgentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskDagWakeup{}
	for rows.Next() {
		var i TaskDagWakeup
		if err := rows.Scan(
			&i.ID,
			&i.DagKey,
			&i.NodeKey,
			&i.WakeupKind,
			&i.TargetAgentID,
			&i.PromptPayload,
			&i.IdempotencyKey,
			&i.Status,
			&i.AttemptCount,
			&i.NextRetryAt,
			&i.ClaimedAt,
			&i.ClaimedBy,
			&i.LeaseExpiresAt,
			&i.SentAt,
			&i.BoundTurnID,
			&i.TurnBoundAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RunID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reclaimStaleDispatchingTaskDagWakeups = `-- name: ReclaimStaleDispatchingTaskDagWakeups :execrows
UPDATE task_dag_wakeups
SET status = 'pending', claimed_at = NULL, claimed_by = '', lease_expires_at = NULL, updated_at = NOW()
WHERE status = 'dispatching' AND lease_expires_at < NOW()
`

func (q *Queries) ReclaimStaleDispatchingTaskDagWakeups(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, reclaimStaleDispatchingTaskDagWakeups)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
