// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_dag_node_read.sql

package sqlc

import (
	"context"
)

const getTaskDagNodesForUpdate = `-- name: GetTaskDagNodesForUpdate :many
SELECT id, dag_key, node_key, title, node_type, assigned_to, depends_on, status, command_ref, config, result, started_at, finished_at, created_at, updated_at, active_turn_id, active_wakeup_id, last_event_at, spawning_thread_id
FROM task_dag_nodes
WHERE dag_key = $1
ORDER BY created_at, id
FOR UPDATE
`

func (q *Queries) GetTaskDagNodesForUpdate(ctx context.Context, dagKey string) ([]TaskDagNode, error) {
	rows, err := q.db.Query(ctx, getTaskDagNodesForUpdate, dagKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskDagNode{}
	for rows.Next() {
		var i TaskDagNode
		if err := rows.Scan(
			&i.ID,
			&i.DagKey,
			&i.NodeKey,
			&i.Title,
			&i.NodeType,
			&i.AssignedTo,
			&i.DependsOn,
			&i.Status,
			&i.CommandRef,
			&i.Config,
			&i.Result,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ActiveTurnID,
			&i.ActiveWakeupID,
			&i.LastEventAt,
			&i.SpawningThreadID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunningTaskDagNodesByAssignee = `-- name: ListRunningTaskDagNodesByAssignee :many
SELECT id, dag_key, node_key, title, node_type, assigned_to, depends_on, status, command_ref, config, result, started_at, finished_at, created_at, updated_at, active_turn_id, active_wakeup_id, last_event_at, spawning_thread_id
FROM task_dag_nodes
WHERE assigned_to = $1 AND status = 'running'
ORDER BY created_at
`

func (q *Queries) ListRunningTaskDagNodesByAssignee(ctx context.Context, assignedTo string) ([]TaskDagNode, error) {
	rows, err := q.db.Query(ctx, listRunningTaskDagNodesByAssignee, assignedTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskDagNode{}
	for rows.Next() {
		var i TaskDagNode
		if err := rows.Scan(
			&i.ID,
			&i.DagKey,
			&i.NodeKey,
			&i.Title,
			&i.NodeType,
			&i.AssignedTo,
			&i.DependsOn,
			&i.Status,
			&i.CommandRef,
			&i.Config,
			&i.Result,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ActiveTurnID,
			&i.ActiveWakeupID,
			&i.LastEventAt,
			&i.SpawningThreadID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskDagNodes = `-- name: ListTaskDagNodes :many
SELECT id, dag_key, node_key, title, node_type, assigned_to, depends_on, status, command_ref, config, result, started_at, finished_at, created_at, updated_at, active_turn_id, active_wakeup_id, last_event_at, spawning_thread_id
FROM task_dag_nodes
WHERE dag_key = $1
ORDER BY created_at
`

func (q *Queries) ListTaskDagNodes(ctx context.Context, dagKey string) ([]TaskDagNode, error) {
	rows, err := q.db.Query(ctx, listTaskDagNodes, dagKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskDagNode{}
	for rows.Next() {
		var i TaskDagNode
		if err := rows.Scan(
			&i.ID,
			&i.DagKey,
			&i.NodeKey,
			&i.Title,
			&i.NodeType,
			&i.AssignedTo,
			&i.DependsOn,
			&i.Status,
			&i.CommandRef,
			&i.Config,
			&i.Result,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ActiveTurnID,
			&i.ActiveWakeupID,
			&i.LastEventAt,
			&i.SpawningThreadID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
