// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_dag_dag.sql

package sqlc

import (
	"context"
)

const getTaskDag = `-- name: GetTaskDag :one
SELECT id, dag_key, title, description, status, created_by, metadata, started_at, finished_at, created_at, updated_at
FROM task_dags
WHERE dag_key = $1
`

func (q *Queries) GetTaskDag(ctx context.Context, dagKey string) (TaskDag, error) {
	row := q.db.QueryRow(ctx, getTaskDag, dagKey)
	var i TaskDag
	err := row.Scan(
		&i.ID,
		&i.DagKey,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedBy,
		&i.Metadata,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskDagForUpdate = `-- name: GetTaskDagForUpdate :one
SELECT id, dag_key, title, description, status, created_by, metadata, started_at, finished_at, created_at, updated_at
FROM task_dags
WHERE dag_key = $1
FOR UPDATE
`

func (q *Queries) GetTaskDagForUpdate(ctx context.Context, dagKey string) (TaskDag, error) {
	row := q.db.QueryRow(ctx, getTaskDagForUpdate, dagKey)
	var i TaskDag
	err := row.Scan(
		&i.ID,
		&i.DagKey,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedBy,
		&i.Metadata,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTaskDags = `-- name: ListTaskDags :many
SELECT id, dag_key, title, description, status, created_by, metadata, started_at, finished_at, created_at, updated_at
FROM task_dags
WHERE ($1::text = '' OR status = $1)
  AND ($2::text = ''
    OR dag_key ILIKE '%' || $2 || '%'
    OR title ILIKE '%' || $2 || '%'
    OR description ILIKE '%' || $2 || '%')
ORDER BY updated_at DESC, id DESC
LIMIT $3
`

type ListTaskDagsParams struct {
	Column1 string `db:"column_1" json:"column_1"`
	Column2 string `db:"column_2" json:"column_2"`
	Limit   int32  `db:"limit" json:"limit"`
}

func (q *Queries) ListTaskDags(ctx context.Context, arg ListTaskDagsParams) ([]TaskDag, error) {
	rows, err := q.db.Query(ctx, listTaskDags, arg.Column1, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskDag{}
	for rows.Next() {
		var i TaskDag
		if err := rows.Scan(
			&i.ID,
			&i.DagKey,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedBy,
			&i.Metadata,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTaskDag = `-- name: UpsertTaskDag :one
INSERT INTO task_dags (dag_key, title, description, status, created_by, metadata)
VALUES ($1, $2, $3, $4, $5, $6::jsonb)
ON CONFLICT (dag_key) DO UPDATE
SET title = EXCLUDED.title,
    description = EXCLUDED.description,
    status = EXCLUDED.status,
    created_by = EXCLUDED.created_by,
    metadata = EXCLUDED.metadata,
    updated_at = NOW()
RETURNING id, dag_key, title, description, status, created_by, metadata, started_at, finished_at, created_at, updated_at
`

type UpsertTaskDagParams struct {
	DagKey      string `db:"dag_key" json:"dag_key"`
	Title       string `db:"title" json:"title"`
	Description string `db:"description" json:"description"`
	Status      string `db:"status" json:"status"`
	CreatedBy   string `db:"created_by" json:"created_by"`
	Column6     []byte `db:"column_6" json:"column_6"`
}

func (q *Queries) UpsertTaskDag(ctx context.Context, arg UpsertTaskDagParams) (TaskDag, error) {
	row := q.db.QueryRow(ctx, upsertTaskDag,
		arg.DagKey,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.CreatedBy,
		arg.Column6,
	)
	var i TaskDag
	err := row.Scan(
		&i.ID,
		&i.DagKey,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedBy,
		&i.Metadata,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
