// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_ack.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listTaskAcks = `-- name: ListTaskAcks :many
SELECT id, ack_key, title, description, assigned_to, requested_by, priority, status, progress, ack_message, result_summary, metadata, due_at, acked_at, started_at, finished_at, created_at, updated_at
FROM task_acks
WHERE ($1::text = '' OR status = $1)
  AND ($2::text = '' OR priority = $2)
  AND ($3::text = '' OR assigned_to = $3)
  AND ($4::text = ''
    OR ack_key ILIKE '%' || $4 || '%'
    OR title ILIKE '%' || $4 || '%'
    OR description ILIKE '%' || $4 || '%')
ORDER BY updated_at DESC, id DESC
LIMIT $5
`

type ListTaskAcksParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
	Column4 string `json:"column_4"`
	Limit   int32  `json:"limit"`
}

func (q *Queries) ListTaskAcks(ctx context.Context, arg ListTaskAcksParams) ([]TaskAck, error) {
	rows, err := q.db.Query(ctx, listTaskAcks,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskAck{}
	for rows.Next() {
		var i TaskAck
		if err := rows.Scan(
			&i.ID,
			&i.AckKey,
			&i.Title,
			&i.Description,
			&i.AssignedTo,
			&i.RequestedBy,
			&i.Priority,
			&i.Status,
			&i.Progress,
			&i.AckMessage,
			&i.ResultSummary,
			&i.Metadata,
			&i.DueAt,
			&i.AckedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTaskAck = `-- name: UpsertTaskAck :one
INSERT INTO task_acks (
    ack_key, title, description, assigned_to, requested_by,
    priority, status, progress, ack_message, result_summary, metadata, due_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, GREATEST(0, LEAST($8, 100)), $9, $10, $11::jsonb, $12::timestamptz)
ON CONFLICT (ack_key) DO UPDATE
SET title = EXCLUDED.title,
    description = EXCLUDED.description,
    assigned_to = EXCLUDED.assigned_to,
    requested_by = EXCLUDED.requested_by,
    priority = EXCLUDED.priority,
    status = EXCLUDED.status,
    progress = EXCLUDED.progress,
    ack_message = EXCLUDED.ack_message,
    result_summary = EXCLUDED.result_summary,
    metadata = EXCLUDED.metadata,
    due_at = EXCLUDED.due_at,
    updated_at = NOW()
RETURNING id, ack_key, title, description, assigned_to, requested_by, priority, status, progress, ack_message, result_summary, metadata, due_at, acked_at, started_at, finished_at, created_at, updated_at
`

type UpsertTaskAckParams struct {
	AckKey        string             `json:"ack_key"`
	Title         string             `json:"title"`
	Description   string             `json:"description"`
	AssignedTo    string             `json:"assigned_to"`
	RequestedBy   string             `json:"requested_by"`
	Priority      string             `json:"priority"`
	Status        string             `json:"status"`
	Column8       interface{}        `json:"column_8"`
	AckMessage    string             `json:"ack_message"`
	ResultSummary string             `json:"result_summary"`
	Column11      []byte             `json:"column_11"`
	Column12      pgtype.Timestamptz `json:"column_12"`
}

func (q *Queries) UpsertTaskAck(ctx context.Context, arg UpsertTaskAckParams) (TaskAck, error) {
	row := q.db.QueryRow(ctx, upsertTaskAck,
		arg.AckKey,
		arg.Title,
		arg.Description,
		arg.AssignedTo,
		arg.RequestedBy,
		arg.Priority,
		arg.Status,
		arg.Column8,
		arg.AckMessage,
		arg.ResultSummary,
		arg.Column11,
		arg.Column12,
	)
	var i TaskAck
	err := row.Scan(
		&i.ID,
		&i.AckKey,
		&i.Title,
		&i.Description,
		&i.AssignedTo,
		&i.RequestedBy,
		&i.Priority,
		&i.Status,
		&i.Progress,
		&i.AckMessage,
		&i.ResultSummary,
		&i.Metadata,
		&i.DueAt,
		&i.AckedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
