// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_dag_node_runtime.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bindRunningTaskDagNodeTurn = `-- name: BindRunningTaskDagNodeTurn :one
UPDATE task_dag_nodes
SET active_turn_id = $1,
    last_event_at = NOW(),
    updated_at = NOW()
WHERE dag_key = $2
  AND node_key = $3
  AND run_id = $5
  AND $5::bigint > 0
  AND status = 'running'
  AND active_turn_id IS NULL
  AND active_wakeup_id = $4
RETURNING id, dag_key, node_key, run_id, title, node_type, assigned_to, depends_on, status, command_ref, config, result, started_at, finished_at, created_at, updated_at, active_turn_id, active_wakeup_id, last_event_at, spawning_thread_id
`

type BindRunningTaskDagNodeTurnParams struct {
	ActiveTurnID   pgtype.Text `json:"active_turn_id"`
	DagKey         string      `json:"dag_key"`
	NodeKey        string      `json:"node_key"`
	ActiveWakeupID pgtype.Int8 `json:"active_wakeup_id"`
	RunID          int64       `json:"run_id"`
}

func (q *Queries) BindRunningTaskDagNodeTurn(ctx context.Context, arg BindRunningTaskDagNodeTurnParams) (TaskDagNode, error) {
	row := q.db.QueryRow(ctx, bindRunningTaskDagNodeTurn,
		arg.ActiveTurnID,
		arg.DagKey,
		arg.NodeKey,
		arg.ActiveWakeupID,
		arg.RunID,
	)
	var i TaskDagNode
	err := row.Scan(
		&i.ID,
		&i.DagKey,
		&i.NodeKey,
		&i.RunID,
		&i.Title,
		&i.NodeType,
		&i.AssignedTo,
		&i.DependsOn,
		&i.Status,
		&i.CommandRef,
		&i.Config,
		&i.Result,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveTurnID,
		&i.ActiveWakeupID,
		&i.LastEventAt,
		&i.SpawningThreadID,
	)
	return i, err
}

const completeTaskDagNode = `-- name: CompleteTaskDagNode :one
UPDATE task_dag_nodes
SET status = $1, result = $2::jsonb, active_turn_id = NULL, active_wakeup_id = NULL,
    finished_at = COALESCE(finished_at, NOW()), updated_at = NOW()
WHERE dag_key = $3 AND node_key = $4
  AND run_id = $5
  AND $5::bigint > 0
  AND status IN ('ready', 'running', 'awaiting_verify')
RETURNING id, dag_key, node_key, run_id, title, node_type, assigned_to, depends_on, status, command_ref, config, result, started_at, finished_at, created_at, updated_at, active_turn_id, active_wakeup_id, last_event_at, spawning_thread_id
`

type CompleteTaskDagNodeParams struct {
	Status  string `json:"status"`
	Column2 []byte `json:"column_2"`
	DagKey  string `json:"dag_key"`
	NodeKey string `json:"node_key"`
	RunID   int64  `json:"run_id"`
}

func (q *Queries) CompleteTaskDagNode(ctx context.Context, arg CompleteTaskDagNodeParams) (TaskDagNode, error) {
	row := q.db.QueryRow(ctx, completeTaskDagNode,
		arg.Status,
		arg.Column2,
		arg.DagKey,
		arg.NodeKey,
		arg.RunID,
	)
	var i TaskDagNode
	err := row.Scan(
		&i.ID,
		&i.DagKey,
		&i.NodeKey,
		&i.RunID,
		&i.Title,
		&i.NodeType,
		&i.AssignedTo,
		&i.DependsOn,
		&i.Status,
		&i.CommandRef,
		&i.Config,
		&i.Result,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveTurnID,
		&i.ActiveWakeupID,
		&i.LastEventAt,
		&i.SpawningThreadID,
	)
	return i, err
}

const touchRunningTaskDagNodeEvent = `-- name: TouchRunningTaskDagNodeEvent :one
UPDATE task_dag_nodes
SET last_event_at = $1,
    updated_at = NOW()
WHERE dag_key = $2
  AND node_key = $3
  AND run_id = $5
  AND $5::bigint > 0
  AND status = 'running'
  AND active_turn_id = $4
  AND (last_event_at IS NULL OR last_event_at < $1)
RETURNING id, dag_key, node_key, run_id, title, node_type, assigned_to, depends_on, status, command_ref, config, result, started_at, finished_at, created_at, updated_at, active_turn_id, active_wakeup_id, last_event_at, spawning_thread_id
`

type TouchRunningTaskDagNodeEventParams struct {
	LastEventAt  pgtype.Timestamptz `json:"last_event_at"`
	DagKey       string             `json:"dag_key"`
	NodeKey      string             `json:"node_key"`
	ActiveTurnID pgtype.Text        `json:"active_turn_id"`
	RunID        int64              `json:"run_id"`
}

func (q *Queries) TouchRunningTaskDagNodeEvent(ctx context.Context, arg TouchRunningTaskDagNodeEventParams) (TaskDagNode, error) {
	row := q.db.QueryRow(ctx, touchRunningTaskDagNodeEvent,
		arg.LastEventAt,
		arg.DagKey,
		arg.NodeKey,
		arg.ActiveTurnID,
		arg.RunID,
	)
	var i TaskDagNode
	err := row.Scan(
		&i.ID,
		&i.DagKey,
		&i.NodeKey,
		&i.RunID,
		&i.Title,
		&i.NodeType,
		&i.AssignedTo,
		&i.DependsOn,
		&i.Status,
		&i.CommandRef,
		&i.Config,
		&i.Result,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveTurnID,
		&i.ActiveWakeupID,
		&i.LastEventAt,
		&i.SpawningThreadID,
	)
	return i, err
}

const updateAwaitingVerifyTaskDagNodeStatus = `-- name: UpdateAwaitingVerifyTaskDagNodeStatus :one
UPDATE task_dag_nodes
SET status = $1, result = $2::jsonb, active_turn_id = NULL, active_wakeup_id = NULL, updated_at = NOW()
WHERE dag_key = $3 AND node_key = $4
  AND run_id = $5
  AND $5::bigint > 0
  AND status IN ('running')
RETURNING id, dag_key, node_key, run_id, title, node_type, assigned_to, depends_on, status, command_ref, config, result, started_at, finished_at, created_at, updated_at, active_turn_id, active_wakeup_id, last_event_at, spawning_thread_id
`

type UpdateAwaitingVerifyTaskDagNodeStatusParams struct {
	Status  string `json:"status"`
	Column2 []byte `json:"column_2"`
	DagKey  string `json:"dag_key"`
	NodeKey string `json:"node_key"`
	RunID   int64  `json:"run_id"`
}

func (q *Queries) UpdateAwaitingVerifyTaskDagNodeStatus(ctx context.Context, arg UpdateAwaitingVerifyTaskDagNodeStatusParams) (TaskDagNode, error) {
	row := q.db.QueryRow(ctx, updateAwaitingVerifyTaskDagNodeStatus,
		arg.Status,
		arg.Column2,
		arg.DagKey,
		arg.NodeKey,
		arg.RunID,
	)
	var i TaskDagNode
	err := row.Scan(
		&i.ID,
		&i.DagKey,
		&i.NodeKey,
		&i.RunID,
		&i.Title,
		&i.NodeType,
		&i.AssignedTo,
		&i.DependsOn,
		&i.Status,
		&i.CommandRef,
		&i.Config,
		&i.Result,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveTurnID,
		&i.ActiveWakeupID,
		&i.LastEventAt,
		&i.SpawningThreadID,
	)
	return i, err
}

const updateRunningTaskDagNodeStatus = `-- name: UpdateRunningTaskDagNodeStatus :one
UPDATE task_dag_nodes
SET status = $1, result = $2::jsonb, active_turn_id = NULL, active_wakeup_id = $3,
    last_event_at = NULL, started_at = COALESCE(started_at, NOW()), updated_at = NOW()
WHERE dag_key = $4 AND node_key = $5
  AND run_id = $6
  AND $6::bigint > 0
  AND status IN ('pending', 'ready')
RETURNING id, dag_key, node_key, run_id, title, node_type, assigned_to, depends_on, status, command_ref, config, result, started_at, finished_at, created_at, updated_at, active_turn_id, active_wakeup_id, last_event_at, spawning_thread_id
`

type UpdateRunningTaskDagNodeStatusParams struct {
	Status         string      `json:"status"`
	Column2        []byte      `json:"column_2"`
	ActiveWakeupID pgtype.Int8 `json:"active_wakeup_id"`
	DagKey         string      `json:"dag_key"`
	NodeKey        string      `json:"node_key"`
	RunID          int64       `json:"run_id"`
}

func (q *Queries) UpdateRunningTaskDagNodeStatus(ctx context.Context, arg UpdateRunningTaskDagNodeStatusParams) (TaskDagNode, error) {
	row := q.db.QueryRow(ctx, updateRunningTaskDagNodeStatus,
		arg.Status,
		arg.Column2,
		arg.ActiveWakeupID,
		arg.DagKey,
		arg.NodeKey,
		arg.RunID,
	)
	var i TaskDagNode
	err := row.Scan(
		&i.ID,
		&i.DagKey,
		&i.NodeKey,
		&i.RunID,
		&i.Title,
		&i.NodeType,
		&i.AssignedTo,
		&i.DependsOn,
		&i.Status,
		&i.CommandRef,
		&i.Config,
		&i.Result,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveTurnID,
		&i.ActiveWakeupID,
		&i.LastEventAt,
		&i.SpawningThreadID,
	)
	return i, err
}
