// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_dag_run.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveTaskDagRunsByKey = `-- name: CountActiveTaskDagRunsByKey :one
SELECT COUNT(*)::bigint AS active
FROM task_dag_runs
WHERE dag_key = $1 AND status = 'running'
`

// StartDAG 用于多 run 并发 reject：当且仅当 0 时才允许新 run。
// T1.2-mid 限制；F6.5 升级 multi-run 后此 query 不再被 StartDAG 调用。
func (q *Queries) CountActiveTaskDagRunsByKey(ctx context.Context, dagKey string) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveTaskDagRunsByKey, dagKey)
	var active int64
	err := row.Scan(&active)
	return active, err
}

const createTaskDagRun = `-- name: CreateTaskDagRun :one

INSERT INTO task_dag_runs (run_key, dag_key, dag_version_snapshot, trigger_source, status, metadata, budget_limit)
VALUES ($1, $2, $3, $4, 'running', $5::jsonb, $6)
RETURNING id, run_key, dag_key, dag_version_snapshot, trigger_source, status, started_at, finished_at, events, budget_used, budget_limit, metadata, created_at, updated_at
`

type CreateTaskDagRunParams struct {
	RunKey             string      `json:"run_key"`
	DagKey             string      `json:"dag_key"`
	DagVersionSnapshot int64       `json:"dag_version_snapshot"`
	TriggerSource      string      `json:"trigger_source"`
	Column5            []byte      `json:"column_5"`
	BudgetLimit        pgtype.Int8 `json:"budget_limit"`
}

// DAG v2 T1.2-mid: task_dag_runs CRUD + 根节点 promote 入口。
// 蓝图 v2 §5 决策 C 混合：每次 StartDAG 创建一条 run；T1.2-mid 阶段单 DAG
// 单 run，多并发 reject。F6.5 升级为 multi-run + 节点复制带 run_id。
// StartDAG 调用：插入新 run；run_key 由 service 层生成（保证 UNIQUE）。
// dag_version_snapshot 由调用方从 task_dags.version 当前值传入，保证
// run 创建后 DAG 模板被改不影响这次 run（Temporal 风格）。
func (q *Queries) CreateTaskDagRun(ctx context.Context, arg CreateTaskDagRunParams) (TaskDagRun, error) {
	row := q.db.QueryRow(ctx, createTaskDagRun,
		arg.RunKey,
		arg.DagKey,
		arg.DagVersionSnapshot,
		arg.TriggerSource,
		arg.Column5,
		arg.BudgetLimit,
	)
	var i TaskDagRun
	err := row.Scan(
		&i.ID,
		&i.RunKey,
		&i.DagKey,
		&i.DagVersionSnapshot,
		&i.TriggerSource,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Events,
		&i.BudgetUsed,
		&i.BudgetLimit,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskDagRun = `-- name: GetTaskDagRun :one
SELECT id, run_key, dag_key, dag_version_snapshot, trigger_source, status, started_at, finished_at, events, budget_used, budget_limit, metadata, created_at, updated_at
FROM task_dag_runs
WHERE run_key = $1
`

func (q *Queries) GetTaskDagRun(ctx context.Context, runKey string) (TaskDagRun, error) {
	row := q.db.QueryRow(ctx, getTaskDagRun, runKey)
	var i TaskDagRun
	err := row.Scan(
		&i.ID,
		&i.RunKey,
		&i.DagKey,
		&i.DagVersionSnapshot,
		&i.TriggerSource,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Events,
		&i.BudgetUsed,
		&i.BudgetLimit,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTaskDagRunsByKey = `-- name: ListTaskDagRunsByKey :many
SELECT id, run_key, dag_key, dag_version_snapshot, trigger_source, status, started_at, finished_at, events, budget_used, budget_limit, metadata, created_at, updated_at
FROM task_dag_runs
WHERE dag_key = $1
  AND ($2::text = '' OR status = $2)
ORDER BY started_at DESC, id DESC
LIMIT $3
`

type ListTaskDagRunsByKeyParams struct {
	DagKey  string `json:"dag_key"`
	Column2 string `json:"column_2"`
	Limit   int32  `json:"limit"`
}

// 按 dag_key + 可选 status 过滤；空 status 表示全部状态。
// 与 ListTaskDags 风格一致：$2=” 当作未过滤。
func (q *Queries) ListTaskDagRunsByKey(ctx context.Context, arg ListTaskDagRunsByKeyParams) ([]TaskDagRun, error) {
	rows, err := q.db.Query(ctx, listTaskDagRunsByKey, arg.DagKey, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskDagRun{}
	for rows.Next() {
		var i TaskDagRun
		if err := rows.Scan(
			&i.ID,
			&i.RunKey,
			&i.DagKey,
			&i.DagVersionSnapshot,
			&i.TriggerSource,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Events,
			&i.BudgetUsed,
			&i.BudgetLimit,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteRootNodesToReady = `-- name: PromoteRootNodesToReady :execrows
UPDATE task_dag_nodes
SET status = 'ready',
    updated_at = NOW()
WHERE dag_key = $1
  AND status = 'pending'
  AND jsonb_array_length(depends_on) = 0
`

// StartDAG 在新 run 创建后调用：把 dag_key 下所有 depends_on=[] 且 status='pending'
// 的根节点提升为 'ready'。返回受影响行数（service 层用于断言至少一个根节点被
// 提升，否则视为 DAG 无可执行起点）。
// 状态机：pending → ready 是合法转移（见 nodeexec/types.go ValidTransitions）。
func (q *Queries) PromoteRootNodesToReady(ctx context.Context, dagKey string) (int64, error) {
	result, err := q.db.Exec(ctx, promoteRootNodesToReady, dagKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

// finalizeTaskDagRunIfAllNodesTerminal 是 F6.2 新增的 :many query。sqlc
// generate 下次 realignment 会重写本函数；现阶段按 models.go 的 omit_unused_structs
// 手维额外生代码。SQL 语义详见 cmd/mcp-orch/sql/queries/task_dag_run.sql
// 同名查询注释。
//
// finalizeTaskDagRunIfAllNodesTerminal mirrors the same-named query in
// cmd/mcp-orch/sql/queries/task_dag_run.sql. Kept hand-maintained for the same
// reason models.TaskDagRun is hand-maintained (sqlc realignment out of scope).
const finalizeTaskDagRunIfAllNodesTerminal = `-- name: FinalizeTaskDagRunIfAllNodesTerminal :many
WITH node_counts AS (
  SELECT
    COUNT(*) FILTER (WHERE status NOT IN ('done','failed','cancelled','skipped')) AS non_terminal,
    COUNT(*) FILTER (WHERE status = 'failed')    AS failed_cnt,
    COUNT(*) FILTER (WHERE status = 'cancelled') AS cancelled_cnt,
    COUNT(*)                                     AS total
  FROM task_dag_nodes
  WHERE dag_key = $1
),
final AS (
  SELECT CASE
    WHEN total = 0        THEN NULL
    WHEN non_terminal > 0 THEN NULL
    WHEN failed_cnt > 0   THEN 'failed'
    WHEN cancelled_cnt > 0 THEN 'cancelled'
    ELSE 'succeeded'
  END AS final_status
  FROM node_counts
),
dag_meta AS (
  SELECT NULLIF(metadata->>'final_node_key', '') AS final_node_key
  FROM task_dags
  WHERE dag_key = $1
),
final_node AS (
  SELECT
    n.node_key,
    n.title,
    n.result,
    NULLIF(n.config->'outputs'->'to_sharedfile'->>'path', '') AS configured_sharedfile_path
  FROM task_dag_nodes n
  JOIN dag_meta dm ON dm.final_node_key = n.node_key
  WHERE n.dag_key = $1
  LIMIT 1
),
final_output AS (
  SELECT CASE
    WHEN result IS NOT NULL
      AND jsonb_typeof(result) = 'object'
      AND jsonb_typeof(result->'sharedfile') = 'object'
      AND NULLIF(result->'sharedfile'->>'path', '') IS NOT NULL
    THEN jsonb_build_object(
      'kind', 'file',
      'role', 'final_output',
      'title', COALESCE(NULLIF(title, ''), 'Final output'),
      'path', result->'sharedfile'->>'path',
      'source_node_key', node_key
    )
    WHEN configured_sharedfile_path IS NOT NULL
    THEN jsonb_build_object(
      'kind', 'file',
      'role', 'final_output',
      'title', COALESCE(NULLIF(title, ''), 'Final output'),
      'path', configured_sharedfile_path,
      'source_node_key', node_key
    )
    WHEN result IS NULL THEN NULL
    WHEN jsonb_typeof(result) = 'string'
    THEN jsonb_build_object(
      'kind', 'text',
      'role', 'final_output',
      'title', COALESCE(NULLIF(title, ''), 'Final output'),
      'source_node_key', node_key,
      'text', result #>> '{}'
    )
    ELSE jsonb_build_object(
      'kind', 'json',
      'role', 'final_output',
      'title', COALESCE(NULLIF(title, ''), 'Final output'),
      'source_node_key', node_key,
      'result', result
    )
  END AS value
  FROM final_node
)
UPDATE task_dag_runs r
SET status      = (SELECT final_status FROM final),
    finished_at = NOW(),
    updated_at  = NOW(),
    metadata    = CASE
      WHEN (SELECT final_status FROM final) = 'succeeded'
        AND (SELECT value FROM final_output) IS NOT NULL
      THEN jsonb_set(
        CASE
          WHEN jsonb_typeof(r.metadata) = 'object' THEN r.metadata
          ELSE '{}'::jsonb
        END,
        '{final_output}',
        (SELECT value FROM final_output),
        true
      )
      ELSE r.metadata
    END
WHERE r.dag_key = $1
  AND r.status = 'running'
  AND (SELECT final_status FROM final) IS NOT NULL
RETURNING r.run_key, r.status
`

// FinalizeTaskDagRunIfAllNodesTerminalRow 是 finalize 查询返回的最小投影（run_key + status）。
// FinalizeTaskDagRunIfAllNodesTerminalRow is the projection returned by the
// finalize query (run_key + status).
type FinalizeTaskDagRunIfAllNodesTerminalRow struct {
	RunKey string `json:"run_key"`
	Status string `json:"status"`
}

// FinalizeTaskDagRunIfAllNodesTerminal 调用 finalize SQL。受影响 0 行时返回空
// slice（表示节点还未全部终态或 dag_key 下已无 'running' run）；受影响 1 行
// 时返回包含被推进 run 的 run_key + 新终态 status。
//
// FinalizeTaskDagRunIfAllNodesTerminal runs the finalize SQL. An empty slice
// means the statement was a no-op (either some nodes are still non-terminal
// or no 'running' run exists for dag_key). A one-element slice carries the
// (run_key, status) of the row that was just flipped to its terminal status.
func (q *Queries) FinalizeTaskDagRunIfAllNodesTerminal(ctx context.Context, dagKey string) ([]FinalizeTaskDagRunIfAllNodesTerminalRow, error) {
	rows, err := q.db.Query(ctx, finalizeTaskDagRunIfAllNodesTerminal, dagKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FinalizeTaskDagRunIfAllNodesTerminalRow{}
	for rows.Next() {
		var i FinalizeTaskDagRunIfAllNodesTerminalRow
		if err := rows.Scan(&i.RunKey, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const appendTaskDagRunEvent = `-- name: AppendTaskDagRunEvent :one
UPDATE task_dag_runs
SET events     = CASE
        WHEN jsonb_array_length(events || jsonb_build_array($2::jsonb)) <= 50
            THEN events || jsonb_build_array($2::jsonb)
        ELSE COALESCE((
            SELECT jsonb_agg(elem ORDER BY ord)
            FROM jsonb_array_elements(events || jsonb_build_array($2::jsonb)) WITH ORDINALITY AS t(elem, ord)
            WHERE ord > jsonb_array_length(events || jsonb_build_array($2::jsonb)) - 50
        ), '[]'::jsonb)
    END,
    updated_at = NOW()
WHERE dag_key = $1 AND status = 'running'
RETURNING run_key
`

// AppendTaskDagRunEventParams binds (dag_key, event_json) for the events
// jsonb array append in task_dag_runs. The event payload should be a single
// JSON object; the SQL wraps it with jsonb_build_array() so the || operator
// always runs array-append semantics, even when bind would otherwise feed an
// object into || (which PG treats as object-merge, silently losing history).
// R1 P0 #1 工艺修复：see queries/task_dag_run.sql for the long-form rationale.
type AppendTaskDagRunEventParams struct {
	DagKey  string `json:"dag_key"`
	Column2 []byte `json:"column_2"`
}

// AppendTaskDagRunEvent appends a JSON event to the running run's events
// jsonb array. Returns pgx.ErrNoRows when there is no running run for the
// dag_key (callers may treat that as a soft miss; the store layer wraps with
// platformdb.IsNotFound).
func (q *Queries) AppendTaskDagRunEvent(ctx context.Context, arg AppendTaskDagRunEventParams) (string, error) {
	row := q.db.QueryRow(ctx, appendTaskDagRunEvent, arg.DagKey, arg.Column2)
	var runKey string
	err := row.Scan(&runKey)
	return runKey, err
}
