// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_dag_node_runtime.sql

package sqlc

import (
	"context"
	"encoding/json"
)

const bindRunningTaskDagNodeTurn = `-- name: BindRunningTaskDagNodeTurn :execrows
UPDATE task_dag_nodes
SET active_turn_id = ?1,
    last_event_at = (CAST(strftime('%s','now') AS INTEGER) * 1000),
    updated_at = (CAST(strftime('%s','now') AS INTEGER) * 1000)
WHERE dag_key = ?2
  AND node_key = ?3
  AND run_id = ?4
  AND ?4 > 0
  AND status = 'running'
  AND active_turn_id IS NULL
  AND active_wakeup_id = ?5
`

type BindRunningTaskDagNodeTurnParams struct {
	ActiveTurnID   *string `db:"active_turn_id" json:"active_turn_id"`
	DagKey         string  `db:"dag_key" json:"dag_key"`
	NodeKey        string  `db:"node_key" json:"node_key"`
	RunID          *int64  `db:"run_id" json:"run_id"`
	ActiveWakeupID *int64  `db:"active_wakeup_id" json:"active_wakeup_id"`
}

func (q *Queries) BindRunningTaskDagNodeTurn(ctx context.Context, arg BindRunningTaskDagNodeTurnParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, bindRunningTaskDagNodeTurn,
		arg.ActiveTurnID,
		arg.DagKey,
		arg.NodeKey,
		arg.RunID,
		arg.ActiveWakeupID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completeTaskDagNode = `-- name: CompleteTaskDagNode :execrows
UPDATE task_dag_nodes
SET status = ?1, result = ?2, active_turn_id = NULL, active_wakeup_id = NULL,
    finished_at = COALESCE(finished_at, (CAST(strftime('%s','now') AS INTEGER) * 1000)), updated_at = (CAST(strftime('%s','now') AS INTEGER) * 1000)
WHERE task_dag_nodes.dag_key = ?3 AND task_dag_nodes.node_key = ?4
  AND task_dag_nodes.run_id = ?5
  AND ?5 > 0
  AND status IN ('ready', 'running')
  AND (
    CAST(?6 AS INTEGER) = 0
    OR (
      task_dag_nodes.active_wakeup_id = CAST(?6 AS INTEGER)
      AND task_dag_nodes.active_wakeup_id IN (
        SELECT w.id
        FROM task_dag_wakeups w
        WHERE w.id = CAST(?6 AS INTEGER)
          AND w.run_id = task_dag_nodes.run_id
          AND w.dag_key = task_dag_nodes.dag_key
          AND w.node_key = task_dag_nodes.node_key
          AND w.attempt_count = ?7
      )
    )
  )
`

type CompleteTaskDagNodeParams struct {
	Status        string          `db:"status" json:"status"`
	Result        json.RawMessage `db:"result" json:"result"`
	DagKey        string          `db:"dag_key" json:"dag_key"`
	NodeKey       string          `db:"node_key" json:"node_key"`
	RunID         *int64          `db:"run_id" json:"run_id"`
	WakeupID      int64           `db:"wakeup_id" json:"wakeup_id"`
	WakeupAttempt int64           `db:"wakeup_attempt" json:"wakeup_attempt"`
}

func (q *Queries) CompleteTaskDagNode(ctx context.Context, arg CompleteTaskDagNodeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeTaskDagNode,
		arg.Status,
		arg.Result,
		arg.DagKey,
		arg.NodeKey,
		arg.RunID,
		arg.WakeupID,
		arg.WakeupAttempt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listDispatchIncompleteNodesByUpdatedAt = `-- name: ListDispatchIncompleteNodesByUpdatedAt :many
SELECT id, dag_key, node_key, title, node_type, assigned_to, CAST(depends_on AS BLOB) AS depends_on,
       status, command_ref, CAST(config AS BLOB) AS config, CAST(result AS BLOB) AS result, started_at, finished_at,
       created_at, updated_at, active_turn_id, active_wakeup_id,
       last_event_at, run_id, CAST(reads AS BLOB) AS reads, CAST(writes AS BLOB) AS writes, spawning_thread_id
FROM task_dag_nodes
WHERE status = 'dispatch_incomplete'
  AND updated_at = ?1
ORDER BY id
`

type ListDispatchIncompleteNodesByUpdatedAtParams struct {
	UpdatedAt int64 `db:"updated_at" json:"updated_at"`
}

type ListDispatchIncompleteNodesByUpdatedAtRow struct {
	ID               int64   `db:"id" json:"id"`
	DagKey           string  `db:"dag_key" json:"dag_key"`
	NodeKey          string  `db:"node_key" json:"node_key"`
	Title            string  `db:"title" json:"title"`
	NodeType         string  `db:"node_type" json:"node_type"`
	AssignedTo       string  `db:"assigned_to" json:"assigned_to"`
	DependsOn        []byte  `db:"depends_on" json:"depends_on"`
	Status           string  `db:"status" json:"status"`
	CommandRef       string  `db:"command_ref" json:"command_ref"`
	Config           []byte  `db:"config" json:"config"`
	Result           []byte  `db:"result" json:"result"`
	StartedAt        *int64  `db:"started_at" json:"started_at"`
	FinishedAt       *int64  `db:"finished_at" json:"finished_at"`
	CreatedAt        int64   `db:"created_at" json:"created_at"`
	UpdatedAt        int64   `db:"updated_at" json:"updated_at"`
	ActiveTurnID     *string `db:"active_turn_id" json:"active_turn_id"`
	ActiveWakeupID   *int64  `db:"active_wakeup_id" json:"active_wakeup_id"`
	LastEventAt      *int64  `db:"last_event_at" json:"last_event_at"`
	RunID            *int64  `db:"run_id" json:"run_id"`
	Reads            []byte  `db:"reads" json:"reads"`
	Writes           []byte  `db:"writes" json:"writes"`
	SpawningThreadID *string `db:"spawning_thread_id" json:"spawning_thread_id"`
}

func (q *Queries) ListDispatchIncompleteNodesByUpdatedAt(ctx context.Context, arg ListDispatchIncompleteNodesByUpdatedAtParams) ([]ListDispatchIncompleteNodesByUpdatedAtRow, error) {
	rows, err := q.db.QueryContext(ctx, listDispatchIncompleteNodesByUpdatedAt, arg.UpdatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDispatchIncompleteNodesByUpdatedAtRow{}
	for rows.Next() {
		var i ListDispatchIncompleteNodesByUpdatedAtRow
		if err := rows.Scan(
			&i.ID,
			&i.DagKey,
			&i.NodeKey,
			&i.Title,
			&i.NodeType,
			&i.AssignedTo,
			&i.DependsOn,
			&i.Status,
			&i.CommandRef,
			&i.Config,
			&i.Result,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ActiveTurnID,
			&i.ActiveWakeupID,
			&i.LastEventAt,
			&i.RunID,
			&i.Reads,
			&i.Writes,
			&i.SpawningThreadID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDispatchIncompleteNodesWithoutActiveWakeup = `-- name: MarkDispatchIncompleteNodesWithoutActiveWakeup :execrows
UPDATE task_dag_nodes
SET status = 'dispatch_incomplete',
    result = '{"kind":"dispatch_incomplete","reason":"assigned_without_active_wakeup"}',
    active_turn_id = NULL,
    active_wakeup_id = NULL,
    updated_at = ?1
WHERE run_id IS NOT NULL
  AND status IN ('pending', 'ready')
  AND trim(assigned_to) <> ''
  AND id NOT IN (
      SELECT n.id
      FROM task_dag_nodes n
      JOIN task_dag_wakeups w
        ON w.run_id = n.run_id
       AND w.dag_key = n.dag_key
       AND w.node_key = n.node_key
      WHERE w.status IN ('pending', 'dispatching')
         OR (w.status = 'sent' AND w.sent_at IS NOT NULL AND w.bound_turn_id IS NULL)
  )
`

type MarkDispatchIncompleteNodesWithoutActiveWakeupParams struct {
	UpdatedAt int64 `db:"updated_at" json:"updated_at"`
}

func (q *Queries) MarkDispatchIncompleteNodesWithoutActiveWakeup(ctx context.Context, arg MarkDispatchIncompleteNodesWithoutActiveWakeupParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markDispatchIncompleteNodesWithoutActiveWakeup, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchRunningTaskDagNodeEvent = `-- name: TouchRunningTaskDagNodeEvent :execrows
UPDATE task_dag_nodes
SET last_event_at = ?1,
    updated_at = (CAST(strftime('%s','now') AS INTEGER) * 1000)
WHERE dag_key = ?2
  AND node_key = ?3
  AND run_id = ?4
  AND ?4 > 0
  AND status = 'running'
  AND active_turn_id = ?5
  AND (last_event_at IS NULL OR last_event_at < ?1)
`

type TouchRunningTaskDagNodeEventParams struct {
	LastEventAt  *int64  `db:"last_event_at" json:"last_event_at"`
	DagKey       string  `db:"dag_key" json:"dag_key"`
	NodeKey      string  `db:"node_key" json:"node_key"`
	RunID        *int64  `db:"run_id" json:"run_id"`
	ActiveTurnID *string `db:"active_turn_id" json:"active_turn_id"`
}

func (q *Queries) TouchRunningTaskDagNodeEvent(ctx context.Context, arg TouchRunningTaskDagNodeEventParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, touchRunningTaskDagNodeEvent,
		arg.LastEventAt,
		arg.DagKey,
		arg.NodeKey,
		arg.RunID,
		arg.ActiveTurnID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateRunningTaskDagNodeStatus = `-- name: UpdateRunningTaskDagNodeStatus :execrows
UPDATE task_dag_nodes
SET status = ?1, result = ?2, active_turn_id = NULL, active_wakeup_id = ?3,
    last_event_at = NULL, started_at = COALESCE(started_at, (CAST(strftime('%s','now') AS INTEGER) * 1000)), updated_at = (CAST(strftime('%s','now') AS INTEGER) * 1000)
WHERE dag_key = ?4 AND node_key = ?5
  AND run_id = ?6
  AND ?6 > 0
  AND status IN ('pending', 'ready')
`

type UpdateRunningTaskDagNodeStatusParams struct {
	Status         string          `db:"status" json:"status"`
	Result         json.RawMessage `db:"result" json:"result"`
	ActiveWakeupID *int64          `db:"active_wakeup_id" json:"active_wakeup_id"`
	DagKey         string          `db:"dag_key" json:"dag_key"`
	NodeKey        string          `db:"node_key" json:"node_key"`
	RunID          *int64          `db:"run_id" json:"run_id"`
}

func (q *Queries) UpdateRunningTaskDagNodeStatus(ctx context.Context, arg UpdateRunningTaskDagNodeStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateRunningTaskDagNodeStatus,
		arg.Status,
		arg.Result,
		arg.ActiveWakeupID,
		arg.DagKey,
		arg.NodeKey,
		arg.RunID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
