// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_dag_wakeup_dispatch.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bindTaskDagWakeupTurn = `-- name: BindTaskDagWakeupTurn :execrows
UPDATE task_dag_wakeups
SET bound_turn_id = $1, turn_bound_at = NOW(), updated_at = NOW()
WHERE id = $2 AND status = 'sent' AND sent_at IS NOT NULL AND bound_turn_id IS NULL
`

type BindTaskDagWakeupTurnParams struct {
	BoundTurnID pgtype.Text `json:"bound_turn_id"`
	ID          int64       `json:"id"`
}

func (q *Queries) BindTaskDagWakeupTurn(ctx context.Context, arg BindTaskDagWakeupTurnParams) (int64, error) {
	result, err := q.db.Exec(ctx, bindTaskDagWakeupTurn, arg.BoundTurnID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimDueTaskDagWakeups = `-- name: ClaimDueTaskDagWakeups :many
UPDATE task_dag_wakeups
SET status = 'dispatching', claimed_at = NOW(), claimed_by = $1,
    lease_expires_at = NOW() + $2::interval, attempt_count = attempt_count + 1, updated_at = NOW()
WHERE id IN (
    SELECT w.id
    FROM task_dag_wakeups w
    WHERE w.status = 'pending'
      AND w.next_retry_at <= NOW()
      AND (
        BTRIM(w.dag_key) = ''
        OR BTRIM(w.node_key) = ''
        OR EXISTS (
          SELECT 1
          FROM task_dag_runs r
          WHERE r.id = w.run_id
            AND r.dag_key = w.dag_key
            AND r.status = 'running'
        )
      )
    ORDER BY next_retry_at, id
    LIMIT $3
    FOR UPDATE SKIP LOCKED
)
RETURNING id, dag_key, node_key, wakeup_kind, target_agent_id, prompt_payload,
          idempotency_key, status, attempt_count, next_retry_at, claimed_at,
          claimed_by, lease_expires_at, sent_at, bound_turn_id, turn_bound_at,
          last_error, created_at, updated_at, run_id
`

type ClaimDueTaskDagWakeupsParams struct {
	ClaimedBy string          `json:"claimed_by"`
	Column2   pgtype.Interval `json:"column_2"`
	Limit     int32           `json:"limit"`
}

func (q *Queries) ClaimDueTaskDagWakeups(ctx context.Context, arg ClaimDueTaskDagWakeupsParams) ([]TaskDagWakeup, error) {
	rows, err := q.db.Query(ctx, claimDueTaskDagWakeups, arg.ClaimedBy, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskDagWakeup{}
	for rows.Next() {
		var i TaskDagWakeup
		if err := rows.Scan(
			&i.ID,
			&i.DagKey,
			&i.NodeKey,
			&i.WakeupKind,
			&i.TargetAgentID,
			&i.PromptPayload,
			&i.IdempotencyKey,
			&i.Status,
			&i.AttemptCount,
			&i.NextRetryAt,
			&i.ClaimedAt,
			&i.ClaimedBy,
			&i.LeaseExpiresAt,
			&i.SentAt,
			&i.BoundTurnID,
			&i.TurnBoundAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RunID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enqueueTaskDagWakeup = `-- name: EnqueueTaskDagWakeup :execrows
INSERT INTO task_dag_wakeups (dag_key, node_key, run_id, wakeup_kind, target_agent_id, prompt_payload, idempotency_key)
VALUES ($1, $2, $3::bigint, $4, $5, $6::jsonb, $7)
ON CONFLICT (idempotency_key) DO NOTHING
`

type EnqueueTaskDagWakeupParams struct {
	DagKey         string `json:"dag_key"`
	NodeKey        string `json:"node_key"`
	Column3        int64  `json:"column_3"`
	WakeupKind     string `json:"wakeup_kind"`
	TargetAgentID  string `json:"target_agent_id"`
	Column6        []byte `json:"column_6"`
	IdempotencyKey string `json:"idempotency_key"`
}

func (q *Queries) EnqueueTaskDagWakeup(ctx context.Context, arg EnqueueTaskDagWakeupParams) (int64, error) {
	result, err := q.db.Exec(ctx, enqueueTaskDagWakeup,
		arg.DagKey,
		arg.NodeKey,
		arg.Column3,
		arg.WakeupKind,
		arg.TargetAgentID,
		arg.Column6,
		arg.IdempotencyKey,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failTaskDagWakeup = `-- name: FailTaskDagWakeup :execrows
UPDATE task_dag_wakeups
SET status = 'failed', last_error = $1, claimed_at = NULL, claimed_by = '', lease_expires_at = NULL, updated_at = NOW()
WHERE id = $2
  AND status = 'dispatching'
  AND claimed_at = $3
  AND claimed_by = $4
  AND lease_expires_at = $5
  AND lease_expires_at >= NOW()
`

type FailTaskDagWakeupParams struct {
	LastError      string             `json:"last_error"`
	ID             int64              `json:"id"`
	ClaimedAt      pgtype.Timestamptz `json:"claimed_at"`
	ClaimedBy      string             `json:"claimed_by"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
}

func (q *Queries) FailTaskDagWakeup(ctx context.Context, arg FailTaskDagWakeupParams) (int64, error) {
	result, err := q.db.Exec(ctx, failTaskDagWakeup,
		arg.LastError,
		arg.ID,
		arg.ClaimedAt,
		arg.ClaimedBy,
		arg.LeaseExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markTaskDagWakeupSent = `-- name: MarkTaskDagWakeupSent :execrows
UPDATE task_dag_wakeups
SET status = 'sent', sent_at = NOW(), updated_at = NOW()
WHERE id = $1
  AND status = 'dispatching'
  AND claimed_at = $2
  AND claimed_by = $3
  AND lease_expires_at = $4
  AND lease_expires_at >= NOW()
`

type MarkTaskDagWakeupSentParams struct {
	ID             int64              `json:"id"`
	ClaimedAt      pgtype.Timestamptz `json:"claimed_at"`
	ClaimedBy      string             `json:"claimed_by"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
}

func (q *Queries) MarkTaskDagWakeupSent(ctx context.Context, arg MarkTaskDagWakeupSentParams) (int64, error) {
	result, err := q.db.Exec(ctx, markTaskDagWakeupSent,
		arg.ID,
		arg.ClaimedAt,
		arg.ClaimedBy,
		arg.LeaseExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retryTaskDagWakeup = `-- name: RetryTaskDagWakeup :execrows
UPDATE task_dag_wakeups
SET status = 'pending', next_retry_at = NOW() + $1::interval, last_error = $2,
    claimed_at = NULL, claimed_by = '', lease_expires_at = NULL, updated_at = NOW()
WHERE id = $3
  AND status = 'dispatching'
  AND claimed_at = $4
  AND claimed_by = $5
  AND lease_expires_at = $6
  AND lease_expires_at >= NOW()
  AND attempt_count < 8
`

type RetryTaskDagWakeupParams struct {
	Column1        pgtype.Interval    `json:"column_1"`
	LastError      string             `json:"last_error"`
	ID             int64              `json:"id"`
	ClaimedAt      pgtype.Timestamptz `json:"claimed_at"`
	ClaimedBy      string             `json:"claimed_by"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
}

func (q *Queries) RetryTaskDagWakeup(ctx context.Context, arg RetryTaskDagWakeupParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryTaskDagWakeup,
		arg.Column1,
		arg.LastError,
		arg.ID,
		arg.ClaimedAt,
		arg.ClaimedBy,
		arg.LeaseExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
