// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_dag_node_spawning_thread.sql

package sqlc

import (
	"context"
)

const updateTaskDagNodeSpawningThread = `-- name: UpdateTaskDagNodeSpawningThread :execrows
UPDATE task_dag_nodes
SET spawning_thread_id = ?1,
    updated_at = (CAST(strftime('%s','now') AS INTEGER) * 1000)
WHERE dag_key = ?2
  AND node_key = ?3
  AND run_id = ?4
  AND ?4 > 0
  AND status NOT IN ('done', 'failed', 'cancelled', 'skipped')
  AND (
      spawning_thread_id IS NULL
      OR TRIM(spawning_thread_id) = ''
      OR TRIM(spawning_thread_id) = TRIM(COALESCE(?1, ''))
  )
`

type UpdateTaskDagNodeSpawningThreadParams struct {
	SpawningThreadID *string `db:"spawning_thread_id" json:"spawning_thread_id"`
	DagKey           string  `db:"dag_key" json:"dag_key"`
	NodeKey          string  `db:"node_key" json:"node_key"`
	RunID            *int64  `db:"run_id" json:"run_id"`
}

func (q *Queries) UpdateTaskDagNodeSpawningThread(ctx context.Context, arg UpdateTaskDagNodeSpawningThreadParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTaskDagNodeSpawningThread,
		arg.SpawningThreadID,
		arg.DagKey,
		arg.NodeKey,
		arg.RunID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
