// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace_run.sql

package sqlc

import (
	"context"
	"encoding/json"
)

const getWorkspaceRun = `-- name: GetWorkspaceRun :one
SELECT id, run_key, dag_key, source_root, workspace_path, status, created_by, updated_by, CAST(metadata AS BLOB) AS metadata, created_at, updated_at, finished_at
FROM workspace_runs
WHERE
    run_key = ?1
`

type GetWorkspaceRunParams struct {
	RunKey string `db:"run_key" json:"run_key"`
}

type GetWorkspaceRunRow struct {
	ID            int64  `db:"id" json:"id"`
	RunKey        string `db:"run_key" json:"run_key"`
	DagKey        string `db:"dag_key" json:"dag_key"`
	SourceRoot    string `db:"source_root" json:"source_root"`
	WorkspacePath string `db:"workspace_path" json:"workspace_path"`
	Status        string `db:"status" json:"status"`
	CreatedBy     string `db:"created_by" json:"created_by"`
	UpdatedBy     string `db:"updated_by" json:"updated_by"`
	Metadata      []byte `db:"metadata" json:"metadata"`
	CreatedAt     int64  `db:"created_at" json:"created_at"`
	UpdatedAt     int64  `db:"updated_at" json:"updated_at"`
	FinishedAt    *int64 `db:"finished_at" json:"finished_at"`
}

func (q *Queries) GetWorkspaceRun(ctx context.Context, arg GetWorkspaceRunParams) (GetWorkspaceRunRow, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceRun, arg.RunKey)
	var i GetWorkspaceRunRow
	err := row.Scan(
		&i.ID,
		&i.RunKey,
		&i.DagKey,
		&i.SourceRoot,
		&i.WorkspacePath,
		&i.Status,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getWorkspaceRunFile = `-- name: GetWorkspaceRunFile :one
SELECT id, run_key, relative_path, baseline_sha256, workspace_sha256, source_sha256_before, source_sha256_after, state, last_error, created_at, updated_at
FROM workspace_run_files
WHERE run_key = ?1 AND relative_path = ?2
`

type GetWorkspaceRunFileParams struct {
	RunKey       string `db:"run_key" json:"run_key"`
	RelativePath string `db:"relative_path" json:"relative_path"`
}

func (q *Queries) GetWorkspaceRunFile(ctx context.Context, arg GetWorkspaceRunFileParams) (WorkspaceRunFile, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceRunFile, arg.RunKey, arg.RelativePath)
	var i WorkspaceRunFile
	err := row.Scan(
		&i.ID,
		&i.RunKey,
		&i.RelativePath,
		&i.BaselineSha256,
		&i.WorkspaceSha256,
		&i.SourceSha256Before,
		&i.SourceSha256After,
		&i.State,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertWorkspaceRun = `-- name: InsertWorkspaceRun :execrows
INSERT INTO workspace_runs (
    run_key, dag_key, source_root, workspace_path, status,
    created_by, updated_by, metadata, created_at, updated_at, finished_at
) VALUES (
    ?1, ?2, ?3, ?4, ?5,
    ?6, ?7, ?8,
    (CAST(strftime('%s','now') AS INTEGER) * 1000),
    (CAST(strftime('%s','now') AS INTEGER) * 1000), ?9
)
`

type InsertWorkspaceRunParams struct {
	RunKey        string          `db:"run_key" json:"run_key"`
	DagKey        string          `db:"dag_key" json:"dag_key"`
	SourceRoot    string          `db:"source_root" json:"source_root"`
	WorkspacePath string          `db:"workspace_path" json:"workspace_path"`
	Status        string          `db:"status" json:"status"`
	CreatedBy     string          `db:"created_by" json:"created_by"`
	UpdatedBy     string          `db:"updated_by" json:"updated_by"`
	Metadata      json.RawMessage `db:"metadata" json:"metadata"`
	FinishedAt    *int64          `db:"finished_at" json:"finished_at"`
}

func (q *Queries) InsertWorkspaceRun(ctx context.Context, arg InsertWorkspaceRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertWorkspaceRun,
		arg.RunKey,
		arg.DagKey,
		arg.SourceRoot,
		arg.WorkspacePath,
		arg.Status,
		arg.CreatedBy,
		arg.UpdatedBy,
		arg.Metadata,
		arg.FinishedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertWorkspaceRunFile = `-- name: InsertWorkspaceRunFile :execrows
INSERT INTO workspace_run_files (
    run_key, relative_path, baseline_sha256, workspace_sha256,
    source_sha256_before, source_sha256_after, state, last_error, created_at, updated_at
) VALUES (
    ?1, ?2, ?3, ?4,
    ?5, ?6, ?7, ?8,
    (CAST(strftime('%s','now') AS INTEGER) * 1000),
    (CAST(strftime('%s','now') AS INTEGER) * 1000)
)
`

type InsertWorkspaceRunFileParams struct {
	RunKey             string `db:"run_key" json:"run_key"`
	RelativePath       string `db:"relative_path" json:"relative_path"`
	BaselineSha256     string `db:"baseline_sha256" json:"baseline_sha256"`
	WorkspaceSha256    string `db:"workspace_sha256" json:"workspace_sha256"`
	SourceSha256Before string `db:"source_sha256_before" json:"source_sha256_before"`
	SourceSha256After  string `db:"source_sha256_after" json:"source_sha256_after"`
	State              string `db:"state" json:"state"`
	LastError          string `db:"last_error" json:"last_error"`
}

func (q *Queries) InsertWorkspaceRunFile(ctx context.Context, arg InsertWorkspaceRunFileParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertWorkspaceRunFile,
		arg.RunKey,
		arg.RelativePath,
		arg.BaselineSha256,
		arg.WorkspaceSha256,
		arg.SourceSha256Before,
		arg.SourceSha256After,
		arg.State,
		arg.LastError,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listWorkspaceRunFiles = `-- name: ListWorkspaceRunFiles :many
SELECT id, run_key, relative_path, baseline_sha256, workspace_sha256, source_sha256_before, source_sha256_after, state, last_error, created_at, updated_at
FROM workspace_run_files
WHERE (?1 = '' OR run_key = ?1)
  AND (?2 = '' OR state = ?2)
ORDER BY updated_at DESC, id DESC
LIMIT ?3
`

type ListWorkspaceRunFilesParams struct {
	RunKeyFilter interface{} `db:"run_key_filter" json:"run_key_filter"`
	StateFilter  interface{} `db:"state_filter" json:"state_filter"`
	LimitCount   int64       `db:"limit_count" json:"limit_count"`
}

func (q *Queries) ListWorkspaceRunFiles(ctx context.Context, arg ListWorkspaceRunFilesParams) ([]WorkspaceRunFile, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaceRunFiles, arg.RunKeyFilter, arg.StateFilter, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceRunFile{}
	for rows.Next() {
		var i WorkspaceRunFile
		if err := rows.Scan(
			&i.ID,
			&i.RunKey,
			&i.RelativePath,
			&i.BaselineSha256,
			&i.WorkspaceSha256,
			&i.SourceSha256Before,
			&i.SourceSha256After,
			&i.State,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceRuns = `-- name: ListWorkspaceRuns :many
SELECT id, run_key, dag_key, source_root, workspace_path, status, created_by, updated_by, CAST('{}' AS BLOB) AS metadata, created_at, updated_at, finished_at
FROM workspace_runs
WHERE (?1 = '' OR status = ?1)
  AND (?2 = '' OR dag_key = ?2)
ORDER BY updated_at DESC, id DESC
LIMIT ?3
`

type ListWorkspaceRunsParams struct {
	StatusFilter interface{} `db:"status_filter" json:"status_filter"`
	DagKeyFilter interface{} `db:"dag_key_filter" json:"dag_key_filter"`
	LimitCount   int64       `db:"limit_count" json:"limit_count"`
}

type ListWorkspaceRunsRow struct {
	ID            int64  `db:"id" json:"id"`
	RunKey        string `db:"run_key" json:"run_key"`
	DagKey        string `db:"dag_key" json:"dag_key"`
	SourceRoot    string `db:"source_root" json:"source_root"`
	WorkspacePath string `db:"workspace_path" json:"workspace_path"`
	Status        string `db:"status" json:"status"`
	CreatedBy     string `db:"created_by" json:"created_by"`
	UpdatedBy     string `db:"updated_by" json:"updated_by"`
	Metadata      []byte `db:"metadata" json:"metadata"`
	CreatedAt     int64  `db:"created_at" json:"created_at"`
	UpdatedAt     int64  `db:"updated_at" json:"updated_at"`
	FinishedAt    *int64 `db:"finished_at" json:"finished_at"`
}

func (q *Queries) ListWorkspaceRuns(ctx context.Context, arg ListWorkspaceRunsParams) ([]ListWorkspaceRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaceRuns, arg.StatusFilter, arg.DagKeyFilter, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceRunsRow{}
	for rows.Next() {
		var i ListWorkspaceRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.RunKey,
			&i.DagKey,
			&i.SourceRoot,
			&i.WorkspacePath,
			&i.Status,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transitionWorkspaceRunStatus = `-- name: TransitionWorkspaceRunStatus :execrows
UPDATE workspace_runs
SET status = ?1,
    updated_by = ?2,
    metadata = ?3,
    updated_at = (CAST(strftime('%s','now') AS INTEGER) * 1000),
    finished_at = ?4
WHERE
    run_key = ?5 AND status = ?6
`

type TransitionWorkspaceRunStatusParams struct {
	NewStatus      string          `db:"new_status" json:"new_status"`
	UpdatedBy      string          `db:"updated_by" json:"updated_by"`
	Metadata       json.RawMessage `db:"metadata" json:"metadata"`
	FinishedAt     *int64          `db:"finished_at" json:"finished_at"`
	RunKey         string          `db:"run_key" json:"run_key"`
	ExpectedStatus string          `db:"expected_status" json:"expected_status"`
}

func (q *Queries) TransitionWorkspaceRunStatus(ctx context.Context, arg TransitionWorkspaceRunStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, transitionWorkspaceRunStatus,
		arg.NewStatus,
		arg.UpdatedBy,
		arg.Metadata,
		arg.FinishedAt,
		arg.RunKey,
		arg.ExpectedStatus,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateWorkspaceRun = `-- name: UpdateWorkspaceRun :execrows
UPDATE workspace_runs
SET dag_key = ?1,
    source_root = ?2,
    workspace_path = ?3,
    status = ?4,
    updated_by = ?5,
    metadata = ?6,
    updated_at = (CAST(strftime('%s','now') AS INTEGER) * 1000),
    finished_at = ?7
WHERE
    run_key = ?8
`

type UpdateWorkspaceRunParams struct {
	DagKey        string          `db:"dag_key" json:"dag_key"`
	SourceRoot    string          `db:"source_root" json:"source_root"`
	WorkspacePath string          `db:"workspace_path" json:"workspace_path"`
	Status        string          `db:"status" json:"status"`
	UpdatedBy     string          `db:"updated_by" json:"updated_by"`
	Metadata      json.RawMessage `db:"metadata" json:"metadata"`
	FinishedAt    *int64          `db:"finished_at" json:"finished_at"`
	RunKey        string          `db:"run_key" json:"run_key"`
}

func (q *Queries) UpdateWorkspaceRun(ctx context.Context, arg UpdateWorkspaceRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateWorkspaceRun,
		arg.DagKey,
		arg.SourceRoot,
		arg.WorkspacePath,
		arg.Status,
		arg.UpdatedBy,
		arg.Metadata,
		arg.FinishedAt,
		arg.RunKey,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateWorkspaceRunFile = `-- name: UpdateWorkspaceRunFile :execrows
UPDATE workspace_run_files
SET baseline_sha256 = ?1,
    workspace_sha256 = ?2,
    source_sha256_before = ?3,
    source_sha256_after = ?4,
    state = ?5,
    last_error = ?6,
    updated_at = (CAST(strftime('%s','now') AS INTEGER) * 1000)
WHERE
    run_key = ?7 AND relative_path = ?8
`

type UpdateWorkspaceRunFileParams struct {
	BaselineSha256     string `db:"baseline_sha256" json:"baseline_sha256"`
	WorkspaceSha256    string `db:"workspace_sha256" json:"workspace_sha256"`
	SourceSha256Before string `db:"source_sha256_before" json:"source_sha256_before"`
	SourceSha256After  string `db:"source_sha256_after" json:"source_sha256_after"`
	State              string `db:"state" json:"state"`
	LastError          string `db:"last_error" json:"last_error"`
	RunKey             string `db:"run_key" json:"run_key"`
	RelativePath       string `db:"relative_path" json:"relative_path"`
}

func (q *Queries) UpdateWorkspaceRunFile(ctx context.Context, arg UpdateWorkspaceRunFileParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateWorkspaceRunFile,
		arg.BaselineSha256,
		arg.WorkspaceSha256,
		arg.SourceSha256Before,
		arg.SourceSha256After,
		arg.State,
		arg.LastError,
		arg.RunKey,
		arg.RelativePath,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateWorkspaceRunStatus = `-- name: UpdateWorkspaceRunStatus :execrows
UPDATE workspace_runs
SET status = ?1,
    updated_by = ?2,
    metadata = ?3,
    updated_at = (CAST(strftime('%s','now') AS INTEGER) * 1000),
    finished_at = ?4
WHERE run_key = ?5
`

type UpdateWorkspaceRunStatusParams struct {
	NewStatus  string          `db:"new_status" json:"new_status"`
	UpdatedBy  string          `db:"updated_by" json:"updated_by"`
	Metadata   json.RawMessage `db:"metadata" json:"metadata"`
	FinishedAt *int64          `db:"finished_at" json:"finished_at"`
	RunKey     string          `db:"run_key" json:"run_key"`
}

func (q *Queries) UpdateWorkspaceRunStatus(ctx context.Context, arg UpdateWorkspaceRunStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateWorkspaceRunStatus,
		arg.NewStatus,
		arg.UpdatedBy,
		arg.Metadata,
		arg.FinishedAt,
		arg.RunKey,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
