// @ts-check

import {
  validateBuiltinToolsResponse,
  validateLspPromptHintResponse,
  validateRuntimeConfigResponse,
  validateWindowBootstrapResponse,
} from "./core/config.js";
import {
  validateCodeSaveResponse,
  validateDashboardLogsResponse,
  validateDashboardPageResponse,
  validateFrontendIngestResponse,
  validateNullResponse,
  validateOKResponse,
  validateOpenWindowResponse,
  validateProjectsStateResponse,
  validateVideoAPIKeyStatusResponse,
} from "./core/desktop.js";
import { validateAppUpdateInstallResponse, validateSkillReadResponse } from "./core/services.js";
import {
  validateThreadCompactResponse,
  validateThreadConfigResponse,
} from "./core/thread-config.js";
import {
  validateThreadForkResponse,
  validateThreadMessagesResponse,
  validateThreadResolveResponse,
  validateThreadStartResponse,
  validateTurnForceCompleteResponse,
  validateTurnStartResponse,
} from "./core/thread-actions.js";
import {
  validateDashboardDagCreateAndStartResponse,
  validateDashboardDagStartResponse,
} from "./core/workflow.js";
import {
  validateDatasourceChunksResponse,
  validateDatasourceDeleteResponse,
  validateDatasourceDetailResponse,
  validateDatasourceDocumentResponse,
  validateDatasourceDocumentsResponse,
  validateDatasourceImportResponse,
} from "./datasource.js";
import {
  createMCPServerControlResponseValidator,
  validateMCPServerListResponse,
  validateModelProviderRegistryResponse,
} from "./mcp-model-provider.js";
import {
  validateCronDeleteResponse,
  validateCronJobResponse,
  validateCronListRunsResponse,
  validateCronListResponse,
  validateCronSetEnabledResponse,
} from "./runtime/cron.js";
import { validateSidebarStateResponse } from "./runtime/sidebar-state.js";
import {
  validateThreadPromptHistoryResponse,
  validateThreadRecoverResponse,
} from "./runtime/thread.js";
import { validateToolbridgeToolsListResponse } from "./runtime/toolbridge.js";
import { validateUIStateResponse } from "./runtime/ui.js";
import {
  validateDashboardPromptsResponse,
  validateMemoryAutoDreamIntentResponse,
  validateMemoryConsolidationJobResponse,
  validateMemoryEntryDeleteResponse,
  validateMemoryEntryDetailResponse,
  validateMemorySimilarityIgnoreResponse,
  validateMemorySnapshotResponse,
  validateObservabilityResultResponse,
  validatePersonalizationProfileResponse,
  validatePromptAssetsResponse,
  validatePromptDetailResponse,
  validatePromptIntentCommitResponse,
  validatePromptIntentDiscardResponse,
  validatePromptIntentDraftResponse,
  validatePromptIntentDryRunResponse,
  validateSharedFileDeleteResponse,
  validateSharedFileDetailResponse,
  validateSharedFilesDashboardResponse,
  validateWorkflowMaterialWriteResponse,
} from "./schema-responses.js";
import {
  validateSkillFilesResponse,
  validateSkillImportResponse,
  validateSkillResolutionApplyResponse,
  validateSkillResolutionListResponse,
  validateSkillResolutionPreviewResponse,
  validateSkillSummarySuggestionResponse,
  validateSkillToolMutationResponse,
  validateSkillToolsListResponse,
} from "./skills.js";
import {
  validateDashboardDagApplyOpsResponse,
  validateDashboardDagDispatchNodeResponse,
  validateDashboardDagDetailResponse,
  validateDashboardDagRunResponse,
  validateDashboardDagRunsResponse,
  validateDashboardDagTerminateResponse,
} from "./workflow/dag.js";
import {
  validateWorkflowTemplateDraftResponse,
  validateWorkflowTemplateRollbackResponse,
  validateWorkflowTemplateResponse,
  validateWorkflowTemplateSaveResponse,
  validateWorkflowTemplatesListResponse,
} from "./workflow/templates.js";

export { validateDatasourceDeleteResponse, validateDatasourceImportResponse };

/** @param {Record<string, string>} methods */
export function createBackendResponseValidators(methods) {
  const validateControlResponse = createMCPServerControlResponseValidator(methods);
  return Object.freeze({
    [methods.APP_UPDATE_INSTALL]: validateAppUpdateInstallResponse,
    [methods.APP_UPDATE_INSTALL_LATEST]: validateAppUpdateInstallResponse,
    [methods.CONFIG_READ]: validateRuntimeConfigResponse,
    [methods.CONFIG_BUILTIN_TOOLS_READ]: validateBuiltinToolsResponse,
    [methods.CONFIG_BUILTIN_TOOLS_WRITE]: validateBuiltinToolsResponse,
    [methods.CONFIG_LSP_PROMPT_HINT_READ]: validateLspPromptHintResponse,
    [methods.CONFIG_LSP_PROMPT_HINT_WRITE]: validateLspPromptHintResponse,
    [methods.DASHBOARD_SHARED_FILES]: validateSharedFilesDashboardResponse,
    [methods.CRONJOB_CREATE]: validateCronJobResponse,
    [methods.CRONJOB_DELETE]: validateCronDeleteResponse,
    [methods.CRONJOB_GET]: validateCronJobResponse,
    [methods.CRONJOB_LIST]: validateCronListResponse,
    [methods.CRONJOB_LIST_RUNS]: validateCronListRunsResponse,
    [methods.CRONJOB_RUN_ONCE]: validateCronJobResponse,
    [methods.CRONJOB_SET_ENABLED]: validateCronSetEnabledResponse,
    [methods.CRONJOB_UPDATE]: validateCronJobResponse,
    [methods.DASHBOARD_WORKFLOW_MATERIAL_WRITE]: validateWorkflowMaterialWriteResponse,
    [methods.DASHBOARD_PROMPTS]: validateDashboardPromptsResponse,
    [methods.MCP_SERVER_LIST]: validateMCPServerListResponse,
    [methods.TOOLBRIDGE_TOOLS_LIST]: validateToolbridgeToolsListResponse,
    [methods.MCP_SERVER_SQLITE_START]: validateControlResponse,
    [methods.MCP_SERVER_SQLITE_STOP]: validateControlResponse,
    [methods.MCP_SERVER_PLAYWRIGHT_START]: validateControlResponse,
    [methods.MCP_SERVER_PLAYWRIGHT_STOP]: validateControlResponse,
    [methods.MODEL_PROVIDERS_APPLY]: validateModelProviderRegistryResponse,
    [methods.MODEL_PROVIDERS_LIST]: validateModelProviderRegistryResponse,
    [methods.MODEL_PROVIDERS_SAVE]: validateModelProviderRegistryResponse,
    [methods.OBSERVABILITY_ERROR_LIST]: validateObservabilityResultResponse,
    [methods.OBSERVABILITY_FRONTEND_INGEST]: validateFrontendIngestResponse,
    [methods.OBSERVABILITY_RECENT_LIST]: validateObservabilityResultResponse,
    [methods.OBSERVABILITY_SLOW_LIST]: validateObservabilityResultResponse,
    [methods.OBSERVABILITY_THREAD_RECENT]: validateObservabilityResultResponse,
    [methods.OBSERVABILITY_TRACE_GET]: validateObservabilityResultResponse,
    [methods.UI_CODE_SAVE]: validateCodeSaveResponse,
    [methods.UI_DASHBOARD_GET]: validateDashboardPageResponse,
    [methods.UI_OPEN_NEW_WINDOW]: validateOpenWindowResponse,
    [methods.UI_PREFERENCES_SET]: validateOKResponse,
    [methods.UI_PROJECTS_ADD]: validateProjectsStateResponse,
    [methods.UI_PROJECTS_GET]: validateProjectsStateResponse,
    [methods.UI_PROJECTS_REMOVE]: validateProjectsStateResponse,
    [methods.UI_PROJECTS_SET_ACTIVE]: validateProjectsStateResponse,
    [methods.UI_VIDEO_GET_API_KEY]: validateVideoAPIKeyStatusResponse,
    [methods.UI_VIDEO_SET_API_KEY]: validateOKResponse,
    [methods.UI_WINDOW_BOOTSTRAP_GET]: validateWindowBootstrapResponse,
    [methods.UI_SIDEBAR_GET]: validateSidebarStateResponse,
    [methods.UI_STATE_GET]: validateUIStateResponse,
    [methods.UI_MEMORY_GET]: validateMemorySnapshotResponse,
    [methods.UI_MEMORY_ENTRY_GET]: validateMemoryEntryDetailResponse,
    [methods.UI_MEMORY_ENTRY_UPSERT]: validateMemoryEntryDetailResponse,
    [methods.UI_MEMORY_ENTRY_DELETE]: validateMemoryEntryDeleteResponse,
    [methods.UI_MEMORY_AUTO_DREAM_SET_INTENT]: validateMemoryAutoDreamIntentResponse,
    [methods.UI_MEMORY_ENTRY_MERGE]: validateMemoryEntryDetailResponse,
    [methods.UI_MEMORY_SIMILARITY_IGNORE]: validateMemorySimilarityIgnoreResponse,
    [methods.UI_MEMORY_SIMILARITY_CONSOLIDATE_ALL_START]: validateMemoryConsolidationJobResponse,
    [methods.UI_MEMORY_SIMILARITY_CONSOLIDATE_ALL_STATUS]: validateMemoryConsolidationJobResponse,
    [methods.UI_SHARED_FILE_GET]: validateSharedFileDetailResponse,
    [methods.UI_SHARED_FILE_DELETE]: validateSharedFileDeleteResponse,
    [methods.PROMPT_ASSETS_LIST]: validatePromptAssetsResponse,
    [methods.PROMPTS_GET]: validatePromptDetailResponse,
    [methods.PROMPTS_WRITE]: validatePromptDetailResponse,
    [methods.PROMPTS_DELETE]: validateOKResponse,
    [methods.PROMPT_INTENTS_DRAFT]: validatePromptIntentDraftResponse,
    [methods.PROMPT_INTENTS_COMMIT]: validatePromptIntentCommitResponse,
    [methods.PROMPT_INTENTS_DISCARD]: validatePromptIntentDiscardResponse,
    [methods.PROMPT_INTENTS_DRY_RUN]: validatePromptIntentDryRunResponse,
    [methods.PERSONALIZATION_PROFILE_GET]: validatePersonalizationProfileResponse,
    [methods.PERSONALIZATION_PROFILE_SAVE]: validatePersonalizationProfileResponse,
    [methods.SKILLS_LOCAL_READ]: validateSkillReadResponse,
    [methods.SKILLS_LOCAL_LIST_FILES]: validateSkillFilesResponse,
    [methods.SKILLS_LOCAL_IMPORT_DIR]: validateSkillImportResponse,
    [methods.SKILLS_SUMMARY_SUGGEST]: validateSkillSummarySuggestionResponse,
    [methods.SKILLS_RESOLUTION_LIST]: validateSkillResolutionListResponse,
    [methods.SKILLS_RESOLUTION_PREVIEW]: validateSkillResolutionPreviewResponse,
    [methods.SKILLS_RESOLUTION_APPLY]: validateSkillResolutionApplyResponse,
    [methods.SKILL_TOOLS_LIST]: validateSkillToolsListResponse,
    [methods.SKILL_TOOLS_CREATE]: validateSkillToolMutationResponse,
    [methods.DATASOURCE_V2_LIST]: validateDatasourceDocumentsResponse,
    [methods.DATASOURCE_V2_GET]: validateDatasourceDetailResponse,
    [methods.DATASOURCE_V2_LIST_CHUNKS]: validateDatasourceChunksResponse,
    [methods.DATASOURCE_V2_IMPORT_LOCAL_FILE]: validateDatasourceImportResponse,
    [methods.DATASOURCE_V2_UPDATE]: validateDatasourceDocumentResponse,
    [methods.DATASOURCE_V2_DELETE]: validateDatasourceDeleteResponse,
    [methods.THREAD_ARCHIVE]: validateNullResponse,
    [methods.THREAD_UNARCHIVE]: validateNullResponse,
    [methods.THREAD_DELETE]: validateNullResponse,
    [methods.THREAD_CONFIG_GET]: validateThreadConfigResponse,
    [methods.THREAD_CONFIG_SET]: validateThreadConfigResponse,
    [methods.THREAD_COMPACT_START]: validateThreadCompactResponse,
    [methods.THREAD_FORK]: validateThreadForkResponse,
    [methods.THREAD_NAME_SET]: validateNullResponse,
    [methods.THREAD_RECOVER]: validateThreadRecoverResponse,
    [methods.THREAD_START]: validateThreadStartResponse,
    [methods.THREAD_MESSAGES]: validateThreadMessagesResponse,
    [methods.THREAD_PROMPT_HISTORY]: validateThreadPromptHistoryResponse,
    [methods.THREAD_RESOLVE]: validateThreadResolveResponse,
    [methods.APPROVAL_RESPOND]: validateNullResponse,
    [methods.TURN_START]: validateTurnStartResponse,
    [methods.TURN_FORCE_COMPLETE]: validateTurnForceCompleteResponse,
    [methods.DASHBOARD_LOGS]: validateDashboardLogsResponse,
    [methods.DASHBOARD_DAG_DETAIL]: validateDashboardDagDetailResponse,
    [methods.DASHBOARD_DAG_RUNS]: validateDashboardDagRunsResponse,
    [methods.DASHBOARD_DAG_RUN]: validateDashboardDagRunResponse,
    [methods.DASHBOARD_DAG_START]: validateDashboardDagStartResponse,
    [methods.DASHBOARD_DAG_CREATE_AND_START]: validateDashboardDagCreateAndStartResponse,
    [methods.DASHBOARD_DAG_DISPATCH_NODE]: validateDashboardDagDispatchNodeResponse,
    [methods.DASHBOARD_DAG_TERMINATE]: validateDashboardDagTerminateResponse,
    [methods.DASHBOARD_DAG_APPLY_OPS]: validateDashboardDagApplyOpsResponse,
    [methods.WORKFLOW_TEMPLATES_LIST]: validateWorkflowTemplatesListResponse,
    [methods.WORKFLOW_TEMPLATES_GET]: validateWorkflowTemplateResponse,
    [methods.WORKFLOW_TEMPLATES_RENDER_DAG]: validateWorkflowTemplateDraftResponse,
    [methods.WORKFLOW_TEMPLATES_SAVE]: validateWorkflowTemplateSaveResponse,
    [methods.WORKFLOW_TEMPLATES_ROLLBACK]: validateWorkflowTemplateRollbackResponse,
  });
}
