#!/usr/bin/env bash
# P25-HIGH-02t: generate Phase 3 authenticated Claude CLI E2E evidence from raw test output.
# This helper is fail-closed: it requires an explicitly authenticated environment,
# a real PASS for TestMcpSkillMode_ClaudeCLIManagedSameBinarySkillE2E, and no skip/
# unauthenticated markers before writing evidence. It does not enable defaults.

set -euo pipefail

RAW_E2E_OUTPUT_FILE="${SKILL_PD_CLAUDECLI_E2E_OUTPUT_FILE:-${SKILL_PD_CLAUDECLI_E2E_RAW_OUTPUT_FILE:-}}"
EVIDENCE_OUT="${SKILL_PD_CLAUDECLI_E2E_EVIDENCE_OUT:-}"
VERSION_COMMIT="${SKILL_PD_VERSION_COMMIT:-}"
OPERATOR="${SKILL_PD_OPERATOR:-}"
AUTHENTICATED_ENVIRONMENT="${SKILL_PD_AUTHENTICATED_ENVIRONMENT:-false}"
E2E_COMMAND="${SKILL_PD_CLAUDECLI_E2E_COMMAND:-go test ./cmd/agent-terminal -run '^TestMcpSkillMode_ClaudeCLIManagedSameBinarySkillE2E$' -count=1}"
EVIDENCE_DATE="${SKILL_PD_EVIDENCE_DATE:-$(date +%F)}"
TEST_NAME="TestMcpSkillMode_ClaudeCLIManagedSameBinarySkillE2E"

fail() {
  echo "P25-HIGH-02t authenticated Claude CLI E2E evidence generation failed: $*" >&2
  exit 1
}

[[ -n "${RAW_E2E_OUTPUT_FILE}" ]] || fail "SKILL_PD_CLAUDECLI_E2E_OUTPUT_FILE is required"
[[ -f "${RAW_E2E_OUTPUT_FILE}" ]] || fail "raw Claude CLI E2E output file not found: ${RAW_E2E_OUTPUT_FILE}"
[[ -n "${EVIDENCE_OUT}" ]] || fail "SKILL_PD_CLAUDECLI_E2E_EVIDENCE_OUT is required"
[[ -n "${VERSION_COMMIT}" ]] || fail "SKILL_PD_VERSION_COMMIT is required"
[[ -n "${OPERATOR}" ]] || fail "SKILL_PD_OPERATOR is required"
[[ -n "${E2E_COMMAND}" ]] || fail "SKILL_PD_CLAUDECLI_E2E_COMMAND must not be empty"
[[ "${AUTHENTICATED_ENVIRONMENT}" == "true" ]] || fail "SKILL_PD_AUTHENTICATED_ENVIRONMENT must be true"

python3 - "${RAW_E2E_OUTPUT_FILE}" "${EVIDENCE_OUT}" "${EVIDENCE_DATE}" "${VERSION_COMMIT}" "${OPERATOR}" "${AUTHENTICATED_ENVIRONMENT}" "${E2E_COMMAND}" "${TEST_NAME}" <<'PY_SCRIPT'
import re
import sys
from pathlib import Path

raw_path = Path(sys.argv[1])
out_path = Path(sys.argv[2])
evidence_date = sys.argv[3]
version_commit = sys.argv[4]
operator = sys.argv[5]
authenticated_environment = sys.argv[6]
e2e_command = sys.argv[7]
test_name = sys.argv[8]

raw = raw_path.read_text(encoding="utf-8", errors="replace").strip()
if not raw:
    raise SystemExit("raw Claude CLI E2E output is empty")

if authenticated_environment != "true":
    raise SystemExit("authenticated environment must be true")
if re.search(r"(?i)\bskip(?:ped|ping)?\b", raw):
    raise SystemExit("raw E2E output must not contain skip markers")
if re.search(r"(?im)^\s*---\s+FAIL:\s*" + re.escape(test_name) + r"\b", raw) or re.search(r"(?m)^FAIL\b", raw):
    raise SystemExit("raw E2E output contains FAIL")
if re.search(r"(?i)\b(unauthenticated|not authenticated|authentication required|auth required)\b", raw):
    raise SystemExit("raw E2E output indicates unauthenticated environment")
if f"=== RUN   {test_name}" not in raw:
    raise SystemExit(f"raw E2E output missing run marker for {test_name}")
if f"--- PASS: {test_name}" not in raw:
    raise SystemExit(f"raw E2E output missing PASS marker for {test_name}")
if not re.search(r"(?m)^PASS\s*$", raw):
    raise SystemExit("raw E2E output missing standalone PASS line")

body = f"""# Skill Progressive Disclosure Authenticated Claude CLI E2E Evidence

Evidence type: authenticated-claudecli-e2e
Status: generated by P25-HIGH-02t authenticated Claude CLI E2E evidence generator.

## Filled evidence

Evidence date: {evidence_date}
Version / commit: {version_commit}
Operator: {operator}
Authenticated environment: true
Command: {e2e_command}
Test name: {test_name}
Result: PASS
Skip status: none

## Raw E2E output

```text
{raw}
```

This generated evidence does not enable ENABLE_SKILL_PROGRESSIVE_DISCLOSURE and does not delete overrideSkillsToSummary.
"""
if "TODO" in body:
    raise SystemExit("generated authenticated Claude CLI E2E evidence still contains TODO")
if "SKIP" in body:
    raise SystemExit("generated authenticated Claude CLI E2E evidence still contains SKIP")
out_path.parent.mkdir(parents=True, exist_ok=True)
out_path.write_text(body, encoding="utf-8")
print("P25-HIGH-02t authenticated Claude CLI E2E evidence generated.")
print(f"Evidence file: {out_path}")
print(f"Test name: {test_name}")
print("Result: PASS")
print("Skip status: none")
print("This generator does not enable ENABLE_SKILL_PROGRESSIVE_DISCLOSURE and does not delete overrideSkillsToSummary.")
PY_SCRIPT
