#!/usr/bin/env bash
# P25-HIGH-02v: one-command Phase 3 evidence readiness check + collector runner.
# It first runs the read-only readiness status helper in fail-closed mode, then
# runs the canonical evidence collector only when phase3_collect_ready=true.
# This helper writes bundle artifacts but does not enable defaults, delete
# overrides, merge branches, or mark rollout complete.

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
STATUS_SCRIPT="${SKILL_PD_PHASE3_EVIDENCE_STATUS_SCRIPT:-${SCRIPT_DIR}/skill-progressive-disclosure-phase3-evidence-status.sh}"
COLLECT_SCRIPT="${SKILL_PD_PHASE3_EVIDENCE_COLLECT_SCRIPT:-${SCRIPT_DIR}/skill-progressive-disclosure-phase3-evidence-collect.sh}"
BUNDLE_OUT_DIR="${SKILL_PD_BUNDLE_OUT_DIR:-}"
PRODUCTION_SMOKE_EVIDENCE="${SKILL_PD_PRODUCTION_SMOKE_EVIDENCE:-}"
CLAUDECLI_E2E_EVIDENCE="${SKILL_PD_CLAUDECLI_E2E_EVIDENCE:-}"
OBSERVATION_FILE="${SKILL_PD_OBSERVATION_FILE:-}"
REQUIRED_SAMPLE_DAYS="${SKILL_PD_REQUIRED_SAMPLE_DAYS:-30}"
MAX_NON_OK_RATE="${SKILL_PD_MAX_NON_OK_RATE:-0.05}"
WRITE_MANIFEST="${SKILL_PD_EVIDENCE_BUNDLE_WRITE_MANIFEST:-true}"
RUN_LOCAL_GO_TESTS="${SKILL_PD_RUN_LOCAL_GO_TESTS:-false}"

fail() {
  echo "P25-HIGH-02v phase3 evidence ready collect failed: $*" >&2
  exit 1
}

require_executable() {
  local path="$1"
  local label="$2"
  [[ -x "${path}" ]] || fail "${label} script is not executable: ${path}"
}

run_and_capture() {
  local output_path="$1"
  local label="$2"
  shift 2
  local tmp_output
  tmp_output="$(mktemp)"
  if "$@" >"${tmp_output}" 2>&1; then
    mv "${tmp_output}" "${output_path}"
    return 0
  fi
  mv "${tmp_output}" "${output_path}"
  fail "${label} failed; see ${output_path}"
}

[[ -n "${BUNDLE_OUT_DIR}" ]] || fail "SKILL_PD_BUNDLE_OUT_DIR is required"
[[ -n "${PRODUCTION_SMOKE_EVIDENCE}" ]] || fail "SKILL_PD_PRODUCTION_SMOKE_EVIDENCE is required"
[[ -n "${CLAUDECLI_E2E_EVIDENCE}" ]] || fail "SKILL_PD_CLAUDECLI_E2E_EVIDENCE is required"
[[ -n "${OBSERVATION_FILE}" ]] || fail "SKILL_PD_OBSERVATION_FILE is required"

require_executable "${STATUS_SCRIPT}" "Phase 3 evidence status"
require_executable "${COLLECT_SCRIPT}" "Phase 3 evidence collector"

mkdir -p "${BUNDLE_OUT_DIR}"
BUNDLE_OUT_DIR="$(cd -- "${BUNDLE_OUT_DIR}" && pwd)"
STATUS_OUTPUT="${BUNDLE_OUT_DIR}/phase3-evidence-status-output.txt"
COLLECT_OUTPUT="${BUNDLE_OUT_DIR}/phase3-evidence-collect-output.txt"

# Avoid stale green status/collector transcript when reusing a bundle directory.
rm -f "${STATUS_OUTPUT}" "${COLLECT_OUTPUT}"

run_and_capture "${STATUS_OUTPUT}" "Phase 3 evidence status" \
  env SKILL_PD_OBSERVATION_FILE="${OBSERVATION_FILE}" \
      SKILL_PD_PRODUCTION_SMOKE_EVIDENCE="${PRODUCTION_SMOKE_EVIDENCE}" \
      SKILL_PD_CLAUDECLI_E2E_EVIDENCE="${CLAUDECLI_E2E_EVIDENCE}" \
      SKILL_PD_REQUIRED_SAMPLE_DAYS="${REQUIRED_SAMPLE_DAYS}" \
      SKILL_PD_MAX_NON_OK_RATE="${MAX_NON_OK_RATE}" \
      SKILL_PD_PHASE3_STATUS_FAIL_ON_BLOCKERS=true \
      "${STATUS_SCRIPT}"

python3 - "${STATUS_OUTPUT}" <<'PY_SCRIPT'
import sys
from pathlib import Path
body = Path(sys.argv[1]).read_text(encoding="utf-8", errors="replace")
required = [
    "P25-HIGH-02u phase3 evidence status:",
    "phase3_collect_ready=true",
    "blocker_count=0",
]
missing = [token for token in required if token not in body]
if missing:
    raise SystemExit("status output missing ready tokens: " + ", ".join(missing))
PY_SCRIPT

run_and_capture "${COLLECT_OUTPUT}" "Phase 3 evidence collector" \
  env SKILL_PD_BUNDLE_OUT_DIR="${BUNDLE_OUT_DIR}" \
      SKILL_PD_PRODUCTION_SMOKE_EVIDENCE="${PRODUCTION_SMOKE_EVIDENCE}" \
      SKILL_PD_CLAUDECLI_E2E_EVIDENCE="${CLAUDECLI_E2E_EVIDENCE}" \
      SKILL_PD_OBSERVATION_FILE="${OBSERVATION_FILE}" \
      SKILL_PD_REQUIRED_SAMPLE_DAYS="${REQUIRED_SAMPLE_DAYS}" \
      SKILL_PD_MAX_NON_OK_RATE="${MAX_NON_OK_RATE}" \
      SKILL_PD_EVIDENCE_BUNDLE_WRITE_MANIFEST="${WRITE_MANIFEST}" \
      SKILL_PD_RUN_LOCAL_GO_TESTS="${RUN_LOCAL_GO_TESTS}" \
      "${COLLECT_SCRIPT}"

cat "${STATUS_OUTPUT}"
cat "${COLLECT_OUTPUT}"
cat <<EOF_SUMMARY
P25-HIGH-02v phase3 evidence ready collect passed.
Bundle dir: ${BUNDLE_OUT_DIR}
Generated transcripts:
- phase3-evidence-status-output.txt
- phase3-evidence-collect-output.txt
Canonical evidence bundle is generated by P25-HIGH-02n collector in the same directory.
This helper does not enable ENABLE_SKILL_PROGRESSIVE_DISCLOSURE, delete overrideSkillsToSummary, merge branches, or mark rollout complete.
EOF_SUMMARY
