#!/usr/bin/env bash
# P25-HIGH-02w: generate a review-ready Phase 3 evidence handoff report.
# It verifies the canonical bundle plus ready-collect transcripts, records SHA256
# checksums, and writes a concise report for PR / release review. It does not
# enable defaults, delete overrides, merge branches, or mark rollout complete.

set -euo pipefail

BUNDLE_DIR="${SKILL_PD_EVIDENCE_BUNDLE_DIR:-}"
HANDOFF_REPORT_OUT="${SKILL_PD_HANDOFF_REPORT_OUT:-}"

fail() {
  echo "P25-HIGH-02w phase3 handoff report failed: $*" >&2
  exit 1
}

[[ -n "${BUNDLE_DIR}" ]] || fail "SKILL_PD_EVIDENCE_BUNDLE_DIR is required"
[[ -d "${BUNDLE_DIR}" ]] || fail "evidence bundle dir not found: ${BUNDLE_DIR}"
BUNDLE_DIR="$(cd -- "${BUNDLE_DIR}" && pwd)"
if [[ -z "${HANDOFF_REPORT_OUT}" ]]; then
  HANDOFF_REPORT_OUT="${BUNDLE_DIR}/phase3-handoff-report.md"
fi

python3 - "${BUNDLE_DIR}" "${HANDOFF_REPORT_OUT}" <<'PY_SCRIPT'
import datetime as _dt
import hashlib
import re
import sys
from pathlib import Path

bundle = Path(sys.argv[1])
out = Path(sys.argv[2])

required_files = [
    "production-smoke-evidence.md",
    "claudecli-e2e-evidence.md",
    "rollout-observation.md",
    "rollout-gate-output.txt",
    "phase3-preflight-output.txt",
    "evidence-bundle-output.txt",
    "manifest.md",
    "phase3-evidence-status-output.txt",
    "phase3-evidence-collect-output.txt",
]

checks = {
    "production-smoke-evidence.md": ["Evidence type: production-smoke", "P25-HIGH-02g smoke passed.", "real traffic is non-zero"],
    "claudecli-e2e-evidence.md": ["Evidence type: authenticated-claudecli-e2e", "Authenticated environment: true", "TestMcpSkillMode_ClaudeCLIManagedSameBinarySkillE2E", "PASS"],
    "rollout-gate-output.txt": ["P25-HIGH-02i rollout gate passed", "rollback_drill_pass=true"],
    "phase3-preflight-output.txt": ["P25-HIGH-02j phase3 preflight passed.", "does not enable ENABLE_SKILL_PROGRESSIVE_DISCLOSURE"],
    "evidence-bundle-output.txt": ["P25-HIGH-02l evidence bundle passed."],
    "manifest.md": ["Evidence type: phase3-evidence-bundle", "P25-HIGH-02l evidence bundle passed."],
    "phase3-evidence-status-output.txt": ["P25-HIGH-02u phase3 evidence status:", "phase3_collect_ready=true", "blocker_count=0"],
    "phase3-evidence-collect-output.txt": ["P25-HIGH-02n evidence collect passed.", "evidence bundle passed"],
}

bodies = {}
for name in required_files:
    path = bundle / name
    if not path.is_file():
        raise SystemExit(f"missing bundle file: {name}")
    body = path.read_text(encoding="utf-8", errors="replace")
    bodies[name] = body
    if "TODO" in body:
        raise SystemExit(f"bundle file still contains TODO: {name}")
    if name == "claudecli-e2e-evidence.md" and "SKIP" in body:
        raise SystemExit("Claude CLI E2E evidence must not contain SKIP")
    for token in checks.get(name, []):
        if token not in body:
            raise SystemExit(f"{name} missing token: {token}")

status = bodies["phase3-evidence-status-output.txt"]

def field(name: str, default: str = "unknown") -> str:
    match = re.search(rf"(?m)^{re.escape(name)}=(.+)$", status)
    return match.group(1).strip() if match else default

sample_days = field("sample_days")
required_sample_days = field("required_sample_days")
remaining_sample_days = field("remaining_sample_days")
total_host_tool_calls = field("total_host_tool_calls")
non_ok_rate = field("non_ok_rate")
rollback_drill_pass = field("rollback_drill_pass")
last_sample_date = field("last_sample_date")

rows = []
for name in required_files:
    path = bundle / name
    digest = hashlib.sha256(path.read_bytes()).hexdigest()
    rows.append((name, path.stat().st_size, digest))

lines = [
    "# Skill Progressive Disclosure Phase 3 Handoff Report",
    "",
    "Evidence type: phase3-handoff-report",
    "Status: generated by P25-HIGH-02w phase3 handoff report helper.",
    f"Generated at: {_dt.datetime.utcnow().isoformat(timespec='seconds')}Z",
    f"Bundle dir: {bundle}",
    "",
    "## Readiness summary",
    "",
    "- phase3_collect_ready: true",
    "- blocker_count: 0",
    f"- sample_days: {sample_days}",
    f"- required_sample_days: {required_sample_days}",
    f"- remaining_sample_days: {remaining_sample_days}",
    f"- total_host_tool_calls: {total_host_tool_calls}",
    f"- non_ok_rate: {non_ok_rate}",
    f"- rollback_drill_pass: {rollback_drill_pass}",
    f"- last_sample_date: {last_sample_date}",
    "",
    "## Required evidence files",
    "",
    "| File | Bytes | SHA256 |",
    "|---|---:|---|",
]
for name, size, digest in rows:
    lines.append(f"| `{name}` | {size} | `{digest}` |")
lines.extend([
    "",
    "## Gate outputs verified",
    "",
    "- P25-HIGH-02u phase3 evidence status passed with `phase3_collect_ready=true` and `blocker_count=0`.",
    "- P25-HIGH-02n evidence collector passed and produced the canonical bundle.",
    "- P25-HIGH-02l evidence bundle verifier passed.",
    "- P25-HIGH-02j phase3 preflight passed.",
    "- P25-HIGH-02i rollout gate passed with rollback drill evidence.",
    "",
    "## Next owner action",
    "",
    "Attach this report and the full bundle to the Phase 3 review. Default policy formalization and `overrideSkillsToSummary` deletion still require a separate owner-approved Phase 3 PR.",
    "",
    "This report does not enable ENABLE_SKILL_PROGRESSIVE_DISCLOSURE, delete overrideSkillsToSummary, merge branches, or mark rollout complete.",
    "",
])
report = "\n".join(lines)
if "TODO" in report:
    raise SystemExit("generated handoff report still contains TODO")
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text(report, encoding="utf-8")
print("P25-HIGH-02w phase3 handoff report generated.")
print(f"Report file: {out}")
print(f"Bundle dir: {bundle}")
print("phase3_collect_ready=true")
print("blocker_count=0")
print("This helper does not enable ENABLE_SKILL_PROGRESSIVE_DISCLOSURE, delete overrideSkillsToSummary, merge branches, or mark rollout complete.")
PY_SCRIPT
