#!/usr/bin/env bash
# P25-HIGH-02s: generate Phase 3 production-smoke evidence from a rollout report.
# This helper is fail-closed: it requires real non-zero traffic and a raw
# P25-HIGH-02g smoke pass before writing evidence. It does not enable defaults.

set -euo pipefail

ROLLOUT_REPORT_FILE="${SKILL_PD_ROLLOUT_REPORT_FILE:-}"
EVIDENCE_OUT="${SKILL_PD_PRODUCTION_SMOKE_EVIDENCE_OUT:-}"
OPERATOR="${SKILL_PD_OPERATOR:-}"
METRICS_URL="${SUPER_DOLPHIN_METRICS_URL:-}"
PROMETHEUS_URL_ENV="${PROMETHEUS_URL:-}"
ALERTMANAGER_URL="${ALERTMANAGER_URL:-}"
EVIDENCE_DATE="${SKILL_PD_EVIDENCE_DATE:-$(date +%F)}"

fail() {
  echo "P25-HIGH-02s production smoke evidence generation failed: $*" >&2
  exit 1
}

[[ -n "${ROLLOUT_REPORT_FILE}" ]] || fail "SKILL_PD_ROLLOUT_REPORT_FILE is required"
[[ -f "${ROLLOUT_REPORT_FILE}" ]] || fail "rollout report file not found: ${ROLLOUT_REPORT_FILE}"
[[ -n "${EVIDENCE_OUT}" ]] || fail "SKILL_PD_PRODUCTION_SMOKE_EVIDENCE_OUT is required"
[[ -n "${OPERATOR}" ]] || fail "SKILL_PD_OPERATOR is required"
[[ -n "${METRICS_URL}" ]] || fail "SUPER_DOLPHIN_METRICS_URL is required"
[[ -n "${ALERTMANAGER_URL}" ]] || fail "ALERTMANAGER_URL is required"

python3 - "${ROLLOUT_REPORT_FILE}" "${EVIDENCE_OUT}" "${EVIDENCE_DATE}" "${OPERATOR}" "${METRICS_URL}" "${PROMETHEUS_URL_ENV}" "${ALERTMANAGER_URL}" <<'PY_SCRIPT'
import re
import sys
from pathlib import Path

report_path = Path(sys.argv[1])
out_path = Path(sys.argv[2])
evidence_date = sys.argv[3]
operator = sys.argv[4]
metrics_url = sys.argv[5]
prometheus_url_env = sys.argv[6]
alertmanager_url = sys.argv[7]

report = report_path.read_text(encoding="utf-8", errors="replace")
lines = report.splitlines()

def cells_for(line: str):
    stripped = line.strip()
    if not stripped.startswith("|"):
        return None
    cells = [c.strip() for c in stripped.strip("|").split("|")]
    if len(cells) < 16:
        return None
    return cells

def clean(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and value[0] == "`" and value[-1] == "`":
        value = value[1:-1]
    return value.strip()

row = None
for line in lines:
    cells = cells_for(line)
    if not cells:
        continue
    if re.fullmatch(r"\d{4}-\d{2}-\d{2}", clean(cells[0])):
        row = cells
        break
if row is None:
    raise SystemExit("rollout report does not contain a daily observation row")

row_date = clean(row[0])
version = clean(row[1])
total = int(float(clean(row[4])))
prometheus_smoke = clean(row[11])
decision = clean(row[14])
if total <= 0:
    raise SystemExit(f"{row_date}: Total host tool calls must be positive, got {total}")
if prometheus_smoke != "PASS":
    raise SystemExit(f"{row_date}: Production Prometheus smoke result is {prometheus_smoke!r}, want PASS")
if decision != "continue":
    raise SystemExit(f"{row_date}: Decision is {decision!r}, want continue")

prometheus_url = prometheus_url_env
match = re.search(r"(?m)^- Prometheus URL:\s*(\S+)\s*$", report)
if match:
    prometheus_url = match.group(1)
if not prometheus_url:
    raise SystemExit("PROMETHEUS_URL is required or report must contain '- Prometheus URL:'")

smoke_output = ""
marker = "## Production smoke output"
if marker in report:
    after_marker = report.split(marker, 1)[1]
    fence_match = re.search(r"```(?:text)?\s*\n(.*?)\n```", after_marker, re.S)
    if fence_match:
        smoke_output = fence_match.group(1).strip()
if not smoke_output:
    raise SystemExit("raw production smoke output block is required")
if "P25-HIGH-02g rollout smoke passed." not in smoke_output:
    raise SystemExit("raw production smoke output missing P25-HIGH-02g rollout smoke passed.")

body = f"""# Skill Progressive Disclosure Production Smoke Evidence

Evidence type: production-smoke
Status: generated by P25-HIGH-02s production smoke evidence generator.

## Filled evidence

Evidence date: {evidence_date}
Version / commit: {version}
Operator: {operator}
Metrics URL: {metrics_url}
Prometheus URL: {prometheus_url}
Alertmanager URL: {alertmanager_url}
Observation row date: {row_date}
Total host tool calls: {total}
Production smoke result: P25-HIGH-02g smoke passed.
Real traffic statement: real traffic is non-zero

## Raw smoke output

```text
{smoke_output}
```

This generated evidence does not enable ENABLE_SKILL_PROGRESSIVE_DISCLOSURE and does not delete overrideSkillsToSummary.
"""
if "TODO" in body:
    raise SystemExit("generated production smoke evidence still contains TODO")
out_path.parent.mkdir(parents=True, exist_ok=True)
out_path.write_text(body, encoding="utf-8")
print("P25-HIGH-02s production smoke evidence generated.")
print(f"Evidence file: {out_path}")
print(f"Observation row date: {row_date}")
print(f"Total host tool calls: {total}")
print("This generator does not enable ENABLE_SKILL_PROGRESSIVE_DISCLOSURE and does not delete overrideSkillsToSummary.")
PY_SCRIPT
