import {
  applySkillResolution as applySkillResolutionBackend,
  createSkill as createSkillBackend,
  deleteDatasourceDocument as deleteDatasourceDocumentBackend,
  deleteSkill as deleteSkillBackend,
  getDashboardPage as getDashboardPageBackend,
  getDatasourceDocument as getDatasourceDocumentBackend,
  importDatasourceLocalFile as importDatasourceLocalFileBackend,
  importSkillDirectories as importSkillDirectoriesBackend,
  listDatasourceChunks as listDatasourceChunksBackend,
  listDatasourceDocuments as listDatasourceDocumentsBackend,
  listMCPServers as listMCPServersBackend,
  listSkillFiles as listSkillFilesBackend,
  listSkillResolutions as listSkillResolutionsBackend,
  listSkillTools as listSkillToolsBackend,
  previewSkillResolution as previewSkillResolutionBackend,
  readSkill as readSkillBackend,
  selectDatasourceImportFile as selectDatasourceImportFileBackend,
  selectFiles as selectFilesBackend,
  selectProjectDirs as selectProjectDirsBackend,
  startPlaywrightMCPServer as startPlaywrightMCPServerBackend,
  startSQLiteMCPServer as startSQLiteMCPServerBackend,
  stopPlaywrightMCPServer as stopPlaywrightMCPServerBackend,
  stopSQLiteMCPServer as stopSQLiteMCPServerBackend,
  suggestSkillSummary as suggestSkillSummaryBackend,
  updateDatasourceDocument as updateDatasourceDocumentBackend,
  writeSkill as writeSkillBackend,
} from '../../../shared/api/backendApi.js';

/*
 * skills page service only forwards page actions to backendApi.
 * SkillsPage keeps UI state, query invalidation, and error wording locally.
 */

export const skillsPageService = Object.freeze({
  applySkillResolution: (payload) => applySkillResolutionBackend(payload),
  createSkill: (payload) => createSkillBackend(payload),
  deleteDatasourceDocument: (payload) => deleteDatasourceDocumentBackend(payload),
  deleteSkill: (payload) => deleteSkillBackend(payload),
  getDashboardPage: (payload) => getDashboardPageBackend(payload),
  getDatasourceDocument: (payload) => getDatasourceDocumentBackend(payload),
  importDatasourceLocalFile: (payload) => importDatasourceLocalFileBackend(payload),
  importSkillDirectories: (payload) => importSkillDirectoriesBackend(payload),
  listDatasourceChunks: (payload) => listDatasourceChunksBackend(payload),
  listDatasourceDocuments: (payload) => listDatasourceDocumentsBackend(payload),
  listMCPServers: (payload) => listMCPServersBackend(payload),
  listSkillFiles: (payload) => listSkillFilesBackend(payload),
  listSkillResolutions: (payload) => listSkillResolutionsBackend(payload),
  listSkillTools: (payload) => listSkillToolsBackend(payload),
  previewSkillResolution: (payload) => previewSkillResolutionBackend(payload),
  readSkill: (payload) => readSkillBackend(payload),
  selectDatasourceImportFile: (payload) => selectDatasourceImportFileBackend(payload),
  selectFiles: (payload) => selectFilesBackend(payload),
  selectProjectDirs: (payload) => selectProjectDirsBackend(payload),
  startPlaywrightMCPServer: (payload) => startPlaywrightMCPServerBackend(payload),
  startSQLiteMCPServer: (payload) => startSQLiteMCPServerBackend(payload),
  stopPlaywrightMCPServer: (payload) => stopPlaywrightMCPServerBackend(payload),
  stopSQLiteMCPServer: (payload) => stopSQLiteMCPServerBackend(payload),
  suggestSkillSummary: (payload) => suggestSkillSummaryBackend(payload),
  updateDatasourceDocument: (payload) => updateDatasourceDocumentBackend(payload),
  writeSkill: (payload) => writeSkillBackend(payload),
});
